## Generate feature extracted data based on window size, overlap and class numbers.
1. Extract two class .
2. Extract three class features.

In [1]:
import os
import pickle
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from tqdm import tqdm
from essentials import resample_data, three_class_labels, two_class_labels, normalize
from features_acc_gyr_improved import GenerateFeatures 
import copy

In [2]:
with open('data/df_dict_imu.pkl', 'rb') as f:
    imu_dict = pickle.load(f)
with open('data/df_minze_dict.pkl', 'rb') as f:
    ground_truth_dict = pickle.load(f)
with open('data/df_dict_urineestimate_method1.pkl', 'rb') as f:
    urine_estimate_dict = pickle.load(f)

Remove the data with the almost the entire data being void.
1. subj_9_void4
2. subj_11_void2

In [3]:
del imu_dict['subj_9_void4']
del imu_dict['subj_11_void2']

Extract windowed features from the 3 axis of the accelerometer and the acceleration magnitude.
1. mean
2. rms
3. std
4. range
5. variance
6. min
7. max
8. time energy
9. spectral energy
10. permutation entropy
11. spectral entropy
12. spectral_centroid
13. spectral_spread
14. spectral_flatness
15. peak_frequency_ratio
16. hjorth_frequency
17. spectral_skewness
18. spectral_kurtosis
19. snr

## Two class data

## Data 1
classes: void, non-void

fs: original

sliding window: 1s

overlap: 0

filename: two_class_raw_1s_no.csv

In [5]:
labelled_imu_dict = {}
dict = copy.deepcopy(imu_dict)
for i_void_instance, void_instance in tqdm(enumerate(dict.keys()), desc="Adding labels to IMU data"):
    acc = dict[void_instance]
    gt = ground_truth_dict[void_instance]
    
    # normalize data
    df = normalize(acc)
    
    # add the labels
    labelled_df = two_class_labels(df, gt)
    
    labelled_imu_dict[void_instance] = labelled_df

Adding labels to IMU data: 0it [00:00, ?it/s]

Adding labels to IMU data: 41it [00:00, 324.79it/s]

In [5]:
#  do not upsample
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=1.0, overlap=0.0)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.07it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.33it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.97it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.86it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.51it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.53it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.14it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.67it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.28it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.67it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.44it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.43it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.46it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.08it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.02it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.05it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.84it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.19it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.77it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.78it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.75it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.29it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.92it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.50it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.33it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.78it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.87it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.38it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.97it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.40it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.09it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.85it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.94it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.55it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.15it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.71it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.65it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.28it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.76it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.68it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.53it/s]

In [6]:
final_features.to_csv('improved_features_data_main/two_class_raw_1s_no.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,0.499593,0.000000,0.999186,0.840598,0.524760,0.938842,1.134729,5.349532,1.472764,1.287610,...,5.306330,2.733279,0.051141,0.248079,7.643653,0.771207,6.505756,-4.815822,non-void,1
1,1.498779,0.999186,1.998371,0.816380,0.561207,1.115575,0.848165,3.553001,1.401390,0.719385,...,3.076435,2.032066,0.019512,0.338830,7.038916,1.899025,12.455712,-2.903304,non-void,1
2,2.497964,1.998371,2.997557,0.892873,0.755155,0.804784,0.245606,1.054752,0.841427,0.060322,...,6.125751,5.084524,0.310876,0.211430,13.267912,1.507646,6.138261,-5.716727,non-void,1
3,3.497150,2.997557,3.996743,0.928689,0.707887,0.720945,0.292908,1.507445,0.778175,0.085795,...,3.310932,3.995551,0.127136,0.494355,11.415845,2.877557,13.332518,-0.098072,non-void,1
4,4.496336,3.996743,4.995929,0.874944,0.797456,0.588285,0.231525,1.161934,0.632205,0.053604,...,5.479265,4.786192,0.167407,0.217080,11.995728,1.275285,4.429930,-5.570982,non-void,1

## Data 1b
classes: void, non-void

fs: original

sliding window: 1s

overlap: 0.5

filename: two_class_raw_1s_yo_0.5.csv

In [8]:
#  do not upsample
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=1.0, overlap=0.5)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.95it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.54it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.96it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.30it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.87it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.30it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.37it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.82it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.14it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.91it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.73it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.20it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.01it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.92it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.05it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.45it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.28it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.75it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.09it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.18it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.47it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.10it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.55it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.16it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.09it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.83it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.90it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.53it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.98it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.16it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.89it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.46it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.42it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.64it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.03it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.35it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.84it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.04it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.80it/s]
Analyzing : 100%|██████████| 8/8 [00:05<00:00,  1.35it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.22it/s]

In [9]:
final_features.to_csv('improved_features_data_main/two_class_raw_1s_yo_0.5.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,0.499593,0.000000,0.999186,0.840598,0.524760,0.938842,1.134729,5.349532,1.472764,1.287610,...,5.306330,2.733279,0.051141,0.248079,7.643653,0.771207,6.505756,-4.815822,non-void,1
1,0.990718,0.491125,1.490311,0.782302,0.565548,1.226644,1.215409,5.349532,1.726810,1.477218,...,4.883914,2.581943,0.050737,0.199835,7.901586,1.419999,7.359840,-6.025093,non-void,1
2,1.481843,0.982250,1.981436,0.816380,0.556779,1.084483,0.893955,4.363070,1.405439,0.799155,...,3.217451,2.062397,0.020646,0.307651,7.289360,1.845554,11.901870,-3.522674,non-void,1
3,1.972968,1.473376,2.472561,0.902610,0.695212,0.751729,0.312815,1.479456,0.814217,0.097853,...,3.182097,4.696033,0.171839,0.622803,10.469649,3.014652,12.540498,2.177829,non-void,1
4,2.464094,1.964501,2.963686,0.898106,0.761268,0.813395,0.236576,1.054752,0.847100,0.055968,...,6.300229,5.136663,0.299109,0.202180,13.276005,1.541503,6.277918,-5.961678,non-void,1

## Data 1c
classes: void, non-void

fs: original

sliding window: 1s

overlap: 0.8

filename: two_class_raw_1s_yo_0.8.csv

In [10]:
#  do not upsample
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=1.0, overlap=0.8)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.99it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.63it/s]
Analyzing : 100%|██████████| 8/8 [00:05<00:00,  1.57it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.73it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.58it/s]
Analyzing : 100%|██████████| 8/8 [00:05<00:00,  1.34it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.12it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.20it/s]
Analyzing : 100%|██████████| 8/8 [00:06<00:00,  1.21it/s]
Analyzing : 100%|██████████| 8/8 [00:05<00:00,  1.44it/s]
Analyzing : 100%|██████████| 8/8 [00:07<00:00,  1.03it/s]
Analyzing : 100%|██████████| 8/8 [00:06<00:00,  1.16it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.75it/s]
Analyzing : 100%|██████████| 8/8 [00:05<00:00,  1.37it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.77it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.26it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.23it/s]
Analyzing : 100%|██████████| 8/8 [00:08<00:00,  1.09s/it]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.67it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.73it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.59it/s]
Analyzing : 100%|██████████| 8/8 [00:06<00:00,  1.16it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.96it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.61it/s]
Analyzing : 100%|██████████| 8/8 [00:06<00:00,  1.17it/s]
Analyzing : 100%|██████████| 8/8 [00:05<00:00,  1.46it/s]
Analyzing : 100%|██████████| 8/8 [00:11<00:00,  1.43s/it]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.14it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.64it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.93it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.83it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.24it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.04it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.54it/s]
Analyzing : 100%|██████████| 8/8 [00:05<00:00,  1.51it/s]
Analyzing : 100%|██████████| 8/8 [00:05<00:00,  1.55it/s]
Analyzing : 100%|██████████| 8/8 [00:05<00:00,  1.42it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.27it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.56it/s]
Analyzing : 100%|██████████| 8/8 [00:16<00:00,  2.07s/it]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.31it/s]

In [11]:
final_features.to_csv('improved_features_data_main/two_class_raw_1s_yo_0.8.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,0.499593,0.000000,0.999186,0.840598,0.524760,0.938842,1.134729,5.349532,1.472764,1.287610,...,5.306330,2.733279,0.051141,0.248079,7.643653,0.771207,6.505756,-4.815822,non-void,1
1,0.685882,0.186289,1.185475,0.833607,0.520173,0.989449,1.158952,5.349532,1.523870,1.343169,...,4.268954,3.377154,0.088183,0.257060,7.601092,1.608695,7.237971,-4.609194,non-void,1
2,0.872171,0.372578,1.371763,0.823753,0.562236,1.193638,1.186426,5.349532,1.682967,1.407606,...,4.808645,3.009955,0.076827,0.205324,7.764113,1.251045,6.677416,-5.877510,non-void,1
3,1.058459,0.558867,1.558052,0.837070,0.566957,1.251707,1.200011,5.349532,1.734012,1.440027,...,4.752375,2.387227,0.039506,0.289355,7.820157,1.777259,8.436346,-3.902217,non-void,1
4,1.244748,0.745155,1.744341,0.815424,0.582808,1.165694,1.210199,5.349532,1.680305,1.464581,...,4.233775,2.168477,0.023998,0.417141,7.311981,2.212388,10.930827,-1.452808,non-void,1

## Data 2
classes: void, non-void

fs: original

overlap: 0

sliding window: 2s

filename: two_class_raw_2s_no.csv

In [12]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=2.0, overlap=0.0)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.30it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 26.74it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.56it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.16it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.68it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.42it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.93it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.57it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.60it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.05it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.74it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.41it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.55it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.44it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 30.09it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.35it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 24.16it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.82it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 27.12it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 28.58it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 27.64it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.43it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.06it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.78it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.08it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.11it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.49it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.87it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 26.94it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.01it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.90it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 32.28it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.27it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.57it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.67it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.63it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.91it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.29it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 26.56it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.19it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 24.96it/s]

In [13]:
final_features.to_csv('improved_features_data_main/two_class_raw_2s_no.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,0.999186,0.000000,1.998371,0.837517,0.656083,1.027208,1.005637,5.349532,1.437520,1.011306,...,4.210266,2.685595,0.045715,0.138766,7.530395,1.485243,7.823790,-7.928376,non-void,1
1,2.997557,1.998371,3.996743,0.914142,0.780981,0.762864,0.273525,1.507445,0.810418,0.074816,...,4.216358,5.355153,0.189565,0.264783,11.913386,2.050556,7.265505,-4.435249,non-void,1
2,4.995929,3.996743,5.995114,0.911102,0.825743,0.381709,0.479763,3.273455,0.613086,0.230173,...,2.637375,4.147660,0.125559,0.479169,9.893914,3.003664,13.040857,-0.362089,non-void,1
3,6.994300,5.995114,7.993486,0.880385,0.714032,0.842092,0.846989,5.457410,1.194366,0.717390,...,5.555974,4.448240,0.188434,0.117977,11.186629,1.356856,6.042452,-8.736818,non-void,1
4,8.992671,7.993486,9.991857,0.915965,0.812030,0.565058,0.443517,2.956667,0.718330,0.196707,...,2.867927,4.054715,0.072544,0.401812,10.344716,2.305104,8.328354,-1.728156,non-void,1

## Data 2b
classes: void, non-void

fs: original

overlap: 0.5

sliding window: 2s

filename: two_class_raw_2s_yo_0.5.csv

In [14]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=2.0, overlap=0.5)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.03it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.16it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.16it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.96it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.64it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.03it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.98it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.85it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.37it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.68it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.43it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.26it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.85it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.99it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.51it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.28it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.90it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.36it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.65it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.63it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.80it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.20it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.25it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.34it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.17it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.48it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.77it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.40it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.07it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.48it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.12it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.33it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.88it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.38it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.05it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.45it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.43it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.19it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.71it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.61it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.37it/s]

In [15]:
final_features.to_csv('improved_features_data_main/two_class_raw_2s_yo_0.5.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,0.999186,0.000000,1.998371,0.837517,0.656083,1.027208,1.005637,5.349532,1.437520,1.011306,...,4.210266,2.685595,0.045715,0.138766,7.530395,1.485243,7.823790,-7.928376,non-void,1
1,1.998371,0.999186,2.997557,0.872310,0.644016,0.960179,0.643429,3.553001,1.155831,0.414001,...,1.554765,2.285525,0.037806,0.548477,7.611644,5.216276,42.900194,0.844792,non-void,1
2,2.997557,1.998371,3.996743,0.914142,0.780981,0.762864,0.273525,1.507445,0.810418,0.074816,...,4.216358,5.355153,0.189565,0.264783,11.913386,2.050556,7.265505,-4.435249,non-void,1
3,3.996743,2.997557,4.995929,0.909732,0.722111,0.654615,0.272212,1.507445,0.708957,0.074099,...,4.400715,4.280577,0.122783,0.135475,11.686805,1.561870,5.068502,-8.049201,non-void,1
4,4.995929,3.996743,5.995114,0.911102,0.825743,0.381709,0.479763,3.273455,0.613086,0.230173,...,2.637375,4.147660,0.125559,0.479169,9.893914,3.003664,13.040857,-0.362089,non-void,1

## Data 2c
classes: void, non-void

fs: original

overlap: 0.8

sliding window: 2s

filename: two_class_raw_2s_yo_0.8.csv

In [16]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=2.0, overlap=0.8)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.43it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.51it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.24it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.61it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.80it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.76it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.45it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.59it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.38it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.91it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.03it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.43it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.90it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.04it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.70it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.11it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.60it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.13it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.54it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.40it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.38it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.16it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.89it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.28it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.32it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.95it/s]
Analyzing : 100%|██████████| 8/8 [00:05<00:00,  1.46it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.51it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.65it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.00it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.92it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.97it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.32it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.32it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.20it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.40it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.92it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.56it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.35it/s]
Analyzing : 100%|██████████| 8/8 [00:08<00:00,  1.02s/it]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.59it/s]

In [17]:
final_features.to_csv('improved_features_data_main/two_class_raw_2s_yo_0.8.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,0.999186,0.000000,1.998371,0.837517,0.656083,1.027208,1.005637,5.349532,1.437520,1.011306,...,4.210266,2.685595,0.045715,0.138766,7.530395,1.485243,7.823790,-7.928376,non-void,1
1,1.388699,0.389513,2.387885,0.856472,0.634105,1.049054,0.936724,5.349532,1.406402,0.877451,...,2.941457,2.428876,0.018062,0.256845,8.128318,1.595079,8.256730,-4.614092,non-void,1
2,1.778212,0.779026,2.777398,0.866184,0.638264,0.996176,0.888607,5.349532,1.334912,0.789622,...,1.835055,2.061409,0.022764,0.444376,7.743594,3.246126,23.742008,-0.970309,non-void,1
3,2.167725,1.168539,3.166911,0.878813,0.663285,0.929198,0.584101,3.553001,1.097535,0.341174,...,1.750001,3.143792,0.073959,0.627298,7.975435,4.514501,27.936459,2.261127,non-void,1
4,2.557238,1.558052,3.556424,0.905723,0.782317,0.762776,0.265824,1.479456,0.807768,0.070662,...,4.716907,5.377161,0.227554,0.195576,11.546377,1.867454,6.718064,-6.141682,non-void,1

## Data 3
classes: void, non-void

fs: original

overlap: 0

sliding window: 3s

filename: two_class_raw_3s_no.csv

In [20]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=3.0, overlap=0.0)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 26.90it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 38.47it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.77it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 26.03it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 42.55it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.71it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 32.09it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 33.95it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.16it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 22.17it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.77it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.39it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 29.35it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 22.38it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 47.09it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 36.38it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 36.43it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.22it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 38.45it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 42.30it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 39.55it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.55it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 29.26it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.74it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.28it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.26it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.06it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 31.84it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 39.53it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 30.29it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 27.36it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 46.68it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 30.92it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 39.01it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 22.78it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 24.95it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.14it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 33.06it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 39.16it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.48it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 35.55it/s]

In [21]:
final_features.to_csv('improved_features_data_main/two_class_raw_3s_no.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,1.498779,0.000000,2.997557,0.868352,0.694367,0.953067,0.839825,5.349532,1.270292,0.705305,...,2.461041,2.506423,0.022774,0.266252,7.726912,1.861881,9.498110,-4.402532,non-void,1
1,4.496336,2.997557,5.995114,0.919605,0.790731,0.494788,0.455654,3.273455,0.672633,0.207621,...,3.861172,4.668567,0.132210,0.218693,10.305278,1.800977,6.169655,-5.529856,non-void,1
2,7.493893,5.995114,8.992671,0.903234,0.730563,0.758589,0.711104,5.457410,1.039772,0.505669,...,5.470428,4.032702,0.138253,0.101895,10.879283,1.268957,5.823152,-9.451749,non-void,1
3,10.491450,8.992671,11.990229,0.873187,0.787136,0.635391,0.492101,2.956667,0.803670,0.242164,...,2.297263,3.427390,0.072944,0.411297,10.469553,2.801351,12.751083,-1.557411,non-void,1
4,13.489007,11.990229,14.987786,0.915277,0.765171,0.386718,0.475147,3.601410,0.612630,0.225764,...,3.683765,4.274507,0.108906,0.131188,11.523342,1.792527,6.080342,-8.210314,non-void,1

## Data 3b
classes: void, non-void

fs: original

overlap: 0.5

sliding window: 3s

filename: two_class_raw_3s_yo_0.5.csv

In [22]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=3.0, overlap=0.5)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.75it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.59it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.91it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.77it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.61it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.93it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.51it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.10it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.33it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.80it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.73it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.97it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.65it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.78it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.06it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.67it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.31it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.85it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.67it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.56it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.63it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.85it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.99it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.15it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.69it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.99it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.44it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.52it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.33it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.83it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.52it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.10it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.54it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.79it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.73it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.27it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.78it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.46it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.50it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.78it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.53it/s]

In [23]:
final_features.to_csv('improved_features_data_main/two_class_raw_3s_yo_0.5.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,1.498779,0.000000,2.997557,0.868352,0.694367,0.953067,0.839825,5.349532,1.270292,0.705305,...,2.461041,2.506423,0.022774,0.266252,7.726912,1.861881,9.498110,-4.402532,non-void,1
1,2.989089,1.490311,4.487868,0.906822,0.799264,0.731636,0.286953,1.507445,0.785897,0.082342,...,2.902116,4.373274,0.120202,0.368178,11.168543,2.669813,11.228383,-2.345368,non-void,1
2,4.479400,2.980622,5.978179,0.919605,0.791796,0.483426,0.432560,2.498092,0.648698,0.187108,...,3.968988,4.685634,0.136108,0.196031,10.783502,1.756885,5.986617,-6.129133,non-void,1
3,5.969711,4.470933,7.468490,0.892201,0.713119,0.548849,0.809403,5.457410,0.977941,0.655133,...,2.312049,2.995658,0.057945,0.174233,10.887106,3.474177,19.055846,-6.757281,non-void,1
4,7.460022,5.961244,8.958801,0.902390,0.730050,0.776208,0.723594,5.457410,1.061172,0.523588,...,5.497719,4.060469,0.136958,0.100459,10.795328,1.275731,5.857152,-9.520320,non-void,1

## Data 3c
classes: void, non-void

fs: original

overlap: 0.8

sliding window: 3s

filename: two_class_raw_3s_yo_0.8.csv

In [24]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=3.0, overlap=0.8)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.14it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.00it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.87it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.43it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.87it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.13it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.69it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.92it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.77it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.59it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.19it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.69it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.02it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.73it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.43it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.53it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.51it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.18it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.61it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.73it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.20it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.65it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.03it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.94it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.55it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.37it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.14it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.52it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.43it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.04it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.78it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.28it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.36it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.69it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.71it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.07it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.44it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.19it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.18it/s]
Analyzing : 100%|██████████| 8/8 [00:05<00:00,  1.53it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.34it/s]

In [25]:
final_features.to_csv('improved_features_data_main/two_class_raw_3s_yo_0.8.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,1.498779,0.000000,2.997557,0.868352,0.694367,0.953067,0.839825,5.349532,1.270292,0.705305,...,2.461041,2.506423,0.022774,0.266252,7.726912,1.861881,9.498110,-4.402532,non-void,1
1,2.091516,0.592737,3.590294,0.891024,0.700772,0.937189,0.752365,5.349532,1.201822,0.566053,...,1.583183,2.266877,0.029356,0.478029,8.301187,3.869287,28.466800,-0.381925,non-void,1
2,2.684253,1.185475,4.183032,0.904307,0.779004,0.836695,0.516392,3.553001,0.983219,0.266661,...,1.705613,3.568219,0.069833,0.698554,8.725039,3.870708,20.551180,3.649895,non-void,1
3,3.276990,1.778212,4.775769,0.900103,0.797495,0.724808,0.273863,1.507445,0.774821,0.075001,...,3.262713,4.221081,0.117658,0.202735,11.859443,2.446862,10.084393,-5.946738,non-void,1
4,3.869728,2.370949,5.368506,0.917587,0.797179,0.654555,0.289030,1.550907,0.715528,0.083538,...,3.877225,4.234889,0.138326,0.115002,11.831409,1.860618,6.621215,-8.862387,non-void,1

## Data 4
classes: void, non-void

fs: original

overlap: 0.0

sliding window: 4s

filename: two_class_raw_4s_no.csv

In [26]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=4.0, overlap=0.0)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 36.09it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 37.73it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 30.23it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 32.17it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 56.45it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.87it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 41.50it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 45.53it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 24.50it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 27.71it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.06it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 22.30it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 36.53it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 29.63it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 65.56it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 50.47it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 44.34it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.14it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 51.81it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 54.69it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 50.50it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 22.54it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 37.14it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 30.81it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.57it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 29.42it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.32it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 41.53it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 50.73it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 38.97it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 38.17it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 65.92it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 41.30it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 50.72it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 31.40it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 32.99it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 28.83it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 45.88it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 50.70it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.80it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 44.21it/s]

In [27]:
final_features.to_csv('improved_features_data_main/two_class_raw_4s_no.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,1.998371,0.000000,3.996743,0.888082,0.724174,0.895036,0.748686,5.349532,1.166885,0.560530,...,1.757958,2.363537,0.023546,0.378289,7.993584,2.792905,16.875743,-2.157651,non-void,1
1,5.995114,3.996743,7.993486,0.900675,0.721296,0.611901,0.725789,5.457410,0.949311,0.526770,...,2.370783,3.211427,0.070162,0.176927,10.877452,3.269067,16.924244,-6.676436,non-void,1
2,9.991857,7.993486,11.990229,0.901749,0.809333,0.624439,0.438269,2.956667,0.762892,0.192080,...,2.280468,3.244797,0.049070,0.202000,10.298491,2.742677,11.523219,-5.966507,non-void,1
3,13.988600,11.990229,15.986972,0.917454,0.790501,0.295423,0.460685,3.601410,0.547271,0.212231,...,3.594969,4.297765,0.106973,0.149105,11.390399,1.948610,7.025725,-7.563844,non-void,1
4,17.985343,15.986972,19.983714,0.922168,0.631454,0.394139,1.000649,5.412671,1.075474,1.001298,...,1.803849,2.919558,0.046947,0.370729,9.376217,3.296280,16.508770,-2.297819,void,1

## Data 4b
classes: void, non-void

fs: original

overlap: 0.5

sliding window: 4s

filename: two_class_raw_4s_yo_0.5.csv

In [30]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=4.0, overlap=0.5)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.52it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 26.83it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.47it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.54it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 29.40it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.68it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.40it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.49it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.32it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.27it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.51it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.07it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.93it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.59it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 33.54it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.83it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 24.62it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.74it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 28.90it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 28.64it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 27.57it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.30it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.48it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.39it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.16it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.78it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.14it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 22.67it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 27.31it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.36it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.28it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 33.49it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.47it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.67it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.41it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.67it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.58it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 22.49it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 27.22it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.94it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 24.76it/s]

In [31]:
final_features.to_csv('improved_features_data_main/two_class_raw_4s_yo_0.5.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,1.998371,0.000000,3.996743,0.888082,0.724174,0.895036,0.748686,5.349532,1.166885,0.560530,...,1.757958,2.363537,0.023546,0.378289,7.993584,2.792905,16.875743,-2.157651,non-void,1
1,3.996743,1.998371,5.995114,0.916050,0.817238,0.572287,0.434528,3.273455,0.718559,0.188814,...,4.014628,4.407476,0.146710,0.096566,10.605104,1.838920,6.530791,-9.710707,non-void,1
2,5.995114,3.996743,7.993486,0.900675,0.721296,0.611901,0.725789,5.457410,0.949311,0.526770,...,2.370783,3.211427,0.070162,0.176927,10.877452,3.269067,16.924244,-6.676436,non-void,1
3,7.993486,5.995114,9.991857,0.908323,0.745699,0.703575,0.690098,5.457410,0.985522,0.476235,...,4.945471,3.917865,0.106546,0.089000,10.796953,1.313625,5.522609,-10.101282,non-void,1
4,9.991857,7.993486,11.990229,0.901749,0.809333,0.624439,0.438269,2.956667,0.762892,0.192080,...,2.280468,3.244797,0.049070,0.202000,10.298491,2.742677,11.523219,-5.966507,non-void,1

## Data 4c
classes: void, non-void

fs: original

overlap: 0.8

sliding window: 4s

filename: two_class_raw_4s_yo_0.8.csv

In [32]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=4.0, overlap=0.8)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.01it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.90it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.36it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.10it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.89it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.44it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.53it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.43it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.90it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.05it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.16it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.77it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.81it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.28it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.01it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.55it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.05it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.23it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.67it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.03it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.12it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.84it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.15it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.60it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.88it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.02it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.94it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.01it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.52it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.20it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.65it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.14it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.47it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.78it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.30it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.60it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.81it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.30it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.13it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.95it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.67it/s]

In [33]:
final_features.to_csv('improved_features_data_main/two_class_raw_4s_yo_0.8.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,1.998371,0.000000,3.996743,0.888082,0.724174,0.895036,0.748686,5.349532,1.166885,0.560530,...,1.757958,2.363537,0.023546,0.378289,7.993584,2.792905,16.875743,-2.157651,non-void,1
1,2.794333,0.795962,4.792704,0.888588,0.758875,0.833254,0.676522,5.349532,1.073310,0.457682,...,1.440627,2.949622,0.049368,0.592436,8.564711,4.304169,26.515211,1.624452,non-void,1
2,3.590294,1.591923,5.588666,0.914118,0.829681,0.643343,0.329404,1.727885,0.722771,0.108507,...,3.544588,4.260239,0.139328,0.124713,11.746799,2.088974,7.902043,-8.462379,non-void,1
3,4.386256,2.387885,6.384627,0.918808,0.782531,0.602633,0.553150,3.840626,0.818011,0.305975,...,3.488677,4.348005,0.119989,0.162421,10.491200,2.027482,7.367323,-7.123842,non-void,1
4,5.182217,3.183846,7.180589,0.906615,0.724715,0.569451,0.682941,5.457410,0.889204,0.466409,...,1.897575,2.877078,0.054205,0.258576,11.184598,3.731776,21.370457,-4.574787,non-void,1

## Data 5
classes: void, non-void

fs: original

overlap: 0.0

sliding window: 5s

filename: two_class_raw_5s_no.csv

In [34]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=5.0, overlap=0.0)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 41.14it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 60.81it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 36.69it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 40.51it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 61.33it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 30.98it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 48.41it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 55.43it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 29.50it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 33.71it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 24.77it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 28.97it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 44.32it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 29.88it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 72.55it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 47.78it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 48.72it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.06it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 63.20it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 72.88it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 62.09it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 27.13it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 49.02it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 37.16it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 28.18it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 34.57it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.39it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 49.82it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 62.83it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 49.33it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 44.38it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 73.22it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 48.29it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 63.87it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 37.98it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 40.48it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 34.59it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 55.39it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 63.02it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.99it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 52.40it/s]

In [35]:
final_features.to_csv('improved_features_data_main/two_class_raw_5s_no.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,2.497964,0.000000,4.995929,0.888117,0.737073,0.833686,0.688622,5.349532,1.081311,0.474200,...,1.617072,2.350395,0.024553,0.404284,8.245249,3.127276,19.880895,-1.683529,non-void,1
1,7.493893,4.995929,9.991857,0.911608,0.753020,0.597887,0.699962,5.457410,0.920552,0.489947,...,4.690571,4.341615,0.148484,0.108091,10.561185,1.606723,6.546609,-9.165319,non-void,1
2,12.489822,9.991857,14.987786,0.897663,0.801344,0.505559,0.478334,3.601410,0.695984,0.228804,...,2.973004,3.450777,0.086805,0.181868,11.101539,2.734657,12.686831,-6.530662,non-void,1
3,17.485750,14.987786,19.983714,0.924754,0.681130,0.319619,0.915191,5.412671,0.969397,0.837574,...,3.821186,4.318341,0.106302,0.295233,9.701800,1.645202,6.218948,-3.778817,void,1
4,22.481679,19.983714,24.979643,0.944870,0.844899,0.984424,0.390305,2.799139,1.058975,0.152338,...,4.889428,4.922858,0.183170,0.145711,11.683898,1.875272,7.333640,-7.681112,void,1

## Data 5b
classes: void, non-void

fs: original

overlap: 0.5

sliding window: 5s

filename: two_class_raw_5s_yo_0.5.csv

In [36]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=5.0, overlap=0.5)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 22.33it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 31.51it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.22it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.52it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 33.31it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.00it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 26.72it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 28.37it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.04it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.04it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.67it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.15it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.40it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.77it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 40.16it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 31.66it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 30.17it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.80it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 34.11it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 36.20it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 32.18it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.61it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.16it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.71it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.84it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.37it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.86it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 26.80it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 34.56it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.13it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.04it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 40.57it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 26.21it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 31.97it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.77it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.56it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.91it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 29.84it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 34.63it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.01it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 30.02it/s]

In [37]:
final_features.to_csv('improved_features_data_main/two_class_raw_5s_yo_0.5.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,2.497964,0.000000,4.995929,0.888117,0.737073,0.833686,0.688622,5.349532,1.081311,0.474200,...,1.617072,2.350395,0.024553,0.404284,8.245249,3.127276,19.880895,-1.683529,non-void,1
1,4.987461,2.489497,7.485425,0.898142,0.746140,0.620001,0.656198,5.457410,0.902772,0.430596,...,2.450661,3.649857,0.083254,0.249120,11.027673,2.801303,12.268361,-4.791626,non-void,1
2,7.476958,4.978993,9.974922,0.911677,0.752174,0.599177,0.699707,5.457410,0.921197,0.489590,...,4.651736,4.342851,0.147285,0.109168,10.579421,1.622638,6.595524,-9.116990,non-void,1
3,9.966454,7.468490,12.464418,0.909585,0.818971,0.636508,0.432122,2.956667,0.769332,0.186729,...,2.372533,3.329026,0.049887,0.170858,10.259312,2.633681,10.589064,-6.859946,non-void,1
4,12.455951,9.957987,14.953915,0.899875,0.801243,0.507144,0.476810,3.601410,0.696092,0.227348,...,2.952632,3.422863,0.084961,0.179897,11.080950,2.760638,12.915935,-6.588454,non-void,1

## Data 5c
classes: void, non-void

fs: original

overlap: 0.8

sliding window: 5s

filename: two_class_raw_5s_yo_0.8.csv

In [38]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=5.0, overlap=0.8)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.77it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.25it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.69it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.56it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.42it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.67it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.78it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.13it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.09it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.49it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.14it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.06it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.80it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.67it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.26it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.52it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.17it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.09it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.30it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.95it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.32it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.76it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.86it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.02it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.68it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.23it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.52it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.10it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.88it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.86it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.36it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.53it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.13it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.82it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.62it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.18it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.07it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.07it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.74it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.40it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.27it/s]

In [39]:
final_features.to_csv('improved_features_data_main/two_class_raw_5s_yo_0.8.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,2.497964,0.000000,4.995929,0.888117,0.737073,0.833686,0.688622,5.349532,1.081311,0.474200,...,1.617072,2.350395,0.024553,0.404284,8.245249,3.127276,19.880895,-1.683529,non-void,1
1,3.480215,0.982250,5.978179,0.903643,0.831037,0.669089,0.585473,4.363070,0.889078,0.342779,...,2.222707,3.726635,0.084080,0.403024,9.043875,2.993030,13.751198,-1.706252,non-void,1
2,4.462465,1.964501,6.960429,0.908870,0.749159,0.646192,0.548827,3.840626,0.847806,0.301211,...,3.681019,4.372275,0.134324,0.119460,11.457835,1.949541,7.037544,-8.675283,non-void,1
3,5.444715,2.946751,7.942680,0.907880,0.743695,0.628383,0.661715,5.457410,0.912541,0.437867,...,1.930021,2.955711,0.056641,0.238822,11.040642,3.624378,20.095024,-5.034129,non-void,1
4,6.426966,3.929001,8.924930,0.908219,0.746226,0.612415,0.656816,5.457410,0.898031,0.431407,...,2.507182,3.363227,0.079969,0.167024,10.688664,3.083834,15.269799,-6.978540,non-void,1

## Three class data

## Data 6
classes: pre-void, void, non-void

fs: original

overlap: 0.0

sliding window: 1s

filename: three_class_raw_1s_no.csv

In [7]:
labelled_imu_dict = {}
dict = copy.deepcopy(imu_dict)
for i_void_instance, void_instance in tqdm(enumerate(dict.keys()), desc="Adding labels to IMU data"):
    acc = dict[void_instance]
    gt = ground_truth_dict[void_instance]
    
    # normalize data
    df = normalize(acc)
    
    # add the labels
    labelled_df = three_class_labels(df, gt)
    
    labelled_imu_dict[void_instance] = labelled_df

Adding labels to IMU data: 0it [00:00, ?it/s]

Adding labels to IMU data: 41it [00:00, 287.77it/s]

In [6]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=1.0, overlap=0.0)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.86it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.68it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.61it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.91it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.60it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.73it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.40it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.09it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.18it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.87it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.53it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.55it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.69it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.75it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.88it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.93it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.68it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.30it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.03it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.25it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.67it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.04it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.02it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.81it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.18it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.68it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.56it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.40it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.23it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.03it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.67it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.90it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.82it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.74it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.23it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.17it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.66it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.58it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.76it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.15it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.51it/s]

In [ ]:
final_features.to_csv('features_data_main/three_class_raw_1s_no.csv', index=False)
# final_features.head()

## Data 6b
classes: pre-void, void, non-void

fs: original

overlap: 0.5

sliding window: 1s

filename: three_class_raw_1s_yo_0.5.csv

In [ ]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=1.0, overlap=0.5)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

In [ ]:
final_features.to_csv('features_data_main/three_class_raw_1s_yo_0.5.csv', index=False)

## Data 6c
classes: pre-void, void, non-void

fs: original

overlap: 0.8

sliding window: 1s

filename: three_class_raw_1s_yo_0.8.csv

In [13]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=1.0, overlap=0.8)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.49it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.28it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.95it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.16it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.42it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.66it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.64it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.79it/s]
Analyzing : 100%|██████████| 8/8 [00:05<00:00,  1.47it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.81it/s]
Analyzing : 100%|██████████| 8/8 [00:06<00:00,  1.26it/s]
Analyzing : 100%|██████████| 8/8 [00:07<00:00,  1.10it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.40it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.91it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.04it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.15it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.11it/s]
Analyzing : 100%|██████████| 8/8 [00:05<00:00,  1.34it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.48it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.58it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.38it/s]
Analyzing : 100%|██████████| 8/8 [00:05<00:00,  1.55it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.58it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.11it/s]
Analyzing : 100%|██████████| 8/8 [00:05<00:00,  1.55it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.92it/s]
Analyzing : 100%|██████████| 8/8 [00:08<00:00,  1.07s/it]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.74it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.37it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.50it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.39it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.15it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.48it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.08it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.99it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.06it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.76it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.81it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.11it/s]
Analyzing : 100%|██████████| 8/8 [00:13<00:00,  1.68s/it]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.96it/s]

In [ ]:
final_features.to_csv('features_data_main/three_class_raw_1s_yo_0.8.csv', index=False)

## Data 7
classes: pre-void, void, non-void

fs: original

overlap: 0.0

sliding window: 2s

filename: three_class_raw_2s_no.csv

In [15]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=2.0, overlap=0.0)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.88it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 34.09it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.52it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.81it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 34.69it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.31it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 26.67it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 28.14it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.42it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.74it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.16it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.94it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.42it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.60it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 39.79it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 31.63it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 30.46it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.23it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 32.21it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 32.94it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 33.69it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.59it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 24.75it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.71it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.59it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.19it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.28it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 27.13it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 33.96it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.32it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 24.02it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 40.42it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 27.23it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 32.45it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.94it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.50it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.78it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 29.36it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 34.40it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.08it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 30.62it/s]

In [ ]:
final_features.to_csv('features_data_main/three_class_raw_2s_no.csv', index=False)

## Data 7b
classes: pre-void, void, non-void

fs: original

overlap: 0.5

sliding window: 2s

filename: three_class_raw_2s_yo_0.5.csv

In [17]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=2.0, overlap=0.5)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.86it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.38it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.22it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.44it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.33it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.52it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.94it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.62it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.08it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.58it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.85it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.71it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.52it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.16it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.95it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.06it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.68it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.75it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.56it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.88it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.35it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.71it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.89it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.48it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.78it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.53it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.71it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.26it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.19it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.79it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.33it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.33it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.55it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.99it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.09it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.77it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.34it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.52it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.97it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.16it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.45it/s]

In [ ]:
final_features.to_csv('features_data_main/three_class_raw_2s_yo_0.5.csv', index=False)

## Data 7c
classes: pre-void, void, non-void

fs: original

overlap: 0.8

sliding window: 2s

filename: three_class_raw_2s_yo_0.8.csv

In [7]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=2.0, overlap=0.8)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.98it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.10it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.91it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.34it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.90it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.32it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.33it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.58it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.01it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.58it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.58it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.00it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.69it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.73it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.55it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.20it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.17it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.63it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.73it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.80it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.54it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.85it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.86it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.37it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.74it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.53it/s]
Analyzing : 100%|██████████| 8/8 [00:05<00:00,  1.49it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.81it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.05it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.24it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.48it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.23it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.33it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.61it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.56it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.79it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.85it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.36it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.11it/s]
Analyzing : 100%|██████████| 8/8 [00:06<00:00,  1.17it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.64it/s]

In [ ]:
final_features.to_csv('features_data_main/three_class_raw_2s_yo_0.8.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_std,gyr_mag_range,gyr_mag_rms,gyr_mag_var,gyr_mag_min,gyr_mag_max,gyr_mag_time_energy,gyr_mag_spectral_energy,label,experiment_id
0,0.999186,0.000000,1.998371,0.837517,0.656083,1.027208,1.005637,5.349532,1.437520,1.011306,...,1.742222,7.487364,3.090512,3.035336,0.262540,7.749904,1127.049263,132991.813018,pre-void,1
1,1.388699,0.389513,2.387885,0.856472,0.634105,1.049054,0.936724,5.349532,1.406402,0.877451,...,1.787973,7.614706,2.800308,3.196848,0.135198,7.749904,925.323664,109188.192384,pre-void,1
2,1.778212,0.779026,2.777398,0.866184,0.638264,0.996176,0.888607,5.349532,1.334912,0.789622,...,1.741895,7.657108,2.450640,3.034198,0.092797,7.749904,708.665105,83622.482415,pre-void,1
3,2.167725,1.168539,3.166911,0.878813,0.663285,0.929198,0.584101,3.553001,1.097535,0.341174,...,1.502970,7.657108,1.939446,2.258920,0.092797,7.749904,443.851412,52374.466635,pre-void,1
4,2.557238,1.558052,3.556424,0.905723,0.782317,0.762776,0.265824,1.479456,0.807768,0.070662,...,0.436316,3.250805,0.733959,0.190372,0.076565,3.327370,63.566144,7500.804959,pre-void,1

## Data 8
classes: pre-void, void, non-void

fs: original

overlap: 0.0

sliding window: 3s

filename: three_class_raw_3s_no.csv

In [19]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=3.0, overlap=0.0)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 32.03it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 47.14it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 28.80it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 32.40it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 51.58it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.83it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 39.30it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 41.51it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 22.18it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 26.97it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.62it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.67it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 36.02it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 26.06it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 44.89it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 43.49it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 46.04it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.95it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 50.64it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 51.85it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 46.88it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.32it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 35.24it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 28.78it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.94it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.32it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.44it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 39.62it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 47.97it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 36.38it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 33.74it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 57.74it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 38.84it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 48.86it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 28.44it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 29.07it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.55it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 42.11it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 48.95it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.92it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 44.70it/s]

In [ ]:
final_features.to_csv('features_data_main/three_class_raw_3s_no.csv', index=False)

## Data 8b
classes: pre-void, void, non-void

fs: original

overlap: 0.5

sliding window: 3s

filename: three_class_raw_3s_yo_0.5.csv

In [22]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=3.0, overlap=0.5)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.21it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.19it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.79it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.12it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.58it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.06it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.09it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.18it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.33it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.41it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.16it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.56it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.49it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.45it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 31.15it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 22.93it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 22.52it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.27it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 26.36it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 27.10it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.77it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.56it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.66it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.02it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.98it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.08it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.87it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.52it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.67it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.55it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.54it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 28.79it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.02it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.45it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.32it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.81it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.91it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.93it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.47it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.67it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 22.77it/s]

In [ ]:
final_features.to_csv('features_data_main/three_class_raw_3s_yo_0.5.csv', index=False)

## Data 8c
classes: pre-void, void, non-void

fs: original

overlap: 0.8

sliding window: 3s

filename: three_class_raw_3s_yo_0.8.csv

In [24]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=3.0, overlap=0.8)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.72it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.28it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.55it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.24it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.92it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.11it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.20it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.05it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.74it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.80it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.01it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.68it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.01it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.80it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.52it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.74it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.70it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.99it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.30it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.16it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.18it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.57it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.49it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.19it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.52it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.62it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.74it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.42it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.66it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.56it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.93it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.11it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.97it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.94it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.58it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.38it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.27it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.85it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.35it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.84it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.94it/s]

In [ ]:
final_features.to_csv('features_data_main/three_class_raw_3s_yo_0.8.csv', index=False)

## Data 9
classes: pre-void, void, non-void

fs: original

overlap: 0.0

sliding window: 4s

filename: three_class_raw_4s_no.csv

In [26]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=4.0, overlap=0.0)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 41.48it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 59.54it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 30.49it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 38.17it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 67.80it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 31.16it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 51.51it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 55.47it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 29.58it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 33.73it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.71it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 27.96it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 46.29it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 37.34it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 77.49it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 58.72it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 55.36it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.18it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 69.67it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 67.93it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 62.31it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 27.42it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 40.05it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 37.70it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 27.71it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 35.86it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.92it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 47.00it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 40.76it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 46.20it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 46.71it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 80.06it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 48.57it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 63.95it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 37.61it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 37.05it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 35.07it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 57.56it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 63.36it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.26it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 57.60it/s]

In [ ]:
final_features.to_csv('features_data_main/three_class_raw_4s_no.csv', index=False)

## Data 9b
classes: pre-void, void, non-void

fs: original

overlap: 0.5

sliding window: 4s

filename: three_class_raw_4s_yo_0.5.csv

In [28]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=4.0, overlap=0.5)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 22.99it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 33.33it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.16it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.71it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 34.29it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.70it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 26.16it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 28.11it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.29it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.40it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.95it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.79it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.06it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.13it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 39.57it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 31.66it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 30.31it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.23it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 36.13it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 34.96it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 32.77it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.84it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.46it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.11it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.94it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.43it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.47it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 27.71it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 34.26it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 24.92it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 24.08it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 36.30it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.47it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 31.85it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.09it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.68it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.03it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 27.87it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 33.49it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.14it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 29.38it/s]

In [ ]:
final_features.to_csv('features_data_main/three_class_raw_4s_yo_0.5.csv', index=False)

## Data 9c
classes: pre-void, void, non-void

fs: original

overlap: 0.8

sliding window: 4s

filename: three_class_raw_4s_yo_0.8.csv

In [30]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=4.0, overlap=0.8)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.29it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.66it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.72it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.97it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.77it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.84it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.77it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.85it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.22it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.53it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.21it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.15it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.41it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.82it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.21it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.23it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.75it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.32it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.80it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.10it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.80it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.94it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.33it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.10it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.92it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.56it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.55it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.41it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.44it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.34it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.72it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.89it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.86it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.36it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.89it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.83it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.34it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.04it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.92it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.48it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.36it/s]

In [31]:
final_features.to_csv('features_data_main/three_class_raw_4s_yo_0.8.csv', index=False)

## Data 10
classes: pre-void, void, non-void

fs: original

overlap: 0.0

sliding window: 5s

filename: three_class_raw_5s_no.csv

In [32]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=5.0, overlap=0.0)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 54.29it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 77.59it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 45.20it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 50.82it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 78.33it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 39.28it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 59.57it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 67.45it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 37.27it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 43.21it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 31.21it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 36.95it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 53.54it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 44.41it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 84.14it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 74.59it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 65.12it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 31.11it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 73.41it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 86.99it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 73.11it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 30.37it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 59.07it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 46.76it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 35.61it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 42.43it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.05it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 61.32it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 76.17it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 60.30it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 50.54it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 92.49it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 52.39it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 78.83it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 45.87it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 49.39it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 43.28it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 70.03it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 78.92it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.69it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 67.72it/s]

In [33]:
final_features.to_csv('features_data_main/three_class_raw_5s_no.csv', index=False)

## Data 10b
classes: pre-void, void, non-void

fs: original

overlap: 0.5

sliding window: 5s

filename: three_class_raw_5s_yo_0.5.csv

In [8]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=5.0, overlap=0.5)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.56it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 34.87it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.97it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.04it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 37.57it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.56it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 28.93it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 31.72it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.48it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.84it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.82it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.85it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.27it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.90it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 44.52it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 34.59it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 33.40it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.07it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 37.85it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 33.01it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 34.10it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.30it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 27.12it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 22.82it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.91it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.44it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.65it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 28.31it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 37.97it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 27.48it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.27it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 48.82it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 29.12it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 36.01it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.34it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 22.88it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.06it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 30.99it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 36.95it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.73it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 32.74it/s]

In [9]:
final_features.to_csv('features_data_main/three_class_raw_5s_yo_0.5.csv', index=False)

## Data 10c
classes: pre-void, void, non-void

fs: original

overlap: 0.8

sliding window: 5s

filename: three_class_raw_5s_yo_0.8.csv

In [36]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=5.0, overlap=0.8)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.30it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.65it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.22it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.51it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.15it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.09it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.60it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.20it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.45it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.30it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.12it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.55it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.29it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.03it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.12it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.78it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.80it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.38it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.00it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.78it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.68it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.29it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.53it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.29it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.25it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.82it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.33it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.00it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.08it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.40it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.98it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.99it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.07it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.32it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.85it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.66it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.00it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.75it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.98it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.05it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.34it/s]

In [37]:
final_features.to_csv('features_data_main/three_class_raw_5s_yo_0.8.csv', index=False)

## Validation data

In [3]:
val_dict = {}

val_dict['subj_11_void2'] = imu_dict['subj_11_void2']
val_dict['subj_9_void4'] = imu_dict['subj_9_void4']

In [4]:
labelled_imu_dict = {}
dict = copy.deepcopy(val_dict)
for i_void_instance, void_instance in tqdm(enumerate(dict.keys()), desc="Adding labels to IMU data"):
    acc = dict[void_instance]
    gt = ground_truth_dict[void_instance]
    
    # normalize data
    df = normalize(acc)
    
    # add the labels
    labelled_df = two_class_labels(df, gt)

    labelled_imu_dict[void_instance] = labelled_df

Adding labels to IMU data: 2it [00:00, 205.45it/s]

In [5]:
#  do not upsample
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(70, window_duration=2.0, overlap=0.8)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.03it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.27it/s]

In [7]:
final_features.to_csv('features_data_main/two_class_val.csv', index=False)
final_features.tail()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_std,gyr_mag_range,gyr_mag_rms,gyr_mag_var,gyr_mag_min,gyr_mag_max,gyr_mag_time_energy,gyr_mag_spectral_energy,label,experiment_id
100,14.114286,13.114286,15.114286,0.930832,0.730233,-1.178798,0.731628,3.633834,1.387388,0.535279,...,1.235417,5.315622,2.251936,1.526256,0.312845,5.628466,709.970431,99395.860359,void,2
101,14.500000,13.500000,15.500000,0.932324,0.733342,-1.144809,0.760778,3.798803,1.374544,0.578783,...,1.139086,5.315622,2.384957,1.297517,0.312845,5.628466,796.322961,111485.214506,void,2
102,14.885714,13.885714,15.885714,0.931391,0.731257,-1.048505,0.811455,3.798803,1.325829,0.658460,...,1.113900,5.315622,2.471362,1.240772,0.312845,5.628466,855.068405,119709.576741,void,2
103,15.271429,14.271429,16.271429,0.925552,0.702774,-1.158220,0.780274,3.798803,1.396532,0.608827,...,1.049136,5.075138,2.483381,1.100686,0.553328,5.628466,863.405358,120876.750124,void,2
104,15.657143,14.657143,16.657143,0.912977,0.796122,-1.147611,0.741121,3.798803,1.366115,0.549260,...,0.735421,2.843374,1.920129,0.540844,0.391111,3.234486,516.165187,72263.126185,void,2

In [24]:
from features_acc_gyr_more import GenerateFeatures

In [25]:
labelled_imu_dict = {}
dict = copy.deepcopy(imu_dict)
for i_void_instance, void_instance in tqdm(enumerate(dict.keys()), desc="Adding labels to IMU data"):
    acc = dict[void_instance]
    gt = ground_truth_dict[void_instance]
    
    # normalize data
    df = normalize(acc)
    
    # add the labels
    labelled_df = two_class_labels(df, gt)
    
    labelled_imu_dict[void_instance] = labelled_df

Adding labels to IMU data: 41it [00:00, 132.89it/s]

In [26]:
#  do not upsample
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=1.0, overlap=0.0)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.05it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.11it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.38it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.36it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.78it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.04it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.24it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.30it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  4.00it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.93it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.25it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.20it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.66it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.41it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.94it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.47it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.60it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.21it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.75it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.89it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.48it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.98it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.95it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.32it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.97it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.86it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.44it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.74it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.64it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.78it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.23it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.56it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.77it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.28it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.62it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.19it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.70it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.46it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.37it/s]
Analyzing : 100%|██████████| 8/8 [00:05<00:00,  1.49it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.55it/s]

In [27]:
final_features.to_csv('more_features_raw_1s_no.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_zero_crossing_rate,gyr_mag_slope,gyr_mag_autocorr_lag1,gyr_mag_peak_count,gyr_mag_skewness,gyr_mag_kurtosis,gyr_mag_iqr,gyr_mag_mad,label,experiment_id
0,0.499593,0.000000,0.999186,0.840598,0.524760,0.938842,1.134729,5.349532,1.472764,1.287610,...,0.0,0.002833,0.815575,7,0.968601,0.099250,1.595640,0.796588,non-void,1
1,1.498779,0.999186,1.998371,0.816380,0.561207,1.115575,0.848165,3.553001,1.401390,0.719385,...,0.0,-0.071335,0.937234,3,1.045409,0.413415,2.704403,1.274651,non-void,1
2,2.497964,1.998371,2.997557,0.892873,0.755155,0.804784,0.245606,1.054752,0.841427,0.060322,...,0.0,-0.006908,0.741973,12,0.618432,-0.063181,0.316204,0.182714,non-void,1
3,3.497150,2.997557,3.996743,0.928689,0.707887,0.720945,0.292908,1.507445,0.778175,0.085795,...,0.0,0.016839,0.869018,8,1.361755,1.778505,0.624453,0.331375,non-void,1
4,4.496336,3.996743,4.995929,0.874944,0.797456,0.588285,0.231525,1.161934,0.632205,0.053604,...,0.0,-0.001478,0.673278,13,0.547656,0.444346,0.410836,0.201083,non-void,1