## Generate feature extracted data based on window size, overlap and class numbers.
1. Extract two class .
2. Extract three class features.

In [1]:
import os
import pickle
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from tqdm import tqdm
from essentials import resample_data, three_class_labels, two_class_labels, normalize
# from acc_features import GenerateFeatures
from features_acc_gyr import GenerateFeatures
import copy

In [2]:
with open('data/df_dict_imu.pkl', 'rb') as f:
    imu_dict = pickle.load(f)
with open('data/df_minze_dict.pkl', 'rb') as f:
    ground_truth_dict = pickle.load(f)
with open('data/df_dict_urineestimate_method1.pkl', 'rb') as f:
    urine_estimate_dict = pickle.load(f)

Remove the data with the almost the entire data being void.
1. subj_9_void4
2. subj_11_void2

In [3]:
del imu_dict['subj_9_void4']
del imu_dict['subj_11_void2']

Extract windowed features from the 3 axis of the accelerometer and the acceleration magnitude.
1. mean
2. rms
3. std
4. range
5. variance
6. min
7. max
8. time energy
9. spectral energy
10. permutation entropy
11. spectral entropy

## Two class data

## Data 1
classes: void, non-void

fs: original

sliding window: 1s

overlap: 0

filename: two_class_raw_1s_no.csv

In [18]:
labelled_imu_dict = {}
dict = copy.deepcopy(imu_dict)
for i_void_instance, void_instance in tqdm(enumerate(dict.keys()), desc="Adding labels to IMU data"):
    acc = dict[void_instance]
    gt = ground_truth_dict[void_instance]
    
    # normalize data
    df = normalize(acc)
    
    # add the labels
    labelled_df = two_class_labels(df, gt)
    
    labelled_imu_dict[void_instance] = labelled_df

Adding labels to IMU data: 0it [00:00, ?it/s]

Adding labels to IMU data: 43it [00:00, 133.94it/s]

In [19]:
#  do not upsample
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=1.0, overlap=0.0)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.45it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.25it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.64it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.02it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.37it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.84it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.79it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.07it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.76it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.32it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.49it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.76it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.14it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.73it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.44it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.54it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.24it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.60it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.98it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.40it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.63it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.56it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.59it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.28it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.72it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.15it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.56it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.77it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.09it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.52it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.15it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.42it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 31.26it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.05it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.09it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.03it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.76it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.37it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.58it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.61it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.02it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.14it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.68it/s]

In [ ]:
final_features.to_csv('features_data_main/two_class_raw_1s_no.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_std,gyr_mag_range,gyr_mag_rms,gyr_mag_var,gyr_mag_min,gyr_mag_max,gyr_mag_time_energy,gyr_mag_spectral_energy,label,experiment_id
0,0.499593,0.000000,0.999186,0.840598,0.524760,0.938842,1.134729,5.349532,1.472764,1.287610,...,1.531820,6.466757,3.178085,2.346471,0.522757,6.989515,595.913308,35158.885176,non-void,1
1,1.498779,0.999186,1.998371,0.816380,0.561207,1.115575,0.848165,3.553001,1.401390,0.719385,...,1.901742,7.487364,3.000384,3.616622,0.262540,7.749904,531.135955,31337.021333,non-void,1
2,2.497964,1.998371,2.997557,0.892873,0.755155,0.804784,0.245606,1.054752,0.841427,0.060322,...,0.260639,1.076729,0.559115,0.067933,0.092797,1.169525,18.443960,1088.193632,non-void,1
3,3.497150,2.997557,3.996743,0.928689,0.707887,0.720945,0.292908,1.507445,0.778175,0.085795,...,0.578422,2.648913,1.046190,0.334572,0.076565,2.725477,64.576255,3809.999061,non-void,1
4,4.496336,3.996743,4.995929,0.874944,0.797456,0.588285,0.231525,1.161934,0.632205,0.053604,...,0.344607,1.593548,0.929221,0.118754,0.280080,1.873628,50.943675,3005.676845,non-void,1

## Data 1b
classes: void, non-void

fs: original

sliding window: 1s

overlap: 0.5

filename: two_class_raw_1s_yo_0.5.csv

In [7]:
#  do not upsample
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=1.0, overlap=0.5)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.38it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.28it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.04it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.59it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.83it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.21it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.66it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.25it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.05it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.88it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.34it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  4.00it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.27it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.11it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.32it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.98it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.67it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.44it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.96it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.44it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.54it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.70it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.36it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.19it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.86it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.72it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.36it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.04it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.76it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.34it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.12it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.60it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.68it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.17it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.90it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.36it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.71it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.57it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.40it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.65it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.75it/s]

In [8]:
final_features.to_csv('features_data_acc_gyr/two_class_raw_1s_yo_0.5.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_std,gyr_mag_range,gyr_mag_rms,gyr_mag_var,gyr_mag_min,gyr_mag_max,gyr_mag_time_energy,gyr_mag_spectral_energy,label,experiment_id
0,0.499593,0.000000,0.999186,0.840598,0.524760,0.938842,1.134729,5.349532,1.472764,1.287610,...,1.531820,6.466757,3.178085,2.346471,0.522757,6.989515,595.913308,35158.885176,non-void,1
1,0.990718,0.491125,1.490311,0.782302,0.565548,1.226644,1.215409,5.349532,1.726810,1.477218,...,1.629047,6.773205,3.349521,2.653795,0.976699,7.749904,661.938011,39054.342658,non-void,1
2,1.481843,0.982250,1.981436,0.816380,0.556779,1.084483,0.893955,4.363070,1.405439,0.799155,...,1.935129,7.454564,3.094729,3.744725,0.295341,7.749904,565.063348,33338.737556,non-void,1
3,1.972968,1.473376,2.472561,0.902610,0.695212,0.751729,0.312815,1.479456,0.814217,0.097853,...,1.060611,4.219935,1.471907,1.124895,0.135198,4.355134,127.824147,7541.624648,non-void,1
4,2.464094,1.964501,2.963686,0.898106,0.761268,0.813395,0.236576,1.054752,0.847100,0.055968,...,0.261232,1.076729,0.549707,0.068242,0.092797,1.169525,17.828479,1051.880243,non-void,1

## Data 1c
classes: void, non-void

fs: original

sliding window: 1s

overlap: 0.8

filename: two_class_raw_1s_yo_0.8.csv

In [9]:
#  do not upsample
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=1.0, overlap=0.8)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.41it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.20it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.93it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.16it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.27it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.63it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.53it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.75it/s]
Analyzing : 100%|██████████| 8/8 [00:05<00:00,  1.46it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.80it/s]
Analyzing : 100%|██████████| 8/8 [00:06<00:00,  1.25it/s]
Analyzing : 100%|██████████| 8/8 [00:05<00:00,  1.47it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.35it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.84it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.85it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.07it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.97it/s]
Analyzing : 100%|██████████| 8/8 [00:06<00:00,  1.28it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.12it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.43it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.24it/s]
Analyzing : 100%|██████████| 8/8 [00:05<00:00,  1.47it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.40it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.03it/s]
Analyzing : 100%|██████████| 8/8 [00:05<00:00,  1.47it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.80it/s]
Analyzing : 100%|██████████| 8/8 [00:09<00:00,  1.13s/it]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.69it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.34it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.41it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.35it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.11it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.53it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.11it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.89it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.01it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.71it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.81it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.18it/s]
Analyzing : 100%|██████████| 8/8 [00:13<00:00,  1.67s/it]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.92it/s]

In [ ]:
final_features.to_csv('features_data_main/two_class_raw_1s_yo_0.8.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_std,gyr_mag_range,gyr_mag_rms,gyr_mag_var,gyr_mag_min,gyr_mag_max,gyr_mag_time_energy,gyr_mag_spectral_energy,label,experiment_id
0,0.499593,0.000000,0.999186,0.840598,0.524760,0.938842,1.134729,5.349532,1.472764,1.287610,...,1.531820,6.466757,3.178085,2.346471,0.522757,6.989515,595.913308,35158.885176,non-void,1
1,0.685882,0.186289,1.185475,0.833607,0.520173,0.989449,1.158952,5.349532,1.523870,1.343169,...,1.626363,6.466757,3.364270,2.645058,0.522757,6.989515,667.780264,39399.035547,non-void,1
2,0.872171,0.372578,1.371763,0.823753,0.562236,1.193638,1.186426,5.349532,1.682967,1.407606,...,1.765196,6.773205,3.628778,3.115918,0.976699,7.749904,776.913565,45837.900320,non-void,1
3,1.058459,0.558867,1.558052,0.837070,0.566957,1.251707,1.200011,5.349532,1.734012,1.440027,...,1.637583,6.773205,3.470608,2.681678,0.976699,7.749904,710.662013,41929.058762,non-void,1
4,1.244748,0.745155,1.744341,0.815424,0.582808,1.165694,1.210199,5.349532,1.680305,1.464581,...,1.718490,7.195847,3.427120,2.953208,0.554057,7.749904,692.963767,40884.862224,non-void,1

## Data 2
classes: void, non-void

fs: original

overlap: 0

sliding window: 2s

filename: two_class_raw_2s_no.csv

In [11]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=2.0, overlap=0.0)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.45it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 33.11it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.44it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 22.04it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 34.91it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.35it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.42it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 26.55it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.61it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.37it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.42it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.76it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.40it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.43it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 39.27it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 31.28it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 29.15it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.33it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 33.97it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 33.51it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 33.02it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.95it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 22.33it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.28it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.40it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.83it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.96it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 27.93it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 33.39it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.15it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 24.27it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 33.20it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.51it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 31.08it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.93it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.63it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.08it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 27.59it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 32.15it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.30it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 30.48it/s]

In [12]:
final_features.to_csv('features_data_acc_gyr/two_class_raw_2s_no.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_std,gyr_mag_range,gyr_mag_rms,gyr_mag_var,gyr_mag_min,gyr_mag_max,gyr_mag_time_energy,gyr_mag_spectral_energy,label,experiment_id
0,0.999186,0.000000,1.998371,0.837517,0.656083,1.027208,1.005637,5.349532,1.437520,1.011306,...,1.742222,7.487364,3.090512,3.035336,0.262540,7.749904,1127.049263,132991.813018,non-void,1
1,2.997557,1.998371,3.996743,0.914142,0.780981,0.762864,0.273525,1.507445,0.810418,0.074816,...,0.486624,2.648913,0.838786,0.236803,0.076565,2.725477,83.020215,9796.385387,non-void,1
2,4.995929,3.996743,5.995114,0.911102,0.825743,0.381709,0.479763,3.273455,0.613086,0.230173,...,1.144504,5.980251,1.824972,1.309890,0.253437,6.233687,393.001886,46374.222586,non-void,1
3,6.994300,5.995114,7.993486,0.880385,0.714032,0.842092,0.846989,5.457410,1.194366,0.717390,...,0.714052,3.422639,1.856639,0.509870,0.130083,3.552722,406.758871,47997.546800,non-void,1
4,8.992671,7.993486,9.991857,0.915965,0.812030,0.565058,0.443517,2.956667,0.718330,0.196707,...,1.109270,5.186274,2.154653,1.230481,0.268381,5.454655,547.818630,64642.598316,non-void,1

## Data 2b
classes: void, non-void

fs: original

overlap: 0.5

sliding window: 2s

filename: two_class_raw_2s_yo_0.5.csv

In [35]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=2.0, overlap=0.5)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.87it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.82it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.92it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.44it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.86it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.39it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.79it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.69it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.79it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.41it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.55it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.72it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.46it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.12it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.87it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.40it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.38it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.60it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.63it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.19it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.44it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.80it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.03it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.57it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.88it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.62it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.77it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.26it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.56it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.14it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.42it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.34it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.50it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.73it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.04it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.69it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.16it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.03it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.03it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.22it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.60it/s]

In [36]:
final_features.to_csv('features_data_acc_gyr/two_class_raw_2s_yo_0.5.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_std,gyr_mag_range,gyr_mag_rms,gyr_mag_var,gyr_mag_min,gyr_mag_max,gyr_mag_time_energy,gyr_mag_spectral_energy,label,experiment_id
0,0.999186,0.000000,1.998371,0.837517,0.656083,1.027208,1.005637,5.349532,1.437520,1.011306,...,1.742222,7.487364,3.090512,3.035336,0.262540,7.749904,1127.049263,132991.813018,non-void,1
1,1.998371,0.999186,2.997557,0.872310,0.644016,0.960179,0.643429,3.553001,1.155831,0.414001,...,1.635818,7.657108,2.158114,2.675900,0.092797,7.749904,549.579915,64850.429931,non-void,1
2,2.997557,1.998371,3.996743,0.914142,0.780981,0.762864,0.273525,1.507445,0.810418,0.074816,...,0.486624,2.648913,0.838786,0.236803,0.076565,2.725477,83.020215,9796.385387,non-void,1
3,3.996743,2.997557,4.995929,0.909732,0.722111,0.654615,0.272212,1.507445,0.708957,0.074099,...,0.476111,2.648913,0.989435,0.226682,0.076565,2.725477,115.519931,13631.351813,non-void,1
4,4.995929,3.996743,5.995114,0.911102,0.825743,0.381709,0.479763,3.273455,0.613086,0.230173,...,1.144504,5.980251,1.824972,1.309890,0.253437,6.233687,393.001886,46374.222586,non-void,1

## Data 2c
classes: void, non-void

fs: original

overlap: 0.8

sliding window: 2s

filename: two_class_raw_2s_yo_0.8.csv

In [15]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=2.0, overlap=0.8)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.09it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.59it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.61it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.46it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.20it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.25it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.41it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.51it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.13it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.74it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.66it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.01it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.81it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.71it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.85it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.20it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.26it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.60it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.67it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.98it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.59it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.86it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.01it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.98it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.89it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.47it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.84it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.62it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.88it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.72it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.91it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.96it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.93it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.56it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.91it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.19it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.63it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.88it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.68it/s]
Analyzing : 100%|██████████| 8/8 [00:06<00:00,  1.26it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.00it/s]

In [16]:
final_features.to_csv('features_data_acc_gyr/two_class_raw_2s_yo_0.8.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_std,gyr_mag_range,gyr_mag_rms,gyr_mag_var,gyr_mag_min,gyr_mag_max,gyr_mag_time_energy,gyr_mag_spectral_energy,label,experiment_id
0,0.999186,0.000000,1.998371,0.837517,0.656083,1.027208,1.005637,5.349532,1.437520,1.011306,...,1.742222,7.487364,3.090512,3.035336,0.262540,7.749904,1127.049263,132991.813018,non-void,1
1,1.388699,0.389513,2.387885,0.856472,0.634105,1.049054,0.936724,5.349532,1.406402,0.877451,...,1.787973,7.614706,2.800308,3.196848,0.135198,7.749904,925.323664,109188.192384,non-void,1
2,1.778212,0.779026,2.777398,0.866184,0.638264,0.996176,0.888607,5.349532,1.334912,0.789622,...,1.741895,7.657108,2.450640,3.034198,0.092797,7.749904,708.665105,83622.482415,non-void,1
3,2.167725,1.168539,3.166911,0.878813,0.663285,0.929198,0.584101,3.553001,1.097535,0.341174,...,1.502970,7.657108,1.939446,2.258920,0.092797,7.749904,443.851412,52374.466635,non-void,1
4,2.557238,1.558052,3.556424,0.905723,0.782317,0.762776,0.265824,1.479456,0.807768,0.070662,...,0.436316,3.250805,0.733959,0.190372,0.076565,3.327370,63.566144,7500.804959,non-void,1

## Data 3
classes: void, non-void

fs: original

overlap: 0

sliding window: 3s

filename: two_class_raw_3s_no.csv

In [17]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=3.0, overlap=0.0)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 33.04it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 42.03it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 29.58it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 33.11it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 53.07it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.94it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 36.59it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 40.64it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.72it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 27.26it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.96it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 22.88it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 37.13it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 28.50it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 59.57it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 46.01it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 45.54it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.54it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 54.16it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 52.46it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 48.66it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 22.20it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 37.57it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 29.73it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 22.35it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 26.57it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.71it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 38.98it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 50.12it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 37.97it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 35.72it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 60.25it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 39.99it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 49.40it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 28.25it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 31.35it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 27.22it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 41.48it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 49.21it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.30it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 38.17it/s]

In [18]:
final_features.to_csv('features_data_acc_gyr/two_class_raw_3s_no.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_std,gyr_mag_range,gyr_mag_rms,gyr_mag_var,gyr_mag_min,gyr_mag_max,gyr_mag_time_energy,gyr_mag_spectral_energy,label,experiment_id
0,1.498779,0.000000,2.997557,0.868352,0.694367,0.953067,0.839825,5.349532,1.270292,0.705305,...,1.728403,7.657108,2.543956,2.987378,0.092797,7.749904,1145.493223,202752.300425,non-void,1
1,4.496336,2.997557,5.995114,0.919605,0.790731,0.494788,0.455654,3.273455,0.672633,0.207621,...,1.025643,6.157122,1.607852,1.051944,0.076565,6.233687,457.578142,80991.331063,non-void,1
2,7.493893,5.995114,8.992671,0.903234,0.730563,0.758589,0.711104,5.457410,1.039772,0.505669,...,0.729897,3.447654,1.824172,0.532750,0.130083,3.577737,588.986049,104250.530656,non-void,1
3,10.491450,8.992671,11.990229,0.873187,0.787136,0.635391,0.492101,2.956667,0.803670,0.242164,...,1.099241,5.244594,1.943212,1.208330,0.210061,5.454655,668.365166,118300.634302,non-void,1
4,13.489007,11.990229,14.987786,0.915277,0.765171,0.386718,0.475147,3.601410,0.612630,0.225764,...,0.652270,3.934588,1.353623,0.425456,0.138521,4.073109,324.316017,57403.935017,non-void,1

## Data 3b
classes: void, non-void

fs: original

overlap: 0.5

sliding window: 3s

filename: two_class_raw_3s_yo_0.5.csv

In [19]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=3.0, overlap=0.5)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.69it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 24.92it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.92it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.88it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 27.17it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.71it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.32it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.63it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.77it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.86it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.87it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.06it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.48it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.69it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 31.51it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 24.13it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 22.83it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.96it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 27.44it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 27.16it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.23it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.55it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.84it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.57it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.08it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.23it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.75it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.81it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 26.30it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.84it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.00it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 30.82it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.73it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.35it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.83it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.61it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.83it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 22.01it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.44it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.68it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 22.40it/s]

In [20]:
final_features.to_csv('features_data_acc_gyr/two_class_raw_3s_yo_0.5.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_std,gyr_mag_range,gyr_mag_rms,gyr_mag_var,gyr_mag_min,gyr_mag_max,gyr_mag_time_energy,gyr_mag_spectral_energy,label,experiment_id
0,1.498779,0.000000,2.997557,0.868352,0.694367,0.953067,0.839825,5.349532,1.270292,0.705305,...,1.728403,7.657108,2.543956,2.987378,0.092797,7.749904,1145.493223,202752.300425,non-void,1
1,2.989089,1.490311,4.487868,0.906822,0.799264,0.731636,0.286953,1.507445,0.785897,0.082342,...,0.718296,4.278569,1.100089,0.515950,0.076565,4.355134,214.204840,37914.256657,non-void,1
2,4.479400,2.980622,5.978179,0.919605,0.791796,0.483426,0.432560,2.498092,0.648698,0.187108,...,1.012529,6.157122,1.587233,1.025215,0.076565,6.233687,445.917530,78927.402744,non-void,1
3,5.969711,4.470933,7.468490,0.892201,0.713119,0.548849,0.809403,5.457410,0.977941,0.655133,...,1.042992,6.103604,1.943620,1.087832,0.130083,6.233687,668.645645,118350.279202,non-void,1
4,7.460022,5.961244,8.958801,0.902390,0.730050,0.776208,0.723594,5.457410,1.061172,0.523588,...,0.777252,4.637339,1.870010,0.604120,0.130083,4.767422,618.958007,109555.567167,non-void,1

## Data 3c
classes: void, non-void

fs: original

overlap: 0.8

sliding window: 3s

filename: two_class_raw_3s_yo_0.8.csv

In [21]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=3.0, overlap=0.8)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.72it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.44it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.96it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.67it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.01it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.11it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.20it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.19it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.77it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.83it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.03it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.64it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.47it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.97it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.49it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.49it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.42it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  4.00it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.91it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.70it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.26it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.61it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.62it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.35it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.55it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.69it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.77it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.52it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.76it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.73it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.41it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.36it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.90it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.15it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.91it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.40it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.61it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.78it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.47it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.93it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.33it/s]

In [22]:
final_features.to_csv('features_data_acc_gyr/two_class_raw_3s_yo_0.8.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_std,gyr_mag_range,gyr_mag_rms,gyr_mag_var,gyr_mag_min,gyr_mag_max,gyr_mag_time_energy,gyr_mag_spectral_energy,label,experiment_id
0,1.498779,0.000000,2.997557,0.868352,0.694367,0.953067,0.839825,5.349532,1.270292,0.705305,...,1.728403,7.657108,2.543956,2.987378,0.092797,7.749904,1145.493223,202752.300425,non-void,1
1,2.091516,0.592737,3.590294,0.891024,0.700772,0.937189,0.752365,5.349532,1.201822,0.566053,...,1.533905,7.673340,2.072981,2.352866,0.076565,7.749904,760.613526,134628.594022,non-void,1
2,2.684253,1.185475,4.183032,0.904307,0.779004,0.836695,0.516392,3.553001,0.983219,0.266661,...,1.279308,7.673340,1.686910,1.636629,0.076565,7.749904,503.682588,89151.818152,non-void,1
3,3.276990,1.778212,4.775769,0.900103,0.797495,0.724808,0.273863,1.507445,0.774821,0.075001,...,0.451421,2.648913,0.841481,0.203781,0.076565,2.725477,125.332096,22183.780959,non-void,1
4,3.869728,2.370949,5.368506,0.917587,0.797179,0.654555,0.289030,1.550907,0.715528,0.083538,...,0.496264,2.648913,0.950062,0.246278,0.076565,2.725477,159.763415,28278.124511,non-void,1

## Data 4
classes: void, non-void

fs: original

overlap: 0.0

sliding window: 4s

filename: two_class_raw_4s_no.csv

In [6]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=4.0, overlap=0.0)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 43.98it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 59.47it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 37.78it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 41.91it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 70.45it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 26.91it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 53.02it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 57.79it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 30.43it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 36.30it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.03it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 28.43it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 46.20it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 38.26it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 79.93it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 63.20it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 56.30it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.67it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 72.09it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 72.02it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 63.67it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 29.29it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 48.65it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 39.90it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 29.81it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 37.24it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.15it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 47.51it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 63.70it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 48.63it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 48.84it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 81.89it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 53.43it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 64.94it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 39.21it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 41.47it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 36.33it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 58.33it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 64.81it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.57it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 55.24it/s]

In [7]:
final_features.to_csv('features_data_acc_gyr/two_class_raw_4s_no.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_std,gyr_mag_range,gyr_mag_rms,gyr_mag_var,gyr_mag_min,gyr_mag_max,gyr_mag_time_energy,gyr_mag_spectral_energy,label,experiment_id
0,1.998371,0.000000,3.996743,0.888082,0.724174,0.895036,0.748686,5.349532,1.166885,0.560530,...,1.584224,7.673340,2.264379,2.509766,0.076565,7.749904,1210.069478,285576.396811,non-void,1
1,5.995114,3.996743,7.993486,0.900675,0.721296,0.611901,0.725789,5.457410,0.949311,0.526770,...,0.965011,6.103604,1.840874,0.931246,0.130083,6.233687,799.760758,188743.538773,non-void,1
2,9.991857,7.993486,11.990229,0.901749,0.809333,0.624439,0.438269,2.956667,0.762892,0.192080,...,1.023847,5.244594,1.898474,1.048263,0.210061,5.454655,850.592343,200739.793011,non-void,1
3,13.988600,11.990229,15.986972,0.917454,0.790501,0.295423,0.460685,3.601410,0.547271,0.212231,...,0.610050,3.934588,1.320361,0.372161,0.138521,4.073109,411.431146,97097.750462,non-void,1
4,17.985343,15.986972,19.983714,0.922168,0.631454,0.394139,1.000649,5.412671,1.075474,1.001298,...,1.615157,7.530653,2.164120,2.608733,0.080535,7.611187,1105.285925,260847.478394,void,1

## Data 4b
classes: void, non-void

fs: original

overlap: 0.5

sliding window: 4s

filename: two_class_raw_4s_yo_0.5.csv

In [25]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=4.0, overlap=0.5)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 24.69it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 33.65it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.24it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.26it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 36.22it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.65it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 26.63it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 29.24it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.57it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.00it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.57it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.22it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 24.68it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.62it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 41.09it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 33.07it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 31.26it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.91it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 36.04it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 35.87it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 34.23it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.30it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 26.06it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.73it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.98it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.30it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.05it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 28.45it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 34.43it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 26.04it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.16it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 42.64it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 27.21it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 32.57it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.53it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.09it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.41it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 29.61it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 34.66it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.29it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 31.32it/s]

In [26]:
final_features.to_csv('features_data_acc_gyr/two_class_raw_4s_yo_0.5.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_std,gyr_mag_range,gyr_mag_rms,gyr_mag_var,gyr_mag_min,gyr_mag_max,gyr_mag_time_energy,gyr_mag_spectral_energy,label,experiment_id
0,1.998371,0.000000,3.996743,0.888082,0.724174,0.895036,0.748686,5.349532,1.166885,0.560530,...,1.584224,7.673340,2.264379,2.509766,0.076565,7.749904,1210.069478,285576.396811,non-void,1
1,3.996743,1.998371,5.995114,0.916050,0.817238,0.572287,0.434528,3.273455,0.718559,0.188814,...,0.953738,6.157122,1.420226,0.909616,0.076565,6.233687,476.022101,112341.215947,non-void,1
2,5.995114,3.996743,7.993486,0.900675,0.721296,0.611901,0.725789,5.457410,0.949311,0.526770,...,0.965011,6.103604,1.840874,0.931246,0.130083,6.233687,799.760758,188743.538773,non-void,1
3,7.993486,5.995114,9.991857,0.908323,0.745699,0.703575,0.690098,5.457410,0.985522,0.476235,...,0.935211,5.324572,2.011174,0.874620,0.130083,5.454655,954.577501,225280.290232,non-void,1
4,9.991857,7.993486,11.990229,0.901749,0.809333,0.624439,0.438269,2.956667,0.762892,0.192080,...,1.023847,5.244594,1.898474,1.048263,0.210061,5.454655,850.592343,200739.793011,non-void,1

## Data 4c
classes: void, non-void

fs: original

overlap: 0.8

sliding window: 4s

filename: two_class_raw_4s_yo_0.8.csv

In [27]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=4.0, overlap=0.8)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.35it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.10it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.89it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.97it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.91it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.79it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.81it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.82it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.10it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.53it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.31it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.20it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.66it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.51it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.33it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.01it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.80it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.35it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.92it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.09it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.98it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.11it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.35it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.71it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.01it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.04it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.50it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.45it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.62it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.36it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.77it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.90it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.03it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.57it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.01it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.55it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.44it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.99it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.03it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.49it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.43it/s]

In [28]:
final_features.to_csv('features_data_acc_gyr/two_class_raw_4s_yo_0.8.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_std,gyr_mag_range,gyr_mag_rms,gyr_mag_var,gyr_mag_min,gyr_mag_max,gyr_mag_time_energy,gyr_mag_spectral_energy,label,experiment_id
0,1.998371,0.000000,3.996743,0.888082,0.724174,0.895036,0.748686,5.349532,1.166885,0.560530,...,1.584224,7.673340,2.264379,2.509766,0.076565,7.749904,1210.069478,285576.396811,non-void,1
1,2.794333,0.795962,4.792704,0.888588,0.758875,0.833254,0.676522,5.349532,1.073310,0.457682,...,1.358278,7.673340,1.852557,1.844918,0.076565,7.749904,809.944415,191146.882047,non-void,1
2,3.590294,1.591923,5.588666,0.914118,0.829681,0.643343,0.329404,1.727885,0.722771,0.108507,...,0.509337,2.648913,0.972463,0.259424,0.076565,2.725477,223.181471,52670.827240,non-void,1
3,4.386256,2.387885,6.384627,0.918808,0.782531,0.602633,0.553150,3.840626,0.818011,0.305975,...,1.012198,6.157122,1.566153,1.024544,0.076565,6.233687,578.868798,136613.036407,non-void,1
4,5.182217,3.183846,7.180589,0.906615,0.724715,0.569451,0.682941,5.457410,0.889204,0.466409,...,0.984923,6.157122,1.702665,0.970074,0.076565,6.233687,684.179820,161466.437419,non-void,1

## Data 5
classes: void, non-void

fs: original

overlap: 0.0

sliding window: 5s

filename: two_class_raw_5s_no.csv

In [29]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=5.0, overlap=0.0)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 60.79it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 79.18it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 45.99it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 51.46it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 78.59it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 41.48it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 59.99it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 66.55it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 35.69it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 43.14it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 31.38it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 37.06it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 54.98it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 46.27it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 91.66it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 80.06it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 67.67it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 31.01it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 78.93it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 91.93it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 71.27it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 27.10it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 55.46it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 47.34it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 35.40it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 43.77it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 22.21it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 63.17it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 80.06it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 61.61it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 56.23it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 92.53it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 62.18it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 80.12it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 47.30it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 50.92it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 42.99it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 70.85it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 80.37it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.95it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 68.27it/s]

In [30]:
final_features.to_csv('features_data_acc_gyr/two_class_raw_5s_no.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_std,gyr_mag_range,gyr_mag_rms,gyr_mag_var,gyr_mag_min,gyr_mag_max,gyr_mag_time_energy,gyr_mag_spectral_energy,label,experiment_id
0,2.497964,0.000000,4.995929,0.888117,0.737073,0.833686,0.688622,5.349532,1.081311,0.474200,...,1.456968,7.673340,2.067516,2.122757,0.076565,7.749904,1261.013153,371998.880241,non-void,1
1,7.493893,4.995929,9.991857,0.911608,0.753020,0.597887,0.699962,5.457410,0.920552,0.489947,...,1.039946,6.103604,2.096515,1.081487,0.130083,6.233687,1296.635712,382507.535028,non-void,1
2,12.489822,9.991857,14.987786,0.897663,0.801344,0.505559,0.478334,3.601410,0.695984,0.228804,...,0.747518,4.635002,1.457988,0.558783,0.138521,4.773524,627.089731,184991.470502,non-void,1
3,17.485750,14.987786,19.983714,0.924754,0.681130,0.319619,0.915191,5.412671,0.969397,0.837574,...,1.464495,7.530653,2.010482,2.144745,0.080535,7.611187,1192.401054,351758.311041,void,1
4,22.481679,19.983714,24.979643,0.944870,0.844899,0.984424,0.390305,2.799139,1.058975,0.152338,...,0.528273,2.821759,1.010333,0.279073,0.084164,2.905923,301.127821,88832.707089,void,1

## Data 5b
classes: void, non-void

fs: original

overlap: 0.5

sliding window: 5s

filename: two_class_raw_5s_yo_0.5.csv

In [8]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=5.0, overlap=0.5)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 30.12it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 39.04it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.54it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 27.24it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 43.63it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.70it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 34.12it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 36.14it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.94it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.12it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.15it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.91it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 28.83it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.48it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 47.03it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 39.72it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 37.21it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.96it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 43.97it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 47.37it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 41.17it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.89it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 31.99it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.18it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.75it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.03it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.28it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 34.38it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 44.44it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 31.59it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 30.19it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 49.04it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 33.24it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 41.00it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 24.09it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.95it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.16it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 38.62it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 43.97it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.82it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 38.40it/s]

In [9]:
final_features.to_csv('features_data_acc_gyr/two_class_raw_5s_yo_0.5.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_std,gyr_mag_range,gyr_mag_rms,gyr_mag_var,gyr_mag_min,gyr_mag_max,gyr_mag_time_energy,gyr_mag_spectral_energy,label,experiment_id
0,2.497964,0.000000,4.995929,0.888117,0.737073,0.833686,0.688622,5.349532,1.081311,0.474200,...,1.456968,7.673340,2.067516,2.122757,0.076565,7.749904,1261.013153,371998.880241,non-void,1
1,4.987461,2.489497,7.485425,0.898142,0.746140,0.620001,0.656198,5.457410,0.902772,0.430596,...,0.976821,6.157122,1.625113,0.954179,0.076565,6.233687,779.092651,229832.331971,non-void,1
2,7.476958,4.978993,9.974922,0.911677,0.752174,0.599177,0.699707,5.457410,0.921197,0.489590,...,1.040874,6.103604,2.095486,1.083419,0.130083,6.233687,1295.363381,382132.197506,non-void,1
3,9.966454,7.468490,12.464418,0.909585,0.818971,0.636508,0.432122,2.956667,0.769332,0.186729,...,0.953761,5.298439,1.841953,0.909660,0.156216,5.454655,1000.873469,295257.673488,non-void,1
4,12.455951,9.957987,14.953915,0.899875,0.801243,0.507144,0.476810,3.601410,0.696092,0.227348,...,0.747232,4.635002,1.457428,0.558356,0.138521,4.773524,626.608844,184849.609082,non-void,1

## Data 5c
classes: void, non-void

fs: original

overlap: 0.8

sliding window: 5s

filename: two_class_raw_5s_yo_0.8.csv

In [33]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=5.0, overlap=0.8)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.38it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.11it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.40it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.30it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.94it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.21it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.57it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.21it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.57it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.37it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.39it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.51it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.98it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.47it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.15it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.83it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.49it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.42it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.84it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.21it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.64it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.21it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.50it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.34it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.29it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.83it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.42it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.62it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.00it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.39it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.48it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 22.13it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.06it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.46it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.50it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.60it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.03it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.12it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.35it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.05it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.50it/s]

In [34]:
final_features.to_csv('features_data_acc_gyr/two_class_raw_5s_yo_0.8.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_std,gyr_mag_range,gyr_mag_rms,gyr_mag_var,gyr_mag_min,gyr_mag_max,gyr_mag_time_energy,gyr_mag_spectral_energy,label,experiment_id
0,2.497964,0.000000,4.995929,0.888117,0.737073,0.833686,0.688622,5.349532,1.081311,0.474200,...,1.456968,7.673340,2.067516,2.122757,0.076565,7.749904,1261.013153,371998.880241,non-void,1
1,3.480215,0.982250,5.978179,0.903643,0.831037,0.669089,0.585473,4.363070,0.889078,0.342779,...,1.327310,7.673340,1.867705,1.761753,0.076565,7.749904,1029.055413,303571.346840,non-void,1
2,4.462465,1.964501,6.960429,0.908870,0.749159,0.646192,0.548827,3.840626,0.847806,0.301211,...,0.959267,6.157122,1.519203,0.920193,0.076565,6.233687,680.853135,200851.674784,non-void,1
3,5.444715,2.946751,7.942680,0.907880,0.743695,0.628383,0.661715,5.457410,0.912541,0.437867,...,0.938362,6.157122,1.692626,0.880523,0.076565,6.233687,845.169979,249325.143925,non-void,1
4,6.426966,3.929001,8.924930,0.908219,0.746226,0.612415,0.656816,5.457410,0.898031,0.431407,...,0.930838,6.103604,1.818064,0.866459,0.130083,6.233687,975.079725,287648.518736,non-void,1

## Three class data

## Data 6
classes: pre-void, void, non-void

fs: original

overlap: 0.0

sliding window: 1s

filename: three_class_raw_1s_no.csv

In [5]:
labelled_imu_dict = {}
dict = copy.deepcopy(imu_dict)
for i_void_instance, void_instance in tqdm(enumerate(dict.keys()), desc="Adding labels to IMU data"):
    acc = dict[void_instance]
    gt = ground_truth_dict[void_instance]
    
    # normalize data
    df = normalize(acc)
    
    # add the labels
    labelled_df = three_class_labels(df, gt)
    
    labelled_imu_dict[void_instance] = labelled_df

Adding labels to IMU data: 0it [00:00, ?it/s]

Adding labels to IMU data: 41it [00:00, 119.94it/s]

In [6]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=1.0, overlap=0.0)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.86it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.68it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.61it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.91it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.60it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.73it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.40it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.09it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.18it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.87it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.53it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.55it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.69it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.75it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.88it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.93it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.68it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.30it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.03it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.25it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.67it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.04it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.02it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.81it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.18it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.68it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.56it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.40it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.23it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.03it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.67it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.90it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.82it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.74it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.23it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.17it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.66it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.58it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.76it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.15it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.51it/s]

In [8]:
final_features.to_csv('features_data_main/three_class_raw_1s_no.csv', index=False)
# final_features.head()

## Data 6b
classes: pre-void, void, non-void

fs: original

overlap: 0.5

sliding window: 1s

filename: three_class_raw_1s_yo_0.5.csv

In [ ]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=1.0, overlap=0.5)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

In [ ]:
final_features.to_csv('features_data_main/three_class_raw_1s_yo_0.5.csv', index=False)

## Data 6c
classes: pre-void, void, non-void

fs: original

overlap: 0.8

sliding window: 1s

filename: three_class_raw_1s_yo_0.8.csv

In [13]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=1.0, overlap=0.8)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.49it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.28it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.95it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.16it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.42it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.66it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.64it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.79it/s]
Analyzing : 100%|██████████| 8/8 [00:05<00:00,  1.47it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.81it/s]
Analyzing : 100%|██████████| 8/8 [00:06<00:00,  1.26it/s]
Analyzing : 100%|██████████| 8/8 [00:07<00:00,  1.10it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.40it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.91it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.04it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.15it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.11it/s]
Analyzing : 100%|██████████| 8/8 [00:05<00:00,  1.34it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.48it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.58it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.38it/s]
Analyzing : 100%|██████████| 8/8 [00:05<00:00,  1.55it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.58it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.11it/s]
Analyzing : 100%|██████████| 8/8 [00:05<00:00,  1.55it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.92it/s]
Analyzing : 100%|██████████| 8/8 [00:08<00:00,  1.07s/it]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.74it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.37it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.50it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.39it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.15it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.48it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.08it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.99it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.06it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.76it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.81it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.11it/s]
Analyzing : 100%|██████████| 8/8 [00:13<00:00,  1.68s/it]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.96it/s]

In [14]:
final_features.to_csv('features_data_main/three_class_raw_1s_yo_0.8.csv', index=False)

## Data 7
classes: pre-void, void, non-void

fs: original

overlap: 0.0

sliding window: 2s

filename: three_class_raw_2s_no.csv

In [15]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=2.0, overlap=0.0)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.88it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 34.09it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.52it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.81it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 34.69it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.31it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 26.67it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 28.14it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.42it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.74it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.16it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.94it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.42it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.60it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 39.79it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 31.63it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 30.46it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.23it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 32.21it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 32.94it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 33.69it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.59it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 24.75it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.71it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.59it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.19it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.28it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 27.13it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 33.96it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.32it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 24.02it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 40.42it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 27.23it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 32.45it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.94it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.50it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.78it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 29.36it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 34.40it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.08it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 30.62it/s]

In [16]:
final_features.to_csv('features_data_main/three_class_raw_2s_no.csv', index=False)

## Data 7b
classes: pre-void, void, non-void

fs: original

overlap: 0.5

sliding window: 2s

filename: three_class_raw_2s_yo_0.5.csv

In [17]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=2.0, overlap=0.5)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.86it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.38it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.22it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.44it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.33it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.52it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.94it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.62it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.08it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.58it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.85it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.71it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.52it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.16it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.95it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.06it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.68it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.75it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.56it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.88it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.35it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.71it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.89it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.48it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.78it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.53it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.71it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.26it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.19it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.79it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.33it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.33it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.55it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.99it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.09it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.77it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.34it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.52it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.97it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.16it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.45it/s]

In [18]:
final_features.to_csv('features_data_main/three_class_raw_2s_yo_0.5.csv', index=False)

## Data 7c
classes: pre-void, void, non-void

fs: original

overlap: 0.8

sliding window: 2s

filename: three_class_raw_2s_yo_0.8.csv

In [7]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=2.0, overlap=0.8)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.98it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.10it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.91it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.34it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.90it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.32it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.33it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.58it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.01it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.58it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.58it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.00it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.69it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.73it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.55it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.20it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.17it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.63it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.73it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.80it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.54it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.85it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.86it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.37it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.74it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.53it/s]
Analyzing : 100%|██████████| 8/8 [00:05<00:00,  1.49it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.81it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.05it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.24it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.48it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.23it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.33it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.61it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.56it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.79it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.85it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.36it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.11it/s]
Analyzing : 100%|██████████| 8/8 [00:06<00:00,  1.17it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.64it/s]

In [ ]:
# final_features.to_csv('features_data_acc_gyr/three_class_raw_2s_yo_0.8.csv', index=False)
# final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_std,gyr_mag_range,gyr_mag_rms,gyr_mag_var,gyr_mag_min,gyr_mag_max,gyr_mag_time_energy,gyr_mag_spectral_energy,label,experiment_id
0,0.999186,0.000000,1.998371,0.837517,0.656083,1.027208,1.005637,5.349532,1.437520,1.011306,...,1.742222,7.487364,3.090512,3.035336,0.262540,7.749904,1127.049263,132991.813018,pre-void,1
1,1.388699,0.389513,2.387885,0.856472,0.634105,1.049054,0.936724,5.349532,1.406402,0.877451,...,1.787973,7.614706,2.800308,3.196848,0.135198,7.749904,925.323664,109188.192384,pre-void,1
2,1.778212,0.779026,2.777398,0.866184,0.638264,0.996176,0.888607,5.349532,1.334912,0.789622,...,1.741895,7.657108,2.450640,3.034198,0.092797,7.749904,708.665105,83622.482415,pre-void,1
3,2.167725,1.168539,3.166911,0.878813,0.663285,0.929198,0.584101,3.553001,1.097535,0.341174,...,1.502970,7.657108,1.939446,2.258920,0.092797,7.749904,443.851412,52374.466635,pre-void,1
4,2.557238,1.558052,3.556424,0.905723,0.782317,0.762776,0.265824,1.479456,0.807768,0.070662,...,0.436316,3.250805,0.733959,0.190372,0.076565,3.327370,63.566144,7500.804959,pre-void,1

## Data 8
classes: pre-void, void, non-void

fs: original

overlap: 0.0

sliding window: 3s

filename: three_class_raw_3s_no.csv

In [19]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=3.0, overlap=0.0)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 32.03it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 47.14it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 28.80it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 32.40it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 51.58it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.83it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 39.30it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 41.51it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 22.18it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 26.97it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.62it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.67it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 36.02it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 26.06it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 44.89it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 43.49it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 46.04it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.95it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 50.64it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 51.85it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 46.88it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.32it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 35.24it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 28.78it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.94it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.32it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.44it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 39.62it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 47.97it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 36.38it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 33.74it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 57.74it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 38.84it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 48.86it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 28.44it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 29.07it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.55it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 42.11it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 48.95it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.92it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 44.70it/s]

In [21]:
final_features.to_csv('features_data_main/three_class_raw_3s_no.csv', index=False)

## Data 8b
classes: pre-void, void, non-void

fs: original

overlap: 0.5

sliding window: 3s

filename: three_class_raw_3s_yo_0.5.csv

In [22]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=3.0, overlap=0.5)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.21it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.19it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.79it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.12it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.58it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.06it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.09it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.18it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.33it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.41it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.16it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.56it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.49it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.45it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 31.15it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 22.93it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 22.52it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.27it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 26.36it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 27.10it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.77it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.56it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.66it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.02it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.98it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.08it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.87it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.52it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.67it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.55it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.54it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 28.79it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.02it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.45it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.32it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.81it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.91it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.93it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.47it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.67it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 22.77it/s]

In [23]:
final_features.to_csv('features_data_main/three_class_raw_3s_yo_0.5.csv', index=False)

## Data 8c
classes: pre-void, void, non-void

fs: original

overlap: 0.8

sliding window: 3s

filename: three_class_raw_3s_yo_0.8.csv

In [24]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=3.0, overlap=0.8)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.72it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.28it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.55it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.24it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.92it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.11it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.20it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.05it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.74it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.80it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.01it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.68it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.01it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.80it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.52it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.74it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.70it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.99it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.30it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.16it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.18it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.57it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.49it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.19it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.52it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.62it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.74it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.42it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.66it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.56it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.93it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.11it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.97it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.94it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.58it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.38it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.27it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.85it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.35it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.84it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.94it/s]

In [25]:
final_features.to_csv('features_data_main/three_class_raw_3s_yo_0.8.csv', index=False)

## Data 9
classes: pre-void, void, non-void

fs: original

overlap: 0.0

sliding window: 4s

filename: three_class_raw_4s_no.csv

In [26]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=4.0, overlap=0.0)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 41.48it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 59.54it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 30.49it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 38.17it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 67.80it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 31.16it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 51.51it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 55.47it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 29.58it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 33.73it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.71it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 27.96it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 46.29it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 37.34it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 77.49it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 58.72it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 55.36it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.18it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 69.67it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 67.93it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 62.31it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 27.42it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 40.05it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 37.70it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 27.71it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 35.86it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.92it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 47.00it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 40.76it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 46.20it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 46.71it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 80.06it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 48.57it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 63.95it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 37.61it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 37.05it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 35.07it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 57.56it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 63.36it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.26it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 57.60it/s]

In [27]:
final_features.to_csv('features_data_main/three_class_raw_4s_no.csv', index=False)

## Data 9b
classes: pre-void, void, non-void

fs: original

overlap: 0.5

sliding window: 4s

filename: three_class_raw_4s_yo_0.5.csv

In [28]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=4.0, overlap=0.5)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 22.99it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 33.33it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.16it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.71it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 34.29it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.70it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 26.16it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 28.11it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.29it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.40it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.95it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.79it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.06it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.13it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 39.57it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 31.66it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 30.31it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.23it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 36.13it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 34.96it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 32.77it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.84it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.46it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.11it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.94it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.43it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.47it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 27.71it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 34.26it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 24.92it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 24.08it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 36.30it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.47it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 31.85it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.09it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.68it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.03it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 27.87it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 33.49it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.14it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 29.38it/s]

In [29]:
final_features.to_csv('features_data_main/three_class_raw_4s_yo_0.5.csv', index=False)

## Data 9c
classes: pre-void, void, non-void

fs: original

overlap: 0.8

sliding window: 4s

filename: three_class_raw_4s_yo_0.8.csv

In [30]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=4.0, overlap=0.8)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.29it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.66it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.72it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.97it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.77it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.84it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.77it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.85it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.22it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.53it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.21it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.15it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.41it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.82it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.21it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.23it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.75it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.32it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.80it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.10it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.80it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.94it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.33it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.10it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.92it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.56it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.55it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.41it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.44it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.34it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.72it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.89it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.86it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.36it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.89it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.83it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.34it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.04it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.92it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.48it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.36it/s]

In [31]:
final_features.to_csv('features_data_main/three_class_raw_4s_yo_0.8.csv', index=False)

## Data 10
classes: pre-void, void, non-void

fs: original

overlap: 0.0

sliding window: 5s

filename: three_class_raw_5s_no.csv

In [32]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=5.0, overlap=0.0)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 54.29it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 77.59it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 45.20it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 50.82it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 78.33it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 39.28it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 59.57it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 67.45it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 37.27it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 43.21it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 31.21it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 36.95it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 53.54it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 44.41it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 84.14it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 74.59it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 65.12it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 31.11it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 73.41it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 86.99it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 73.11it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 30.37it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 59.07it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 46.76it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 35.61it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 42.43it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.05it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 61.32it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 76.17it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 60.30it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 50.54it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 92.49it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 52.39it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 78.83it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 45.87it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 49.39it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 43.28it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 70.03it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 78.92it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.69it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 67.72it/s]

In [33]:
final_features.to_csv('features_data_main/three_class_raw_5s_no.csv', index=False)

## Data 10b
classes: pre-void, void, non-void

fs: original

overlap: 0.5

sliding window: 5s

filename: three_class_raw_5s_yo_0.5.csv

In [34]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=5.0, overlap=0.5)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 27.32it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 39.98it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.51it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 26.62it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 41.00it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.50it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 32.45it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 34.86it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.61it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 22.22it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.57it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.01it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 29.20it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.02it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 48.46it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 38.49it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 37.17it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.82it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 42.29it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 45.33it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 38.70it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.84it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 30.62it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.99it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.00it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.62it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.93it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 32.35it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 42.23it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 31.13it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 29.69it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 51.31it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 32.67it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 38.96it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.15it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 24.21it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.34it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 37.03it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 40.41it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.57it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 36.51it/s]

In [35]:
final_features.to_csv('features_data_main/three_class_raw_5s_yo_0.5.csv', index=False)

## Data 10c
classes: pre-void, void, non-void

fs: original

overlap: 0.8

sliding window: 5s

filename: three_class_raw_5s_yo_0.8.csv

In [36]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=5.0, overlap=0.8)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.30it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.65it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.22it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.51it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.15it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.09it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.60it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.20it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.45it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.30it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.12it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.55it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.29it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.03it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.12it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.78it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.80it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.38it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.00it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.78it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.68it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.29it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.53it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.29it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.25it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.82it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.33it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.00it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.08it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.40it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.98it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.99it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.07it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.32it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.85it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.66it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.00it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.75it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.98it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.05it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.34it/s]

In [37]:
final_features.to_csv('features_data_main/three_class_raw_5s_yo_0.8.csv', index=False)

## Validation data

In [3]:
val_dict = {}

val_dict['subj_11_void2'] = imu_dict['subj_11_void2']
val_dict['subj_9_void4'] = imu_dict['subj_9_void4']

In [4]:
labelled_imu_dict = {}
dict = copy.deepcopy(val_dict)
for i_void_instance, void_instance in tqdm(enumerate(dict.keys()), desc="Adding labels to IMU data"):
    acc = dict[void_instance]
    gt = ground_truth_dict[void_instance]
    
    # normalize data
    df = normalize(acc)
    
    # add the labels
    labelled_df = two_class_labels(df, gt)

    labelled_imu_dict[void_instance] = labelled_df

Adding labels to IMU data: 2it [00:00, 205.45it/s]

In [5]:
#  do not upsample
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(70, window_duration=2.0, overlap=0.8)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.03it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.27it/s]

In [7]:
final_features.to_csv('features_data_main/two_class_val.csv', index=False)
final_features.tail()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_std,gyr_mag_range,gyr_mag_rms,gyr_mag_var,gyr_mag_min,gyr_mag_max,gyr_mag_time_energy,gyr_mag_spectral_energy,label,experiment_id
100,14.114286,13.114286,15.114286,0.930832,0.730233,-1.178798,0.731628,3.633834,1.387388,0.535279,...,1.235417,5.315622,2.251936,1.526256,0.312845,5.628466,709.970431,99395.860359,void,2
101,14.500000,13.500000,15.500000,0.932324,0.733342,-1.144809,0.760778,3.798803,1.374544,0.578783,...,1.139086,5.315622,2.384957,1.297517,0.312845,5.628466,796.322961,111485.214506,void,2
102,14.885714,13.885714,15.885714,0.931391,0.731257,-1.048505,0.811455,3.798803,1.325829,0.658460,...,1.113900,5.315622,2.471362,1.240772,0.312845,5.628466,855.068405,119709.576741,void,2
103,15.271429,14.271429,16.271429,0.925552,0.702774,-1.158220,0.780274,3.798803,1.396532,0.608827,...,1.049136,5.075138,2.483381,1.100686,0.553328,5.628466,863.405358,120876.750124,void,2
104,15.657143,14.657143,16.657143,0.912977,0.796122,-1.147611,0.741121,3.798803,1.366115,0.549260,...,0.735421,2.843374,1.920129,0.540844,0.391111,3.234486,516.165187,72263.126185,void,2

In [24]:
from features_acc_gyr_more import GenerateFeatures

In [25]:
labelled_imu_dict = {}
dict = copy.deepcopy(imu_dict)
for i_void_instance, void_instance in tqdm(enumerate(dict.keys()), desc="Adding labels to IMU data"):
    acc = dict[void_instance]
    gt = ground_truth_dict[void_instance]
    
    # normalize data
    df = normalize(acc)
    
    # add the labels
    labelled_df = two_class_labels(df, gt)
    
    labelled_imu_dict[void_instance] = labelled_df

Adding labels to IMU data: 41it [00:00, 132.89it/s]

In [26]:
#  do not upsample
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=1.0, overlap=0.0)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.05it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.11it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.38it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.36it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.78it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.04it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.24it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.30it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  4.00it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.93it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.25it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.20it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.66it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.41it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.94it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.47it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.60it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.21it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.75it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.89it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.48it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.98it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.95it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.32it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.97it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.86it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.44it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.74it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.64it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.78it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.23it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.56it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.77it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.28it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.62it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.19it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.70it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.46it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.37it/s]
Analyzing : 100%|██████████| 8/8 [00:05<00:00,  1.49it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.55it/s]

In [27]:
final_features.to_csv('more_features_raw_1s_no.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_zero_crossing_rate,gyr_mag_slope,gyr_mag_autocorr_lag1,gyr_mag_peak_count,gyr_mag_skewness,gyr_mag_kurtosis,gyr_mag_iqr,gyr_mag_mad,label,experiment_id
0,0.499593,0.000000,0.999186,0.840598,0.524760,0.938842,1.134729,5.349532,1.472764,1.287610,...,0.0,0.002833,0.815575,7,0.968601,0.099250,1.595640,0.796588,non-void,1
1,1.498779,0.999186,1.998371,0.816380,0.561207,1.115575,0.848165,3.553001,1.401390,0.719385,...,0.0,-0.071335,0.937234,3,1.045409,0.413415,2.704403,1.274651,non-void,1
2,2.497964,1.998371,2.997557,0.892873,0.755155,0.804784,0.245606,1.054752,0.841427,0.060322,...,0.0,-0.006908,0.741973,12,0.618432,-0.063181,0.316204,0.182714,non-void,1
3,3.497150,2.997557,3.996743,0.928689,0.707887,0.720945,0.292908,1.507445,0.778175,0.085795,...,0.0,0.016839,0.869018,8,1.361755,1.778505,0.624453,0.331375,non-void,1
4,4.496336,3.996743,4.995929,0.874944,0.797456,0.588285,0.231525,1.161934,0.632205,0.053604,...,0.0,-0.001478,0.673278,13,0.547656,0.444346,0.410836,0.201083,non-void,1