In [23]:
import os
import pickle
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from tqdm import tqdm
from essentials import resample_data, three_class_labels, two_class_labels, normalize
from features_acc_gyr import GenerateFeatures
import copy

In [24]:
with open('data/df_dict_imu.pkl', 'rb') as f:
    imu_dict = pickle.load(f)
with open('data/df_minze_dict.pkl', 'rb') as f:
    ground_truth_dict = pickle.load(f)
with open('data/df_dict_urineestimate_method1.pkl', 'rb') as f:
    urine_estimate_dict = pickle.load(f)

Remove the data with the almost the entire data being void.
1. subj_9_void4
2. subj_11_void2

In [25]:
del imu_dict['subj_9_void4']
del imu_dict['subj_11_void2']

Extract windowed features from the 3 axis of the accelerometer and the acceleration magnitude.
1. mean
2. rms
3. std
4. range
5. variance
6. min
7. max
8. time energy
9. spectral energy
10. permutation entropy
11. spectral entropy

## Data 1
classes: void, non-void

fs: original

sliding window: 1s

overlap: 0

filename: two_class_raw_1s_no.csv

In [26]:
labelled_imu_dict = {}
dict = copy.deepcopy(imu_dict)
for i_void_instance, void_instance in tqdm(enumerate(dict.keys()), desc="Adding labels to IMU data"):
    acc = dict[void_instance]
    gt = ground_truth_dict[void_instance]
    
    # normalize data
    df = normalize(acc)
    
    # add the labels
    labelled_df = two_class_labels(df, gt)

    labelled_imu_dict[void_instance] = labelled_df

Adding labels to IMU data: 0it [00:00, ?it/s]

Adding labels to IMU data: 41it [00:00, 278.53it/s]

In [34]:
#  do not upsample
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=1.0, overlap=0.0)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 4/4 [00:00<00:00, 12.28it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 16.50it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 10.09it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 10.98it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 17.36it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  7.92it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 13.29it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 14.19it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  7.82it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  9.49it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  6.67it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  7.78it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 12.51it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 10.17it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 20.14it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 16.15it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 15.41it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  6.79it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 17.54it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 15.28it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 16.90it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  7.84it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 12.94it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 10.57it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  7.87it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  9.51it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  4.67it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 13.43it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 17.15it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 12.80it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 11.97it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 19.52it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 13.21it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 15.87it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  9.27it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 10.45it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  9.24it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 15.02it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 16.80it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  3.33it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 15.56it/s]

In [ ]:
final_features.to_csv('features_data_acc/two_class_raw_1s_no.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,acc_mag_std,acc_mag_range,acc_mag_rms,acc_mag_var,acc_mag_min,acc_mag_max,acc_mag_time_energy,acc_mag_spectral_energy,label,experiment_id
0,0.499593,0.000000,0.999186,0.840598,0.524760,0.938842,1.134729,5.349532,1.472764,1.287610,...,0.950861,4.338769,1.989574,0.904136,0.107588,4.446357,233.545858,13779.205614,non-void,1
1,1.498779,0.999186,1.998371,0.816380,0.561207,1.115575,0.848165,3.553001,1.401390,0.719385,...,0.857739,3.178608,1.767278,0.735717,0.395825,3.574433,184.273057,10872.110385,non-void,1
2,2.497964,1.998371,2.997557,0.892873,0.755155,0.804784,0.245606,1.054752,0.841427,0.060322,...,0.256452,1.056056,1.182674,0.065768,0.704282,1.760338,82.524353,4868.936821,non-void,1
3,3.497150,2.997557,3.996743,0.928689,0.707887,0.720945,0.292908,1.507445,0.778175,0.085795,...,0.297366,1.209767,1.123668,0.088427,0.668530,1.878297,74.495131,4395.212706,non-void,1
4,4.496336,3.996743,4.995929,0.874944,0.797456,0.588285,0.231525,1.161934,0.632205,0.053604,...,0.484519,2.415279,1.983645,0.234759,0.738840,3.154119,232.155916,13697.199038,non-void,1

## Data 1b
classes: void, non-void

fs: original

sliding window: 1s

overlap: 0.5

filename: two_class_raw_1s_yo_0.5.csv

In [36]:
#  do not upsample
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=1.0, overlap=0.5)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 4/4 [00:00<00:00,  6.11it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  8.33it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  5.10it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  5.54it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  8.80it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  4.29it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  6.84it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  7.32it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  4.08it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  4.84it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  3.42it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  3.95it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  6.29it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  4.85it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  9.88it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  7.69it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  7.39it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  3.39it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  8.98it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  9.17it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  8.57it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  3.88it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  6.39it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  5.26it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  3.84it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  4.68it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  2.36it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  6.84it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  8.43it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  5.90it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  6.01it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 10.25it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  6.46it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  7.97it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  4.87it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  5.38it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  4.69it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  7.24it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  8.50it/s]
Analyzing : 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  7.77it/s]

In [ ]:
final_features.to_csv('features_data_acc/two_class_raw_1s_yo_0.5.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,acc_mag_std,acc_mag_range,acc_mag_rms,acc_mag_var,acc_mag_min,acc_mag_max,acc_mag_time_energy,acc_mag_spectral_energy,label,experiment_id
0,0.499593,0.000000,0.999186,0.840598,0.524760,0.938842,1.134729,5.349532,1.472764,1.287610,...,0.950861,4.338769,1.989574,0.904136,0.107588,4.446357,233.545858,13779.205614,non-void,1
1,0.990718,0.491125,1.490311,0.782302,0.565548,1.226644,1.215409,5.349532,1.726810,1.477218,...,1.040282,4.338769,2.165554,1.082186,0.107588,4.446357,276.687882,16324.585010,non-void,1
2,1.481843,0.982250,1.981436,0.816380,0.556779,1.084483,0.893955,4.363070,1.405439,0.799155,...,0.884071,3.178608,1.809670,0.781582,0.395825,3.574433,193.219530,11399.952251,non-void,1
3,1.972968,1.473376,2.472561,0.902610,0.695212,0.751729,0.312815,1.479456,0.814217,0.097853,...,0.261445,1.009681,1.104056,0.068353,0.590924,1.600604,71.917433,4243.128539,non-void,1
4,2.464094,1.964501,2.963686,0.898106,0.761268,0.813395,0.236576,1.054752,0.847100,0.055968,...,0.258237,1.056056,1.183620,0.066686,0.704282,1.760338,82.656417,4876.728619,non-void,1

## Data 1c
classes: void, non-void

fs: original

sliding window: 1s

overlap: 0.8

filename: two_class_raw_1s_yo_0.8.csv

In [38]:
#  do not upsample
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=1.0, overlap=0.8)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 4/4 [00:01<00:00,  2.44it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  3.27it/s]
Analyzing : 100%|██████████| 4/4 [00:02<00:00,  1.89it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  2.13it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  3.42it/s]
Analyzing : 100%|██████████| 4/4 [00:02<00:00,  1.66it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  2.62it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  2.71it/s]
Analyzing : 100%|██████████| 4/4 [00:02<00:00,  1.49it/s]
Analyzing : 100%|██████████| 4/4 [00:02<00:00,  1.82it/s]
Analyzing : 100%|██████████| 4/4 [00:03<00:00,  1.25it/s]
Analyzing : 100%|██████████| 4/4 [00:02<00:00,  1.48it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  2.36it/s]
Analyzing : 100%|██████████| 4/4 [00:02<00:00,  1.87it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  3.95it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  3.00it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  2.97it/s]
Analyzing : 100%|██████████| 4/4 [00:03<00:00,  1.30it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  3.34it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  3.40it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  3.12it/s]
Analyzing : 100%|██████████| 4/4 [00:02<00:00,  1.43it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  2.44it/s]
Analyzing : 100%|██████████| 4/4 [00:02<00:00,  1.97it/s]
Analyzing : 100%|██████████| 4/4 [00:02<00:00,  1.34it/s]
Analyzing : 100%|██████████| 4/4 [00:02<00:00,  1.72it/s]
Analyzing : 100%|██████████| 4/4 [00:04<00:00,  1.16s/it]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  2.56it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  3.26it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  2.29it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  2.27it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  3.97it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  2.49it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  2.95it/s]
Analyzing : 100%|██████████| 4/4 [00:02<00:00,  1.85it/s]
Analyzing : 100%|██████████| 4/4 [00:02<00:00,  1.99it/s]
Analyzing : 100%|██████████| 4/4 [00:02<00:00,  1.71it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  2.78it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  3.05it/s]
Analyzing : 100%|██████████| 4/4 [00:06<00:00,  1.66s/it]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  2.76it/s]

In [ ]:
final_features.to_csv('features_data_acc/two_class_raw_1s_yo_0.8.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,acc_mag_std,acc_mag_range,acc_mag_rms,acc_mag_var,acc_mag_min,acc_mag_max,acc_mag_time_energy,acc_mag_spectral_energy,label,experiment_id
0,0.499593,0.000000,0.999186,0.840598,0.524760,0.938842,1.134729,5.349532,1.472764,1.287610,...,0.950861,4.338769,1.989574,0.904136,0.107588,4.446357,233.545858,13779.205614,non-void,1
1,0.685882,0.186289,1.185475,0.833607,0.520173,0.989449,1.158952,5.349532,1.523870,1.343169,...,0.974930,4.338769,1.987275,0.950488,0.107588,4.446357,233.006397,13747.377440,non-void,1
2,0.872171,0.372578,1.371763,0.823753,0.562236,1.193638,1.186426,5.349532,1.682967,1.407606,...,1.031948,4.338769,2.169826,1.064918,0.107588,4.446357,277.780664,16389.059150,non-void,1
3,1.058459,0.558867,1.558052,0.837070,0.566957,1.251707,1.200011,5.349532,1.734012,1.440027,...,1.012218,4.338769,2.173449,1.024585,0.107588,4.446357,278.708959,16443.828570,non-void,1
4,1.244748,0.745155,1.744341,0.815424,0.582808,1.165694,1.210199,5.349532,1.680305,1.464581,...,1.084391,4.338769,2.106941,1.175903,0.107588,4.446357,261.912788,15452.854511,non-void,1

## Data 2
classes: void, non-void

fs: original

overlap: 0

sliding window: 2s

filename: two_class_raw_2s_no.csv

In [41]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=2.0, overlap=0.0)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 4/4 [00:00<00:00, 23.27it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 32.39it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 19.41it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 21.69it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 35.16it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 16.97it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 26.38it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 29.28it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 15.16it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 18.92it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 13.36it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 15.12it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 22.48it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 19.62it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 40.38it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 32.23it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 30.67it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 13.37it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 32.49it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 35.13it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 31.63it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 15.51it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 25.93it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 20.57it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 14.95it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 18.18it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  8.70it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 27.89it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 34.12it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 25.47it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 24.91it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 40.99it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 26.68it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 31.91it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 20.29it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 21.66it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 18.54it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 29.28it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 32.73it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  6.45it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 29.51it/s]

In [ ]:
final_features.to_csv('features_data_acc/two_class_raw_2s_no.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,acc_mag_std,acc_mag_range,acc_mag_rms,acc_mag_var,acc_mag_min,acc_mag_max,acc_mag_time_energy,acc_mag_spectral_energy,label,experiment_id
0,0.999186,0.000000,1.998371,0.837517,0.656083,1.027208,1.005637,5.349532,1.437520,1.011306,...,0.911140,4.338769,1.881712,0.830176,0.107588,4.446357,417.818915,49302.631999,non-void,1
1,2.997557,1.998371,3.996743,0.914142,0.780981,0.762864,0.273525,1.507445,0.810418,0.074816,...,0.279919,1.209767,1.153548,0.078355,0.668530,1.878297,157.019484,18528.299055,non-void,1
2,4.995929,3.996743,5.995114,0.911102,0.825743,0.381709,0.479763,3.273455,0.613086,0.230173,...,0.597792,2.836612,1.896750,0.357355,0.577774,3.414386,424.524123,50093.846566,non-void,1
3,6.994300,5.995114,7.993486,0.880385,0.714032,0.842092,0.846989,5.457410,1.194366,0.717390,...,0.771801,3.302792,1.712800,0.595677,0.139373,3.442165,346.174540,40848.595671,non-void,1
4,8.992671,7.993486,9.991857,0.915965,0.812030,0.565058,0.443517,2.956667,0.718330,0.196707,...,0.549810,2.723102,1.488531,0.302291,0.259292,2.982394,261.455590,30851.759615,non-void,1

## Data 2b
classes: void, non-void

fs: original

overlap: 0.5

sliding window: 2s

filename: two_class_raw_2s_yo_0.5.csv

In [43]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=2.0, overlap=0.5)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 4/4 [00:00<00:00, 11.65it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 16.58it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  9.96it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 10.94it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 17.60it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  8.24it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 12.64it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 14.65it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  7.83it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  9.12it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  6.49it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  7.31it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 11.87it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  8.73it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 19.54it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 15.93it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 15.76it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  6.80it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 16.72it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 17.64it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 17.17it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  7.59it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 12.77it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  9.27it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  7.45it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  9.25it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  4.55it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 13.57it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 17.53it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 11.56it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 11.61it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 21.66it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 13.43it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 17.02it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  9.89it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 10.56it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  9.31it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 15.05it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 17.11it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  3.27it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 15.16it/s]

In [ ]:
final_features.to_csv('features_data_acc/two_class_raw_2s_yo_0.5.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,acc_mag_std,acc_mag_range,acc_mag_rms,acc_mag_var,acc_mag_min,acc_mag_max,acc_mag_time_energy,acc_mag_spectral_energy,label,experiment_id
0,0.999186,0.000000,1.998371,0.837517,0.656083,1.027208,1.005637,5.349532,1.437520,1.011306,...,0.911140,4.338769,1.881712,0.830176,0.107588,4.446357,417.818915,49302.631999,non-void,1
1,1.998371,0.999186,2.997557,0.872310,0.644016,0.960179,0.643429,3.553001,1.155831,0.414001,...,0.662489,3.178608,1.503661,0.438892,0.395825,3.574433,266.797410,31482.094413,non-void,1
2,2.997557,1.998371,3.996743,0.914142,0.780981,0.762864,0.273525,1.507445,0.810418,0.074816,...,0.279919,1.209767,1.153548,0.078355,0.668530,1.878297,157.019484,18528.299055,non-void,1
3,3.996743,2.997557,4.995929,0.909732,0.722111,0.654615,0.272212,1.507445,0.708957,0.074099,...,0.581355,2.485588,1.612060,0.337974,0.668530,3.154119,306.651047,36184.823489,non-void,1
4,4.995929,3.996743,5.995114,0.911102,0.825743,0.381709,0.479763,3.273455,0.613086,0.230173,...,0.597792,2.836612,1.896750,0.357355,0.577774,3.414386,424.524123,50093.846566,non-void,1

## Data 2c
classes: void, non-void

fs: original

overlap: 0.8

sliding window: 2s

filename: two_class_raw_2s_yo_0.8.csv

In [45]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=2.0, overlap=0.8)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 4/4 [00:00<00:00,  5.21it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  6.56it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  3.94it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  4.46it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  7.13it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  3.37it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  5.55it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  5.70it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  3.08it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  3.70it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  2.47it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  3.09it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  4.80it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  3.65it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  8.37it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  6.47it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  6.29it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  2.69it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  6.86it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  6.71it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  6.63it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  3.04it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  4.89it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  4.23it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  3.06it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  3.57it/s]
Analyzing : 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  5.52it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  6.83it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  5.00it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  4.80it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  8.48it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  5.25it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  6.44it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  4.03it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  4.17it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  3.67it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  5.93it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  6.46it/s]
Analyzing : 100%|██████████| 4/4 [00:03<00:00,  1.25it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  5.76it/s]

In [ ]:
final_features.to_csv('features_data_acc/two_class_raw_2s_yo_0.8.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,acc_mag_std,acc_mag_range,acc_mag_rms,acc_mag_var,acc_mag_min,acc_mag_max,acc_mag_time_energy,acc_mag_spectral_energy,label,experiment_id
0,0.999186,0.000000,1.998371,0.837517,0.656083,1.027208,1.005637,5.349532,1.437520,1.011306,...,0.911140,4.338769,1.881712,0.830176,0.107588,4.446357,417.818915,49302.631999,non-void,1
1,1.388699,0.389513,2.387885,0.856472,0.634105,1.049054,0.936724,5.349532,1.406402,0.877451,...,0.884438,4.338769,1.782682,0.782231,0.107588,4.446357,374.998746,44249.852041,non-void,1
2,1.778212,0.779026,2.777398,0.866184,0.638264,0.996176,0.888607,5.349532,1.334912,0.789622,...,0.849718,4.338769,1.714939,0.722020,0.107588,4.446357,347.039661,40950.680050,non-void,1
3,2.167725,1.168539,3.166911,0.878813,0.663285,0.929198,0.584101,3.553001,1.097535,0.341174,...,0.588361,3.178608,1.422764,0.346169,0.395825,3.574433,238.862264,28185.747098,non-void,1
4,2.557238,1.558052,3.556424,0.905723,0.782317,0.762776,0.265824,1.479456,0.807768,0.070662,...,0.267589,1.169414,1.115914,0.071604,0.590924,1.760338,146.941278,17339.070841,non-void,1

## Data 3
classes: void, non-void

fs: original

overlap: 0

sliding window: 3s

filename: two_class_raw_3s_no.csv

In [47]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=3.0, overlap=0.0)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 4/4 [00:00<00:00, 25.42it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 48.04it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 29.49it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 32.34it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 49.54it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 24.30it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 37.80it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 42.30it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 19.90it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 27.16it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 19.51it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 21.90it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 37.09it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 28.26it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 55.11it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 42.94it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 43.75it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 18.49it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 49.56it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 51.26it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 41.35it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 20.58it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 37.13it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 28.86it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 21.81it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 22.36it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 12.60it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 37.36it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 48.39it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 35.82it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 33.86it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 58.22it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 40.29it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 48.87it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 28.40it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 29.27it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 25.60it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 40.80it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 40.74it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  9.21it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 44.83it/s]

In [ ]:
final_features.to_csv('features_data_acc/two_class_raw_3s_no.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,acc_mag_std,acc_mag_range,acc_mag_rms,acc_mag_var,acc_mag_min,acc_mag_max,acc_mag_time_energy,acc_mag_spectral_energy,label,experiment_id
0,1.498779,0.000000,2.997557,0.868352,0.694367,0.953067,0.839825,5.349532,1.270292,0.705305,...,0.793182,4.338769,1.681308,0.629138,0.107588,4.446357,500.343268,88560.758463,non-void,1
1,4.496336,2.997557,5.995114,0.919605,0.790731,0.494788,0.455654,3.273455,0.672633,0.207621,...,0.617890,2.836612,1.679082,0.381788,0.577774,3.414386,499.019254,88326.407967,non-void,1
2,7.493893,5.995114,8.992671,0.903234,0.730563,0.758589,0.711104,5.457410,1.039772,0.505669,...,0.678783,3.302792,1.627338,0.460747,0.139373,3.442165,468.736388,82966.340654,non-void,1
3,10.491450,8.992671,11.990229,0.873187,0.787136,0.635391,0.492101,2.956667,0.803670,0.242164,...,0.592989,3.389304,1.441788,0.351636,0.259292,3.648596,367.939015,65125.205680,non-void,1
4,13.489007,11.990229,14.987786,0.915277,0.765171,0.386718,0.475147,3.601410,0.612630,0.225764,...,0.614338,2.984583,1.298698,0.377411,0.286777,3.271360,298.531126,52840.009224,non-void,1

## Data 3b
classes: void, non-void

fs: original

overlap: 0.5

sliding window: 3s

filename: two_class_raw_3s_yo_0.5.csv

In [49]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=3.0, overlap=0.5)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 4/4 [00:00<00:00, 17.07it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 23.91it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 14.29it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 15.92it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 25.31it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 12.05it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 16.65it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 20.66it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 11.57it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 13.55it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  9.66it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 10.76it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 18.37it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 14.76it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 30.48it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 24.08it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 23.02it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  9.96it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 26.18it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 26.52it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 24.97it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 11.55it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 19.04it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 15.51it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 11.59it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 14.18it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  6.90it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 20.29it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 25.96it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 18.76it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 17.87it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 23.11it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 19.53it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 25.00it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 14.69it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 14.65it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 13.94it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 21.90it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 25.79it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  4.69it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 22.62it/s]

In [ ]:
final_features.to_csv('features_data_acc/two_class_raw_3s_yo_0.5.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,acc_mag_std,acc_mag_range,acc_mag_rms,acc_mag_var,acc_mag_min,acc_mag_max,acc_mag_time_energy,acc_mag_spectral_energy,label,experiment_id
0,1.498779,0.000000,2.997557,0.868352,0.694367,0.953067,0.839825,5.349532,1.270292,0.705305,...,0.793182,4.338769,1.681308,0.629138,0.107588,4.446357,500.343268,88560.758463,non-void,1
1,2.989089,1.490311,4.487868,0.906822,0.799264,0.731636,0.286953,1.507445,0.785897,0.082342,...,0.364200,1.948523,1.240488,0.132642,0.590924,2.539447,272.369514,48209.403897,non-void,1
2,4.479400,2.980622,5.978179,0.919605,0.791796,0.483426,0.432560,2.498092,0.648698,0.187108,...,0.607107,2.836612,1.663638,0.368579,0.577774,3.414386,489.881299,86708.989944,non-void,1
3,5.969711,4.470933,7.468490,0.892201,0.713119,0.548849,0.809403,5.457410,0.977941,0.655133,...,0.762938,3.302792,1.861156,0.582074,0.139373,3.442165,613.110558,108520.568723,non-void,1
4,7.460022,5.961244,8.958801,0.902390,0.730050,0.776208,0.723594,5.457410,1.061172,0.523588,...,0.688580,3.302792,1.648256,0.474143,0.139373,3.442165,480.864329,85112.986222,non-void,1

## Data 3c
classes: void, non-void

fs: original

overlap: 0.8

sliding window: 3s

filename: two_class_raw_3s_yo_0.8.csv

In [51]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=3.0, overlap=0.8)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 4/4 [00:00<00:00,  7.41it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  9.62it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  5.62it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  6.61it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 10.93it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  5.04it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  7.95it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  8.40it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  4.56it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  5.55it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  3.92it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  4.59it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  7.36it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  5.93it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 12.53it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  9.65it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  9.16it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  3.79it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 10.06it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 10.61it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 10.29it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  4.29it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  7.51it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  5.77it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  4.52it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  5.50it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  2.75it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  8.41it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 10.71it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  7.60it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  7.37it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 13.07it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  7.92it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  9.21it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  5.83it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  6.33it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  5.57it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  8.61it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  9.48it/s]
Analyzing : 100%|██████████| 4/4 [00:02<00:00,  1.84it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  8.16it/s]

In [ ]:
final_features.to_csv('features_data_acc/two_class_raw_3s_yo_0.8.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,acc_mag_std,acc_mag_range,acc_mag_rms,acc_mag_var,acc_mag_min,acc_mag_max,acc_mag_time_energy,acc_mag_spectral_energy,label,experiment_id
0,1.498779,0.000000,2.997557,0.868352,0.694367,0.953067,0.839825,5.349532,1.270292,0.705305,...,0.793182,4.338769,1.681308,0.629138,0.107588,4.446357,500.343268,88560.758463,non-void,1
1,2.091516,0.592737,3.590294,0.891024,0.700772,0.937189,0.752365,5.349532,1.201822,0.566053,...,0.740157,4.338769,1.548707,0.547832,0.107588,4.446357,424.533445,75142.419722,non-void,1
2,2.684253,1.185475,4.183032,0.904307,0.779004,0.836695,0.516392,3.553001,0.983219,0.266661,...,0.516758,3.178608,1.332152,0.267039,0.395825,3.574433,314.109554,55597.391084,non-void,1
3,3.276990,1.778212,4.775769,0.900103,0.797495,0.724808,0.273863,1.507445,0.774821,0.075001,...,0.476615,2.287177,1.401814,0.227162,0.668530,2.955708,347.819423,61564.037784,non-void,1
4,3.869728,2.370949,5.368506,0.917587,0.797179,0.654555,0.289030,1.550907,0.715528,0.083538,...,0.563559,2.485588,1.560147,0.317599,0.668530,3.154119,430.828222,76256.595374,non-void,1

## Data 4
classes: void, non-void

fs: original

overlap: 0.0

sliding window: 4s

filename: two_class_raw_4s_no.csv

In [53]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=4.0, overlap=0.0)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 4/4 [00:00<00:00, 41.42it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 59.44it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 36.94it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 40.27it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 69.29it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 31.88it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 49.09it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 53.03it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 28.29it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 36.01it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 24.95it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 23.99it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 41.31it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 34.33it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 73.74it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 56.32it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 55.66it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 24.28it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 66.87it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 69.07it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 60.53it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 28.96it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 45.72it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 37.55it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 28.19it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 34.83it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 16.90it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 38.00it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 53.22it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 45.41it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 47.59it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 79.95it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 52.35it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 64.65it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 39.07it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 38.69it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 35.45it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 55.39it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 62.80it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 11.93it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 58.06it/s]

In [ ]:
final_features.to_csv('features_data_acc/two_class_raw_4s_no.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,acc_mag_std,acc_mag_range,acc_mag_rms,acc_mag_var,acc_mag_min,acc_mag_max,acc_mag_time_energy,acc_mag_spectral_energy,label,experiment_id
0,1.998371,0.000000,3.996743,0.888082,0.724174,0.895036,0.748686,5.349532,1.166885,0.560530,...,0.723731,4.338769,1.560691,0.523787,0.107588,4.446357,574.838399,135661.862108,non-void,1
1,5.995114,3.996743,7.993486,0.900675,0.721296,0.611901,0.725789,5.457410,0.949311,0.526770,...,0.703477,3.302792,1.807117,0.494880,0.139373,3.442165,770.698663,181884.884474,non-void,1
2,9.991857,7.993486,11.990229,0.901749,0.809333,0.624439,0.438269,2.956667,0.762892,0.192080,...,0.555408,3.389304,1.441663,0.308478,0.259292,3.648596,490.500863,115758.203769,non-void,1
3,13.988600,11.990229,15.986972,0.917454,0.790501,0.295423,0.460685,3.601410,0.547271,0.212231,...,0.605685,3.149696,1.285374,0.366855,0.121664,3.271360,389.916005,92020.177087,non-void,1
4,17.985343,15.986972,19.983714,0.922168,0.631454,0.394139,1.000649,5.412671,1.075474,1.001298,...,0.906005,3.925659,1.794342,0.820845,0.157846,4.083505,759.840559,179322.371830,void,1

## Data 4b
classes: void, non-void

fs: original

overlap: 0.5

sliding window: 4s

filename: two_class_raw_4s_yo_0.5.csv

In [55]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=4.0, overlap=0.5)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 4/4 [00:00<00:00, 23.12it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 32.33it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 18.41it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 19.96it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 34.12it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 16.27it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 21.83it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 28.36it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 15.59it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 18.57it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 13.09it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 15.11it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 24.08it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 18.89it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 41.13it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 30.93it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 30.33it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 13.15it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 34.27it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 34.63it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 32.59it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 14.82it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 25.18it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 20.39it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 15.11it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 18.42it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  8.66it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 24.02it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 33.40it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 25.02it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 23.92it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 41.95it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 26.86it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 32.63it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 19.18it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 21.07it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 18.62it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 29.42it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 34.57it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  6.24it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 30.59it/s]

In [ ]:
final_features.to_csv('features_data_acc/two_class_raw_4s_yo_0.5.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,acc_mag_std,acc_mag_range,acc_mag_rms,acc_mag_var,acc_mag_min,acc_mag_max,acc_mag_time_energy,acc_mag_spectral_energy,label,experiment_id
0,1.998371,0.000000,3.996743,0.888082,0.724174,0.895036,0.748686,5.349532,1.166885,0.560530,...,0.723731,4.338769,1.560691,0.523787,0.107588,4.446357,574.838399,135661.862108,non-void,1
1,3.996743,1.998371,5.995114,0.916050,0.817238,0.572287,0.434528,3.273455,0.718559,0.188814,...,0.577754,2.836612,1.569767,0.333800,0.577774,3.414386,581.543607,137244.291241,non-void,1
2,5.995114,3.996743,7.993486,0.900675,0.721296,0.611901,0.725789,5.457410,0.949311,0.526770,...,0.703477,3.302792,1.807117,0.494880,0.139373,3.442165,770.698663,181884.884474,non-void,1
3,7.993486,5.995114,9.991857,0.908323,0.745699,0.703575,0.690098,5.457410,0.985522,0.476235,...,0.674016,3.302792,1.604588,0.454297,0.139373,3.442165,607.630130,143400.710573,non-void,1
4,9.991857,7.993486,11.990229,0.901749,0.809333,0.624439,0.438269,2.956667,0.762892,0.192080,...,0.555408,3.389304,1.441663,0.308478,0.259292,3.648596,490.500863,115758.203769,non-void,1

## Data 4c
classes: void, non-void

fs: original

overlap: 0.8

sliding window: 4s

filename: two_class_raw_4s_yo_0.8.csv

In [59]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=4.0, overlap=0.8)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 4/4 [00:00<00:00,  9.01it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 13.23it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  7.62it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  8.68it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 13.91it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  6.76it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 10.36it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 11.60it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  5.68it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  7.53it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  5.15it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  6.11it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  9.64it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  7.68it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 17.30it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 13.06it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 10.94it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  5.23it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 13.80it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 13.35it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 12.08it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  5.99it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 10.11it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  8.32it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  6.11it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  7.39it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  3.68it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 11.48it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 12.04it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 10.21it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  9.70it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 17.60it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 10.83it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 13.47it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  7.94it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  8.42it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  7.51it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 11.85it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 13.94it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  2.51it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 12.36it/s]

In [ ]:
final_features.to_csv('features_data_acc/two_class_raw_4s_yo_0.8.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,acc_mag_std,acc_mag_range,acc_mag_rms,acc_mag_var,acc_mag_min,acc_mag_max,acc_mag_time_energy,acc_mag_spectral_energy,label,experiment_id
0,1.998371,0.000000,3.996743,0.888082,0.724174,0.895036,0.748686,5.349532,1.166885,0.560530,...,0.723731,4.338769,1.560691,0.523787,0.107588,4.446357,574.838399,135661.862108,non-void,1
1,2.794333,0.795962,4.792704,0.888588,0.758875,0.833254,0.676522,5.349532,1.073310,0.457682,...,0.707550,4.338769,1.601925,0.500627,0.107588,4.446357,605.614925,142925.122382,non-void,1
2,3.590294,1.591923,5.588666,0.914118,0.829681,0.643343,0.329404,1.727885,0.722771,0.108507,...,0.564595,2.823462,1.522869,0.318767,0.590924,3.414386,547.314495,129166.220728,non-void,1
3,4.386256,2.387885,6.384627,0.918808,0.782531,0.602633,0.553150,3.840626,0.818011,0.305975,...,0.663644,3.302792,1.678899,0.440423,0.139373,3.442165,665.213293,156990.337111,non-void,1
4,5.182217,3.183846,7.180589,0.906615,0.724715,0.569451,0.682941,5.457410,0.889204,0.466409,...,0.692580,3.302792,1.734392,0.479667,0.139373,3.442165,709.915653,167540.094067,non-void,1

## Data 5
classes: void, non-void

fs: original

overlap: 0.0

sliding window: 5s

filename: two_class_raw_5s_no.csv

In [60]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=5.0, overlap=0.0)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 4/4 [00:00<00:00, 53.35it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 68.70it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 43.72it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 47.29it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 77.95it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 40.84it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 60.73it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 64.67it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 35.83it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 42.36it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 30.71it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 33.39it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 53.02it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 42.84it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 83.30it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 75.62it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 66.80it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 30.76it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 71.33it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 89.61it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 74.55it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 32.87it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 58.40it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 45.66it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 34.30it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 36.57it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 21.15it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 61.40it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 73.85it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 59.75it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 39.29it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 75.72it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 59.71it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 74.03it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 46.40it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 49.37it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 43.58it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 66.23it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 77.34it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 14.97it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 64.74it/s]

In [ ]:
final_features.to_csv('features_data_acc/two_class_raw_5s_no.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,acc_mag_std,acc_mag_range,acc_mag_rms,acc_mag_var,acc_mag_min,acc_mag_max,acc_mag_time_energy,acc_mag_spectral_energy,label,experiment_id
0,2.497964,0.000000,4.995929,0.888117,0.737073,0.833686,0.688622,5.349532,1.081311,0.474200,...,0.716086,4.338769,1.653957,0.512779,0.107588,4.446357,806.994315,238063.322826,non-void,1
1,7.493893,4.995929,9.991857,0.911608,0.753020,0.597887,0.699962,5.457410,0.920552,0.489947,...,0.679047,3.302792,1.646772,0.461105,0.139373,3.442165,799.998337,235999.509440,non-void,1
2,12.489822,9.991857,14.987786,0.897663,0.801344,0.505559,0.478334,3.601410,0.695984,0.228804,...,0.595264,3.361819,1.337309,0.354339,0.286777,3.648596,527.576399,155635.037713,non-void,1
3,17.485750,14.987786,19.983714,0.924754,0.681130,0.319619,0.915191,5.412671,0.969397,0.837574,...,0.869110,3.961842,1.698679,0.755352,0.121664,4.083505,851.225438,251111.504107,void,1
4,22.481679,19.983714,24.979643,0.944870,0.844899,0.984424,0.390305,2.799139,1.058975,0.152338,...,0.608275,2.809447,2.129921,0.369998,0.791294,3.600741,1338.286375,394794.480693,void,1

## Data 5b
classes: void, non-void

fs: original

overlap: 0.5

sliding window: 5s

filename: two_class_raw_5s_yo_0.5.csv

In [62]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=5.0, overlap=0.5)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 4/4 [00:00<00:00, 27.31it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 33.16it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 21.19it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 24.95it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 42.11it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 20.03it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 33.45it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 35.63it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 18.99it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 22.57it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 15.96it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  7.73it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 29.93it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 23.71it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 52.22it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 40.59it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 36.73it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 15.95it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 42.97it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 42.72it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 40.99it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 18.49it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 31.03it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 24.71it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 17.90it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 22.66it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 10.71it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 32.18it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 42.64it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 31.05it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 29.44it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 50.45it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 33.42it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 39.27it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 23.82it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 20.53it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 21.27it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 38.01it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 43.55it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  7.52it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 37.36it/s]

In [ ]:
final_features.to_csv('features_data_acc/two_class_raw_5s_yo_0.5.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,acc_mag_std,acc_mag_range,acc_mag_rms,acc_mag_var,acc_mag_min,acc_mag_max,acc_mag_time_energy,acc_mag_spectral_energy,label,experiment_id
0,2.497964,0.000000,4.995929,0.888117,0.737073,0.833686,0.688622,5.349532,1.081311,0.474200,...,0.716086,4.338769,1.653957,0.512779,0.107588,4.446357,806.994315,238063.322826,non-void,1
1,4.987461,2.489497,7.485425,0.898142,0.746140,0.620001,0.656198,5.457410,0.902772,0.430596,...,0.679124,3.302792,1.657899,0.461209,0.139373,3.442165,810.845896,239199.539386,non-void,1
2,7.476958,4.978993,9.974922,0.911677,0.752174,0.599177,0.699707,5.457410,0.921197,0.489590,...,0.681776,3.302792,1.651465,0.464818,0.139373,3.442165,804.563913,237346.354202,non-void,1
3,9.966454,7.468490,12.464418,0.909585,0.818971,0.636508,0.432122,2.956667,0.769332,0.186729,...,0.562112,3.389304,1.457127,0.315970,0.259292,3.648596,626.349530,184773.111299,non-void,1
4,12.455951,9.957987,14.953915,0.899875,0.801243,0.507144,0.476810,3.601410,0.696092,0.227348,...,0.594089,3.361819,1.342048,0.352941,0.286777,3.648596,531.322627,156740.174850,non-void,1

## Data 5c
classes: void, non-void

fs: original

overlap: 0.8

sliding window: 5s

filename: two_class_raw_5s_yo_0.8.csv

In [64]:
all_features = []
for exp_id, imu_data in enumerate(labelled_imu_dict.keys()):    
    # Extract features
    
    df = labelled_imu_dict[imu_data]    
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=5.0, overlap=0.8)
    features, _ = analyzer.analyze_multi_axis_imu(labelled_imu_dict[imu_data])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id + 1  # Track source
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 4/4 [00:00<00:00, 11.93it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 16.48it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  8.68it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 10.65it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 17.07it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  8.19it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 13.88it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 14.62it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  7.22it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  9.05it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  6.36it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  7.40it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 12.29it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  9.57it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 21.08it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 14.60it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 15.33it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  6.19it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 18.00it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 18.51it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 14.74it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  7.23it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 12.13it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 10.12it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  7.15it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  9.05it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  4.35it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 13.13it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 17.12it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 12.11it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 11.97it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 21.32it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 13.21it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 16.13it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  9.07it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 10.34it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00,  8.96it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 14.63it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 17.10it/s]
Analyzing : 100%|██████████| 4/4 [00:01<00:00,  3.05it/s]
Analyzing : 100%|██████████| 4/4 [00:00<00:00, 15.16it/s]

In [ ]:
final_features.to_csv('features_data_acc/two_class_raw_5s_yo_0.8.csv', index=False)
final_features.head()

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,acc_mag_std,acc_mag_range,acc_mag_rms,acc_mag_var,acc_mag_min,acc_mag_max,acc_mag_time_energy,acc_mag_spectral_energy,label,experiment_id
0,2.497964,0.000000,4.995929,0.888117,0.737073,0.833686,0.688622,5.349532,1.081311,0.474200,...,0.716086,4.338769,1.653957,0.512779,0.107588,4.446357,806.994315,238063.322826,non-void,1
1,3.480215,0.982250,5.978179,0.903643,0.831037,0.669089,0.585473,4.363070,0.889078,0.342779,...,0.644985,3.178608,1.611580,0.416005,0.395825,3.574433,766.171423,226020.569699,non-void,1
2,4.462465,1.964501,6.960429,0.908870,0.749159,0.646192,0.548827,3.840626,0.847806,0.301211,...,0.640390,3.302792,1.623112,0.410099,0.139373,3.442165,777.174905,229266.597066,non-void,1
3,5.444715,2.946751,7.942680,0.907880,0.743695,0.628383,0.661715,5.457410,0.912541,0.437867,...,0.684722,3.302792,1.687541,0.468845,0.139373,3.442165,840.099468,247829.343144,non-void,1
4,6.426966,3.929001,8.924930,0.908219,0.746226,0.612415,0.656816,5.457410,0.898031,0.431407,...,0.664194,3.302792,1.744343,0.441153,0.139373,3.442165,897.605878,264793.733995,non-void,1