In [1]:
import pickle
import pandas as pd

In [2]:
with open('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/imb_files/dt_imb_152_entire_improved.pkl', 'rb') as f:
    dt_results = pickle.load(f)
with open('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/imb_files/rf_imb_152_entire_improved.pkl', 'rb') as f:
    rf_results = pickle.load(f)
with open('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/imb_files/xgb_imb_152_entire_improved.pkl', 'rb') as f:
    xgb_results = pickle.load(f)

In [3]:
imb_tech = ['none', 'oversample_smote', 'undersample_tomek_links', 'combined_smote_tomek']
models = ['Decision Tree', 'Random Forest', 'XGBoost']

In [4]:
# Combine all model results into one dictionary
all_results = {
    'Decision Tree': dt_results,
    'Random Forest': rf_results,
    'XGBoost': xgb_results
}

In [5]:
import pandas as pd
import numpy as np

def format_cv_results_separate_models(model_results_dict, imb_tech, models):
    """
    Convert cross-validation results from separate model dictionaries to tabular format.
    
    Parameters:
    model_results_dict: Dictionary where keys are model names and values are 
                    dictionaries with structure {dataset: {imbalance_technique: {metrics...}}}
    imb_tech: List of imbalance handling techniques
    models: List of model names
    
    Returns:
    pandas.DataFrame: Formatted results table
    """
    
    formatted_data = []
    
    # Iterate through each model
    for model in models:
        if model in model_results_dict:
            model_data = model_results_dict[model]
            
            
            # Iterate through each dataset for this model
            for dataset, dataset_results in model_data.items():
                
                # Iterate through each imbalance technique
                for technique in imb_tech:
                    # Check if this technique exists in the results
                    if technique in dataset_results:
                        technique_results = dataset_results[technique]
                        
                        recall_void_avg = technique_results.get('mean_recall_minority', 0)
                        recall_void_std = technique_results.get('std_recall_minority', 0)
                        accuracy_avg = technique_results.get('mean_accuracy', 0)
                        accuracy_std = technique_results.get('std_accuracy', 0)
                        f1_void_avg = technique_results.get('mean_f1_minority', 0)
                        f1_void_std = technique_results.get('std_f1_minority', 0)
                        macro_f1_avg = technique_results.get('macro_f1', 0)
                        macro_f1_std = technique_results.get('std_macro_f1', 0)
                        weighted_f1_avg = technique_results.get('weighted_f1', 0)
                        weighted_f1_std = technique_results.get('std_weighted_f1', 0)
                        
                        if technique == "none":
                            technique = "Baseline (none)"
                        elif technique == "oversample_smote":
                            technique = "SMOTE"
                        elif technique == "undersample_tomek_links":
                            technique = "TomekLinks"
                        elif technique == "combined_smote_tomek":
                            technique = "SMOTETomek"
                        
                        # Add row to formatted data
                        formatted_data.append({
                            'Dataset': dataset,
                            'Model': model,
                            'Imbalance Technique': technique,
                            'F1-Score (avg)': round(f1_void_avg, 5),
                            'F1-Score (std)': round(f1_void_std, 5),
                            'F1-Score (avg:std)': round(f1_void_avg/f1_void_std, 5),
                            'Recall (avg)': round(recall_void_avg, 5),
                            'Recall (std)': round(recall_void_std, 5),
                            'Recall (avg:std)': round(recall_void_avg/recall_void_std, 5),
                            'Accuracy (avg)': round(accuracy_avg, 5),
                            'Accuracy (std)': round(accuracy_std, 5),
                            'Accuracy (avg:std)': round(accuracy_avg/accuracy_std, 5),
                            'Macro F1 (avg)': round(macro_f1_avg, 5),
                            'Macro F1 (std)': round(macro_f1_std, 5),
                            'Macro F1 (avg:std)': round(macro_f1_avg/macro_f1_std, 5),
                            'Weighted F1 (avg)': round(weighted_f1_avg, 5),
                            'Weighted F1 (std)': round(weighted_f1_std, 5),
                            'Weighted F1 (avg:std)': round(weighted_f1_avg/weighted_f1_std, 5)
                            
                        })
                        
                        
    
    # Create DataFrame
    df = pd.DataFrame(formatted_data)
    
    # Sort by Dataset, Model, and Imbalance Technique for better organization
    # df = df.sort_values(['Dataset', 'Model', 'Imbalance Technique']).reset_index(drop=True)
    
    return df


print("Function ready to use for separate model dictionaries.")

Function ready to use for separate model dictionaries.

In [6]:
df = format_cv_results_separate_models(all_results, imb_tech, models)
df

,Dataset,Model,Imbalance Technique,F1-Score (avg),F1-Score (std),F1-Score (avg:std),Recall (avg),Recall (std),Recall (avg:std),Accuracy (avg),Accuracy (std),Accuracy (avg:std),Macro F1 (avg),Macro F1 (std),Macro F1 (avg:std),Weighted F1 (avg),Weighted F1 (std),Weighted F1 (avg:std)
0,1s_no,Decision Tree,Baseline (none),0.47537,0.07788,6.10413,0.49075,0.07925,6.19283,0.59426,0.05665,10.49038,0.56398,0.03578,15.76335,0.59972,0.06603,9.08264
1,1s_no,Decision Tree,SMOTE,0.48098,0.06601,7.28625,0.51553,0.09311,5.53646,0.58494,0.06506,8.99083,0.56021,0.04577,12.23837,0.59184,0.07519,7.87131
2,1s_no,Decision Tree,TomekLinks,0.53868,0.07341,7.33821,0.59503,0.06994,8.50749,0.61928,0.05365,11.54249,0.59891,0.03949,15.16547,0.62723,0.06036,10.39073
3,1s_no,Decision Tree,SMOTETomek,0.49280,0.09363,5.26308,0.53476,0.13951,3.83312,0.59469,0.06665,8.92225,0.56871,0.05433,10.46763,0.60044,0.07584,7.91715
4,1s_0.5,Decision Tree,Baseline (none),0.52683,0.06393,8.24048,0.54209,0.10550,5.13816,0.62158,0.07571,8.20977,0.60216,0.06428,9.36697,0.62359,0.08034,7.76234
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,5s_0.5,XGBoost,SMOTETomek,0.63321,0.11632,5.44364,0.64635,0.16871,3.83109,0.70467,0.12417,5.67494,0.68739,0.11266,6.10163,0.70453,0.12955,5.43827
176,5s_0.8,XGBoost,Baseline (none),0.61180,0.11703,5.22760,0.59551,0.17179,3.46656,0.68684,0.12984,5.28969,0.66801,0.11764,5.67861,0.68366,0.13317,5.13381
177,5s_0.8,XGBoost,SMOTE,0.62476,0.11708,5.33636,0.63282,0.17686,3.57816,0.68203,0.13969,4.88246,0.66622,0.12880,5.17240,0.68217,0.14032,4.86162
178,5s_0.8,XGBoost,TomekLinks,0.63092,0.12790,4.93309,0.62563,0.19045,3.28507,0.69592,0.14003,4.96988,0.67889,0.12915,5.25658,0.69358,0.14283,4.85592
179,5s_0.8,XGBoost,SMOTETomek,0.63459,0.09616,6.59938,0.64158,0.15230,4.21254,0.68829,0.12540,5.48872,0.67422,0.11348,5.94105,0.68885,0.12560,5.48471

<!-- Sort in ascending order based on ### Recall Void (avg:std) -->

In [ ]:
# Save the DataFrame to a CSV file
# df.to_csv('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/imb_files/combined_results_separate_models.csv', index=False)

In [12]:
# Sort in descending order based on 'Recall Void (avg:std)'
df_sorted = df.sort_values(by='Macro F1 (avg)', ascending=False).reset_index(drop=True)
df_sorted

,Dataset,Model,Imbalance Technique,F1-Score (avg),F1-Score (std),F1-Score (avg:std),Recall (avg),Recall (std),Recall (avg:std),Accuracy (avg),Accuracy (std),Accuracy (avg:std),Macro F1 (avg),Macro F1 (std),Macro F1 (avg:std),Weighted F1 (avg),Weighted F1 (std),Weighted F1 (avg:std)
0,3s_no,Random Forest,TomekLinks,0.68003,0.08269,8.22398,0.72279,0.15140,4.77406,0.72936,0.10341,7.05298,0.71663,0.09278,7.72392,0.72984,0.10521,6.93686
1,5s_0.5,Random Forest,TomekLinks,0.67558,0.11230,6.01590,0.71529,0.18737,3.81749,0.72884,0.11649,6.25672,0.71593,0.10795,6.63181,0.72932,0.12134,6.01046
2,5s_0.5,Random Forest,SMOTETomek,0.66934,0.07799,8.58271,0.70880,0.17016,4.16541,0.72370,0.09737,7.43243,0.71083,0.08671,8.19804,0.72515,0.10189,7.11693
3,3s_0.5,Random Forest,TomekLinks,0.66729,0.07578,8.80534,0.69255,0.13962,4.96024,0.72257,0.08638,8.36493,0.70984,0.07431,9.55295,0.72301,0.08744,8.26883
4,5s_0.5,Random Forest,SMOTE,0.66155,0.11187,5.91348,0.68442,0.17811,3.84269,0.71893,0.12473,5.76395,0.70611,0.11424,6.18122,0.71899,0.12939,5.55666
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,1s_no,Decision Tree,Baseline (none),0.47537,0.07788,6.10413,0.49075,0.07925,6.19283,0.59426,0.05665,10.49038,0.56398,0.03578,15.76335,0.59972,0.06603,9.08264
176,4s_no,Decision Tree,TomekLinks,0.49201,0.11185,4.39900,0.53446,0.15441,3.46141,0.58303,0.07052,8.26771,0.56065,0.06649,8.43266,0.58569,0.07830,7.48018
177,1s_no,Decision Tree,SMOTE,0.48098,0.06601,7.28625,0.51553,0.09311,5.53646,0.58494,0.06506,8.99083,0.56021,0.04577,12.23837,0.59184,0.07519,7.87131
178,4s_no,Decision Tree,SMOTE,0.47678,0.11742,4.06036,0.49801,0.17928,2.77790,0.58554,0.11088,5.28067,0.55856,0.10065,5.54952,0.58297,0.11714,4.97681
179,2s_0.5,Decision Tree,TomekLinks,0.46386,0.09109,5.09259,0.46539,0.09983,4.66168,0.58890,0.07704,7.64403,0.55766,0.05991,9.30881,0.59136,0.08064,7.33312

In [ ]:
# Save the DataFrame to a CSV file
# df_sorted.to_csv('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/imb_files/combined_results_separate_models_recall.csv', index=False)

In [25]:
df_sorted_2 = df.sort_values(by='Accuracy (avg:std)', ascending=False).reset_index(drop=True)
df_sorted_2

,Dataset,Model,Imbalance Technique,F1-Score (avg),F1-Score (std),F1-Score (avg:std),Recall (avg),Recall (std),Recall (avg:std),Accuracy (avg),Accuracy (std),Accuracy (avg:std),Macro F1 (avg),Macro F1 (std),Macro F1 (avg:std),Weighted F1 (avg),Weighted F1 (std),Weighted F1 (avg:std)
0,1s_no,Decision Tree,TomekLinks,0.53868,0.07341,7.33821,0.59503,0.06994,8.50749,0.61928,0.05365,11.54249,0.59891,0.03949,15.16547,0.62723,0.06036,10.39073
1,1s_0.8,Decision Tree,SMOTETomek,0.50269,0.08384,5.99602,0.50334,0.08168,6.16202,0.61929,0.05696,10.87164,0.58886,0.03574,16.47656,0.62020,0.06501,9.54014
2,1s_0.8,Decision Tree,TomekLinks,0.50465,0.10140,4.97683,0.51698,0.11240,4.59966,0.61618,0.05689,10.83026,0.58750,0.04739,12.39716,0.61782,0.06718,9.19626
3,1s_0.8,Decision Tree,Baseline (none),0.49439,0.08288,5.96482,0.49591,0.08447,5.87074,0.61289,0.05776,10.61102,0.58266,0.03832,15.20607,0.61347,0.06750,9.08883
4,1s_no,Decision Tree,Baseline (none),0.47537,0.07788,6.10413,0.49075,0.07925,6.19283,0.59426,0.05665,10.49038,0.56398,0.03578,15.76335,0.59972,0.06603,9.08264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,5s_0.5,XGBoost,SMOTE,0.62354,0.11654,5.35029,0.63632,0.17402,3.65664,0.69132,0.13191,5.24075,0.67602,0.11910,5.67601,0.68994,0.13839,4.98560
176,3s_0.8,XGBoost,TomekLinks,0.59678,0.10391,5.74316,0.60432,0.17194,3.51469,0.67711,0.13192,5.13277,0.65679,0.11507,5.70778,0.67624,0.13637,4.95885
177,3s_0.8,XGBoost,Baseline (none),0.57914,0.10233,5.65969,0.56060,0.16455,3.40699,0.67336,0.13547,4.97059,0.64943,0.11610,5.59386,0.66888,0.14053,4.75980
178,5s_0.8,XGBoost,TomekLinks,0.63092,0.12790,4.93309,0.62563,0.19045,3.28507,0.69592,0.14003,4.96988,0.67889,0.12915,5.25658,0.69358,0.14283,4.85592
179,5s_0.8,XGBoost,SMOTE,0.62476,0.11708,5.33636,0.63282,0.17686,3.57816,0.68203,0.13969,4.88246,0.66622,0.12880,5.17240,0.68217,0.14032,4.86162

In [ ]:
# Save the DataFrame to a CSV file
# df_sorted_2.to_csv('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/imb_files/combined_results_separate_models_accuracy.csv', index=False)

In [26]:
df_sorted_f1_score = df.sort_values(by='F1-Score (avg)', ascending=False).reset_index(drop=True)
df_sorted_f1_score

,Dataset,Model,Imbalance Technique,F1-Score (avg),F1-Score (std),F1-Score (avg:std),Recall (avg),Recall (std),Recall (avg:std),Accuracy (avg),Accuracy (std),Accuracy (avg:std),Macro F1 (avg),Macro F1 (std),Macro F1 (avg:std),Weighted F1 (avg),Weighted F1 (std),Weighted F1 (avg:std)
0,3s_no,Random Forest,TomekLinks,0.68003,0.08269,8.22398,0.72279,0.15140,4.77406,0.72936,0.10341,7.05298,0.71663,0.09278,7.72392,0.72984,0.10521,6.93686
1,5s_0.5,Random Forest,TomekLinks,0.67558,0.11230,6.01590,0.71529,0.18737,3.81749,0.72884,0.11649,6.25672,0.71593,0.10795,6.63181,0.72932,0.12134,6.01046
2,5s_no,Random Forest,TomekLinks,0.67090,0.10125,6.62609,0.73954,0.20724,3.56848,0.71475,0.11998,5.95704,0.70574,0.11160,6.32381,0.71664,0.12422,5.76916
3,5s_0.5,Random Forest,SMOTETomek,0.66934,0.07799,8.58271,0.70880,0.17016,4.16541,0.72370,0.09737,7.43243,0.71083,0.08671,8.19804,0.72515,0.10189,7.11693
4,3s_0.5,Random Forest,TomekLinks,0.66729,0.07578,8.80534,0.69255,0.13962,4.96024,0.72257,0.08638,8.36493,0.70984,0.07431,9.55295,0.72301,0.08744,8.26883
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,4s_no,Decision Tree,TomekLinks,0.49201,0.11185,4.39900,0.53446,0.15441,3.46141,0.58303,0.07052,8.26771,0.56065,0.06649,8.43266,0.58569,0.07830,7.48018
176,1s_no,Decision Tree,SMOTE,0.48098,0.06601,7.28625,0.51553,0.09311,5.53646,0.58494,0.06506,8.99083,0.56021,0.04577,12.23837,0.59184,0.07519,7.87131
177,4s_no,Decision Tree,SMOTE,0.47678,0.11742,4.06036,0.49801,0.17928,2.77790,0.58554,0.11088,5.28067,0.55856,0.10065,5.54952,0.58297,0.11714,4.97681
178,1s_no,Decision Tree,Baseline (none),0.47537,0.07788,6.10413,0.49075,0.07925,6.19283,0.59426,0.05665,10.49038,0.56398,0.03578,15.76335,0.59972,0.06603,9.08264
179,2s_0.5,Decision Tree,TomekLinks,0.46386,0.09109,5.09259,0.46539,0.09983,4.66168,0.58890,0.07704,7.64403,0.55766,0.05991,9.30881,0.59136,0.08064,7.33312

In [ ]:
# Save the DataFrame to a CSV file
# df_sorted_f1_score.to_csv('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/imb_files/combined_results_separate_models_f1_score.csv', index=False)