In [9]:
import pickle
import pandas as pd

In [10]:
with open('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/training_results/3_class_dt_cv_results_5_fold_stratified.pkl', 'rb') as f:
    dt_results = pickle.load(f)
with open('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/training_results/3_class_rf_cv_results_5_fold_stratified.pkl', 'rb') as f:
    rf_results = pickle.load(f)
with open('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/training_results/3_class_xgb_cv_results_5_fold_stratified.pkl', 'rb') as f:
    xgb_results = pickle.load(f)

In [11]:
imb_tech = ['none', 'oversample_smote', 'undersample_tomek_links', 'combined_smote_tomek']
models = ['Decision Tree', 'Random Forest', 'XGBoost']

In [12]:
# Combine all model results into one dictionary
all_results = {
    'Decision Tree': dt_results,
    'Random Forest': rf_results,
    'XGBoost': xgb_results
}

In [13]:
def format_cv_results_separate_models(model_results_dict, models):
    """
    Convert cross-validation results from separate model dictionaries to tabular format.
    
    Parameters:
    model_results_dict: Dictionary where keys are model names and values are 
                    dictionaries with structure {dataset: {imbalance_technique: {metrics...}}}
    imb_tech: List of imbalance handling techniques
    models: List of model names
    
    Returns:
    pandas.DataFrame: Formatted results table
    """
    
    formatted_data = []
    
    # Iterate through each model
    for model in models:
        if model in model_results_dict:
            model_data = model_results_dict[model]
            
            
            # Iterate through each dataset for this model
            for dataset, dataset_results in model_data.items():
                
                # # Iterate through each imbalance technique
                # for technique in imb_tech:
                #     # Check if this technique exists in the results
                #     if technique in dataset_results:
                #         technique_results = dataset_results[technique]
                accuracy_avg = dataset_results.get('mean_accuracy', 0)
                accuracy_std = dataset_results.get('std_accuracy', 0)   
                macro_f1_avg = dataset_results.get('mean_macro_f1', 0)
                macro_f1_std = dataset_results.get('std_macro_f1', 0)
                macro_precision_avg = dataset_results.get('mean_macro_precision', 0)
                macro_precision_std = dataset_results.get('std_macro_precision', 0)
                macro_recall_avg = dataset_results.get('mean_macro_recall', 0)
                macro_recall_std = dataset_results.get('std_macro_recall', 0)
                weighted_f1_avg = dataset_results.get('mean_weighted_f1', 0)
                weighted_f1_std = dataset_results.get('std_weighted_f1', 0)
                weighted_precision_avg = dataset_results.get('mean_weighted_precision', 0)
                weighted_precision_std = dataset_results.get('std_weighted_precision', 0)
                weighted_recall_avg = dataset_results.get('mean_weighted_recall', 0)
                weighted_recall_std = dataset_results.get('std_weighted_recall', 0)
                
                precision_pre_void_avg = dataset_results.get('mean_precision_pre_void', 0)
                precision_pre_void_std = dataset_results.get('std_precision_pre_void', 0)
                recall_pre_void_avg = dataset_results.get('mean_recall_pre_void', 0)
                recall_pre_void_std = dataset_results.get('std_recall_pre_void', 0) 
                f1_pre_void_avg = dataset_results.get('mean_f1_pre_void', 0)
                f1_pre_void_std = dataset_results.get('std_f1_pre_void', 0)
                
                precision_void_avg = dataset_results.get('mean_precision_void', 0)
                precision_void_std = dataset_results.get('std_precision_void', 0)   
                recall_void_avg = dataset_results.get('mean_recall_void', 0)
                recall_void_std = dataset_results.get('std_recall_void', 0)
                f1_void_avg = dataset_results.get('mean_f1_void', 0)
                f1_void_std = dataset_results.get('std_f1_void', 0)
                
                precision_post_void_avg = dataset_results.get('mean_precision_post_void', 0)
                precision_post_void_std = dataset_results.get('std_precision_post_void', 0)
                recall_post_void_avg = dataset_results.get('mean_recall_post_void', 0)
                recall_post_void_std = dataset_results.get('std_recall_post_void', 0)
                f1_post_void_avg = dataset_results.get('mean_f1_post_void', 0)
                f1_post_void_std = dataset_results.get('std_f1_post_void', 0)
                
                
            
                # Add row to formatted data
                formatted_data.append({
                        'Dataset': dataset,
                        'Model': model,
                        'Accuracy (avg)': round(accuracy_avg, 5),
                        'Accuracy (std)': round(accuracy_std, 5),
                        'Accuracy (avg:std)': round(accuracy_avg/accuracy_std, 5),
                        'Macro F1 (avg)': round(macro_f1_avg, 5),
                        'Macro F1 (std)': round(macro_f1_std, 5),
                        'Macro F1 (avg:std)': round(macro_f1_avg/macro_f1_std, 5),
                        'Macro Precision (avg)': round(macro_precision_avg, 5),
                        'Macro Precision (std)': round(macro_precision_std, 5),
                        'Macro Precision (avg:std)': round(macro_precision_avg/macro_precision_std, 5),
                        'Macro Recall (avg)': round(macro_recall_avg, 5),
                        'Macro Recall (std)': round(macro_recall_std, 5),
                        'Macro Recall (avg:std)': round(macro_recall_avg/macro_recall_std, 5),
                        'Weighted F1 (avg)': round(weighted_f1_avg, 5),
                        'Weighted F1 (std)': round(weighted_f1_std, 5),
                        'Weighted F1 (avg:std)': round(weighted_f1_avg/weighted_f1_std, 5),
                        'Weighted Precision (avg)': round(weighted_precision_avg, 5),
                        'Weighted Precision (std)': round(weighted_precision_std, 5),
                        'Weighted Precision (avg:std)': round(weighted_precision_avg/weighted_precision_std, 5),
                        'Weighted Recall (avg)': round(weighted_recall_avg, 5),
                        'Weighted Recall (std)': round(weighted_recall_std, 5),
                        'Weighted Recall (avg:std)': round(weighted_recall_avg/weighted_recall_std, 5),
                        
                        'Precision Pre-Void (avg)': round(precision_pre_void_avg, 5),
                        'Precision Pre-Void (std)': round(precision_pre_void_std, 5),
                        'Precision Pre-Void (avg:std)': round(precision_pre_void_avg/precision_pre_void_std, 5),
                        'Recall Pre-Void (avg)': round(recall_pre_void_avg, 5),
                        'Recall Pre-Void (std)': round(recall_pre_void_std, 5),
                        'Recall Pre-Void (avg:std)': round(recall_pre_void_avg/recall_pre_void_std, 5),
                        'F1-Score Pre-Void (avg)': round(f1_pre_void_avg, 5),       
                        'F1-Score Pre-Void (std)': round(f1_pre_void_std, 5),
                        'F1-Score Pre-Void (avg:std)': round(f1_pre_void_avg/f1_pre_void_std, 5),   
                        
                        'Precision Void (avg)': round(precision_void_avg, 5),
                        'Precision Void (std)': round(precision_void_std, 5),
                        'Precision Void (avg:std)': round(precision_void_avg/precision_void_std, 5),
                        'Recall Void (avg)': round(recall_void_avg, 5),
                        'Recall Void (std)': round(recall_void_std, 5),
                        'Recall Void (avg/std)': round(recall_void_avg/recall_void_std, 5) ,
                        'F1-Score Void (avg)': round(f1_void_avg, 5),
                        'F1-Score Void (std)': round(f1_void_std, 5),
                        'F1-Score Void (avg:std)': round(f1_void_avg/f1_void_std, 5),
                        
                        
                        'Precision Post-Void (avg)': round(precision_post_void_avg, 5),
                        'Precision Post-Void (std)': round(precision_post_void_std, 5),
                        'Precision Post-Void (avg:std)': round(precision_post_void_avg/precision_post_void_std, 5),
                        'Recall Post-Void (avg)': round(recall_post_void_avg, 5),
                        'Recall Post-Void (std)': round(recall_post_void_std, 5),
                        'Recall Post-Void (avg:std)': round(recall_post_void_avg/recall_post_void_std, 5),  
                        'F1-Score Post-Void (avg)': round(f1_post_void_avg, 5),
                        'F1-Score Post-Void (std)': round(f1_post_void_std, 5),
                        'F1-Score Post-Void (avg:std)': round(f1_post_void_avg/f1_post_void_std, 5),
                        
                    })
                        
                        
    
    # Create DataFrame
    df = pd.DataFrame(formatted_data)
    
    # Sort by Dataset, Model, and Imbalance Technique for better organization
    # df = df.sort_values(['Dataset', 'Model', 'Imbalance Technique']).reset_index(drop=True)
    
    return df


print("Function ready to use for separate model dictionaries.")

Function ready to use for separate model dictionaries.

In [14]:
df = format_cv_results_separate_models(all_results, models)
df

,Dataset,Model,Accuracy (avg),Accuracy (std),Accuracy (avg:std),Macro F1 (avg),Macro F1 (std),Macro F1 (avg:std),Macro Precision (avg),Macro Precision (std),...,F1-Score Void (avg:std),Precision Post-Void (avg),Precision Post-Void (std),Precision Post-Void (avg:std),Recall Post-Void (avg),Recall Post-Void (std),Recall Post-Void (avg:std),F1-Score Post-Void (avg),F1-Score Post-Void (std),F1-Score Post-Void (avg:std)
0,1s_no,Decision Tree,0.64932,0.05297,12.25773,0.64651,0.05342,12.10172,0.64653,0.05359,...,10.26924,0.72789,0.05350,13.60482,0.68502,0.07965,8.60056,0.70320,0.05393,13.03843
1,1s_0.5,Decision Tree,0.69058,0.04479,15.41663,0.68519,0.04755,14.40935,0.69506,0.03020,...,16.20302,0.75005,0.08821,8.50289,0.79704,0.07074,11.26720,0.77055,0.06879,11.20123
2,1s_0.8,Decision Tree,0.68222,0.06859,9.94581,0.67718,0.07130,9.49817,0.67998,0.06583,...,6.19851,0.73599,0.08026,9.16996,0.76823,0.04953,15.50939,0.74699,0.03868,19.31217
3,2s_no,Decision Tree,0.63605,0.03488,18.23442,0.63754,0.03693,17.26554,0.64682,0.03337,...,20.36289,0.70651,0.03747,18.85613,0.66553,0.04534,14.68021,0.68459,0.03456,19.80839
4,2s_0.5,Decision Tree,0.64795,0.05673,11.42192,0.64016,0.05519,11.59936,0.65416,0.06079,...,9.68251,0.71197,0.07289,9.76719,0.74198,0.13703,5.41456,0.71676,0.07562,9.47874
5,2s_0.8,Decision Tree,0.63946,0.04397,14.54259,0.63403,0.04259,14.88725,0.64344,0.04222,...,9.68061,0.68614,0.04586,14.96011,0.70743,0.11563,6.11826,0.69014,0.04550,15.16722
6,3s_no,Decision Tree,0.64670,0.10110,6.39673,0.64118,0.10287,6.23273,0.65202,0.09602,...,9.51862,0.68645,0.08836,7.76897,0.67893,0.19983,3.39760,0.67406,0.14719,4.57952
7,3s_0.5,Decision Tree,0.64158,0.07230,8.87403,0.63506,0.07706,8.24162,0.64553,0.08203,...,9.56835,0.70391,0.14226,4.94809,0.70485,0.08696,8.10558,0.69665,0.08619,8.08296
8,3s_0.8,Decision Tree,0.66100,0.04819,13.71620,0.64552,0.05785,11.15885,0.65282,0.04964,...,6.51959,0.67989,0.09757,6.96802,0.74708,0.13735,5.43934,0.70397,0.08506,8.27590
9,4s_no,Decision Tree,0.64440,0.07120,9.05078,0.63664,0.07463,8.53090,0.64844,0.07406,...,11.18112,0.65092,0.13063,4.98305,0.71048,0.18922,3.75477,0.67697,0.15822,4.27874
10,4s_0.5,Decision Tree,0.61351,0.04528,13.54893,0.60715,0.05039,12.04888,0.62222,0.04932,...,8.86080,0.64919,0.09806,6.62016,0.58818,0.10991,5.35142,0.61234,0.08811,6.94942
11,4s_0.8,Decision Tree,0.62601,0.07897,7.92731,0.61431,0.07591,8.09264,0.62991,0.08342,...,8.50404,0.66256,0.09296,7.12752,0.72122,0.17738,4.06606,0.68517,0.11912,5.75207
12,5s_no,Decision Tree,0.63893,0.05191,12.30862,0.63661,0.05479,11.61952,0.63859,0.05887,...,8.67721,0.66787,0.04253,15.70328,0.77079,0.07660,10.06216,0.71329,0.04336,16.45013
13,5s_0.5,Decision Tree,0.57890,0.06562,8.82204,0.57755,0.06736,8.57457,0.59410,0.06887,...,6.32371,0.61840,0.05272,11.73030,0.66391,0.13475,4.92707,0.63497,0.08296,7.65369
14,5s_0.8,Decision Tree,0.61135,0.06605,9.25551,0.60161,0.06761,8.89818,0.61118,0.06182,...,6.99877,0.66166,0.11216,5.89916,0.69030,0.16503,4.18276,0.66313,0.11000,6.02857
15,1s_no,Random Forest,0.74305,0.04802,15.47315,0.73888,0.05186,14.24803,0.74679,0.05245,...,11.80999,0.78492,0.09152,8.57609,0.82335,0.08463,9.72890,0.79815,0.05398,14.78688
16,1s_0.5,Random Forest,0.73358,0.05556,13.20397,0.72754,0.05560,13.08547,0.73502,0.04907,...,9.01862,0.76895,0.11051,6.95826,0.83801,0.07150,11.71981,0.79836,0.07643,10.44543
17,1s_0.8,Random Forest,0.73222,0.04593,15.94149,0.72323,0.04836,14.95445,0.73689,0.03965,...,6.55671,0.76246,0.09614,7.93041,0.82056,0.07403,11.08356,0.78340,0.04475,17.50511
18,2s_no,Random Forest,0.73883,0.05615,13.15898,0.73503,0.05895,12.46886,0.74896,0.05235,...,11.81562,0.80075,0.10184,7.86305,0.78469,0.07796,10.06530,0.79131,0.08372,9.45170
19,2s_0.5,Random Forest,0.73707,0.05114,14.41189,0.73210,0.05261,13.91581,0.74881,0.05438,...,15.04255,0.78721,0.08287,9.49927,0.81366,0.05613,14.49685,0.79710,0.04995,15.95748
20,2s_0.8,Random Forest,0.72583,0.06672,10.87894,0.71912,0.07044,10.20851,0.72349,0.06182,...,6.63243,0.74292,0.07216,10.29495,0.82013,0.13299,6.16694,0.77497,0.08365,9.26477
21,3s_no,Random Forest,0.75041,0.03309,22.67925,0.74747,0.03465,21.57112,0.75334,0.03385,...,14.98937,0.78299,0.07059,11.09226,0.80552,0.06247,12.89521,0.79267,0.05778,13.71867
22,3s_0.5,Random Forest,0.72961,0.06057,12.04518,0.71884,0.06062,11.85804,0.73832,0.07245,...,21.88788,0.79090,0.09908,7.98283,0.80056,0.13753,5.82092,0.78783,0.08620,9.13936
23,3s_0.8,Random Forest,0.71883,0.06508,11.04539,0.70758,0.07927,8.92627,0.72157,0.08387,...,7.91824,0.75204,0.11353,6.62419,0.80939,0.15721,5.14838,0.76477,0.07701,9.93049
24,4s_no,Random Forest,0.73073,0.02761,26.46234,0.72287,0.03120,23.16930,0.73303,0.02590,...,20.00308,0.77293,0.07015,11.01854,0.80740,0.13823,5.84093,0.78726,0.09994,7.87718
25,4s_0.5,Random Forest,0.72661,0.04362,16.65710,0.71168,0.05910,12.04184,0.73528,0.04910,...,17.48982,0.76807,0.08597,8.93408,0.78249,0.14920,5.24444,0.76971,0.10066,7.64638
26,4s_0.8,Random Forest,0.72074,0.07176,10.04346,0.70247,0.07291,9.63453,0.73080,0.08682,...,11.99836,0.78807,0.11169,7.05589,0.80337,0.12713,6.31932,0.78955,0.09073,8.70219
27,5s_no,Random Forest,0.73982,0.05935,12.46460,0.73161,0.06255,11.69567,0.75133,0.06657,...,13.65648,0.80855,0.09697,8.33846,0.77089,0.10440,7.38392,0.78587,0.08776,8.95477
28,5s_0.5,Random Forest,0.74281,0.04797,15.48548,0.73560,0.04531,16.23644,0.74805,0.05474,...,13.93368,0.78823,0.09601,8.20959,0.79696,0.07726,10.31542,0.78987,0.07370,10.71727
29,5s_0.8,Random Forest,0.73176,0.04368,16.75374,0.71797,0.05346,13.43050,0.74116,0.06158,...,13.76139,0.76760,0.12176,6.30440,0.79576,0.16958,4.69259,0.76381,0.08684,8.79520
30,1s_no,XGBoost,0.73750,0.06691,11.02202,0.73347,0.07095,10.33714,0.73803,0.07041,...,8.33723,0.78388,0.10715,7.31596,0.83012,0.07608,10.91049,0.80120,0.06526,12.27748
31,1s_0.5,XGBoost,0.74065,0.04723,15.68161,0.73742,0.04592,16.05733,0.74379,0.03653,...,10.79877,0.76600,0.10011,7.65157,0.85165,0.06384,13.34099,0.80352,0.07075,11.35689
32,1s_0.8,XGBoost,0.73859,0.04476,16.50173,0.73309,0.04791,15.30177,0.74443,0.03312,...,8.66111,0.75465,0.08043,9.38216,0.83101,0.05066,16.40267,0.78810,0.05018,15.70467
33,2s_no,XGBoost,0.74060,0.06872,10.77688,0.73937,0.06891,10.73000,0.74491,0.07003,...,11.94601,0.77946,0.09367,8.32093,0.80957,0.07461,10.85127,0.79245,0.07838,10.11056
34,2s_0.5,XGBoost,0.74152,0.06848,10.82806,0.73799,0.06836,10.79612,0.75478,0.07328,...,9.84678,0.78316,0.10455,7.49101,0.82973,0.07402,11.21004,0.80016,0.06390,12.52241
35,2s_0.8,XGBoost,0.73742,0.07280,10.12955,0.73377,0.07453,9.84531,0.73765,0.06621,...,6.77299,0.73797,0.08342,8.84592,0.84009,0.12119,6.93180,0.78188,0.08342,9.37328
36,3s_no,XGBoost,0.76140,0.04673,16.29269,0.76034,0.04894,15.53660,0.76425,0.04455,...,26.04395,0.79037,0.09008,8.77391,0.84629,0.06260,13.51973,0.81476,0.06513,12.50927
37,3s_0.5,XGBoost,0.73424,0.07602,9.65822,0.72848,0.07709,9.45020,0.73887,0.08347,...,12.13929,0.76892,0.11688,6.57857,0.83862,0.09803,8.55450,0.79571,0.08139,9.77650
38,3s_0.8,XGBoost,0.72419,0.06826,10.60949,0.71595,0.07815,9.16176,0.72728,0.07707,...,7.31143,0.74750,0.12201,6.12632,0.83605,0.12288,6.80402,0.77612,0.06632,11.70337
39,4s_no,XGBoost,0.74200,0.05828,12.73129,0.74223,0.06022,12.32444,0.74863,0.05460,...,16.27988,0.74799,0.08500,8.79982,0.81602,0.11150,7.31844,0.77939,0.09207,8.46537
40,4s_0.5,XGBoost,0.71695,0.05329,13.45303,0.71125,0.05710,12.45593,0.72753,0.06214,...,13.91475,0.75877,0.10318,7.35419,0.80956,0.09698,8.34803,0.77822,0.07488,10.39229
41,4s_0.8,XGBoost,0.72947,0.07953,9.17244,0.71756,0.07956,9.01904,0.74307,0.09241,...,12.30604,0.77730,0.12921,6.01574,0.84092,0.13119,6.40989,0.79837,0.09350,8.53908
42,5s_no,XGBoost,0.78163,0.04482,17.43819,0.78090,0.04971,15.70880,0.79366,0.05580,...,17.35276,0.81374,0.08321,9.77937,0.84639,0.04687,18.05900,0.82559,0.03515,23.48720
43,5s_0.5,XGBoost,0.75114,0.09190,8.17337,0.74412,0.08975,8.29066,0.76236,0.09514,...,8.18468,0.81064,0.14681,5.52154,0.80761,0.11515,7.01331,0.80199,0.10894,7.36200
44,5s_0.8,XGBoost,0.74494,0.07852,9.48701,0.73866,0.08547,8.64196,0.75245,0.08606,...,11.16188,0.75803,0.15069,5.03049,0.80654,0.12962,6.22238,0.77303,0.11159,6.92716

In [15]:
df_sorted_f1_score = df.sort_values(by='Accuracy (avg)', ascending=False).reset_index(drop=True)
df_sorted_f1_score

,Dataset,Model,Accuracy (avg),Accuracy (std),Accuracy (avg:std),Macro F1 (avg),Macro F1 (std),Macro F1 (avg:std),Macro Precision (avg),Macro Precision (std),...,F1-Score Void (avg:std),Precision Post-Void (avg),Precision Post-Void (std),Precision Post-Void (avg:std),Recall Post-Void (avg),Recall Post-Void (std),Recall Post-Void (avg:std),F1-Score Post-Void (avg),F1-Score Post-Void (std),F1-Score Post-Void (avg:std)
0,5s_no,XGBoost,0.78163,0.04482,17.43819,0.78090,0.04971,15.70880,0.79366,0.05580,...,17.35276,0.81374,0.08321,9.77937,0.84639,0.04687,18.05900,0.82559,0.03515,23.48720
1,3s_no,XGBoost,0.76140,0.04673,16.29269,0.76034,0.04894,15.53660,0.76425,0.04455,...,26.04395,0.79037,0.09008,8.77391,0.84629,0.06260,13.51973,0.81476,0.06513,12.50927
2,5s_0.5,XGBoost,0.75114,0.09190,8.17337,0.74412,0.08975,8.29066,0.76236,0.09514,...,8.18468,0.81064,0.14681,5.52154,0.80761,0.11515,7.01331,0.80199,0.10894,7.36200
3,3s_no,Random Forest,0.75041,0.03309,22.67925,0.74747,0.03465,21.57112,0.75334,0.03385,...,14.98937,0.78299,0.07059,11.09226,0.80552,0.06247,12.89521,0.79267,0.05778,13.71867
4,5s_0.8,XGBoost,0.74494,0.07852,9.48701,0.73866,0.08547,8.64196,0.75245,0.08606,...,11.16188,0.75803,0.15069,5.03049,0.80654,0.12962,6.22238,0.77303,0.11159,6.92716
5,1s_no,Random Forest,0.74305,0.04802,15.47315,0.73888,0.05186,14.24803,0.74679,0.05245,...,11.80999,0.78492,0.09152,8.57609,0.82335,0.08463,9.72890,0.79815,0.05398,14.78688
6,5s_0.5,Random Forest,0.74281,0.04797,15.48548,0.73560,0.04531,16.23644,0.74805,0.05474,...,13.93368,0.78823,0.09601,8.20959,0.79696,0.07726,10.31542,0.78987,0.07370,10.71727
7,4s_no,XGBoost,0.74200,0.05828,12.73129,0.74223,0.06022,12.32444,0.74863,0.05460,...,16.27988,0.74799,0.08500,8.79982,0.81602,0.11150,7.31844,0.77939,0.09207,8.46537
8,2s_0.5,XGBoost,0.74152,0.06848,10.82806,0.73799,0.06836,10.79612,0.75478,0.07328,...,9.84678,0.78316,0.10455,7.49101,0.82973,0.07402,11.21004,0.80016,0.06390,12.52241
9,1s_0.5,XGBoost,0.74065,0.04723,15.68161,0.73742,0.04592,16.05733,0.74379,0.03653,...,10.79877,0.76600,0.10011,7.65157,0.85165,0.06384,13.34099,0.80352,0.07075,11.35689
10,2s_no,XGBoost,0.74060,0.06872,10.77688,0.73937,0.06891,10.73000,0.74491,0.07003,...,11.94601,0.77946,0.09367,8.32093,0.80957,0.07461,10.85127,0.79245,0.07838,10.11056
11,5s_no,Random Forest,0.73982,0.05935,12.46460,0.73161,0.06255,11.69567,0.75133,0.06657,...,13.65648,0.80855,0.09697,8.33846,0.77089,0.10440,7.38392,0.78587,0.08776,8.95477
12,2s_no,Random Forest,0.73883,0.05615,13.15898,0.73503,0.05895,12.46886,0.74896,0.05235,...,11.81562,0.80075,0.10184,7.86305,0.78469,0.07796,10.06530,0.79131,0.08372,9.45170
13,1s_0.8,XGBoost,0.73859,0.04476,16.50173,0.73309,0.04791,15.30177,0.74443,0.03312,...,8.66111,0.75465,0.08043,9.38216,0.83101,0.05066,16.40267,0.78810,0.05018,15.70467
14,1s_no,XGBoost,0.73750,0.06691,11.02202,0.73347,0.07095,10.33714,0.73803,0.07041,...,8.33723,0.78388,0.10715,7.31596,0.83012,0.07608,10.91049,0.80120,0.06526,12.27748
15,2s_0.8,XGBoost,0.73742,0.07280,10.12955,0.73377,0.07453,9.84531,0.73765,0.06621,...,6.77299,0.73797,0.08342,8.84592,0.84009,0.12119,6.93180,0.78188,0.08342,9.37328
16,2s_0.5,Random Forest,0.73707,0.05114,14.41189,0.73210,0.05261,13.91581,0.74881,0.05438,...,15.04255,0.78721,0.08287,9.49927,0.81366,0.05613,14.49685,0.79710,0.04995,15.95748
17,3s_0.5,XGBoost,0.73424,0.07602,9.65822,0.72848,0.07709,9.45020,0.73887,0.08347,...,12.13929,0.76892,0.11688,6.57857,0.83862,0.09803,8.55450,0.79571,0.08139,9.77650
18,1s_0.5,Random Forest,0.73358,0.05556,13.20397,0.72754,0.05560,13.08547,0.73502,0.04907,...,9.01862,0.76895,0.11051,6.95826,0.83801,0.07150,11.71981,0.79836,0.07643,10.44543
19,1s_0.8,Random Forest,0.73222,0.04593,15.94149,0.72323,0.04836,14.95445,0.73689,0.03965,...,6.55671,0.76246,0.09614,7.93041,0.82056,0.07403,11.08356,0.78340,0.04475,17.50511
20,5s_0.8,Random Forest,0.73176,0.04368,16.75374,0.71797,0.05346,13.43050,0.74116,0.06158,...,13.76139,0.76760,0.12176,6.30440,0.79576,0.16958,4.69259,0.76381,0.08684,8.79520
21,4s_no,Random Forest,0.73073,0.02761,26.46234,0.72287,0.03120,23.16930,0.73303,0.02590,...,20.00308,0.77293,0.07015,11.01854,0.80740,0.13823,5.84093,0.78726,0.09994,7.87718
22,3s_0.5,Random Forest,0.72961,0.06057,12.04518,0.71884,0.06062,11.85804,0.73832,0.07245,...,21.88788,0.79090,0.09908,7.98283,0.80056,0.13753,5.82092,0.78783,0.08620,9.13936
23,4s_0.8,XGBoost,0.72947,0.07953,9.17244,0.71756,0.07956,9.01904,0.74307,0.09241,...,12.30604,0.77730,0.12921,6.01574,0.84092,0.13119,6.40989,0.79837,0.09350,8.53908
24,4s_0.5,Random Forest,0.72661,0.04362,16.65710,0.71168,0.05910,12.04184,0.73528,0.04910,...,17.48982,0.76807,0.08597,8.93408,0.78249,0.14920,5.24444,0.76971,0.10066,7.64638
25,2s_0.8,Random Forest,0.72583,0.06672,10.87894,0.71912,0.07044,10.20851,0.72349,0.06182,...,6.63243,0.74292,0.07216,10.29495,0.82013,0.13299,6.16694,0.77497,0.08365,9.26477
26,3s_0.8,XGBoost,0.72419,0.06826,10.60949,0.71595,0.07815,9.16176,0.72728,0.07707,...,7.31143,0.74750,0.12201,6.12632,0.83605,0.12288,6.80402,0.77612,0.06632,11.70337
27,4s_0.8,Random Forest,0.72074,0.07176,10.04346,0.70247,0.07291,9.63453,0.73080,0.08682,...,11.99836,0.78807,0.11169,7.05589,0.80337,0.12713,6.31932,0.78955,0.09073,8.70219
28,3s_0.8,Random Forest,0.71883,0.06508,11.04539,0.70758,0.07927,8.92627,0.72157,0.08387,...,7.91824,0.75204,0.11353,6.62419,0.80939,0.15721,5.14838,0.76477,0.07701,9.93049
29,4s_0.5,XGBoost,0.71695,0.05329,13.45303,0.71125,0.05710,12.45593,0.72753,0.06214,...,13.91475,0.75877,0.10318,7.35419,0.80956,0.09698,8.34803,0.77822,0.07488,10.39229
30,1s_0.5,Decision Tree,0.69058,0.04479,15.41663,0.68519,0.04755,14.40935,0.69506,0.03020,...,16.20302,0.75005,0.08821,8.50289,0.79704,0.07074,11.26720,0.77055,0.06879,11.20123
31,1s_0.8,Decision Tree,0.68222,0.06859,9.94581,0.67718,0.07130,9.49817,0.67998,0.06583,...,6.19851,0.73599,0.08026,9.16996,0.76823,0.04953,15.50939,0.74699,0.03868,19.31217
32,3s_0.8,Decision Tree,0.66100,0.04819,13.71620,0.64552,0.05785,11.15885,0.65282,0.04964,...,6.51959,0.67989,0.09757,6.96802,0.74708,0.13735,5.43934,0.70397,0.08506,8.27590
33,1s_no,Decision Tree,0.64932,0.05297,12.25773,0.64651,0.05342,12.10172,0.64653,0.05359,...,10.26924,0.72789,0.05350,13.60482,0.68502,0.07965,8.60056,0.70320,0.05393,13.03843
34,2s_0.5,Decision Tree,0.64795,0.05673,11.42192,0.64016,0.05519,11.59936,0.65416,0.06079,...,9.68251,0.71197,0.07289,9.76719,0.74198,0.13703,5.41456,0.71676,0.07562,9.47874
35,3s_no,Decision Tree,0.64670,0.10110,6.39673,0.64118,0.10287,6.23273,0.65202,0.09602,...,9.51862,0.68645,0.08836,7.76897,0.67893,0.19983,3.39760,0.67406,0.14719,4.57952
36,4s_no,Decision Tree,0.64440,0.07120,9.05078,0.63664,0.07463,8.53090,0.64844,0.07406,...,11.18112,0.65092,0.13063,4.98305,0.71048,0.18922,3.75477,0.67697,0.15822,4.27874
37,3s_0.5,Decision Tree,0.64158,0.07230,8.87403,0.63506,0.07706,8.24162,0.64553,0.08203,...,9.56835,0.70391,0.14226,4.94809,0.70485,0.08696,8.10558,0.69665,0.08619,8.08296
38,2s_0.8,Decision Tree,0.63946,0.04397,14.54259,0.63403,0.04259,14.88725,0.64344,0.04222,...,9.68061,0.68614,0.04586,14.96011,0.70743,0.11563,6.11826,0.69014,0.04550,15.16722
39,5s_no,Decision Tree,0.63893,0.05191,12.30862,0.63661,0.05479,11.61952,0.63859,0.05887,...,8.67721,0.66787,0.04253,15.70328,0.77079,0.07660,10.06216,0.71329,0.04336,16.45013
40,2s_no,Decision Tree,0.63605,0.03488,18.23442,0.63754,0.03693,17.26554,0.64682,0.03337,...,20.36289,0.70651,0.03747,18.85613,0.66553,0.04534,14.68021,0.68459,0.03456,19.80839
41,4s_0.8,Decision Tree,0.62601,0.07897,7.92731,0.61431,0.07591,8.09264,0.62991,0.08342,...,8.50404,0.66256,0.09296,7.12752,0.72122,0.17738,4.06606,0.68517,0.11912,5.75207
42,4s_0.5,Decision Tree,0.61351,0.04528,13.54893,0.60715,0.05039,12.04888,0.62222,0.04932,...,8.86080,0.64919,0.09806,6.62016,0.58818,0.10991,5.35142,0.61234,0.08811,6.94942
43,5s_0.8,Decision Tree,0.61135,0.06605,9.25551,0.60161,0.06761,8.89818,0.61118,0.06182,...,6.99877,0.66166,0.11216,5.89916,0.69030,0.16503,4.18276,0.66313,0.11000,6.02857
44,5s_0.5,Decision Tree,0.57890,0.06562,8.82204,0.57755,0.06736,8.57457,0.59410,0.06887,...,6.32371,0.61840,0.05272,11.73030,0.66391,0.13475,4.92707,0.63497,0.08296,7.65369

In [16]:
df_sorted_f1_score.to_csv('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/accuracy_sorted_sorted_3_class_base_model_comparison.csv', index=False)