In [2]:
import pickle
import pandas as pd

In [3]:
with open('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/imb_files/rf_imb_152.pkl', 'rb') as f:
    xgb_results = pickle.load(f)

In [4]:
xgb_results

{'1s_no': {'none': {'mean_accuracy': np.float64(0.6908557527681505),
   'std_accuracy': np.float64(0.047085188363842595),
   'mean_recall_minority': np.float64(0.5148051931069666),
   'std_recall_minority': np.float64(0.0750584194643462),
   'mean_f1_minority': np.float64(0.5672351507401989),
   'std_f1_minority': np.float64(0.07027009293046432),
   'mean_f1_majority': np.float64(0.7481966614263179),
   'fold_details': [{'fold': 0,
     'recall_void': 0.5283018867924528,
     'precision_void': 0.6666666666666666,
     'f1_void': 0.5894736842105263,
     'macro_f1': 0.7157894736842105,
     'accuracy': 0.7719298245614035,
     'precision_non_void': 0.8062015503875969,
     'recall_non_void': 0.8813559322033898,
     'f1_non_void': 0.8421052631578947,
     'class_distribution_train': {'non-void': np.int64(932),
      'void': np.int64(667)},
     'class_distribution_test': {'non-void': np.int64(118),
      'void': np.int64(53)}},
    {'fold': 1,
     'recall_void': 0.44680851063829785,
     'precision_void': 0.5,
     'f1_void': 0.47191011235955055,
     'macro_f1': 0.6466014440124749,
     'accuracy': 0.7329545454545454,
     'precision_non_void': 0.8059701492537313,
     'recall_non_void': 0.8372093023255814,
     'f1_non_void': 0.8212927756653993,
     'class_distribution_train': {'non-void': np.int64(921),
      'void': np.int64(673)},
     'class_distribution_test': {'non-void': np.int64(129),
      'void': np.int64(47)}},
    {'fold': 2,
     'recall_void': 0.5151515151515151,
     'precision_void': 0.5964912280701754,
     'f1_void': 0.5528455284552846,
     'macro_f1': 0.6563354279831008,
     'accuracy': 0.6875,
     'precision_non_void': 0.7310924369747899,
     'recall_non_void': 0.7909090909090909,
     'f1_non_void': 0.759825327510917,
     'class_distribution_train': {'non-void': np.int64(940),
      'void': np.int64(654)},
     'class_distribution_test': {'non-void': np.int64(110),
      'void': np.int64(66)}},
    {'fold': 3,
     'recall_void': 0.43478260869565216,
     'precision_void': 0.425531914893617,
     'f1_void': 0.43010752688172044,
     'macro_f1': 0.6050952572167938,
     'accuracy': 0.6826347305389222,
     'precision_non_void': 0.7833333333333333,
     'recall_non_void': 0.7768595041322314,
     'f1_non_void': 0.7800829875518672,
     'class_distribution_train': {'non-void': np.int64(929),
      'void': np.int64(674)},
     'class_distribution_test': {'non-void': np.int64(121),
      'void': np.int64(46)}},
    {'fold': 4,
     'recall_void': 0.5384615384615384,
     'precision_void': 0.6885245901639344,
     'f1_void': 0.60431654676259,
     'macro_f1': 0.6596712267491707,
     'accuracy': 0.6686746987951807,
     'precision_non_void': 0.6571428571428571,
     'recall_non_void': 0.7840909090909091,
     'f1_non_void': 0.7150259067357513,
     'class_distribution_train': {'non-void': np.int64(962),
      'void': np.int64(642)},
     'class_distribution_test': {'non-void': np.int64(88),
      'void': np.int64(78)}},
    {'fold': 5,
     'recall_void': 0.42045454545454547,
     'precision_void': 0.74,
     'f1_void': 0.5362318840579711,
     'macro_f1': 0.6401159420289855,
     'accuracy': 0.6701030927835051,
     'precision_non_void': 0.6458333333333334,
     'recall_non_void': 0.8773584905660378,
     'f1_non_void': 0.744,
     'class_distribution_train': {'non-void': np.int64(944),
      'void': np.int64(632)},
     'class_distribution_test': {'non-void': np.int64(106),
      'void': np.int64(88)}},
    {'fold': 6,
     'recall_void': 0.6785714285714286,
     'precision_void': 0.6951219512195121,
     'f1_void': 0.6867469879518072,
     'macro_f1': 0.7251916757940855,
     'accuracy': 0.7305699481865285,
     'precision_non_void': 0.7567567567567568,
     'recall_non_void': 0.7706422018348624,
     'f1_non_void': 0.7636363636363637,
     'class_distribution_train': {'non-void': np.int64(941),
      'void': np.int64(636)},
     'class_distribution_test': {'non-void': np.int64(109),
      'void': np.int64(84)}},
    {'fold': 7,
     'recall_void': 0.4634146341463415,
     'precision_void': 0.76,
     'f1_void': 0.5757575757575758,
     'macro_f1': 0.6464646464646464,
     'accuracy': 0.6606060606060606,
     'precision_non_void': 0.6173913043478261,
     'recall_non_void': 0.8554216867469879,
     'f1_non_void': 0.7171717171717171,
     'class_distribution_train': {'non-void': np.int64(967),
      'void': np.int64(638)},
     'class_distribution_test': {'non-void': np.int64(83),
      'void': np.int64(82)}},
    {'fold': 8,
     'recall_void': 0.53,
     'precision_void': 0.726027397260274,
     'f1_void': 0.6127167630057804,
     'macro_f1': 0.5902293492448256,
     'accuracy': 0.5914634146341463,
     'precision_non_void': 0.4835164835164835,
     'recall_non_void': 0.6875,
     'f1_non_void': 0.567741935483871,
     'class_distribution_train': {'non-void': np.int64(986),
      'void': np.int64(620)},
     'class_distribution_test': {'void': np.int64(100),
      'non-void': np.int64(64)}},
    {'fold': 9,
     'recall_void': 0.5921052631578947,
     'precision_void': 0.6338028169014085,
     'f1_void': 0.6122448979591837,
     'macro_f1': 0.6916646176542907,
     'accuracy': 0.7121212121212122,
     'precision_non_void': 0.7559055118110236,
     'recall_non_void': 0.7868852459016393,
     'f1_non_void': 0.7710843373493976,
     'class_distribution_train': {'non-void': np.int64(928),
      'void': np.int64(644)},
     'class_distribution_test': {'non-void': np.int64(122),
      'void': np.int64(76)}}]},
  'oversample_smote': {'mean_accuracy': np.float64(0.6882394765098081),
   'std_accuracy': np.float64(0.06027278150680365),
   'mean_recall_minority': np.float64(0.5668744079136214),
   'std_recall_minority': np.float64(0.09999916179893124),
   'mean_f1_minority': np.float64(0.5884028449263665),
   'std_f1_minority': np.float64(0.09937834918698434),
   'mean_f1_majority': np.float64(0.7350782246664085),
   'fold_details': [{'fold': 0,
     'recall_void': 0.6792452830188679,
     'precision_void': 0.7659574468085106,
     'f1_void': 0.72,
     'macro_f1': 0.8021487603305786,
     'accuracy': 0.8362573099415205,
     'precision_non_void': 0.8629032258064516,
     'recall_non_void': 0.9067796610169492,
     'f1_non_void': 0.8842975206611571,
     'class_distribution_train': {'non-void': np.int64(932),
      'void': np.int64(932)},
     'class_distribution_test': {'non-void': np.int64(118),
      'void': np.int64(53)}},
    {'fold': 1,
     'recall_void': 0.3617021276595745,
     'precision_void': 0.40476190476190477,
     'f1_void': 0.38202247191011235,
     'macro_f1': 0.5864484983124706,
     'accuracy': 0.6875,
     'precision_non_void': 0.7761194029850746,
     'recall_non_void': 0.8062015503875969,
     'f1_non_void': 0.7908745247148289,
     'class_distribution_train': {'non-void': np.int64(921),
      'void': np.int64(921)},
     'class_distribution_test': {'non-void': np.int64(129),
      'void': np.int64(47)}},
    {'fold': 2,
     'recall_void': 0.5303030303030303,
     'precision_void': 0.5645161290322581,
     'f1_void': 0.546875,
     'macro_f1': 0.6439732142857143,
     'accuracy': 0.6704545454545454,
     'precision_non_void': 0.7280701754385965,
     'recall_non_void': 0.7545454545454545,
     'f1_non_void': 0.7410714285714286,
     'class_distribution_train': {'non-void': np.int64(940),
      'void': np.int64(940)},
     'class_distribution_test': {'non-void': np.int64(110),
      'void': np.int64(66)}},
    {'fold': 3,
     'recall_void': 0.5,
     'precision_void': 0.40350877192982454,
     'f1_void': 0.44660194174757284,
     'macro_f1': 0.5999243474971631,
     'accuracy': 0.6586826347305389,
     'precision_non_void': 0.7909090909090909,
     'recall_non_void': 0.71900826446281,
     'f1_non_void': 0.7532467532467533,
     'class_distribution_train': {'non-void': np.int64(929),
      'void': np.int64(929)},
     'class_distribution_test': {'non-void': np.int64(121),
      'void': np.int64(46)}},
    {'fold': 4,
     'recall_void': 0.6025641025641025,
     'precision_void': 0.6266666666666667,
     'f1_void': 0.6143790849673203,
     'macro_f1': 0.6423850732099171,
     'accuracy': 0.6445783132530121,
     'precision_non_void': 0.6593406593406593,
     'recall_non_void': 0.6818181818181818,
     'f1_non_void': 0.6703910614525139,
     'class_distribution_train': {'non-void': np.int64(962),
      'void': np.int64(962)},
     'class_distribution_test': {'non-void': np.int64(88),
      'void': np.int64(78)}},
    {'fold': 5,
     'recall_void': 0.48863636363636365,
     'precision_void': 0.7413793103448276,
     'f1_void': 0.589041095890411,
     'macro_f1': 0.6705536057964452,
     'accuracy': 0.6907216494845361,
     'precision_non_void': 0.6691176470588235,
     'recall_non_void': 0.8584905660377359,
     'f1_non_void': 0.7520661157024794,
     'class_distribution_train': {'non-void': np.int64(944),
      'void': np.int64(944)},
     'class_distribution_test': {'non-void': np.int64(106),
      'void': np.int64(88)}},
    {'fold': 6,
     'recall_void': 0.7261904761904762,
     'precision_void': 0.648936170212766,
     'f1_void': 0.6853932584269663,
     'macro_f1': 0.7080812445980985,
     'accuracy': 0.7098445595854922,
     'precision_non_void': 0.7676767676767676,
     'recall_non_void': 0.6972477064220184,
     'f1_non_void': 0.7307692307692307,
     'class_distribution_train': {'non-void': np.int64(941),
      'void': np.int64(941)},
     'class_distribution_test': {'non-void': np.int64(109),
      'void': np.int64(84)}},
    {'fold': 7,
     'recall_void': 0.5853658536585366,
     'precision_void': 0.75,
     'f1_void': 0.6575342465753424,
     'macro_f1': 0.6928975580702799,
     'accuracy': 0.696969696969697,
     'precision_non_void': 0.6633663366336634,
     'recall_non_void': 0.8072289156626506,
     'f1_non_void': 0.7282608695652174,
     'class_distribution_train': {'non-void': np.int64(967),
      'void': np.int64(967)},
     'class_distribution_test': {'non-void': np.int64(83),
      'void': np.int64(82)}},
    {'fold': 8,
     'recall_void': 0.55,
     'precision_void': 0.7051282051282052,
     'f1_void': 0.6179775280898876,
     'macro_f1': 0.5823220973782771,
     'accuracy': 0.5853658536585366,
     'precision_non_void': 0.47674418604651164,
     'recall_non_void': 0.640625,
     'f1_non_void': 0.5466666666666666,
     'class_distribution_train': {'non-void': np.int64(986),
      'void': np.int64(986)},
     'class_distribution_test': {'void': np.int64(100),
      'non-void': np.int64(64)}},
    {'fold': 9,
     'recall_void': 0.6447368421052632,
     'precision_void': 0.6049382716049383,
     'f1_void': 0.6242038216560509,
     'macro_f1': 0.6886709484849292,
     'accuracy': 0.702020202020202,
     'precision_non_void': 0.7692307692307693,
     'recall_non_void': 0.7377049180327869,
     'f1_non_void': 0.7531380753138075,
     'class_distribution_train': {'non-void': np.int64(928),
      'void': np.int64(928)},
     'class_distribution_test': {'non-void': np.int64(122),
      'void': np.int64(76)}}]},
  'undersample_tomek_links': {'mean_accuracy': np.float64(0.6985562745785577),
   'std_accuracy': np.float64(0.06160982546992361),
   'mean_recall_minority': np.float64(0.603597404139965),
   'std_recall_minority': np.float64(0.08558345255565734),
   'mean_f1_minority': np.float64(0.6121611775738719),
   'std_f1_minority': np.float64(0.09134770603171373),
   'mean_f1_majority': np.float64(0.7403182037382917),
   'fold_details': [{'fold': 0,
     'recall_void': 0.6981132075471698,
     'precision_void': 0.6981132075471698,
     'f1_void': 0.6981132075471698,
     'macro_f1': 0.7812599936040934,
     'accuracy': 0.8128654970760234,
     'precision_non_void': 0.864406779661017,
     'recall_non_void': 0.864406779661017,
     'f1_non_void': 0.864406779661017,
     'class_distribution_train': {'non-void': np.int64(802),
      'void': np.int64(667)},
     'class_distribution_test': {'non-void': np.int64(118),
      'void': np.int64(53)}},
    {'fold': 1,
     'recall_void': 0.5106382978723404,
     'precision_void': 0.48,
     'f1_void': 0.4948453608247423,
     'macro_f1': 0.6513442490398221,
     'accuracy': 0.7215909090909091,
     'precision_non_void': 0.8174603174603174,
     'recall_non_void': 0.7984496124031008,
     'f1_non_void': 0.807843137254902,
     'class_distribution_train': {'non-void': np.int64(793),
      'void': np.int64(673)},
     'class_distribution_test': {'non-void': np.int64(129),
      'void': np.int64(47)}},
    {'fold': 2,
     'recall_void': 0.5606060606060606,
     'precision_void': 0.5285714285714286,
     'f1_void': 0.5441176470588235,
     'macro_f1': 0.6285403050108932,
     'accuracy': 0.6477272727272727,
     'precision_non_void': 0.7264150943396226,
     'recall_non_void': 0.7,
     'f1_non_void': 0.7129629629629629,
     'class_distribution_train': {'non-void': np.int64(815),
      'void': np.int64(654)},
     'class_distribution_test': {'non-void': np.int64(110),
      'void': np.int64(66)}},
    {'fold': 3,
     'recall_void': 0.45652173913043476,
     'precision_void': 0.4117647058823529,
     'f1_void': 0.4329896907216495,
     'macro_f1': 0.6004610900865631,
     'accuracy': 0.6706586826347305,
     'precision_non_void': 0.7844827586206896,
     'recall_non_void': 0.7520661157024794,
     'f1_non_void': 0.7679324894514767,
     'class_distribution_train': {'non-void': np.int64(812),
      'void': np.int64(674)},
     'class_distribution_test': {'non-void': np.int64(121),
      'void': np.int64(46)}},
    {'fold': 4,
     'recall_void': 0.6025641025641025,
     'precision_void': 0.6266666666666667,
     'f1_void': 0.6143790849673203,
     'macro_f1': 0.6423850732099171,
     'accuracy': 0.6445783132530121,
     'precision_non_void': 0.6593406593406593,
     'recall_non_void': 0.6818181818181818,
     'f1_non_void': 0.6703910614525139,
     'class_distribution_train': {'non-void': np.int64(844),
      'void': np.int64(642)},
     'class_distribution_test': {'non-void': np.int64(88),
      'void': np.int64(78)}},
    {'fold': 5,
     'recall_void': 0.6818181818181818,
     'precision_void': 0.8108108108108109,
     'f1_void': 0.7407407407407407,
     'macro_f1': 0.7774500163880695,
     'accuracy': 0.7835051546391752,
     'precision_non_void': 0.7666666666666667,
     'recall_non_void': 0.8679245283018868,
     'f1_non_void': 0.8141592920353983,
     'class_distribution_train': {'non-void': np.int64(818),
      'void': np.int64(632)},
     'class_distribution_test': {'non-void': np.int64(106),
      'void': np.int64(88)}},
    {'fold': 6,
     'recall_void': 0.75,
     'precision_void': 0.65625,
     'f1_void': 0.7,
     'macro_f1': 0.7189320388349514,
     'accuracy': 0.7202072538860104,
     'precision_non_void': 0.7835051546391752,
     'recall_non_void': 0.6972477064220184,
     'f1_non_void': 0.7378640776699029,
     'class_distribution_train': {'non-void': np.int64(819),
      'void': np.int64(636)},
     'class_distribution_test': {'non-void': np.int64(109),
      'void': np.int64(84)}},
    {'fold': 7,
     'recall_void': 0.5609756097560976,
     'precision_void': 0.7419354838709677,
     'f1_void': 0.6388888888888888,
     'macro_f1': 0.6796594982078853,
     'accuracy': 0.6848484848484848,
     'precision_non_void': 0.6504854368932039,
     'recall_non_void': 0.8072289156626506,
     'f1_non_void': 0.7204301075268817,
     'class_distribution_train': {'non-void': np.int64(841),
      'void': np.int64(638)},
     'class_distribution_test': {'non-void': np.int64(83),
      'void': np.int64(82)}},
    {'fold': 8,
     'recall_void': 0.57,
     'precision_void': 0.7125,
     'f1_void': 0.6333333333333333,
     'macro_f1': 0.5936936936936936,
     'accuracy': 0.5975609756097561,
     'precision_non_void': 0.4880952380952381,
     'recall_non_void': 0.640625,
     'f1_non_void': 0.5540540540540541,
     'class_distribution_train': {'non-void': np.int64(869),
      'void': np.int64(620)},
     'class_distribution_test': {'void': np.int64(100),
      'non-void': np.int64(64)}},
    {'fold': 9,
     'recall_void': 0.6447368421052632,
     'precision_void': 0.6049382716049383,
     'f1_void': 0.6242038216560509,
     'macro_f1': 0.6886709484849292,
     'accuracy': 0.702020202020202,
     'precision_non_void': 0.7692307692307693,
     'recall_non_void': 0.7377049180327869,
     'f1_non_void': 0.7531380753138075,
     'class_distribution_train': {'non-void': np.int64(802),
      'void': np.int64(644)},
     'class_distribution_test': {'non-void': np.int64(122),
      'void': np.int64(76)}}]},
  'combined_smote_tomek': {'mean_accuracy': np.float64(0.6975317249148523),
   'std_accuracy': np.float64(0.05941792924572552),
   'mean_recall_minority': np.float64(0.5825631838497438),
   'std_recall_minority': np.float64(0.09875460048922201),
   'mean_f1_minority': np.float64(0.6019656173290997),
   'std_f1_minority': np.float64(0.10413612327327866),
   'mean_f1_majority': np.float64(0.7417122844839508),
   'fold_details': [{'fold': 0,
     'recall_void': 0.660377358490566,
     'precision_void': 0.7608695652173914,
     'f1_void': 0.7070707070707071,
     'macro_f1': 0.7938645716423494,
     'accuracy': 0.8304093567251462,
     'precision_non_void': 0.856,
     'recall_non_void': 0.9067796610169492,
     'f1_non_void': 0.8806584362139918,
     'class_distribution_train': {'non-void': np.int64(837),
      'void': np.int64(837)},
     'class_distribution_test': {'non-void': np.int64(118),
      'void': np.int64(53)}},
    {'fold': 1,
     'recall_void': 0.425531914893617,
     'precision_void': 0.4166666666666667,
     'f1_void': 0.42105263157894735,
     'macro_f1': 0.60352242473889,
     'accuracy': 0.6875,
     'precision_non_void': 0.7890625,
     'recall_non_void': 0.7829457364341085,
     'f1_non_void': 0.7859922178988327,
     'class_distribution_train': {'non-void': np.int64(830),
      'void': np.int64(830)},
     'class_distribution_test': {'non-void': np.int64(129),
      'void': np.int64(47)}},
    {'fold': 2,
     'recall_void': 0.5606060606060606,
     'precision_void': 0.6166666666666667,
     'f1_void': 0.5873015873015873,
     'macro_f1': 0.678606545863183,
     'accuracy': 0.7045454545454546,
     'precision_non_void': 0.75,
     'recall_non_void': 0.7909090909090909,
     'f1_non_void': 0.7699115044247787,
     'class_distribution_train': {'non-void': np.int64(847),
      'void': np.int64(847)},
     'class_distribution_test': {'non-void': np.int64(110),
      'void': np.int64(66)}},
    {'fold': 3,
     'recall_void': 0.41304347826086957,
     'precision_void': 0.37254901960784315,
     'f1_void': 0.3917525773195876,
     'macro_f1': 0.5714037148201314,
     'accuracy': 0.6467065868263473,
     'precision_non_void': 0.7672413793103449,
     'recall_non_void': 0.7355371900826446,
     'f1_non_void': 0.7510548523206751,
     'class_distribution_train': {'non-void': np.int64(843),
      'void': np.int64(843)},
     'class_distribution_test': {'non-void': np.int64(121),
      'void': np.int64(46)}},
    {'fold': 4,
     'recall_void': 0.6666666666666666,
     'precision_void': 0.6419753086419753,
     'f1_void': 0.6540880503144654,
     'macro_f1': 0.6680844875849783,
     'accuracy': 0.6686746987951807,
     'precision_non_void': 0.6941176470588235,
     'recall_non_void': 0.6704545454545454,
     'f1_non_void': 0.6820809248554913,
     'class_distribution_train': {'non-void': np.int64(889),
      'void': np.int64(889)},
     'class_distribution_test': {'non-void': np.int64(88),
      'void': np.int64(78)}},
    {'fold': 5,
     'recall_void': 0.5568181818181818,
     'precision_void': 0.7538461538461538,
     'f1_void': 0.6405228758169934,
     'macro_f1': 0.703240161312752,
     'accuracy': 0.7164948453608248,
     'precision_non_void': 0.6976744186046512,
     'recall_non_void': 0.8490566037735849,
     'f1_non_void': 0.7659574468085106,
     'class_distribution_train': {'non-void': np.int64(856),

## Baseline

In [3]:
mean_accuracy = []
std_accuracy = []
mean_recall_void = []
std_recall_void = []
for win_data, data in xgb_results.items(): 
    data_ = data["none"]
    
    mean_accuracy.append(data_['mean_accuracy'])
    std_accuracy.append(data_['std_accuracy'])
    mean_recall_void.append(data_['mean_recall_minority'])
    std_recall_void.append(data_['std_recall_minority'])

indexes = xgb_results.keys()
results = {
    'config': indexes,
    'mean_accuracy': mean_accuracy,
    'std_accuracy': std_accuracy,
    'mean_recall_void': mean_recall_void,
    'std_recall_void': std_recall_void
} 
    
df = pd.DataFrame(results)
# df = pd.DataFrame(results, index=indexes)

In [4]:
df

    config  mean_accuracy  std_accuracy  mean_recall_void  std_recall_void
0    1s_no       0.690856      0.047085          0.514805         0.075058
1   1s_0.5       0.695367      0.078156          0.534627         0.148696
2   1s_0.8       0.678299      0.091157          0.480396         0.188534
3    2s_no       0.705599      0.098831          0.549997         0.187726
4   2s_0.5       0.711016      0.052714          0.534605         0.082020
5   2s_0.8       0.709256      0.095052          0.547847         0.190932
6    3s_no       0.704269      0.105258          0.587031         0.152450
7   3s_0.5       0.708997      0.088649          0.557060         0.172564
8   3s_0.8       0.702263      0.094695          0.545117         0.171409
9    4s_no       0.704549      0.125590          0.593655         0.275395
10  4s_0.5       0.712603      0.105865          0.548224         0.203592
11  4s_0.8       0.691141      0.083237          0.544561         0.139893
12   5s_no       0.706055      0.114180          0.625715         0.197179
13  5s_0.5       0.719653      0.083210          0.605234         0.158523
14  5s_0.8       0.702287      0.074577          0.554161         0.137627

In [ ]:
# Get indexes of top N values using nlargest()
def get_top_n_indexes(df, column, n=5):
    """Get indexes of top N values in specified column"""
    top_indexes = df.nlargest(n, column).index.tolist()
    return top_indexes

# Get indexes using argsort() for all values (sorted)
def get_all_indexes_sorted(df, column):
    """Get all indexes sorted by column values (highest to lowest)"""
    sorted_indexes = df[column].argsort()[::-On the knees1].tolist()
    return sorted_indexes

# Get indexes above a certain threshold
def get_indexes_above_threshold(df, column, threshold):
    """Get indexes where column values are above threshold"""
    above_threshold_indexes = df[df[column] > threshold].index.tolist()
    return above_threshold_indexes


# print("DataFrame:")
# print(df)
# print("\n" + "="*50)

# Get top 5 indexes
top_5_indexes = get_top_n_indexes(df, 'mean_recall_void', 5)
print(f"\nTop 5 indexes by mean_recall_void:")
print(f"Indexes: {top_5_indexes}")
print("Corresponding configurations and values:")
for idx in top_5_indexes:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_recall_void']On the knees
    print(f"  Index {idx}: {config} = {value:.6f}")

# Get all indexes sorted
all_sorted_indexes = get_all_indexes_sorted(df, 'mean_recall_void')
print(f"\nAll indexes sorted by mean_recall_void (highest to lowest):")
print(f"Indexes: {all_sorted_indexes}")

# Get indexes above threshold (e.g., 0.55)
threshold = 0.55
above_threshold = get_indexes_above_threshold(df, 'mean_recall_void', threshold)
print(f"\nIndexes with mean_recall_void > {threshold}:")
print(f"Indexes: {above_threshold}")
print("Corresponding configurations and values:")
for idx in above_threshold:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_recall_void']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Highest value index
max_index = df['mean_recall_void'].idxmax()
max_value = df.loc[max_index, 'mean_recall_void']
max_config = df.loc[max_index, 'config']
print(f"\nHighest mean_recall_void:")
print(f"Index {max_index}: {max_config} = {max_value:.6f}")

Top 5 indexes by mean_recall_void:
Indexes: [12, 13, 9, 6, 7]
Corresponding configurations and values:
  Index 12: 5s_no = 0.625715
  Index 13: 5s_0.5 = 0.605234
  Index 9: 4s_no = 0.593655
  Index 6: 3s_no = 0.587031
  Index 7: 3s_0.5 = 0.557060

All indexes sorted by mean_recall_void (highest to lowest):
Indexes: [12, 13, 9, 6, 7, 14, 3, 10, 5, 8, 11, 1, 4, 0, 2]

Indexes with mean_recall_void > 0.55:
Indexes: [6, 7, 9, 12, 13, 14]
Corresponding configurations and values:
  Index 6: 3s_no = 0.587031
  Index 7: 3s_0.5 = 0.557060
  Index 9: 4s_no = 0.593655
  Index 12: 5s_no = 0.625715
  Index 13: 5s_0.5 = 0.605234
  Index 14: 5s_0.8 = 0.554161

Highest mean_recall_void:
Index 12: 5s_no = 0.625715

In [6]:
# Get indexes of top N values using nlargest()
def get_top_n_indexes(df, column, n=5):
    """Get indexes of top N values in specified column"""
    top_indexes = df.nlargest(n, column).index.tolist()
    return top_indexes

# Get indexes using argsort() for all values (sorted)
def get_all_indexes_sorted(df, column):
    """Get all indexes sorted by column values (highest to lowest)"""
    sorted_indexes = df[column].argsort()[::-1].tolist()
    return sorted_indexes

# Get indexes above a certain threshold
def get_indexes_above_threshold(df, column, threshold):
    """Get indexes where column values are above threshold"""
    above_threshold_indexes = df[df[column] > threshold].index.tolist()
    return above_threshold_indexes


# print("DataFrame:")
# print(df)
# print("\n" + "="*50)

# Get top 5 indexes
top_5_indexes = get_top_n_indexes(df, 'mean_accuracy', 5)
print(f"\nTop 5 indexes by mean_accuracy:")
print(f"Indexes: {top_5_indexes}")
print("Corresponding configurations and values:")
for idx in top_5_indexes:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_accuracy']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Get all indexes sorted
all_sorted_indexes = get_all_indexes_sorted(df, 'mean_accuracy')
print(f"\nAll indexes sorted by mean_accuracy (highest to lowest):")
print(f"Indexes: {all_sorted_indexes}")

# Get indexes above threshold (e.g., 0.55)
threshold = 0.55
above_threshold = get_indexes_above_threshold(df, 'mean_accuracy', threshold)
print(f"\nIndexes with mean_accuracy > {threshold}:")
print(f"Indexes: {above_threshold}")
print("Corresponding configurations and values:")
for idx in above_threshold:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_accuracy']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Highest value index
max_index = df['mean_accuracy'].idxmax()
max_value = df.loc[max_index, 'mean_accuracy']
max_config = df.loc[max_index, 'config']
print(f"\nHighest mean_accuracy:")
print(f"Index {max_index}: {max_config} = {max_value:.6f}")

Top 5 indexes by mean_accuracy:
Indexes: [13, 10, 4, 5, 7]
Corresponding configurations and values:
  Index 13: 5s_0.5 = 0.719653
  Index 10: 4s_0.5 = 0.712603
  Index 4: 2s_0.5 = 0.711016
  Index 5: 2s_0.8 = 0.709256
  Index 7: 3s_0.5 = 0.708997

All indexes sorted by mean_accuracy (highest to lowest):
Indexes: [13, 10, 4, 5, 7, 12, 3, 9, 6, 14, 8, 1, 11, 0, 2]

Indexes with mean_accuracy > 0.55:
Indexes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
Corresponding configurations and values:
  Index 0: 1s_no = 0.690856
  Index 1: 1s_0.5 = 0.695367
  Index 2: 1s_0.8 = 0.678299
  Index 3: 2s_no = 0.705599
  Index 4: 2s_0.5 = 0.711016
  Index 5: 2s_0.8 = 0.709256
  Index 6: 3s_no = 0.704269
  Index 7: 3s_0.5 = 0.708997
  Index 8: 3s_0.8 = 0.702263
  Index 9: 4s_no = 0.704549
  Index 10: 4s_0.5 = 0.712603
  Index 11: 4s_0.8 = 0.691141
  Index 12: 5s_no = 0.706055
  Index 13: 5s_0.5 = 0.719653
  Index 14: 5s_0.8 = 0.702287

Highest mean_accuracy:
Index 13: 5s_0.5 = 0.719653

## Oversample

In [7]:
mean_accuracy = []
std_accuracy = []
mean_recall_void = []
std_recall_void = []
for win_data, data in xgb_results.items(): 
    data_ = data["oversample_smote"]
    
    mean_accuracy.append(data_['mean_accuracy'])
    std_accuracy.append(data_['std_accuracy'])
    mean_recall_void.append(data_['mean_recall_minority'])
    std_recall_void.append(data_['std_recall_minority'])

indexes = xgb_results.keys()
results = {
    'config': indexes,
    'mean_accuracy': mean_accuracy,
    'std_accuracy': std_accuracy,
    'mean_recall_void': mean_recall_void,
    'std_recall_void': std_recall_void
} 
    
df = pd.DataFrame(results)

In [8]:
df

    config  mean_accuracy  std_accuracy  mean_recall_void  std_recall_void
0    1s_no       0.688239      0.060273          0.566874         0.099999
1   1s_0.5       0.679906      0.085563          0.563574         0.152188
2   1s_0.8       0.671483      0.097891          0.510002         0.184269
3    2s_no       0.718604      0.116462          0.612904         0.203268
4   2s_0.5       0.711991      0.053108          0.578325         0.075496
5   2s_0.8       0.695780      0.094920          0.561698         0.176020
6    3s_no       0.688079      0.102957          0.623039         0.148576
7   3s_0.5       0.707387      0.100684          0.584447         0.176649
8   3s_0.8       0.699340      0.092419          0.576412         0.164297
9    4s_no       0.698366      0.120855          0.657132         0.234108
10  4s_0.5       0.686403      0.125763          0.591612         0.192385
11  4s_0.8       0.697396      0.075120          0.574683         0.131380
12   5s_no       0.684344      0.102468          0.649882         0.193517
13  5s_0.5       0.702825      0.076614          0.626650         0.110702
14  5s_0.8       0.694372      0.082894          0.572198         0.136480

In [9]:
# Get indexes of top N values using nlargest()
def get_top_n_indexes(df, column, n=5):
    """Get indexes of top N values in specified column"""
    top_indexes = df.nlargest(n, column).index.tolist()
    return top_indexes

# Get indexes using argsort() for all values (sorted)
def get_all_indexes_sorted(df, column):
    """Get all indexes sorted by column values (highest to lowest)"""
    sorted_indexes = df[column].argsort()[::-1].tolist()
    return sorted_indexes

# Get indexes above a certain threshold
def get_indexes_above_threshold(df, column, threshold):
    """Get indexes where column values are above threshold"""
    above_threshold_indexes = df[df[column] > threshold].index.tolist()
    return above_threshold_indexes


# print("DataFrame:")
# print(df)
# print("\n" + "="*50)

# Get top 5 indexes
top_5_indexes = get_top_n_indexes(df, 'mean_recall_void', 5)
print(f"\nTop 5 indexes by mean_recall_void:")
print(f"Indexes: {top_5_indexes}")
print("Corresponding configurations and values:")
for idx in top_5_indexes:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_recall_void']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Get all indexes sorted
all_sorted_indexes = get_all_indexes_sorted(df, 'mean_recall_void')
print(f"\nAll indexes sorted by mean_recall_void (highest to lowest):")
print(f"Indexes: {all_sorted_indexes}")

# Get indexes above threshold (e.g., 0.55)
threshold = 0.55
above_threshold = get_indexes_above_threshold(df, 'mean_recall_void', threshold)
print(f"\nIndexes with mean_recall_void > {threshold}:")
print(f"Indexes: {above_threshold}")
print("Corresponding configurations and values:")
for idx in above_threshold:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_recall_void']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Highest value index
max_index = df['mean_recall_void'].idxmax()
max_value = df.loc[max_index, 'mean_recall_void']
max_config = df.loc[max_index, 'config']
print(f"\nHighest mean_recall_void:")
print(f"Index {max_index}: {max_config} = {max_value:.6f}")

Top 5 indexes by mean_recall_void:
Indexes: [9, 12, 13, 6, 3]
Corresponding configurations and values:
  Index 9: 4s_no = 0.657132
  Index 12: 5s_no = 0.649882
  Index 13: 5s_0.5 = 0.626650
  Index 6: 3s_no = 0.623039
  Index 3: 2s_no = 0.612904

All indexes sorted by mean_recall_void (highest to lowest):
Indexes: [9, 12, 13, 6, 3, 10, 7, 4, 8, 11, 14, 0, 1, 5, 2]

Indexes with mean_recall_void > 0.55:
Indexes: [0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
Corresponding configurations and values:
  Index 0: 1s_no = 0.566874
  Index 1: 1s_0.5 = 0.563574
  Index 3: 2s_no = 0.612904
  Index 4: 2s_0.5 = 0.578325
  Index 5: 2s_0.8 = 0.561698
  Index 6: 3s_no = 0.623039
  Index 7: 3s_0.5 = 0.584447
  Index 8: 3s_0.8 = 0.576412
  Index 9: 4s_no = 0.657132
  Index 10: 4s_0.5 = 0.591612
  Index 11: 4s_0.8 = 0.574683
  Index 12: 5s_no = 0.649882
  Index 13: 5s_0.5 = 0.626650
  Index 14: 5s_0.8 = 0.572198

Highest mean_recall_void:
Index 9: 4s_no = 0.657132

In [10]:
# Get indexes of top N values using nlargest()
def get_top_n_indexes(df, column, n=5):
    """Get indexes of top N values in specified column"""
    top_indexes = df.nlargest(n, column).index.tolist()
    return top_indexes

# Get indexes using argsort() for all values (sorted)
def get_all_indexes_sorted(df, column):
    """Get all indexes sorted by column values (highest to lowest)"""
    sorted_indexes = df[column].argsort()[::-1].tolist()
    return sorted_indexes

# Get indexes above a certain threshold
def get_indexes_above_threshold(df, column, threshold):
    """Get indexes where column values are above threshold"""
    above_threshold_indexes = df[df[column] > threshold].index.tolist()
    return above_threshold_indexes


# print("DataFrame:")
# print(df)
# print("\n" + "="*50)

# Get top 5 indexes
top_5_indexes = get_top_n_indexes(df, 'mean_accuracy', 5)
print(f"\nTop 5 indexes by mean_accuracy:")
print(f"Indexes: {top_5_indexes}")
print("Corresponding configurations and values:")
for idx in top_5_indexes:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_accuracy']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Get all indexes sorted
all_sorted_indexes = get_all_indexes_sorted(df, 'mean_accuracy')
print(f"\nAll indexes sorted by mean_accuracy (highest to lowest):")
print(f"Indexes: {all_sorted_indexes}")

# Get indexes above threshold (e.g., 0.55)
threshold = 0.55
above_threshold = get_indexes_above_threshold(df, 'mean_accuracy', threshold)
print(f"\nIndexes with mean_accuracy > {threshold}:")
print(f"Indexes: {above_threshold}")
print("Corresponding configurations and values:")
for idx in above_threshold:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_accuracy']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Highest value index
max_index = df['mean_accuracy'].idxmax()
max_value = df.loc[max_index, 'mean_accuracy']
max_config = df.loc[max_index, 'config']
print(f"\nHighest mean_accuracy:")
print(f"Index {max_index}: {max_config} = {max_value:.6f}")

Top 5 indexes by mean_accuracy:
Indexes: [3, 4, 7, 13, 8]
Corresponding configurations and values:
  Index 3: 2s_no = 0.718604
  Index 4: 2s_0.5 = 0.711991
  Index 7: 3s_0.5 = 0.707387
  Index 13: 5s_0.5 = 0.702825
  Index 8: 3s_0.8 = 0.699340

All indexes sorted by mean_accuracy (highest to lowest):
Indexes: [3, 4, 7, 13, 8, 9, 11, 5, 14, 0, 6, 10, 12, 1, 2]

Indexes with mean_accuracy > 0.55:
Indexes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
Corresponding configurations and values:
  Index 0: 1s_no = 0.688239
  Index 1: 1s_0.5 = 0.679906
  Index 2: 1s_0.8 = 0.671483
  Index 3: 2s_no = 0.718604
  Index 4: 2s_0.5 = 0.711991
  Index 5: 2s_0.8 = 0.695780
  Index 6: 3s_no = 0.688079
  Index 7: 3s_0.5 = 0.707387
  Index 8: 3s_0.8 = 0.699340
  Index 9: 4s_no = 0.698366
  Index 10: 4s_0.5 = 0.686403
  Index 11: 4s_0.8 = 0.697396
  Index 12: 5s_no = 0.684344
  Index 13: 5s_0.5 = 0.702825
  Index 14: 5s_0.8 = 0.694372

Highest mean_accuracy:
Index 3: 2s_no = 0.718604

## Undersample

In [11]:
mean_accuracy = []
std_accuracy = []
mean_recall_void = []
std_recall_void = []
for win_data, data in xgb_results.items(): 
    data_ = data["undersample_tomek_links"]
    
    mean_accuracy.append(data_['mean_accuracy'])
    std_accuracy.append(data_['std_accuracy'])
    mean_recall_void.append(data_['mean_recall_minority'])
    std_recall_void.append(data_['std_recall_minority'])

indexes = xgb_results.keys()
results = {
    'config': indexes,
    'mean_accuracy': mean_accuracy,
    'std_accuracy': std_accuracy,
    'mean_recall_void': mean_recall_void,
    'std_recall_void': std_recall_void
} 
    
df = pd.DataFrame(results)

In [12]:
df

    config  mean_accuracy  std_accuracy  mean_recall_void  std_recall_void
0    1s_no       0.698556      0.061610          0.603597         0.085583
1   1s_0.5       0.689289      0.080975          0.579814         0.152135
2   1s_0.8       0.674493      0.096504          0.508023         0.194181
3    2s_no       0.713653      0.120675          0.613575         0.206723
4   2s_0.5       0.715187      0.073460          0.615685         0.085267
5   2s_0.8       0.702847      0.106586          0.571314         0.199955
6    3s_no       0.706013      0.114237          0.670130         0.138223
7   3s_0.5       0.703954      0.071521          0.600523         0.165586
8   3s_0.8       0.697396      0.085692          0.567000         0.171831
9    4s_no       0.710130      0.107787          0.651195         0.247955
10  4s_0.5       0.705668      0.114519          0.587745         0.193917
11  4s_0.8       0.693689      0.087328          0.592744         0.139366
12   5s_no       0.688582      0.100445          0.646356         0.197941
13  5s_0.5       0.697836      0.080465          0.622445         0.124590
14  5s_0.8       0.701891      0.095510          0.582803         0.153903

In [13]:
# Get indexes of top N values using nlargest()
def get_top_n_indexes(df, column, n=5):
    """Get indexes of top N values in specified column"""
    top_indexes = df.nlargest(n, column).index.tolist()
    return top_indexes

# Get indexes using argsort() for all values (sorted)
def get_all_indexes_sorted(df, column):
    """Get all indexes sorted by column values (highest to lowest)"""
    sorted_indexes = df[column].argsort()[::-1].tolist()
    return sorted_indexes

# Get indexes above a certain threshold
def get_indexes_above_threshold(df, column, threshold):
    """Get indexes where column values are above threshold"""
    above_threshold_indexes = df[df[column] > threshold].index.tolist()
    return above_threshold_indexes


# print("DataFrame:")
# print(df)
# print("\n" + "="*50)

# Get top 5 indexes
top_5_indexes = get_top_n_indexes(df, 'mean_recall_void', 5)
print(f"\nTop 5 indexes by mean_recall_void:")
print(f"Indexes: {top_5_indexes}")
print("Corresponding configurations and values:")
for idx in top_5_indexes:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_recall_void']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Get all indexes sorted
all_sorted_indexes = get_all_indexes_sorted(df, 'mean_recall_void')
print(f"\nAll indexes sorted by mean_recall_void (highest to lowest):")
print(f"Indexes: {all_sorted_indexes}")

# Get indexes above threshold (e.g., 0.55)
threshold = 0.55
above_threshold = get_indexes_above_threshold(df, 'mean_recall_void', threshold)
print(f"\nIndexes with mean_recall_void > {threshold}:")
print(f"Indexes: {above_threshold}")
print("Corresponding configurations and values:")
for idx in above_threshold:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_recall_void']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Highest value index
max_index = df['mean_recall_void'].idxmax()
max_value = df.loc[max_index, 'mean_recall_void']
max_config = df.loc[max_index, 'config']
print(f"\nHighest mean_recall_void:")
print(f"Index {max_index}: {max_config} = {max_value:.6f}")

Top 5 indexes by mean_recall_void:
Indexes: [6, 9, 12, 13, 4]
Corresponding configurations and values:
  Index 6: 3s_no = 0.670130
  Index 9: 4s_no = 0.651195
  Index 12: 5s_no = 0.646356
  Index 13: 5s_0.5 = 0.622445
  Index 4: 2s_0.5 = 0.615685

All indexes sorted by mean_recall_void (highest to lowest):
Indexes: [6, 9, 12, 13, 4, 3, 0, 7, 11, 10, 14, 1, 5, 8, 2]

Indexes with mean_recall_void > 0.55:
Indexes: [0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
Corresponding configurations and values:
  Index 0: 1s_no = 0.603597
  Index 1: 1s_0.5 = 0.579814
  Index 3: 2s_no = 0.613575
  Index 4: 2s_0.5 = 0.615685
  Index 5: 2s_0.8 = 0.571314
  Index 6: 3s_no = 0.670130
  Index 7: 3s_0.5 = 0.600523
  Index 8: 3s_0.8 = 0.567000
  Index 9: 4s_no = 0.651195
  Index 10: 4s_0.5 = 0.587745
  Index 11: 4s_0.8 = 0.592744
  Index 12: 5s_no = 0.646356
  Index 13: 5s_0.5 = 0.622445
  Index 14: 5s_0.8 = 0.582803

Highest mean_recall_void:
Index 6: 3s_no = 0.670130

In [14]:
# Get indexes of top N values using nlargest()
def get_top_n_indexes(df, column, n=5):
    """Get indexes of top N values in specified column"""
    top_indexes = df.nlargest(n, column).index.tolist()
    return top_indexes

# Get indexes using argsort() for all values (sorted)
def get_all_indexes_sorted(df, column):
    """Get all indexes sorted by column values (highest to lowest)"""
    sorted_indexes = df[column].argsort()[::-1].tolist()
    return sorted_indexes

# Get indexes above a certain threshold
def get_indexes_above_threshold(df, column, threshold):
    """Get indexes where column values are above threshold"""
    above_threshold_indexes = df[df[column] > threshold].index.tolist()
    return above_threshold_indexes


# print("DataFrame:")
# print(df)
# print("\n" + "="*50)

# Get top 5 indexes
top_5_indexes = get_top_n_indexes(df, 'mean_accuracy', 5)
print(f"\nTop 5 indexes by mean_accuracy:")
print(f"Indexes: {top_5_indexes}")
print("Corresponding configurations and values:")
for idx in top_5_indexes:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_accuracy']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Get all indexes sorted
all_sorted_indexes = get_all_indexes_sorted(df, 'mean_accuracy')
print(f"\nAll indexes sorted by mean_accuracy (highest to lowest):")
print(f"Indexes: {all_sorted_indexes}")

# Get indexes above threshold (e.g., 0.55)
threshold = 0.55
above_threshold = get_indexes_above_threshold(df, 'mean_accuracy', threshold)
print(f"\nIndexes with mean_accuracy > {threshold}:")
print(f"Indexes: {above_threshold}")
print("Corresponding configurations and values:")
for idx in above_threshold:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_accuracy']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Highest value index
max_index = df['mean_accuracy'].idxmax()
max_value = df.loc[max_index, 'mean_accuracy']
max_config = df.loc[max_index, 'config']
print(f"\nHighest mean_accuracy:")
print(f"Index {max_index}: {max_config} = {max_value:.6f}")

Top 5 indexes by mean_accuracy:
Indexes: [4, 3, 9, 6, 10]
Corresponding configurations and values:
  Index 4: 2s_0.5 = 0.715187
  Index 3: 2s_no = 0.713653
  Index 9: 4s_no = 0.710130
  Index 6: 3s_no = 0.706013
  Index 10: 4s_0.5 = 0.705668

All indexes sorted by mean_accuracy (highest to lowest):
Indexes: [4, 3, 9, 6, 10, 7, 5, 14, 0, 13, 8, 11, 1, 12, 2]

Indexes with mean_accuracy > 0.55:
Indexes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
Corresponding configurations and values:
  Index 0: 1s_no = 0.698556
  Index 1: 1s_0.5 = 0.689289
  Index 2: 1s_0.8 = 0.674493
  Index 3: 2s_no = 0.713653
  Index 4: 2s_0.5 = 0.715187
  Index 5: 2s_0.8 = 0.702847
  Index 6: 3s_no = 0.706013
  Index 7: 3s_0.5 = 0.703954
  Index 8: 3s_0.8 = 0.697396
  Index 9: 4s_no = 0.710130
  Index 10: 4s_0.5 = 0.705668
  Index 11: 4s_0.8 = 0.693689
  Index 12: 5s_no = 0.688582
  Index 13: 5s_0.5 = 0.697836
  Index 14: 5s_0.8 = 0.701891

Highest mean_accuracy:
Index 4: 2s_0.5 = 0.715187

## Combined Smote Tomek

In [15]:
mean_accuracy = []
std_accuracy = []
mean_recall_void = []
std_recall_void = []
for win_data, data in xgb_results.items(): 
    data_ = data["combined_smote_tomek"]
    
    mean_accuracy.append(data_['mean_accuracy'])
    std_accuracy.append(data_['std_accuracy'])
    mean_recall_void.append(data_['mean_recall_minority'])
    std_recall_void.append(data_['std_recall_minority'])

indexes = xgb_results.keys()
results = {
    'config': indexes,
    'mean_accuracy': mean_accuracy,
    'std_accuracy': std_accuracy,
    'mean_recall_void': mean_recall_void,
    'std_recall_void': std_recall_void
} 
    
df = pd.DataFrame(results)

In [16]:
df

    config  mean_accuracy  std_accuracy  mean_recall_void  std_recall_void
0    1s_no       0.697532      0.059418          0.582563         0.098755
1   1s_0.5       0.685611      0.078925          0.570388         0.146004
2   1s_0.8       0.676738      0.096832          0.523676         0.184242
3    2s_no       0.722920      0.101758          0.610760         0.171816
4   2s_0.5       0.713068      0.060978          0.597030         0.082331
5   2s_0.8       0.694558      0.096688          0.561252         0.189658
6    3s_no       0.715228      0.113714          0.659311         0.151734
7   3s_0.5       0.700749      0.092553          0.601542         0.166896
8   3s_0.8       0.703961      0.082978          0.575904         0.166094
9    4s_no       0.687874      0.129530          0.644285         0.238260
10  4s_0.5       0.714318      0.116198          0.596035         0.204467
11  4s_0.8       0.697211      0.082784          0.585149         0.131986
12   5s_no       0.708132      0.118673          0.694361         0.212597
13  5s_0.5       0.702218      0.094681          0.630522         0.097162
14  5s_0.8       0.696692      0.092664          0.581643         0.155669

In [17]:
# Get indexes of top N values using nlargest()
def get_top_n_indexes(df, column, n=5):
    """Get indexes of top N values in specified column"""
    top_indexes = df.nlargest(n, column).index.tolist()
    return top_indexes

# Get indexes using argsort() for all values (sorted)
def get_all_indexes_sorted(df, column):
    """Get all indexes sorted by column values (highest to lowest)"""
    sorted_indexes = df[column].argsort()[::-1].tolist()
    return sorted_indexes

# Get indexes above a certain threshold
def get_indexes_above_threshold(df, column, threshold):
    """Get indexes where column values are above threshold"""
    above_threshold_indexes = df[df[column] > threshold].index.tolist()
    return above_threshold_indexes


# print("DataFrame:")
# print(df)
# print("\n" + "="*50)

# Get top 5 indexes
top_5_indexes = get_top_n_indexes(df, 'mean_recall_void', 5)
print(f"\nTop 5 indexes by mean_recall_void:")
print(f"Indexes: {top_5_indexes}")
print("Corresponding configurations and values:")
for idx in top_5_indexes:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_recall_void']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Get all indexes sorted
all_sorted_indexes = get_all_indexes_sorted(df, 'mean_recall_void')
print(f"\nAll indexes sorted by mean_recall_void (highest to lowest):")
print(f"Indexes: {all_sorted_indexes}")

# Get indexes above threshold (e.g., 0.55)
threshold = 0.55
above_threshold = get_indexes_above_threshold(df, 'mean_recall_void', threshold)
print(f"\nIndexes with mean_recall_void > {threshold}:")
print(f"Indexes: {above_threshold}")
print("Corresponding configurations and values:")
for idx in above_threshold:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_recall_void']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Highest value index
max_index = df['mean_recall_void'].idxmax()
max_value = df.loc[max_index, 'mean_recall_void']
max_config = df.loc[max_index, 'config']
print(f"\nHighest mean_recall_void:")
print(f"Index {max_index}: {max_config} = {max_value:.6f}")

Top 5 indexes by mean_recall_void:
Indexes: [12, 6, 9, 13, 3]
Corresponding configurations and values:
  Index 12: 5s_no = 0.694361
  Index 6: 3s_no = 0.659311
  Index 9: 4s_no = 0.644285
  Index 13: 5s_0.5 = 0.630522
  Index 3: 2s_no = 0.610760

All indexes sorted by mean_recall_void (highest to lowest):
Indexes: [12, 6, 9, 13, 3, 7, 4, 10, 11, 0, 14, 8, 1, 5, 2]

Indexes with mean_recall_void > 0.55:
Indexes: [0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
Corresponding configurations and values:
  Index 0: 1s_no = 0.582563
  Index 1: 1s_0.5 = 0.570388
  Index 3: 2s_no = 0.610760
  Index 4: 2s_0.5 = 0.597030
  Index 5: 2s_0.8 = 0.561252
  Index 6: 3s_no = 0.659311
  Index 7: 3s_0.5 = 0.601542
  Index 8: 3s_0.8 = 0.575904
  Index 9: 4s_no = 0.644285
  Index 10: 4s_0.5 = 0.596035
  Index 11: 4s_0.8 = 0.585149
  Index 12: 5s_no = 0.694361
  Index 13: 5s_0.5 = 0.630522
  Index 14: 5s_0.8 = 0.581643

Highest mean_recall_void:
Index 12: 5s_no = 0.694361

In [18]:
# Get indexes of top N values using nlargest()
def get_top_n_indexes(df, column, n=5):
    """Get indexes of top N values in specified column"""
    top_indexes = df.nlargest(n, column).index.tolist()
    return top_indexes

# Get indexes using argsort() for all values (sorted)
def get_all_indexes_sorted(df, column):
    """Get all indexes sorted by column values (highest to lowest)"""
    sorted_indexes = df[column].argsort()[::-1].tolist()
    return sorted_indexes

# Get indexes above a certain threshold
def get_indexes_above_threshold(df, column, threshold):
    """Get indexes where column values are above threshold"""
    above_threshold_indexes = df[df[column] > threshold].index.tolist()
    return above_threshold_indexes


# print("DataFrame:")
# print(df)
# print("\n" + "="*50)

# Get top 5 indexes
top_5_indexes = get_top_n_indexes(df, 'mean_accuracy', 5)
print(f"\nTop 5 indexes by mean_accuracy:")
print(f"Indexes: {top_5_indexes}")
print("Corresponding configurations and values:")
for idx in top_5_indexes:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_accuracy']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Get all indexes sorted
all_sorted_indexes = get_all_indexes_sorted(df, 'mean_accuracy')
print(f"\nAll indexes sorted by mean_accuracy (highest to lowest):")
print(f"Indexes: {all_sorted_indexes}")

# Get indexes above threshold (e.g., 0.55)
threshold = 0.55
above_threshold = get_indexes_above_threshold(df, 'mean_accuracy', threshold)
print(f"\nIndexes with mean_accuracy > {threshold}:")
print(f"Indexes: {above_threshold}")
print("Corresponding configurations and values:")
for idx in above_threshold:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_accuracy']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Highest value index
max_index = df['mean_accuracy'].idxmax()
max_value = df.loc[max_index, 'mean_accuracy']
max_config = df.loc[max_index, 'config']
print(f"\nHighest mean_accuracy:")
print(f"Index {max_index}: {max_config} = {max_value:.6f}")

Top 5 indexes by mean_accuracy:
Indexes: [3, 6, 10, 4, 12]
Corresponding configurations and values:
  Index 3: 2s_no = 0.722920
  Index 6: 3s_no = 0.715228
  Index 10: 4s_0.5 = 0.714318
  Index 4: 2s_0.5 = 0.713068
  Index 12: 5s_no = 0.708132

All indexes sorted by mean_accuracy (highest to lowest):
Indexes: [3, 6, 10, 4, 12, 8, 13, 7, 0, 11, 14, 5, 9, 1, 2]

Indexes with mean_accuracy > 0.55:
Indexes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
Corresponding configurations and values:
  Index 0: 1s_no = 0.697532
  Index 1: 1s_0.5 = 0.685611
  Index 2: 1s_0.8 = 0.676738
  Index 3: 2s_no = 0.722920
  Index 4: 2s_0.5 = 0.713068
  Index 5: 2s_0.8 = 0.694558
  Index 6: 3s_no = 0.715228
  Index 7: 3s_0.5 = 0.700749
  Index 8: 3s_0.8 = 0.703961
  Index 9: 4s_no = 0.687874
  Index 10: 4s_0.5 = 0.714318
  Index 11: 4s_0.8 = 0.697211
  Index 12: 5s_no = 0.708132
  Index 13: 5s_0.5 = 0.702218
  Index 14: 5s_0.8 = 0.696692

Highest mean_accuracy:
Index 3: 2s_no = 0.722920