In [10]:
import pickle
import pandas as pd

In [11]:
with open('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/imb_files/rf_imb_152_entire.pkl', 'rb') as f:
    xgb_results = pickle.load(f)

## Baseline

In [12]:
mean_accuracy = []
std_accuracy = []
mean_recall_void = []
std_recall_void = []
for win_data, data in xgb_results.items(): 
    data_ = data["none"]
    
    mean_accuracy.append(data_['mean_accuracy'])
    std_accuracy.append(data_['std_accuracy'])
    mean_recall_void.append(data_['mean_recall_minority'])
    std_recall_void.append(data_['std_recall_minority'])

indexes = xgb_results.keys()
results = {
    'config': indexes,
    'mean_accuracy': mean_accuracy,
    'std_accuracy': std_accuracy,
    'mean_recall_void': mean_recall_void,
    'std_recall_void': std_recall_void
} 
    
df = pd.DataFrame(results)
# df = pd.DataFrame(results, index=indexes)

In [13]:
df

    config  mean_accuracy  std_accuracy  mean_recall_void  std_recall_void
0    1s_no       0.696674      0.082199          0.584295         0.129013
1   1s_0.5       0.694995      0.100919          0.560244         0.182020
2   1s_0.8       0.690141      0.090724          0.556134         0.096974
3    2s_no       0.702500      0.091658          0.574033         0.136570
4   2s_0.5       0.707857      0.086532          0.585692         0.133928
5   2s_0.8       0.698890      0.095530          0.565030         0.134597
6    3s_no       0.720957      0.098953          0.645502         0.169598
7   3s_0.5       0.699673      0.096721          0.594883         0.151006
8   3s_0.8       0.702866      0.116759          0.587149         0.156752
9    4s_no       0.704053      0.101138          0.615924         0.194155
10  4s_0.5       0.712872      0.104958          0.582663         0.182199
11  4s_0.8       0.703445      0.127775          0.616852         0.185276
12   5s_no       0.711004      0.120348          0.587673         0.217057
13  5s_0.5       0.712109      0.110818          0.627965         0.154437
14  5s_0.8       0.699304      0.127057          0.603315         0.184552

In [14]:
# Get indexes of top N values using nlargest()
def get_top_n_indexes(df, column, n=5):
    """Get indexes of top N values in specified column"""
    top_indexes = df.nlargest(n, column).index.tolist()
    return top_indexes

# Get indexes using argsort() for all values (sorted)
def get_all_indexes_sorted(df, column):
    """Get all indexes sorted by column values (highest to lowest)"""
    sorted_indexes = df[column].argsort()[::-1].tolist()
    return sorted_indexes

# Get indexes above a certain threshold
def get_indexes_above_threshold(df, column, threshold):
    """Get indexes where column values are above threshold"""
    above_threshold_indexes = df[df[column] > threshold].index.tolist()
    return above_threshold_indexes


# print("DataFrame:")
# print(df)
# print("\n" + "="*50)

# Get top 5 indexes
top_5_indexes = get_top_n_indexes(df, 'mean_recall_void', 5)
print(f"\nTop 5 indexes by mean_recall_void:")
print(f"Indexes: {top_5_indexes}")
print("Corresponding configurations and values:")
for idx in top_5_indexes:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_recall_void']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Get all indexes sorted
all_sorted_indexes = get_all_indexes_sorted(df, 'mean_recall_void')
print(f"\nAll indexes sorted by mean_recall_void (highest to lowest):")
print(f"Indexes: {all_sorted_indexes}")

# Get indexes above threshold (e.g., 0.55)
threshold = 0.55
above_threshold = get_indexes_above_threshold(df, 'mean_recall_void', threshold)
print(f"\nIndexes with mean_recall_void > {threshold}:")
print(f"Indexes: {above_threshold}")
print("Corresponding configurations and values:")
for idx in above_threshold:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_recall_void']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Highest value index
max_index = df['mean_recall_void'].idxmax()
max_value = df.loc[max_index, 'mean_recall_void']
max_config = df.loc[max_index, 'config']
print(f"\nHighest mean_recall_void:")
print(f"Index {max_index}: {max_config} = {max_value:.6f}")

Top 5 indexes by mean_recall_void:
Indexes: [6, 13, 11, 9, 14]
Corresponding configurations and values:
  Index 6: 3s_no = 0.645502
  Index 13: 5s_0.5 = 0.627965
  Index 11: 4s_0.8 = 0.616852
  Index 9: 4s_no = 0.615924
  Index 14: 5s_0.8 = 0.603315

All indexes sorted by mean_recall_void (highest to lowest):
Indexes: [6, 13, 11, 9, 14, 7, 12, 8, 4, 0, 10, 3, 5, 1, 2]

Indexes with mean_recall_void > 0.55:
Indexes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
Corresponding configurations and values:
  Index 0: 1s_no = 0.584295
  Index 1: 1s_0.5 = 0.560244
  Index 2: 1s_0.8 = 0.556134
  Index 3: 2s_no = 0.574033
  Index 4: 2s_0.5 = 0.585692
  Index 5: 2s_0.8 = 0.565030
  Index 6: 3s_no = 0.645502
  Index 7: 3s_0.5 = 0.594883
  Index 8: 3s_0.8 = 0.587149
  Index 9: 4s_no = 0.615924
  Index 10: 4s_0.5 = 0.582663
  Index 11: 4s_0.8 = 0.616852
  Index 12: 5s_no = 0.587673
  Index 13: 5s_0.5 = 0.627965
  Index 14: 5s_0.8 = 0.603315

Highest mean_recall_void:
Index 6: 3s_no = 0.645502

In [15]:
# Get indexes of top N values using nlargest()
def get_top_n_indexes(df, column, n=5):
    """Get indexes of top N values in specified column"""
    top_indexes = df.nlargest(n, column).index.tolist()
    return top_indexes

# Get indexes using argsort() for all values (sorted)
def get_all_indexes_sorted(df, column):
    """Get all indexes sorted by column values (highest to lowest)"""
    sorted_indexes = df[column].argsort()[::-1].tolist()
    return sorted_indexes

# Get indexes above a certain threshold
def get_indexes_above_threshold(df, column, threshold):
    """Get indexes where column values are above threshold"""
    above_threshold_indexes = df[df[column] > threshold].index.tolist()
    return above_threshold_indexes


# print("DataFrame:")
# print(df)
# print("\n" + "="*50)

# Get top 5 indexes
top_5_indexes = get_top_n_indexes(df, 'mean_accuracy', 5)
print(f"\nTop 5 indexes by mean_accuracy:")
print(f"Indexes: {top_5_indexes}")
print("Corresponding configurations and values:")
for idx in top_5_indexes:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_accuracy']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Get all indexes sorted
all_sorted_indexes = get_all_indexes_sorted(df, 'mean_accuracy')
print(f"\nAll indexes sorted by mean_accuracy (highest to lowest):")
print(f"Indexes: {all_sorted_indexes}")

# Get indexes above threshold (e.g., 0.55)
threshold = 0.55
above_threshold = get_indexes_above_threshold(df, 'mean_accuracy', threshold)
print(f"\nIndexes with mean_accuracy > {threshold}:")
print(f"Indexes: {above_threshold}")
print("Corresponding configurations and values:")
for idx in above_threshold:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_accuracy']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Highest value index
max_index = df['mean_accuracy'].idxmax()
max_value = df.loc[max_index, 'mean_accuracy']
max_config = df.loc[max_index, 'config']
print(f"\nHighest mean_accuracy:")
print(f"Index {max_index}: {max_config} = {max_value:.6f}")

Top 5 indexes by mean_accuracy:
Indexes: [6, 10, 13, 12, 4]
Corresponding configurations and values:
  Index 6: 3s_no = 0.720957
  Index 10: 4s_0.5 = 0.712872
  Index 13: 5s_0.5 = 0.712109
  Index 12: 5s_no = 0.711004
  Index 4: 2s_0.5 = 0.707857

All indexes sorted by mean_accuracy (highest to lowest):
Indexes: [6, 10, 13, 12, 4, 9, 11, 8, 3, 7, 14, 5, 0, 1, 2]

Indexes with mean_accuracy > 0.55:
Indexes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
Corresponding configurations and values:
  Index 0: 1s_no = 0.696674
  Index 1: 1s_0.5 = 0.694995
  Index 2: 1s_0.8 = 0.690141
  Index 3: 2s_no = 0.702500
  Index 4: 2s_0.5 = 0.707857
  Index 5: 2s_0.8 = 0.698890
  Index 6: 3s_no = 0.720957
  Index 7: 3s_0.5 = 0.699673
  Index 8: 3s_0.8 = 0.702866
  Index 9: 4s_no = 0.704053
  Index 10: 4s_0.5 = 0.712872
  Index 11: 4s_0.8 = 0.703445
  Index 12: 5s_no = 0.711004
  Index 13: 5s_0.5 = 0.712109
  Index 14: 5s_0.8 = 0.699304

Highest mean_accuracy:
Index 6: 3s_no = 0.720957

## Oversample

In [16]:
mean_accuracy = []
std_accuracy = []
mean_recall_void = []
std_recall_void = []
for win_data, data in xgb_results.items(): 
    data_ = data["oversample_smote"]
    
    mean_accuracy.append(data_['mean_accuracy'])
    std_accuracy.append(data_['std_accuracy'])
    mean_recall_void.append(data_['mean_recall_minority'])
    std_recall_void.append(data_['std_recall_minority'])

indexes = xgb_results.keys()
results = {
    'config': indexes,
    'mean_accuracy': mean_accuracy,
    'std_accuracy': std_accuracy,
    'mean_recall_void': mean_recall_void,
    'std_recall_void': std_recall_void
} 
    
df = pd.DataFrame(results)

In [17]:
df

    config  mean_accuracy  std_accuracy  mean_recall_void  std_recall_void
0    1s_no       0.681027      0.081234          0.643859         0.122816
1   1s_0.5       0.688788      0.104172          0.620013         0.175888
2   1s_0.8       0.690973      0.093437          0.603747         0.111990
3    2s_no       0.709178      0.095142          0.640007         0.154419
4   2s_0.5       0.702243      0.090026          0.635381         0.119442
5   2s_0.8       0.699701      0.087426          0.609286         0.133879
6    3s_no       0.718280      0.098301          0.679306         0.149492
7   3s_0.5       0.705527      0.098061          0.649407         0.130221
8   3s_0.8       0.703178      0.124266          0.635121         0.159670
9    4s_no       0.696070      0.095192          0.673510         0.171368
10  4s_0.5       0.701797      0.100233          0.620293         0.183728
11  4s_0.8       0.710784      0.117955          0.638643         0.168240
12   5s_no       0.705622      0.113034          0.650982         0.176695
13  5s_0.5       0.718930      0.124729          0.684423         0.178110
14  5s_0.8       0.701924      0.125320          0.632997         0.165942

In [18]:
# Get indexes of top N values using nlargest()
def get_top_n_indexes(df, column, n=5):
    """Get indexes of top N values in specified column"""
    top_indexes = df.nlargest(n, column).index.tolist()
    return top_indexes

# Get indexes using argsort() for all values (sorted)
def get_all_indexes_sorted(df, column):
    """Get all indexes sorted by column values (highest to lowest)"""
    sorted_indexes = df[column].argsort()[::-1].tolist()
    return sorted_indexes

# Get indexes above a certain threshold
def get_indexes_above_threshold(df, column, threshold):
    """Get indexes where column values are above threshold"""
    above_threshold_indexes = df[df[column] > threshold].index.tolist()
    return above_threshold_indexes


# print("DataFrame:")
# print(df)
# print("\n" + "="*50)

# Get top 5 indexes
top_5_indexes = get_top_n_indexes(df, 'mean_recall_void', 5)
print(f"\nTop 5 indexes by mean_recall_void:")
print(f"Indexes: {top_5_indexes}")
print("Corresponding configurations and values:")
for idx in top_5_indexes:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_recall_void']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Get all indexes sorted
all_sorted_indexes = get_all_indexes_sorted(df, 'mean_recall_void')
print(f"\nAll indexes sorted by mean_recall_void (highest to lowest):")
print(f"Indexes: {all_sorted_indexes}")

# Get indexes above threshold (e.g., 0.55)
threshold = 0.55
above_threshold = get_indexes_above_threshold(df, 'mean_recall_void', threshold)
print(f"\nIndexes with mean_recall_void > {threshold}:")
print(f"Indexes: {above_threshold}")
print("Corresponding configurations and values:")
for idx in above_threshold:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_recall_void']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Highest value index
max_index = df['mean_recall_void'].idxmax()
max_value = df.loc[max_index, 'mean_recall_void']
max_config = df.loc[max_index, 'config']
print(f"\nHighest mean_recall_void:")
print(f"Index {max_index}: {max_config} = {max_value:.6f}")

Top 5 indexes by mean_recall_void:
Indexes: [13, 6, 9, 12, 7]
Corresponding configurations and values:
  Index 13: 5s_0.5 = 0.684423
  Index 6: 3s_no = 0.679306
  Index 9: 4s_no = 0.673510
  Index 12: 5s_no = 0.650982
  Index 7: 3s_0.5 = 0.649407

All indexes sorted by mean_recall_void (highest to lowest):
Indexes: [13, 6, 9, 12, 7, 0, 3, 11, 4, 8, 14, 10, 1, 5, 2]

Indexes with mean_recall_void > 0.55:
Indexes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
Corresponding configurations and values:
  Index 0: 1s_no = 0.643859
  Index 1: 1s_0.5 = 0.620013
  Index 2: 1s_0.8 = 0.603747
  Index 3: 2s_no = 0.640007
  Index 4: 2s_0.5 = 0.635381
  Index 5: 2s_0.8 = 0.609286
  Index 6: 3s_no = 0.679306
  Index 7: 3s_0.5 = 0.649407
  Index 8: 3s_0.8 = 0.635121
  Index 9: 4s_no = 0.673510
  Index 10: 4s_0.5 = 0.620293
  Index 11: 4s_0.8 = 0.638643
  Index 12: 5s_no = 0.650982
  Index 13: 5s_0.5 = 0.684423
  Index 14: 5s_0.8 = 0.632997

Highest mean_recall_void:
Index 13: 5s_0.5 = 0.684423

In [19]:
# Get indexes of top N values using nlargest()
def get_top_n_indexes(df, column, n=5):
    """Get indexes of top N values in specified column"""
    top_indexes = df.nlargest(n, column).index.tolist()
    return top_indexes

# Get indexes using argsort() for all values (sorted)
def get_all_indexes_sorted(df, column):
    """Get all indexes sorted by column values (highest to lowest)"""
    sorted_indexes = df[column].argsort()[::-1].tolist()
    return sorted_indexes

# Get indexes above a certain threshold
def get_indexes_above_threshold(df, column, threshold):
    """Get indexes where column values are above threshold"""
    above_threshold_indexes = df[df[column] > threshold].index.tolist()
    return above_threshold_indexes


# print("DataFrame:")
# print(df)
# print("\n" + "="*50)

# Get top 5 indexes
top_5_indexes = get_top_n_indexes(df, 'mean_accuracy', 5)
print(f"\nTop 5 indexes by mean_accuracy:")
print(f"Indexes: {top_5_indexes}")
print("Corresponding configurations and values:")
for idx in top_5_indexes:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_accuracy']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Get all indexes sorted
all_sorted_indexes = get_all_indexes_sorted(df, 'mean_accuracy')
print(f"\nAll indexes sorted by mean_accuracy (highest to lowest):")
print(f"Indexes: {all_sorted_indexes}")

# Get indexes above threshold (e.g., 0.55)
threshold = 0.55
above_threshold = get_indexes_above_threshold(df, 'mean_accuracy', threshold)
print(f"\nIndexes with mean_accuracy > {threshold}:")
print(f"Indexes: {above_threshold}")
print("Corresponding configurations and values:")
for idx in above_threshold:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_accuracy']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Highest value index
max_index = df['mean_accuracy'].idxmax()
max_value = df.loc[max_index, 'mean_accuracy']
max_config = df.loc[max_index, 'config']
print(f"\nHighest mean_accuracy:")
print(f"Index {max_index}: {max_config} = {max_value:.6f}")

Top 5 indexes by mean_accuracy:
Indexes: [13, 6, 11, 3, 12]
Corresponding configurations and values:
  Index 13: 5s_0.5 = 0.718930
  Index 6: 3s_no = 0.718280
  Index 11: 4s_0.8 = 0.710784
  Index 3: 2s_no = 0.709178
  Index 12: 5s_no = 0.705622

All indexes sorted by mean_accuracy (highest to lowest):
Indexes: [13, 6, 11, 3, 12, 7, 8, 4, 14, 10, 5, 9, 2, 1, 0]

Indexes with mean_accuracy > 0.55:
Indexes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
Corresponding configurations and values:
  Index 0: 1s_no = 0.681027
  Index 1: 1s_0.5 = 0.688788
  Index 2: 1s_0.8 = 0.690973
  Index 3: 2s_no = 0.709178
  Index 4: 2s_0.5 = 0.702243
  Index 5: 2s_0.8 = 0.699701
  Index 6: 3s_no = 0.718280
  Index 7: 3s_0.5 = 0.705527
  Index 8: 3s_0.8 = 0.703178
  Index 9: 4s_no = 0.696070
  Index 10: 4s_0.5 = 0.701797
  Index 11: 4s_0.8 = 0.710784
  Index 12: 5s_no = 0.705622
  Index 13: 5s_0.5 = 0.718930
  Index 14: 5s_0.8 = 0.701924

Highest mean_accuracy:
Index 13: 5s_0.5 = 0.718930

## Undersample

In [20]:
mean_accuracy = []
std_accuracy = []
mean_recall_void = []
std_recall_void = []
for win_data, data in xgb_results.items(): 
    data_ = data["undersample_tomek_links"]
    
    mean_accuracy.append(data_['mean_accuracy'])
    std_accuracy.append(data_['std_accuracy'])
    mean_recall_void.append(data_['mean_recall_minority'])
    std_recall_void.append(data_['std_recall_minority'])

indexes = xgb_results.keys()
results = {
    'config': indexes,
    'mean_accuracy': mean_accuracy,
    'std_accuracy': std_accuracy,
    'mean_recall_void': mean_recall_void,
    'std_recall_void': std_recall_void
} 
    
df = pd.DataFrame(results)

In [21]:
df

    config  mean_accuracy  std_accuracy  mean_recall_void  std_recall_void
0    1s_no       0.696666      0.086092          0.664426         0.119176
1   1s_0.5       0.694143      0.098182          0.624990         0.154157
2   1s_0.8       0.691689      0.092105          0.582921         0.118568
3    2s_no       0.709835      0.097567          0.645629         0.152785
4   2s_0.5       0.708011      0.086572          0.646622         0.118084
5   2s_0.8       0.696194      0.091546          0.578920         0.128270
6    3s_no       0.729360      0.103412          0.722786         0.151399
7   3s_0.5       0.722566      0.086380          0.692548         0.139620
8   3s_0.8       0.712372      0.119903          0.621884         0.163393
9    4s_no       0.711983      0.095680          0.701114         0.165721
10  4s_0.5       0.718951      0.100997          0.653520         0.169746
11  4s_0.8       0.701403      0.129903          0.622519         0.188816
12   5s_no       0.714753      0.119985          0.739543         0.207243
13  5s_0.5       0.728843      0.116490          0.715291         0.187372
14  5s_0.8       0.708198      0.124890          0.632830         0.189748

In [22]:
# Get indexes of top N values using nlargest()
def get_top_n_indexes(df, column, n=5):
    """Get indexes of top N values in specified column"""
    top_indexes = df.nlargest(n, column).index.tolist()
    return top_indexes

# Get indexes using argsort() for all values (sorted)
def get_all_indexes_sorted(df, column):
    """Get all indexes sorted by column values (highest to lowest)"""
    sorted_indexes = df[column].argsort()[::-1].tolist()
    return sorted_indexes

# Get indexes above a certain threshold
def get_indexes_above_threshold(df, column, threshold):
    """Get indexes where column values are above threshold"""
    above_threshold_indexes = df[df[column] > threshold].index.tolist()
    return above_threshold_indexes


# print("DataFrame:")
# print(df)
# print("\n" + "="*50)

# Get top 5 indexes
top_5_indexes = get_top_n_indexes(df, 'mean_recall_void', 5)
print(f"\nTop 5 indexes by mean_recall_void:")
print(f"Indexes: {top_5_indexes}")
print("Corresponding configurations and values:")
for idx in top_5_indexes:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_recall_void']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Get all indexes sorted
all_sorted_indexes = get_all_indexes_sorted(df, 'mean_recall_void')
print(f"\nAll indexes sorted by mean_recall_void (highest to lowest):")
print(f"Indexes: {all_sorted_indexes}")

# Get indexes above threshold (e.g., 0.55)
threshold = 0.55
above_threshold = get_indexes_above_threshold(df, 'mean_recall_void', threshold)
print(f"\nIndexes with mean_recall_void > {threshold}:")
print(f"Indexes: {above_threshold}")
print("Corresponding configurations and values:")
for idx in above_threshold:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_recall_void']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Highest value index
max_index = df['mean_recall_void'].idxmax()
max_value = df.loc[max_index, 'mean_recall_void']
max_config = df.loc[max_index, 'config']
print(f"\nHighest mean_recall_void:")
print(f"Index {max_index}: {max_config} = {max_value:.6f}")

Top 5 indexes by mean_recall_void:
Indexes: [12, 6, 13, 9, 7]
Corresponding configurations and values:
  Index 12: 5s_no = 0.739543
  Index 6: 3s_no = 0.722786
  Index 13: 5s_0.5 = 0.715291
  Index 9: 4s_no = 0.701114
  Index 7: 3s_0.5 = 0.692548

All indexes sorted by mean_recall_void (highest to lowest):
Indexes: [12, 6, 13, 9, 7, 0, 10, 4, 3, 14, 1, 11, 8, 2, 5]

Indexes with mean_recall_void > 0.55:
Indexes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
Corresponding configurations and values:
  Index 0: 1s_no = 0.664426
  Index 1: 1s_0.5 = 0.624990
  Index 2: 1s_0.8 = 0.582921
  Index 3: 2s_no = 0.645629
  Index 4: 2s_0.5 = 0.646622
  Index 5: 2s_0.8 = 0.578920
  Index 6: 3s_no = 0.722786
  Index 7: 3s_0.5 = 0.692548
  Index 8: 3s_0.8 = 0.621884
  Index 9: 4s_no = 0.701114
  Index 10: 4s_0.5 = 0.653520
  Index 11: 4s_0.8 = 0.622519
  Index 12: 5s_no = 0.739543
  Index 13: 5s_0.5 = 0.715291
  Index 14: 5s_0.8 = 0.632830

Highest mean_recall_void:
Index 12: 5s_no = 0.739543

In [23]:
# Get indexes of top N values using nlargest()
def get_top_n_indexes(df, column, n=5):
    """Get indexes of top N values in specified column"""
    top_indexes = df.nlargest(n, column).index.tolist()
    return top_indexes

# Get indexes using argsort() for all values (sorted)
def get_all_indexes_sorted(df, column):
    """Get all indexes sorted by column values (highest to lowest)"""
    sorted_indexes = df[column].argsort()[::-1].tolist()
    return sorted_indexes

# Get indexes above a certain threshold
def get_indexes_above_threshold(df, column, threshold):
    """Get indexes where column values are above threshold"""
    above_threshold_indexes = df[df[column] > threshold].index.tolist()
    return above_threshold_indexes


# print("DataFrame:")
# print(df)
# print("\n" + "="*50)

# Get top 5 indexes
top_5_indexes = get_top_n_indexes(df, 'mean_accuracy', 5)
print(f"\nTop 5 indexes by mean_accuracy:")
print(f"Indexes: {top_5_indexes}")
print("Corresponding configurations and values:")
for idx in top_5_indexes:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_accuracy']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Get all indexes sorted
all_sorted_indexes = get_all_indexes_sorted(df, 'mean_accuracy')
print(f"\nAll indexes sorted by mean_accuracy (highest to lowest):")
print(f"Indexes: {all_sorted_indexes}")

# Get indexes above threshold (e.g., 0.55)
threshold = 0.55
above_threshold = get_indexes_above_threshold(df, 'mean_accuracy', threshold)
print(f"\nIndexes with mean_accuracy > {threshold}:")
print(f"Indexes: {above_threshold}")
print("Corresponding configurations and values:")
for idx in above_threshold:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_accuracy']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Highest value index
max_index = df['mean_accuracy'].idxmax()
max_value = df.loc[max_index, 'mean_accuracy']
max_config = df.loc[max_index, 'config']
print(f"\nHighest mean_accuracy:")
print(f"Index {max_index}: {max_config} = {max_value:.6f}")

Top 5 indexes by mean_accuracy:
Indexes: [6, 13, 7, 10, 12]
Corresponding configurations and values:
  Index 6: 3s_no = 0.729360
  Index 13: 5s_0.5 = 0.728843
  Index 7: 3s_0.5 = 0.722566
  Index 10: 4s_0.5 = 0.718951
  Index 12: 5s_no = 0.714753

All indexes sorted by mean_accuracy (highest to lowest):
Indexes: [6, 13, 7, 10, 12, 8, 9, 3, 14, 4, 11, 0, 5, 1, 2]

Indexes with mean_accuracy > 0.55:
Indexes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
Corresponding configurations and values:
  Index 0: 1s_no = 0.696666
  Index 1: 1s_0.5 = 0.694143
  Index 2: 1s_0.8 = 0.691689
  Index 3: 2s_no = 0.709835
  Index 4: 2s_0.5 = 0.708011
  Index 5: 2s_0.8 = 0.696194
  Index 6: 3s_no = 0.729360
  Index 7: 3s_0.5 = 0.722566
  Index 8: 3s_0.8 = 0.712372
  Index 9: 4s_no = 0.711983
  Index 10: 4s_0.5 = 0.718951
  Index 11: 4s_0.8 = 0.701403
  Index 12: 5s_no = 0.714753
  Index 13: 5s_0.5 = 0.728843
  Index 14: 5s_0.8 = 0.708198

Highest mean_accuracy:
Index 6: 3s_no = 0.729360

## Combined Smote Tomek

In [24]:
mean_accuracy = []
std_accuracy = []
mean_recall_void = []
std_recall_void = []
for win_data, data in xgb_results.items(): 
    data_ = data["combined_smote_tomek"]
    
    mean_accuracy.append(data_['mean_accuracy'])
    std_accuracy.append(data_['std_accuracy'])
    mean_recall_void.append(data_['mean_recall_minority'])
    std_recall_void.append(data_['std_recall_minority'])

indexes = xgb_results.keys()
results = {
    'config': indexes,
    'mean_accuracy': mean_accuracy,
    'std_accuracy': std_accuracy,
    'mean_recall_void': mean_recall_void,
    'std_recall_void': std_recall_void
} 
    
df = pd.DataFrame(results)

In [25]:
df

    config  mean_accuracy  std_accuracy  mean_recall_void  std_recall_void
0    1s_no       0.689610      0.084199          0.640372         0.128961
1   1s_0.5       0.695662      0.099895          0.627042         0.166320
2   1s_0.8       0.689050      0.095343          0.605553         0.115381
3    2s_no       0.709974      0.095309          0.626821         0.148867
4   2s_0.5       0.702975      0.094693          0.636413         0.132965
5   2s_0.8       0.702903      0.090809          0.609137         0.130602
6    3s_no       0.713299      0.104556          0.676521         0.179121
7   3s_0.5       0.696952      0.086830          0.651692         0.121440
8   3s_0.8       0.702490      0.120886          0.626754         0.163053
9    4s_no       0.692734      0.121073          0.649477         0.191128
10  4s_0.5       0.707831      0.093471          0.644156         0.175177
11  4s_0.8       0.699142      0.128422          0.622164         0.175544
12   5s_no       0.718884      0.108699          0.694972         0.179292
13  5s_0.5       0.723701      0.097371          0.708796         0.170162
14  5s_0.8       0.703433      0.125588          0.643250         0.179859

In [26]:
# Get indexes of top N values using nlargest()
def get_top_n_indexes(df, column, n=5):
    """Get indexes of top N values in specified column"""
    top_indexes = df.nlargest(n, column).index.tolist()
    return top_indexes

# Get indexes using argsort() for all values (sorted)
def get_all_indexes_sorted(df, column):
    """Get all indexes sorted by column values (highest to lowest)"""
    sorted_indexes = df[column].argsort()[::-1].tolist()
    return sorted_indexes

# Get indexes above a certain threshold
def get_indexes_above_threshold(df, column, threshold):
    """Get indexes where column values are above threshold"""
    above_threshold_indexes = df[df[column] > threshold].index.tolist()
    return above_threshold_indexes


# print("DataFrame:")
# print(df)
# print("\n" + "="*50)

# Get top 5 indexes
top_5_indexes = get_top_n_indexes(df, 'mean_recall_void', 5)
print(f"\nTop 5 indexes by mean_recall_void:")
print(f"Indexes: {top_5_indexes}")
print("Corresponding configurations and values:")
for idx in top_5_indexes:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_recall_void']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Get all indexes sorted
all_sorted_indexes = get_all_indexes_sorted(df, 'mean_recall_void')
print(f"\nAll indexes sorted by mean_recall_void (highest to lowest):")
print(f"Indexes: {all_sorted_indexes}")

# Get indexes above threshold (e.g., 0.55)
threshold = 0.55
above_threshold = get_indexes_above_threshold(df, 'mean_recall_void', threshold)
print(f"\nIndexes with mean_recall_void > {threshold}:")
print(f"Indexes: {above_threshold}")
print("Corresponding configurations and values:")
for idx in above_threshold:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_recall_void']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Highest value index
max_index = df['mean_recall_void'].idxmax()
max_value = df.loc[max_index, 'mean_recall_void']
max_config = df.loc[max_index, 'config']
print(f"\nHighest mean_recall_void:")
print(f"Index {max_index}: {max_config} = {max_value:.6f}")

Top 5 indexes by mean_recall_void:
Indexes: [13, 12, 6, 7, 9]
Corresponding configurations and values:
  Index 13: 5s_0.5 = 0.708796
  Index 12: 5s_no = 0.694972
  Index 6: 3s_no = 0.676521
  Index 7: 3s_0.5 = 0.651692
  Index 9: 4s_no = 0.649477

All indexes sorted by mean_recall_void (highest to lowest):
Indexes: [13, 12, 6, 7, 9, 10, 14, 0, 4, 1, 3, 8, 11, 5, 2]

Indexes with mean_recall_void > 0.55:
Indexes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
Corresponding configurations and values:
  Index 0: 1s_no = 0.640372
  Index 1: 1s_0.5 = 0.627042
  Index 2: 1s_0.8 = 0.605553
  Index 3: 2s_no = 0.626821
  Index 4: 2s_0.5 = 0.636413
  Index 5: 2s_0.8 = 0.609137
  Index 6: 3s_no = 0.676521
  Index 7: 3s_0.5 = 0.651692
  Index 8: 3s_0.8 = 0.626754
  Index 9: 4s_no = 0.649477
  Index 10: 4s_0.5 = 0.644156
  Index 11: 4s_0.8 = 0.622164
  Index 12: 5s_no = 0.694972
  Index 13: 5s_0.5 = 0.708796
  Index 14: 5s_0.8 = 0.643250

Highest mean_recall_void:
Index 13: 5s_0.5 = 0.708796

In [27]:
# Get indexes of top N values using nlargest()
def get_top_n_indexes(df, column, n=5):
    """Get indexes of top N values in specified column"""
    top_indexes = df.nlargest(n, column).index.tolist()
    return top_indexes

# Get indexes using argsort() for all values (sorted)
def get_all_indexes_sorted(df, column):
    """Get all indexes sorted by column values (highest to lowest)"""
    sorted_indexes = df[column].argsort()[::-1].tolist()
    return sorted_indexes

# Get indexes above a certain threshold
def get_indexes_above_threshold(df, column, threshold):
    """Get indexes where column values are above threshold"""
    above_threshold_indexes = df[df[column] > threshold].index.tolist()
    return above_threshold_indexes


# print("DataFrame:")
# print(df)
# print("\n" + "="*50)

# Get top 5 indexes
top_5_indexes = get_top_n_indexes(df, 'mean_accuracy', 5)
print(f"\nTop 5 indexes by mean_accuracy:")
print(f"Indexes: {top_5_indexes}")
print("Corresponding configurations and values:")
for idx in top_5_indexes:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_accuracy']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Get all indexes sorted
all_sorted_indexes = get_all_indexes_sorted(df, 'mean_accuracy')
print(f"\nAll indexes sorted by mean_accuracy (highest to lowest):")
print(f"Indexes: {all_sorted_indexes}")

# Get indexes above threshold (e.g., 0.55)
threshold = 0.55
above_threshold = get_indexes_above_threshold(df, 'mean_accuracy', threshold)
print(f"\nIndexes with mean_accuracy > {threshold}:")
print(f"Indexes: {above_threshold}")
print("Corresponding configurations and values:")
for idx in above_threshold:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_accuracy']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Highest value index
max_index = df['mean_accuracy'].idxmax()
max_value = df.loc[max_index, 'mean_accuracy']
max_config = df.loc[max_index, 'config']
print(f"\nHighest mean_accuracy:")
print(f"Index {max_index}: {max_config} = {max_value:.6f}")

Top 5 indexes by mean_accuracy:
Indexes: [13, 12, 6, 3, 10]
Corresponding configurations and values:
  Index 13: 5s_0.5 = 0.723701
  Index 12: 5s_no = 0.718884
  Index 6: 3s_no = 0.713299
  Index 3: 2s_no = 0.709974
  Index 10: 4s_0.5 = 0.707831

All indexes sorted by mean_accuracy (highest to lowest):
Indexes: [13, 12, 6, 3, 10, 14, 4, 5, 8, 11, 7, 1, 9, 0, 2]

Indexes with mean_accuracy > 0.55:
Indexes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
Corresponding configurations and values:
  Index 0: 1s_no = 0.689610
  Index 1: 1s_0.5 = 0.695662
  Index 2: 1s_0.8 = 0.689050
  Index 3: 2s_no = 0.709974
  Index 4: 2s_0.5 = 0.702975
  Index 5: 2s_0.8 = 0.702903
  Index 6: 3s_no = 0.713299
  Index 7: 3s_0.5 = 0.696952
  Index 8: 3s_0.8 = 0.702490
  Index 9: 4s_no = 0.692734
  Index 10: 4s_0.5 = 0.707831
  Index 11: 4s_0.8 = 0.699142
  Index 12: 5s_no = 0.718884
  Index 13: 5s_0.5 = 0.723701
  Index 14: 5s_0.8 = 0.703433

Highest mean_accuracy:
Index 13: 5s_0.5 = 0.723701