In [1]:
import pickle
import pandas as pd

In [2]:
with open('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/imb_files/xgb_imb_152.pkl', 'rb') as f:
    xgb_results = pickle.load(f)

## Baseline

In [3]:
mean_accuracy = []
std_accuracy = []
mean_recall_void = []
std_recall_void = []
for win_data, data in xgb_results.items(): 
    data_ = data["none"]
    
    mean_accuracy.append(data_['mean_accuracy'])
    std_accuracy.append(data_['std_accuracy'])
    mean_recall_void.append(data_['mean_recall_minority'])
    std_recall_void.append(data_['std_recall_minority'])

indexes = xgb_results.keys()
results = {
    'config': indexes,
    'mean_accuracy': mean_accuracy,
    'std_accuracy': std_accuracy,
    'mean_recall_void': mean_recall_void,
    'std_recall_void': std_recall_void
} 
    
df = pd.DataFrame(results)
# df = pd.DataFrame(results, index=indexes)

In [4]:
df

    config  mean_accuracy  std_accuracy  mean_recall_void  std_recall_void
0    1s_no       0.664465      0.052346          0.489750         0.091651
1   1s_0.5       0.655071      0.099311          0.497436         0.156331
2   1s_0.8       0.645579      0.090777          0.443470         0.161331
3    2s_no       0.677393      0.110861          0.532936         0.172471
4   2s_0.5       0.663800      0.075197          0.517359         0.108891
5   2s_0.8       0.668518      0.099937          0.502965         0.195699
6    3s_no       0.679405      0.110080          0.545158         0.160667
7   3s_0.5       0.670733      0.097877          0.540138         0.188921
8   3s_0.8       0.665264      0.101610          0.532399         0.175548
9    4s_no       0.663649      0.111596          0.563997         0.211709
10  4s_0.5       0.684024      0.094048          0.543233         0.198673
11  4s_0.8       0.669406      0.081680          0.586366         0.151283
12   5s_no       0.667099      0.124945          0.607754         0.242561
13  5s_0.5       0.684457      0.069761          0.602250         0.159067
14  5s_0.8       0.658715      0.103987          0.533421         0.187734

In [5]:
# Get indexes of top N values using nlargest()
def get_top_n_indexes(df, column, n=5):
    """Get indexes of top N values in specified column"""
    top_indexes = df.nlargest(n, column).index.tolist()
    return top_indexes

# Get indexes using argsort() for all values (sorted)
def get_all_indexes_sorted(df, column):
    """Get all indexes sorted by column values (highest to lowest)"""
    sorted_indexes = df[column].argsort()[::-1].tolist()
    return sorted_indexes

# Get indexes above a certain threshold
def get_indexes_above_threshold(df, column, threshold):
    """Get indexes where column values are above threshold"""
    above_threshold_indexes = df[df[column] > threshold].index.tolist()
    return above_threshold_indexes


# print("DataFrame:")
# print(df)
# print("\n" + "="*50)

# Get top 5 indexes
top_5_indexes = get_top_n_indexes(df, 'mean_recall_void', 5)
print(f"\nTop 5 indexes by mean_recall_void:")
print(f"Indexes: {top_5_indexes}")
print("Corresponding configurations and values:")
for idx in top_5_indexes:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_recall_void']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Get all indexes sorted
all_sorted_indexes = get_all_indexes_sorted(df, 'mean_recall_void')
print(f"\nAll indexes sorted by mean_recall_void (highest to lowest):")
print(f"Indexes: {all_sorted_indexes}")

# Get indexes above threshold (e.g., 0.55)
threshold = 0.55
above_threshold = get_indexes_above_threshold(df, 'mean_recall_void', threshold)
print(f"\nIndexes with mean_recall_void > {threshold}:")
print(f"Indexes: {above_threshold}")
print("Corresponding configurations and values:")
for idx in above_threshold:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_recall_void']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Highest value index
max_index = df['mean_recall_void'].idxmax()
max_value = df.loc[max_index, 'mean_recall_void']
max_config = df.loc[max_index, 'config']
print(f"\nHighest mean_recall_void:")
print(f"Index {max_index}: {max_config} = {max_value:.6f}")

Top 5 indexes by mean_recall_void:
Indexes: [12, 13, 11, 9, 6]
Corresponding configurations and values:
  Index 12: 5s_no = 0.607754
  Index 13: 5s_0.5 = 0.602250
  Index 11: 4s_0.8 = 0.586366
  Index 9: 4s_no = 0.563997
  Index 6: 3s_no = 0.545158

All indexes sorted by mean_recall_void (highest to lowest):
Indexes: [12, 13, 11, 9, 6, 10, 7, 14, 3, 8, 4, 5, 1, 0, 2]

Indexes with mean_recall_void > 0.55:
Indexes: [9, 11, 12, 13]
Corresponding configurations and values:
  Index 9: 4s_no = 0.563997
  Index 11: 4s_0.8 = 0.586366
  Index 12: 5s_no = 0.607754
  Index 13: 5s_0.5 = 0.602250

Highest mean_recall_void:
Index 12: 5s_no = 0.607754

In [6]:
# Get indexes of top N values using nlargest()
def get_top_n_indexes(df, column, n=5):
    """Get indexes of top N values in specified column"""
    top_indexes = df.nlargest(n, column).index.tolist()
    return top_indexes

# Get indexes using argsort() for all values (sorted)
def get_all_indexes_sorted(df, column):
    """Get all indexes sorted by column values (highest to lowest)"""
    sorted_indexes = df[column].argsort()[::-1].tolist()
    return sorted_indexes

# Get indexes above a certain threshold
def get_indexes_above_threshold(df, column, threshold):
    """Get indexes where column values are above threshold"""
    above_threshold_indexes = df[df[column] > threshold].index.tolist()
    return above_threshold_indexes


# print("DataFrame:")
# print(df)
# print("\n" + "="*50)

# Get top 5 indexes
top_5_indexes = get_top_n_indexes(df, 'mean_accuracy', 5)
print(f"\nTop 5 indexes by mean_accuracy:")
print(f"Indexes: {top_5_indexes}")
print("Corresponding configurations and values:")
for idx in top_5_indexes:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_accuracy']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Get all indexes sorted
all_sorted_indexes = get_all_indexes_sorted(df, 'mean_accuracy')
print(f"\nAll indexes sorted by mean_accuracy (highest to lowest):")
print(f"Indexes: {all_sorted_indexes}")

# Get indexes above threshold (e.g., 0.55)
threshold = 0.55
above_threshold = get_indexes_above_threshold(df, 'mean_accuracy', threshold)
print(f"\nIndexes with mean_accuracy > {threshold}:")
print(f"Indexes: {above_threshold}")
print("Corresponding configurations and values:")
for idx in above_threshold:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_accuracy']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Highest value index
max_index = df['mean_accuracy'].idxmax()
max_value = df.loc[max_index, 'mean_accuracy']
max_config = df.loc[max_index, 'config']
print(f"\nHighest mean_accuracy:")
print(f"Index {max_index}: {max_config} = {max_value:.6f}")

Top 5 indexes by mean_accuracy:
Indexes: [13, 10, 6, 3, 7]
Corresponding configurations and values:
  Index 13: 5s_0.5 = 0.684457
  Index 10: 4s_0.5 = 0.684024
  Index 6: 3s_no = 0.679405
  Index 3: 2s_no = 0.677393
  Index 7: 3s_0.5 = 0.670733

All indexes sorted by mean_accuracy (highest to lowest):
Indexes: [13, 10, 6, 3, 7, 11, 5, 12, 8, 0, 4, 9, 14, 1, 2]

Indexes with mean_accuracy > 0.55:
Indexes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
Corresponding configurations and values:
  Index 0: 1s_no = 0.664465
  Index 1: 1s_0.5 = 0.655071
  Index 2: 1s_0.8 = 0.645579
  Index 3: 2s_no = 0.677393
  Index 4: 2s_0.5 = 0.663800
  Index 5: 2s_0.8 = 0.668518
  Index 6: 3s_no = 0.679405
  Index 7: 3s_0.5 = 0.670733
  Index 8: 3s_0.8 = 0.665264
  Index 9: 4s_no = 0.663649
  Index 10: 4s_0.5 = 0.684024
  Index 11: 4s_0.8 = 0.669406
  Index 12: 5s_no = 0.667099
  Index 13: 5s_0.5 = 0.684457
  Index 14: 5s_0.8 = 0.658715

Highest mean_accuracy:
Index 13: 5s_0.5 = 0.684457

## Oversample

In [19]:
mean_accuracy = []
std_accuracy = []
mean_recall_void = []
std_recall_void = []
for win_data, data in xgb_results.items(): 
    data_ = data["oversample_smote"]
    
    mean_accuracy.append(data_['mean_accuracy'])
    std_accuracy.append(data_['std_accuracy'])
    mean_recall_void.append(data_['mean_recall_minority'])
    std_recall_void.append(data_['std_recall_minority'])

indexes = xgb_results.keys()
results = {
    'config': indexes,
    'mean_accuracy': mean_accuracy,
    'std_accuracy': std_accuracy,
    'mean_recall_void': mean_recall_void,
    'std_recall_void': std_recall_void
} 
    
df = pd.DataFrame(results)

In [8]:
df

    config  mean_accuracy  std_accuracy  mean_recall_void  std_recall_void
0    1s_no       0.674681      0.057997          0.577318         0.060692
1   1s_0.5       0.641621      0.101492          0.511253         0.154610
2   1s_0.8       0.639214      0.095709          0.472776         0.164199
3    2s_no       0.678128      0.115291          0.566110         0.191854
4   2s_0.5       0.676273      0.072435          0.572780         0.090226
5   2s_0.8       0.668584      0.107972          0.544227         0.191317
6    3s_no       0.676702      0.115646          0.597519         0.125479
7   3s_0.5       0.670237      0.085509          0.584122         0.192612
8   3s_0.8       0.660605      0.102743          0.549026         0.161125
9    4s_no       0.670132      0.131433          0.588355         0.243166
10  4s_0.5       0.660734      0.104970          0.554037         0.170982
11  4s_0.8       0.652178      0.091665          0.567901         0.160440
12   5s_no       0.682040      0.108056          0.611709         0.228809
13  5s_0.5       0.676039      0.066513          0.630000         0.152308
14  5s_0.8       0.671806      0.116838          0.589734         0.190082

In [20]:
# Get indexes of top N values using nlargest()
def get_top_n_indexes(df, column, n=5):
    """Get indexes of top N values in specified column"""
    top_indexes = df.nlargest(n, column).index.tolist()
    return top_indexes

# Get indexes using argsort() for all values (sorted)
def get_all_indexes_sorted(df, column):
    """Get all indexes sorted by column values (highest to lowest)"""
    sorted_indexes = df[column].argsort()[::-1].tolist()
    return sorted_indexes

# Get indexes above a certain threshold
def get_indexes_above_threshold(df, column, threshold):
    """Get indexes where column values are above threshold"""
    above_threshold_indexes = df[df[column] > threshold].index.tolist()
    return above_threshold_indexes


# print("DataFrame:")
# print(df)
# print("\n" + "="*50)

# Get top 5 indexes
top_5_indexes = get_top_n_indexes(df, 'mean_recall_void', 5)
print(f"\nTop 5 indexes by mean_recall_void:")
print(f"Indexes: {top_5_indexes}")
print("Corresponding configurations and values:")
for idx in top_5_indexes:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_recall_void']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Get all indexes sorted
all_sorted_indexes = get_all_indexes_sorted(df, 'mean_recall_void')
print(f"\nAll indexes sorted by mean_recall_void (highest to lowest):")
print(f"Indexes: {all_sorted_indexes}")

# Get indexes above threshold (e.g., 0.55)
threshold = 0.55
above_threshold = get_indexes_above_threshold(df, 'mean_recall_void', threshold)
print(f"\nIndexes with mean_recall_void > {threshold}:")
print(f"Indexes: {above_threshold}")
print("Corresponding configurations and values:")
for idx in above_threshold:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_recall_void']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Highest value index
max_index = df['mean_recall_void'].idxmax()
max_value = df.loc[max_index, 'mean_recall_void']
max_config = df.loc[max_index, 'config']
print(f"\nHighest mean_recall_void:")
print(f"Index {max_index}: {max_config} = {max_value:.6f}")

Top 5 indexes by mean_recall_void:
Indexes: [13, 12, 6, 14, 9]
Corresponding configurations and values:
  Index 13: 5s_0.5 = 0.630000
  Index 12: 5s_no = 0.611709
  Index 6: 3s_no = 0.597519
  Index 14: 5s_0.8 = 0.589734
  Index 9: 4s_no = 0.588355

All indexes sorted by mean_recall_void (highest to lowest):
Indexes: [13, 12, 6, 14, 9, 7, 0, 4, 11, 3, 10, 8, 5, 1, 2]

Indexes with mean_recall_void > 0.55:
Indexes: [0, 3, 4, 6, 7, 9, 10, 11, 12, 13, 14]
Corresponding configurations and values:
  Index 0: 1s_no = 0.577318
  Index 3: 2s_no = 0.566110
  Index 4: 2s_0.5 = 0.572780
  Index 6: 3s_no = 0.597519
  Index 7: 3s_0.5 = 0.584122
  Index 9: 4s_no = 0.588355
  Index 10: 4s_0.5 = 0.554037
  Index 11: 4s_0.8 = 0.567901
  Index 12: 5s_no = 0.611709
  Index 13: 5s_0.5 = 0.630000
  Index 14: 5s_0.8 = 0.589734

Highest mean_recall_void:
Index 13: 5s_0.5 = 0.630000

In [10]:
# Get indexes of top N values using nlargest()
def get_top_n_indexes(df, column, n=5):
    """Get indexes of top N values in specified column"""
    top_indexes = df.nlargest(n, column).index.tolist()
    return top_indexes

# Get indexes using argsort() for all values (sorted)
def get_all_indexes_sorted(df, column):
    """Get all indexes sorted by column values (highest to lowest)"""
    sorted_indexes = df[column].argsort()[::-1].tolist()
    return sorted_indexes

# Get indexes above a certain threshold
def get_indexes_above_threshold(df, column, threshold):
    """Get indexes where column values are above threshold"""
    above_threshold_indexes = df[df[column] > threshold].index.tolist()
    return above_threshold_indexes


# print("DataFrame:")
# print(df)
# print("\n" + "="*50)

# Get top 5 indexes
top_5_indexes = get_top_n_indexes(df, 'mean_accuracy', 5)
print(f"\nTop 5 indexes by mean_accuracy:")
print(f"Indexes: {top_5_indexes}")
print("Corresponding configurations and values:")
for idx in top_5_indexes:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_accuracy']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Get all indexes sorted
all_sorted_indexes = get_all_indexes_sorted(df, 'mean_accuracy')
print(f"\nAll indexes sorted by mean_accuracy (highest to lowest):")
print(f"Indexes: {all_sorted_indexes}")

# Get indexes above threshold (e.g., 0.55)
threshold = 0.55
above_threshold = get_indexes_above_threshold(df, 'mean_accuracy', threshold)
print(f"\nIndexes with mean_accuracy > {threshold}:")
print(f"Indexes: {above_threshold}")
print("Corresponding configurations and values:")
for idx in above_threshold:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_accuracy']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Highest value index
max_index = df['mean_accuracy'].idxmax()
max_value = df.loc[max_index, 'mean_accuracy']
max_config = df.loc[max_index, 'config']
print(f"\nHighest mean_accuracy:")
print(f"Index {max_index}: {max_config} = {max_value:.6f}")

Top 5 indexes by mean_accuracy:
Indexes: [12, 3, 6, 4, 13]
Corresponding configurations and values:
  Index 12: 5s_no = 0.682040
  Index 3: 2s_no = 0.678128
  Index 6: 3s_no = 0.676702
  Index 4: 2s_0.5 = 0.676273
  Index 13: 5s_0.5 = 0.676039

All indexes sorted by mean_accuracy (highest to lowest):
Indexes: [12, 3, 6, 4, 13, 0, 14, 7, 9, 5, 10, 8, 11, 1, 2]

Indexes with mean_accuracy > 0.55:
Indexes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
Corresponding configurations and values:
  Index 0: 1s_no = 0.674681
  Index 1: 1s_0.5 = 0.641621
  Index 2: 1s_0.8 = 0.639214
  Index 3: 2s_no = 0.678128
  Index 4: 2s_0.5 = 0.676273
  Index 5: 2s_0.8 = 0.668584
  Index 6: 3s_no = 0.676702
  Index 7: 3s_0.5 = 0.670237
  Index 8: 3s_0.8 = 0.660605
  Index 9: 4s_no = 0.670132
  Index 10: 4s_0.5 = 0.660734
  Index 11: 4s_0.8 = 0.652178
  Index 12: 5s_no = 0.682040
  Index 13: 5s_0.5 = 0.676039
  Index 14: 5s_0.8 = 0.671806

Highest mean_accuracy:
Index 12: 5s_no = 0.682040

## Undersample

In [11]:
mean_accuracy = []
std_accuracy = []
mean_recall_void = []
std_recall_void = []
for win_data, data in xgb_results.items(): 
    data_ = data["undersample_tomek_links"]
    
    mean_accuracy.append(data_['mean_accuracy'])
    std_accuracy.append(data_['std_accuracy'])
    mean_recall_void.append(data_['mean_recall_minority'])
    std_recall_void.append(data_['std_recall_minority'])

indexes = xgb_results.keys()
results = {
    'config': indexes,
    'mean_accuracy': mean_accuracy,
    'std_accuracy': std_accuracy,
    'mean_recall_void': mean_recall_void,
    'std_recall_void': std_recall_void
} 
    
df = pd.DataFrame(results)

In [12]:
df

    config  mean_accuracy  std_accuracy  mean_recall_void  std_recall_void
0    1s_no       0.674732      0.068891          0.560160         0.092615
1   1s_0.5       0.653809      0.099581          0.546279         0.125550
2   1s_0.8       0.639212      0.101709          0.455455         0.161599
3    2s_no       0.697760      0.114540          0.588797         0.159729
4   2s_0.5       0.685279      0.066162          0.576713         0.099448
5   2s_0.8       0.667908      0.120280          0.526918         0.197850
6    3s_no       0.666914      0.130423          0.666356         0.181201
7   3s_0.5       0.666887      0.088122          0.581828         0.175192
8   3s_0.8       0.665899      0.095339          0.542495         0.165543
9    4s_no       0.667906      0.109366          0.635989         0.253879
10  4s_0.5       0.673763      0.120943          0.579813         0.214468
11  4s_0.8       0.672683      0.076924          0.576896         0.139661
12   5s_no       0.672772      0.126319          0.636150         0.225226
13  5s_0.5       0.664773      0.068758          0.617117         0.157456
14  5s_0.8       0.653197      0.102633          0.590276         0.179529

In [13]:
# Get indexes of top N values using nlargest()
def get_top_n_indexes(df, column, n=5):
    """Get indexes of top N values in specified column"""
    top_indexes = df.nlargest(n, column).index.tolist()
    return top_indexes

# Get indexes using argsort() for all values (sorted)
def get_all_indexes_sorted(df, column):
    """Get all indexes sorted by column values (highest to lowest)"""
    sorted_indexes = df[column].argsort()[::-1].tolist()
    return sorted_indexes

# Get indexes above a certain threshold
def get_indexes_above_threshold(df, column, threshold):
    """Get indexes where column values are above threshold"""
    above_threshold_indexes = df[df[column] > threshold].index.tolist()
    return above_threshold_indexes


# print("DataFrame:")
# print(df)
# print("\n" + "="*50)

# Get top 5 indexes
top_5_indexes = get_top_n_indexes(df, 'mean_recall_void', 5)
print(f"\nTop 5 indexes by mean_recall_void:")
print(f"Indexes: {top_5_indexes}")
print("Corresponding configurations and values:")
for idx in top_5_indexes:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_recall_void']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Get all indexes sorted
all_sorted_indexes = get_all_indexes_sorted(df, 'mean_recall_void')
print(f"\nAll indexes sorted by mean_recall_void (highest to lowest):")
print(f"Indexes: {all_sorted_indexes}")

# Get indexes above threshold (e.g., 0.55)
threshold = 0.55
above_threshold = get_indexes_above_threshold(df, 'mean_recall_void', threshold)
print(f"\nIndexes with mean_recall_void > {threshold}:")
print(f"Indexes: {above_threshold}")
print("Corresponding configurations and values:")
for idx in above_threshold:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_recall_void']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Highest value index
max_index = df['mean_recall_void'].idxmax()
max_value = df.loc[max_index, 'mean_recall_void']
max_config = df.loc[max_index, 'config']
print(f"\nHighest mean_recall_void:")
print(f"Index {max_index}: {max_config} = {max_value:.6f}")

Top 5 indexes by mean_recall_void:
Indexes: [6, 12, 9, 13, 14]
Corresponding configurations and values:
  Index 6: 3s_no = 0.666356
  Index 12: 5s_no = 0.636150
  Index 9: 4s_no = 0.635989
  Index 13: 5s_0.5 = 0.617117
  Index 14: 5s_0.8 = 0.590276

All indexes sorted by mean_recall_void (highest to lowest):
Indexes: [6, 12, 9, 13, 14, 3, 7, 10, 11, 4, 0, 1, 8, 5, 2]

Indexes with mean_recall_void > 0.55:
Indexes: [0, 3, 4, 6, 7, 9, 10, 11, 12, 13, 14]
Corresponding configurations and values:
  Index 0: 1s_no = 0.560160
  Index 3: 2s_no = 0.588797
  Index 4: 2s_0.5 = 0.576713
  Index 6: 3s_no = 0.666356
  Index 7: 3s_0.5 = 0.581828
  Index 9: 4s_no = 0.635989
  Index 10: 4s_0.5 = 0.579813
  Index 11: 4s_0.8 = 0.576896
  Index 12: 5s_no = 0.636150
  Index 13: 5s_0.5 = 0.617117
  Index 14: 5s_0.8 = 0.590276

Highest mean_recall_void:
Index 6: 3s_no = 0.666356

In [14]:
# Get indexes of top N values using nlargest()
def get_top_n_indexes(df, column, n=5):
    """Get indexes of top N values in specified column"""
    top_indexes = df.nlargest(n, column).index.tolist()
    return top_indexes

# Get indexes using argsort() for all values (sorted)
def get_all_indexes_sorted(df, column):
    """Get all indexes sorted by column values (highest to lowest)"""
    sorted_indexes = df[column].argsort()[::-1].tolist()
    return sorted_indexes

# Get indexes above a certain threshold
def get_indexes_above_threshold(df, column, threshold):
    """Get indexes where column values are above threshold"""
    above_threshold_indexes = df[df[column] > threshold].index.tolist()
    return above_threshold_indexes


# print("DataFrame:")
# print(df)
# print("\n" + "="*50)

# Get top 5 indexes
top_5_indexes = get_top_n_indexes(df, 'mean_accuracy', 5)
print(f"\nTop 5 indexes by mean_accuracy:")
print(f"Indexes: {top_5_indexes}")
print("Corresponding configurations and values:")
for idx in top_5_indexes:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_accuracy']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Get all indexes sorted
all_sorted_indexes = get_all_indexes_sorted(df, 'mean_accuracy')
print(f"\nAll indexes sorted by mean_accuracy (highest to lowest):")
print(f"Indexes: {all_sorted_indexes}")

# Get indexes above threshold (e.g., 0.55)
threshold = 0.55
above_threshold = get_indexes_above_threshold(df, 'mean_accuracy', threshold)
print(f"\nIndexes with mean_accuracy > {threshold}:")
print(f"Indexes: {above_threshold}")
print("Corresponding configurations and values:")
for idx in above_threshold:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_accuracy']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Highest value index
max_index = df['mean_accuracy'].idxmax()
max_value = df.loc[max_index, 'mean_accuracy']
max_config = df.loc[max_index, 'config']
print(f"\nHighest mean_accuracy:")
print(f"Index {max_index}: {max_config} = {max_value:.6f}")

Top 5 indexes by mean_accuracy:
Indexes: [3, 4, 0, 10, 12]
Corresponding configurations and values:
  Index 3: 2s_no = 0.697760
  Index 4: 2s_0.5 = 0.685279
  Index 0: 1s_no = 0.674732
  Index 10: 4s_0.5 = 0.673763
  Index 12: 5s_no = 0.672772

All indexes sorted by mean_accuracy (highest to lowest):
Indexes: [3, 4, 0, 10, 12, 11, 5, 9, 6, 7, 8, 13, 1, 14, 2]

Indexes with mean_accuracy > 0.55:
Indexes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
Corresponding configurations and values:
  Index 0: 1s_no = 0.674732
  Index 1: 1s_0.5 = 0.653809
  Index 2: 1s_0.8 = 0.639212
  Index 3: 2s_no = 0.697760
  Index 4: 2s_0.5 = 0.685279
  Index 5: 2s_0.8 = 0.667908
  Index 6: 3s_no = 0.666914
  Index 7: 3s_0.5 = 0.666887
  Index 8: 3s_0.8 = 0.665899
  Index 9: 4s_no = 0.667906
  Index 10: 4s_0.5 = 0.673763
  Index 11: 4s_0.8 = 0.672683
  Index 12: 5s_no = 0.672772
  Index 13: 5s_0.5 = 0.664773
  Index 14: 5s_0.8 = 0.653197

Highest mean_accuracy:
Index 3: 2s_no = 0.697760

## Combined Smote Tomek

In [15]:
mean_accuracy = []
std_accuracy = []
mean_recall_void = []
std_recall_void = []
for win_data, data in xgb_results.items(): 
    data_ = data["combined_smote_tomek"]
    
    mean_accuracy.append(data_['mean_accuracy'])
    std_accuracy.append(data_['std_accuracy'])
    mean_recall_void.append(data_['mean_recall_minority'])
    std_recall_void.append(data_['std_recall_minority'])

indexes = xgb_results.keys()
results = {
    'config': indexes,
    'mean_accuracy': mean_accuracy,
    'std_accuracy': std_accuracy,
    'mean_recall_void': mean_recall_void,
    'std_recall_void': std_recall_void
} 
    
df = pd.DataFrame(results)

In [16]:
df

    config  mean_accuracy  std_accuracy  mean_recall_void  std_recall_void
0    1s_no       0.670384      0.056618          0.541849         0.078702
1   1s_0.5       0.652613      0.089270          0.538647         0.116432
2   1s_0.8       0.661093      0.101757          0.508833         0.176063
3    2s_no       0.686999      0.126544          0.588986         0.168097
4   2s_0.5       0.683732      0.063174          0.604486         0.085884
5   2s_0.8       0.678006      0.114047          0.562199         0.186496
6    3s_no       0.686341      0.109974          0.656099         0.191195
7   3s_0.5       0.654242      0.098733          0.542376         0.210646
8   3s_0.8       0.671002      0.093670          0.569200         0.167069
9    4s_no       0.682356      0.116211          0.628492         0.195243
10  4s_0.5       0.665088      0.130296          0.577006         0.211194
11  4s_0.8       0.671873      0.070841          0.591934         0.151442
12   5s_no       0.679653      0.105860          0.682675         0.192374
13  5s_0.5       0.689121      0.085104          0.631480         0.148806
14  5s_0.8       0.666946      0.102330          0.579055         0.185915

In [17]:
# Get indexes of top N values using nlargest()
def get_top_n_indexes(df, column, n=5):
    """Get indexes of top N values in specified column"""
    top_indexes = df.nlargest(n, column).index.tolist()
    return top_indexes

# Get indexes using argsort() for all values (sorted)
def get_all_indexes_sorted(df, column):
    """Get all indexes sorted by column values (highest to lowest)"""
    sorted_indexes = df[column].argsort()[::-1].tolist()
    return sorted_indexes

# Get indexes above a certain threshold
def get_indexes_above_threshold(df, column, threshold):
    """Get indexes where column values are above threshold"""
    above_threshold_indexes = df[df[column] > threshold].index.tolist()
    return above_threshold_indexes


# print("DataFrame:")
# print(df)
# print("\n" + "="*50)

# Get top 5 indexes
top_5_indexes = get_top_n_indexes(df, 'mean_recall_void', 5)
print(f"\nTop 5 indexes by mean_recall_void:")
print(f"Indexes: {top_5_indexes}")
print("Corresponding configurations and values:")
for idx in top_5_indexes:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_recall_void']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Get all indexes sorted
all_sorted_indexes = get_all_indexes_sorted(df, 'mean_recall_void')
print(f"\nAll indexes sorted by mean_recall_void (highest to lowest):")
print(f"Indexes: {all_sorted_indexes}")

# Get indexes above threshold (e.g., 0.55)
threshold = 0.55
above_threshold = get_indexes_above_threshold(df, 'mean_recall_void', threshold)
print(f"\nIndexes with mean_recall_void > {threshold}:")
print(f"Indexes: {above_threshold}")
print("Corresponding configurations and values:")
for idx in above_threshold:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_recall_void']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Highest value index
max_index = df['mean_recall_void'].idxmax()
max_value = df.loc[max_index, 'mean_recall_void']
max_config = df.loc[max_index, 'config']
print(f"\nHighest mean_recall_void:")
print(f"Index {max_index}: {max_config} = {max_value:.6f}")

Top 5 indexes by mean_recall_void:
Indexes: [12, 6, 13, 9, 4]
Corresponding configurations and values:
  Index 12: 5s_no = 0.682675
  Index 6: 3s_no = 0.656099
  Index 13: 5s_0.5 = 0.631480
  Index 9: 4s_no = 0.628492
  Index 4: 2s_0.5 = 0.604486

All indexes sorted by mean_recall_void (highest to lowest):
Indexes: [12, 6, 13, 9, 4, 11, 3, 14, 10, 8, 5, 7, 0, 1, 2]

Indexes with mean_recall_void > 0.55:
Indexes: [3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 14]
Corresponding configurations and values:
  Index 3: 2s_no = 0.588986
  Index 4: 2s_0.5 = 0.604486
  Index 5: 2s_0.8 = 0.562199
  Index 6: 3s_no = 0.656099
  Index 8: 3s_0.8 = 0.569200
  Index 9: 4s_no = 0.628492
  Index 10: 4s_0.5 = 0.577006
  Index 11: 4s_0.8 = 0.591934
  Index 12: 5s_no = 0.682675
  Index 13: 5s_0.5 = 0.631480
  Index 14: 5s_0.8 = 0.579055

Highest mean_recall_void:
Index 12: 5s_no = 0.682675

In [18]:
# Get indexes of top N values using nlargest()
def get_top_n_indexes(df, column, n=5):
    """Get indexes of top N values in specified column"""
    top_indexes = df.nlargest(n, column).index.tolist()
    return top_indexes

# Get indexes using argsort() for all values (sorted)
def get_all_indexes_sorted(df, column):
    """Get all indexes sorted by column values (highest to lowest)"""
    sorted_indexes = df[column].argsort()[::-1].tolist()
    return sorted_indexes

# Get indexes above a certain threshold
def get_indexes_above_threshold(df, column, threshold):
    """Get indexes where column values are above threshold"""
    above_threshold_indexes = df[df[column] > threshold].index.tolist()
    return above_threshold_indexes


# print("DataFrame:")
# print(df)
# print("\n" + "="*50)

# Get top 5 indexes
top_5_indexes = get_top_n_indexes(df, 'mean_accuracy', 5)
print(f"\nTop 5 indexes by mean_accuracy:")
print(f"Indexes: {top_5_indexes}")
print("Corresponding configurations and values:")
for idx in top_5_indexes:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_accuracy']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Get all indexes sorted
all_sorted_indexes = get_all_indexes_sorted(df, 'mean_accuracy')
print(f"\nAll indexes sorted by mean_accuracy (highest to lowest):")
print(f"Indexes: {all_sorted_indexes}")

# Get indexes above threshold (e.g., 0.55)
threshold = 0.55
above_threshold = get_indexes_above_threshold(df, 'mean_accuracy', threshold)
print(f"\nIndexes with mean_accuracy > {threshold}:")
print(f"Indexes: {above_threshold}")
print("Corresponding configurations and values:")
for idx in above_threshold:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_accuracy']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Highest value index
max_index = df['mean_accuracy'].idxmax()
max_value = df.loc[max_index, 'mean_accuracy']
max_config = df.loc[max_index, 'config']
print(f"\nHighest mean_accuracy:")
print(f"Index {max_index}: {max_config} = {max_value:.6f}")

Top 5 indexes by mean_accuracy:
Indexes: [13, 3, 6, 4, 9]
Corresponding configurations and values:
  Index 13: 5s_0.5 = 0.689121
  Index 3: 2s_no = 0.686999
  Index 6: 3s_no = 0.686341
  Index 4: 2s_0.5 = 0.683732
  Index 9: 4s_no = 0.682356

All indexes sorted by mean_accuracy (highest to lowest):
Indexes: [13, 3, 6, 4, 9, 12, 5, 11, 8, 0, 14, 10, 2, 7, 1]

Indexes with mean_accuracy > 0.55:
Indexes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
Corresponding configurations and values:
  Index 0: 1s_no = 0.670384
  Index 1: 1s_0.5 = 0.652613
  Index 2: 1s_0.8 = 0.661093
  Index 3: 2s_no = 0.686999
  Index 4: 2s_0.5 = 0.683732
  Index 5: 2s_0.8 = 0.678006
  Index 6: 3s_no = 0.686341
  Index 7: 3s_0.5 = 0.654242
  Index 8: 3s_0.8 = 0.671002
  Index 9: 4s_no = 0.682356
  Index 10: 4s_0.5 = 0.665088
  Index 11: 4s_0.8 = 0.671873
  Index 12: 5s_no = 0.679653
  Index 13: 5s_0.5 = 0.689121
  Index 14: 5s_0.8 = 0.666946

Highest mean_accuracy:
Index 13: 5s_0.5 = 0.689121