In [9]:
import pickle
import pandas as pd

In [10]:
with open('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/imb_files/xgb_imb_152_entire.pkl', 'rb') as f:
    xgb_results = pickle.load(f)

## Baseline

In [11]:
mean_accuracy = []
std_accuracy = []
mean_recall_void = []
std_recall_void = []
for win_data, data in xgb_results.items(): 
    data_ = data["none"]
    
    mean_accuracy.append(data_['mean_accuracy'])
    std_accuracy.append(data_['std_accuracy'])
    mean_recall_void.append(data_['mean_recall_minority'])
    std_recall_void.append(data_['std_recall_minority'])

indexes = xgb_results.keys()
results = {
    'config': indexes,
    'mean_accuracy': mean_accuracy,
    'std_accuracy': std_accuracy,
    'mean_recall_void': mean_recall_void,
    'std_recall_void': std_recall_void
} 
    
df = pd.DataFrame(results)
# df = pd.DataFrame(results, index=indexes)

In [12]:
df

    config  mean_accuracy  std_accuracy  mean_recall_void  std_recall_void
0    1s_no       0.669689      0.099822          0.552522         0.123778
1   1s_0.5       0.667103      0.119474          0.542096         0.160267
2   1s_0.8       0.661403      0.100237          0.507168         0.114295
3    2s_no       0.688842      0.104075          0.540921         0.154646
4   2s_0.5       0.679084      0.103277          0.565708         0.151590
5   2s_0.8       0.677198      0.095193          0.554986         0.130573
6    3s_no       0.694445      0.120924          0.601119         0.157582
7   3s_0.5       0.667087      0.108410          0.570642         0.161950
8   3s_0.8       0.673364      0.135470          0.560604         0.164545
9    4s_no       0.674744      0.109861          0.618075         0.197302
10  4s_0.5       0.675394      0.105495          0.556853         0.184673
11  4s_0.8       0.689300      0.126405          0.601030         0.187808
12   5s_no       0.696004      0.119893          0.592616         0.226214
13  5s_0.5       0.712840      0.129801          0.624682         0.183475
14  5s_0.8       0.686839      0.129845          0.595512         0.171788

In [13]:
# Get indexes of top N values using nlargest()
def get_top_n_indexes(df, column, n=5):
    """Get indexes of top N values in specified column"""
    top_indexes = df.nlargest(n, column).index.tolist()
    return top_indexes

# Get indexes using argsort() for all values (sorted)
def get_all_indexes_sorted(df, column):
    """Get all indexes sorted by column values (highest to lowest)"""
    sorted_indexes = df[column].argsort()[::-1].tolist()
    return sorted_indexes

# Get indexes above a certain threshold
def get_indexes_above_threshold(df, column, threshold):
    """Get indexes where column values are above threshold"""
    above_threshold_indexes = df[df[column] > threshold].index.tolist()
    return above_threshold_indexes


# print("DataFrame:")
# print(df)
# print("\n" + "="*50)

# Get top 5 indexes
top_5_indexes = get_top_n_indexes(df, 'mean_recall_void', 5)
print(f"\nTop 5 indexes by mean_recall_void:")
print(f"Indexes: {top_5_indexes}")
print("Corresponding configurations and values:")
for idx in top_5_indexes:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_recall_void']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Get all indexes sorted
all_sorted_indexes = get_all_indexes_sorted(df, 'mean_recall_void')
print(f"\nAll indexes sorted by mean_recall_void (highest to lowest):")
print(f"Indexes: {all_sorted_indexes}")

# Get indexes above threshold (e.g., 0.55)
threshold = 0.55
above_threshold = get_indexes_above_threshold(df, 'mean_recall_void', threshold)
print(f"\nIndexes with mean_recall_void > {threshold}:")
print(f"Indexes: {above_threshold}")
print("Corresponding configurations and values:")
for idx in above_threshold:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_recall_void']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Highest value index
max_index = df['mean_recall_void'].idxmax()
max_value = df.loc[max_index, 'mean_recall_void']
max_config = df.loc[max_index, 'config']
print(f"\nHighest mean_recall_void:")
print(f"Index {max_index}: {max_config} = {max_value:.6f}")

Top 5 indexes by mean_recall_void:
Indexes: [13, 9, 6, 11, 14]
Corresponding configurations and values:
  Index 13: 5s_0.5 = 0.624682
  Index 9: 4s_no = 0.618075
  Index 6: 3s_no = 0.601119
  Index 11: 4s_0.8 = 0.601030
  Index 14: 5s_0.8 = 0.595512

All indexes sorted by mean_recall_void (highest to lowest):
Indexes: [13, 9, 6, 11, 14, 12, 7, 4, 8, 10, 5, 0, 1, 3, 2]

Indexes with mean_recall_void > 0.55:
Indexes: [0, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
Corresponding configurations and values:
  Index 0: 1s_no = 0.552522
  Index 4: 2s_0.5 = 0.565708
  Index 5: 2s_0.8 = 0.554986
  Index 6: 3s_no = 0.601119
  Index 7: 3s_0.5 = 0.570642
  Index 8: 3s_0.8 = 0.560604
  Index 9: 4s_no = 0.618075
  Index 10: 4s_0.5 = 0.556853
  Index 11: 4s_0.8 = 0.601030
  Index 12: 5s_no = 0.592616
  Index 13: 5s_0.5 = 0.624682
  Index 14: 5s_0.8 = 0.595512

Highest mean_recall_void:
Index 13: 5s_0.5 = 0.624682

In [14]:
# Get indexes of top N values using nlargest()
def get_top_n_indexes(df, column, n=5):
    """Get indexes of top N values in specified column"""
    top_indexes = df.nlargest(n, column).index.tolist()
    return top_indexes

# Get indexes using argsort() for all values (sorted)
def get_all_indexes_sorted(df, column):
    """Get all indexes sorted by column values (highest to lowest)"""
    sorted_indexes = df[column].argsort()[::-1].tolist()
    return sorted_indexes

# Get indexes above a certain threshold
def get_indexes_above_threshold(df, column, threshold):
    """Get indexes where column values are above threshold"""
    above_threshold_indexes = df[df[column] > threshold].index.tolist()
    return above_threshold_indexes


# print("DataFrame:")
# print(df)
# print("\n" + "="*50)

# Get top 5 indexes
top_5_indexes = get_top_n_indexes(df, 'mean_accuracy', 5)
print(f"\nTop 5 indexes by mean_accuracy:")
print(f"Indexes: {top_5_indexes}")
print("Corresponding configurations and values:")
for idx in top_5_indexes:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_accuracy']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Get all indexes sorted
all_sorted_indexes = get_all_indexes_sorted(df, 'mean_accuracy')
print(f"\nAll indexes sorted by mean_accuracy (highest to lowest):")
print(f"Indexes: {all_sorted_indexes}")

# Get indexes above threshold (e.g., 0.55)
threshold = 0.55
above_threshold = get_indexes_above_threshold(df, 'mean_accuracy', threshold)
print(f"\nIndexes with mean_accuracy > {threshold}:")
print(f"Indexes: {above_threshold}")
print("Corresponding configurations and values:")
for idx in above_threshold:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_accuracy']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Highest value index
max_index = df['mean_accuracy'].idxmax()
max_value = df.loc[max_index, 'mean_accuracy']
max_config = df.loc[max_index, 'config']
print(f"\nHighest mean_accuracy:")
print(f"Index {max_index}: {max_config} = {max_value:.6f}")

Top 5 indexes by mean_accuracy:
Indexes: [13, 12, 6, 11, 3]
Corresponding configurations and values:
  Index 13: 5s_0.5 = 0.712840
  Index 12: 5s_no = 0.696004
  Index 6: 3s_no = 0.694445
  Index 11: 4s_0.8 = 0.689300
  Index 3: 2s_no = 0.688842

All indexes sorted by mean_accuracy (highest to lowest):
Indexes: [13, 12, 6, 11, 3, 14, 4, 5, 10, 9, 8, 0, 1, 7, 2]

Indexes with mean_accuracy > 0.55:
Indexes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
Corresponding configurations and values:
  Index 0: 1s_no = 0.669689
  Index 1: 1s_0.5 = 0.667103
  Index 2: 1s_0.8 = 0.661403
  Index 3: 2s_no = 0.688842
  Index 4: 2s_0.5 = 0.679084
  Index 5: 2s_0.8 = 0.677198
  Index 6: 3s_no = 0.694445
  Index 7: 3s_0.5 = 0.667087
  Index 8: 3s_0.8 = 0.673364
  Index 9: 4s_no = 0.674744
  Index 10: 4s_0.5 = 0.675394
  Index 11: 4s_0.8 = 0.689300
  Index 12: 5s_no = 0.696004
  Index 13: 5s_0.5 = 0.712840
  Index 14: 5s_0.8 = 0.686839

Highest mean_accuracy:
Index 13: 5s_0.5 = 0.712840

## Oversample

In [15]:
mean_accuracy = []
std_accuracy = []
mean_recall_void = []
std_recall_void = []
for win_data, data in xgb_results.items(): 
    data_ = data["oversample_smote"]
    
    mean_accuracy.append(data_['mean_accuracy'])
    std_accuracy.append(data_['std_accuracy'])
    mean_recall_void.append(data_['mean_recall_minority'])
    std_recall_void.append(data_['std_recall_minority'])

indexes = xgb_results.keys()
results = {
    'config': indexes,
    'mean_accuracy': mean_accuracy,
    'std_accuracy': std_accuracy,
    'mean_recall_void': mean_recall_void,
    'std_recall_void': std_recall_void
} 
    
df = pd.DataFrame(results)

In [16]:
df

    config  mean_accuracy  std_accuracy  mean_recall_void  std_recall_void
0    1s_no       0.676138      0.102100          0.604557         0.117949
1   1s_0.5       0.667911      0.117497          0.596268         0.177575
2   1s_0.8       0.681258      0.100129          0.593887         0.104567
3    2s_no       0.688162      0.095299          0.581571         0.134138
4   2s_0.5       0.692035      0.099804          0.614508         0.132131
5   2s_0.8       0.683680      0.091783          0.587396         0.114173
6    3s_no       0.693986      0.121856          0.652147         0.180535
7   3s_0.5       0.668962      0.098846          0.609708         0.141576
8   3s_0.8       0.675273      0.118881          0.605027         0.165279
9    4s_no       0.679071      0.109926          0.655761         0.195261
10  4s_0.5       0.689414      0.110739          0.608970         0.187355
11  4s_0.8       0.684070      0.126138          0.642589         0.173299
12   5s_no       0.690277      0.107634          0.645926         0.197520
13  5s_0.5       0.691324      0.131913          0.636316         0.174016
14  5s_0.8       0.682027      0.139689          0.632820         0.176856

In [17]:
# Get indexes of top N values using nlargest()
def get_top_n_indexes(df, column, n=5):
    """Get indexes of top N values in specified column"""
    top_indexes = df.nlargest(n, column).index.tolist()
    return top_indexes

# Get indexes using argsort() for all values (sorted)
def get_all_indexes_sorted(df, column):
    """Get all indexes sorted by column values (highest to lowest)"""
    sorted_indexes = df[column].argsort()[::-1].tolist()
    return sorted_indexes

# Get indexes above a certain threshold
def get_indexes_above_threshold(df, column, threshold):
    """Get indexes where column values are above threshold"""
    above_threshold_indexes = df[df[column] > threshold].index.tolist()
    return above_threshold_indexes


# print("DataFrame:")
# print(df)
# print("\n" + "="*50)

# Get top 5 indexes
top_5_indexes = get_top_n_indexes(df, 'mean_recall_void', 5)
print(f"\nTop 5 indexes by mean_recall_void:")
print(f"Indexes: {top_5_indexes}")
print("Corresponding configurations and values:")
for idx in top_5_indexes:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_recall_void']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Get all indexes sorted
all_sorted_indexes = get_all_indexes_sorted(df, 'mean_recall_void')
print(f"\nAll indexes sorted by mean_recall_void (highest to lowest):")
print(f"Indexes: {all_sorted_indexes}")

# Get indexes above threshold (e.g., 0.55)
threshold = 0.55
above_threshold = get_indexes_above_threshold(df, 'mean_recall_void', threshold)
print(f"\nIndexes with mean_recall_void > {threshold}:")
print(f"Indexes: {above_threshold}")
print("Corresponding configurations and values:")
for idx in above_threshold:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_recall_void']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Highest value index
max_index = df['mean_recall_void'].idxmax()
max_value = df.loc[max_index, 'mean_recall_void']
max_config = df.loc[max_index, 'config']
print(f"\nHighest mean_recall_void:")
print(f"Index {max_index}: {max_config} = {max_value:.6f}")

Top 5 indexes by mean_recall_void:
Indexes: [9, 6, 12, 11, 13]
Corresponding configurations and values:
  Index 9: 4s_no = 0.655761
  Index 6: 3s_no = 0.652147
  Index 12: 5s_no = 0.645926
  Index 11: 4s_0.8 = 0.642589
  Index 13: 5s_0.5 = 0.636316

All indexes sorted by mean_recall_void (highest to lowest):
Indexes: [9, 6, 12, 11, 13, 14, 4, 7, 10, 8, 0, 1, 2, 5, 3]

Indexes with mean_recall_void > 0.55:
Indexes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
Corresponding configurations and values:
  Index 0: 1s_no = 0.604557
  Index 1: 1s_0.5 = 0.596268
  Index 2: 1s_0.8 = 0.593887
  Index 3: 2s_no = 0.581571
  Index 4: 2s_0.5 = 0.614508
  Index 5: 2s_0.8 = 0.587396
  Index 6: 3s_no = 0.652147
  Index 7: 3s_0.5 = 0.609708
  Index 8: 3s_0.8 = 0.605027
  Index 9: 4s_no = 0.655761
  Index 10: 4s_0.5 = 0.608970
  Index 11: 4s_0.8 = 0.642589
  Index 12: 5s_no = 0.645926
  Index 13: 5s_0.5 = 0.636316
  Index 14: 5s_0.8 = 0.632820

Highest mean_recall_void:
Index 9: 4s_no = 0.655761

In [18]:
# Get indexes of top N values using nlargest()
def get_top_n_indexes(df, column, n=5):
    """Get indexes of top N values in specified column"""
    top_indexes = df.nlargest(n, column).index.tolist()
    return top_indexes

# Get indexes using argsort() for all values (sorted)
def get_all_indexes_sorted(df, column):
    """Get all indexes sorted by column values (highest to lowest)"""
    sorted_indexes = df[column].argsort()[::-1].tolist()
    return sorted_indexes

# Get indexes above a certain threshold
def get_indexes_above_threshold(df, column, threshold):
    """Get indexes where column values are above threshold"""
    above_threshold_indexes = df[df[column] > threshold].index.tolist()
    return above_threshold_indexes


# print("DataFrame:")
# print(df)
# print("\n" + "="*50)

# Get top 5 indexes
top_5_indexes = get_top_n_indexes(df, 'mean_accuracy', 5)
print(f"\nTop 5 indexes by mean_accuracy:")
print(f"Indexes: {top_5_indexes}")
print("Corresponding configurations and values:")
for idx in top_5_indexes:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_accuracy']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Get all indexes sorted
all_sorted_indexes = get_all_indexes_sorted(df, 'mean_accuracy')
print(f"\nAll indexes sorted by mean_accuracy (highest to lowest):")
print(f"Indexes: {all_sorted_indexes}")

# Get indexes above threshold (e.g., 0.55)
threshold = 0.55
above_threshold = get_indexes_above_threshold(df, 'mean_accuracy', threshold)
print(f"\nIndexes with mean_accuracy > {threshold}:")
print(f"Indexes: {above_threshold}")
print("Corresponding configurations and values:")
for idx in above_threshold:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_accuracy']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Highest value index
max_index = df['mean_accuracy'].idxmax()
max_value = df.loc[max_index, 'mean_accuracy']
max_config = df.loc[max_index, 'config']
print(f"\nHighest mean_accuracy:")
print(f"Index {max_index}: {max_config} = {max_value:.6f}")

Top 5 indexes by mean_accuracy:
Indexes: [6, 4, 13, 12, 10]
Corresponding configurations and values:
  Index 6: 3s_no = 0.693986
  Index 4: 2s_0.5 = 0.692035
  Index 13: 5s_0.5 = 0.691324
  Index 12: 5s_no = 0.690277
  Index 10: 4s_0.5 = 0.689414

All indexes sorted by mean_accuracy (highest to lowest):
Indexes: [6, 4, 13, 12, 10, 3, 11, 5, 14, 2, 9, 0, 8, 7, 1]

Indexes with mean_accuracy > 0.55:
Indexes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
Corresponding configurations and values:
  Index 0: 1s_no = 0.676138
  Index 1: 1s_0.5 = 0.667911
  Index 2: 1s_0.8 = 0.681258
  Index 3: 2s_no = 0.688162
  Index 4: 2s_0.5 = 0.692035
  Index 5: 2s_0.8 = 0.683680
  Index 6: 3s_no = 0.693986
  Index 7: 3s_0.5 = 0.668962
  Index 8: 3s_0.8 = 0.675273
  Index 9: 4s_no = 0.679071
  Index 10: 4s_0.5 = 0.689414
  Index 11: 4s_0.8 = 0.684070
  Index 12: 5s_no = 0.690277
  Index 13: 5s_0.5 = 0.691324
  Index 14: 5s_0.8 = 0.682027

Highest mean_accuracy:
Index 6: 3s_no = 0.693986

## Undersample

In [19]:
mean_accuracy = []
std_accuracy = []
mean_recall_void = []
std_recall_void = []
for win_data, data in xgb_results.items(): 
    data_ = data["undersample_tomek_links"]
    
    mean_accuracy.append(data_['mean_accuracy'])
    std_accuracy.append(data_['std_accuracy'])
    mean_recall_void.append(data_['mean_recall_minority'])
    std_recall_void.append(data_['std_recall_minority'])

indexes = xgb_results.keys()
results = {
    'config': indexes,
    'mean_accuracy': mean_accuracy,
    'std_accuracy': std_accuracy,
    'mean_recall_void': mean_recall_void,
    'std_recall_void': std_recall_void
} 
    
df = pd.DataFrame(results)

In [20]:
df

    config  mean_accuracy  std_accuracy  mean_recall_void  std_recall_void
0    1s_no       0.675032      0.089980          0.624337         0.099058
1   1s_0.5       0.673796      0.108540          0.590664         0.167958
2   1s_0.8       0.665908      0.099280          0.534523         0.106778
3    2s_no       0.693986      0.102980          0.612702         0.151103
4   2s_0.5       0.694316      0.090128          0.638804         0.127901
5   2s_0.8       0.678718      0.095264          0.553437         0.110369
6    3s_no       0.701410      0.108655          0.661793         0.154422
7   3s_0.5       0.679956      0.094974          0.624664         0.137105
8   3s_0.8       0.677108      0.131919          0.604316         0.171940
9    4s_no       0.688505      0.103751          0.663796         0.208600
10  4s_0.5       0.698939      0.095357          0.637585         0.165074
11  4s_0.8       0.693908      0.124267          0.626430         0.190580
12   5s_no       0.716894      0.100445          0.728046         0.186956
13  5s_0.5       0.702360      0.115337          0.655197         0.168224
14  5s_0.8       0.695919      0.140027          0.625628         0.190446

In [21]:
# Get indexes of top N values using nlargest()
def get_top_n_indexes(df, column, n=5):
    """Get indexes of top N values in specified column"""
    top_indexes = df.nlargest(n, column).index.tolist()
    return top_indexes

# Get indexes using argsort() for all values (sorted)
def get_all_indexes_sorted(df, column):
    """Get all indexes sorted by column values (highest to lowest)"""
    sorted_indexes = df[column].argsort()[::-1].tolist()
    return sorted_indexes

# Get indexes above a certain threshold
def get_indexes_above_threshold(df, column, threshold):
    """Get indexes where column values are above threshold"""
    above_threshold_indexes = df[df[column] > threshold].index.tolist()
    return above_threshold_indexes


# print("DataFrame:")
# print(df)
# print("\n" + "="*50)

# Get top 5 indexes
top_5_indexes = get_top_n_indexes(df, 'mean_recall_void', 5)
print(f"\nTop 5 indexes by mean_recall_void:")
print(f"Indexes: {top_5_indexes}")
print("Corresponding configurations and values:")
for idx in top_5_indexes:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_recall_void']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Get all indexes sorted
all_sorted_indexes = get_all_indexes_sorted(df, 'mean_recall_void')
print(f"\nAll indexes sorted by mean_recall_void (highest to lowest):")
print(f"Indexes: {all_sorted_indexes}")

# Get indexes above threshold (e.g., 0.55)
threshold = 0.55
above_threshold = get_indexes_above_threshold(df, 'mean_recall_void', threshold)
print(f"\nIndexes with mean_recall_void > {threshold}:")
print(f"Indexes: {above_threshold}")
print("Corresponding configurations and values:")
for idx in above_threshold:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_recall_void']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Highest value index
max_index = df['mean_recall_void'].idxmax()
max_value = df.loc[max_index, 'mean_recall_void']
max_config = df.loc[max_index, 'config']
print(f"\nHighest mean_recall_void:")
print(f"Index {max_index}: {max_config} = {max_value:.6f}")

Top 5 indexes by mean_recall_void:
Indexes: [12, 9, 6, 13, 4]
Corresponding configurations and values:
  Index 12: 5s_no = 0.728046
  Index 9: 4s_no = 0.663796
  Index 6: 3s_no = 0.661793
  Index 13: 5s_0.5 = 0.655197
  Index 4: 2s_0.5 = 0.638804

All indexes sorted by mean_recall_void (highest to lowest):
Indexes: [12, 9, 6, 13, 4, 10, 11, 14, 7, 0, 3, 8, 1, 5, 2]

Indexes with mean_recall_void > 0.55:
Indexes: [0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
Corresponding configurations and values:
  Index 0: 1s_no = 0.624337
  Index 1: 1s_0.5 = 0.590664
  Index 3: 2s_no = 0.612702
  Index 4: 2s_0.5 = 0.638804
  Index 5: 2s_0.8 = 0.553437
  Index 6: 3s_no = 0.661793
  Index 7: 3s_0.5 = 0.624664
  Index 8: 3s_0.8 = 0.604316
  Index 9: 4s_no = 0.663796
  Index 10: 4s_0.5 = 0.637585
  Index 11: 4s_0.8 = 0.626430
  Index 12: 5s_no = 0.728046
  Index 13: 5s_0.5 = 0.655197
  Index 14: 5s_0.8 = 0.625628

Highest mean_recall_void:
Index 12: 5s_no = 0.728046

In [22]:
# Get indexes of top N values using nlargest()
def get_top_n_indexes(df, column, n=5):
    """Get indexes of top N values in specified column"""
    top_indexes = df.nlargest(n, column).index.tolist()
    return top_indexes

# Get indexes using argsort() for all values (sorted)
def get_all_indexes_sorted(df, column):
    """Get all indexes sorted by column values (highest to lowest)"""
    sorted_indexes = df[column].argsort()[::-1].tolist()
    return sorted_indexes

# Get indexes above a certain threshold
def get_indexes_above_threshold(df, column, threshold):
    """Get indexes where column values are above threshold"""
    above_threshold_indexes = df[df[column] > threshold].index.tolist()
    return above_threshold_indexes


# print("DataFrame:")
# print(df)
# print("\n" + "="*50)

# Get top 5 indexes
top_5_indexes = get_top_n_indexes(df, 'mean_accuracy', 5)
print(f"\nTop 5 indexes by mean_accuracy:")
print(f"Indexes: {top_5_indexes}")
print("Corresponding configurations and values:")
for idx in top_5_indexes:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_accuracy']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Get all indexes sorted
all_sorted_indexes = get_all_indexes_sorted(df, 'mean_accuracy')
print(f"\nAll indexes sorted by mean_accuracy (highest to lowest):")
print(f"Indexes: {all_sorted_indexes}")

# Get indexes above threshold (e.g., 0.55)
threshold = 0.55
above_threshold = get_indexes_above_threshold(df, 'mean_accuracy', threshold)
print(f"\nIndexes with mean_accuracy > {threshold}:")
print(f"Indexes: {above_threshold}")
print("Corresponding configurations and values:")
for idx in above_threshold:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_accuracy']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Highest value index
max_index = df['mean_accuracy'].idxmax()
max_value = df.loc[max_index, 'mean_accuracy']
max_config = df.loc[max_index, 'config']
print(f"\nHighest mean_accuracy:")
print(f"Index {max_index}: {max_config} = {max_value:.6f}")

Top 5 indexes by mean_accuracy:
Indexes: [12, 13, 6, 10, 14]
Corresponding configurations and values:
  Index 12: 5s_no = 0.716894
  Index 13: 5s_0.5 = 0.702360
  Index 6: 3s_no = 0.701410
  Index 10: 4s_0.5 = 0.698939
  Index 14: 5s_0.8 = 0.695919

All indexes sorted by mean_accuracy (highest to lowest):
Indexes: [12, 13, 6, 10, 14, 4, 3, 11, 9, 7, 5, 8, 0, 1, 2]

Indexes with mean_accuracy > 0.55:
Indexes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
Corresponding configurations and values:
  Index 0: 1s_no = 0.675032
  Index 1: 1s_0.5 = 0.673796
  Index 2: 1s_0.8 = 0.665908
  Index 3: 2s_no = 0.693986
  Index 4: 2s_0.5 = 0.694316
  Index 5: 2s_0.8 = 0.678718
  Index 6: 3s_no = 0.701410
  Index 7: 3s_0.5 = 0.679956
  Index 8: 3s_0.8 = 0.677108
  Index 9: 4s_no = 0.688505
  Index 10: 4s_0.5 = 0.698939
  Index 11: 4s_0.8 = 0.693908
  Index 12: 5s_no = 0.716894
  Index 13: 5s_0.5 = 0.702360
  Index 14: 5s_0.8 = 0.695919

Highest mean_accuracy:
Index 12: 5s_no = 0.716894

## Combined Smote Tomek

In [23]:
mean_accuracy = []
std_accuracy = []
mean_recall_void = []
std_recall_void = []
for win_data, data in xgb_results.items(): 
    data_ = data["combined_smote_tomek"]
    
    mean_accuracy.append(data_['mean_accuracy'])
    std_accuracy.append(data_['std_accuracy'])
    mean_recall_void.append(data_['mean_recall_minority'])
    std_recall_void.append(data_['std_recall_minority'])

indexes = xgb_results.keys()
results = {
    'config': indexes,
    'mean_accuracy': mean_accuracy,
    'std_accuracy': std_accuracy,
    'mean_recall_void': mean_recall_void,
    'std_recall_void': std_recall_void
} 
    
df = pd.DataFrame(results)

In [24]:
df

    config  mean_accuracy  std_accuracy  mean_recall_void  std_recall_void
0    1s_no       0.684422      0.093516          0.608710         0.096703
1   1s_0.5       0.670298      0.112369          0.596631         0.161295
2   1s_0.8       0.668503      0.103081          0.565250         0.111255
3    2s_no       0.704811      0.092520          0.599032         0.157397
4   2s_0.5       0.689996      0.093914          0.606845         0.119718
5   2s_0.8       0.675246      0.089994          0.571393         0.128302
6    3s_no       0.709369      0.110440          0.679169         0.180824
7   3s_0.5       0.693693      0.108568          0.647639         0.136384
8   3s_0.8       0.671217      0.122702          0.606188         0.159421
9    4s_no       0.691455      0.113839          0.672464         0.199147
10  4s_0.5       0.697581      0.103034          0.634006         0.181885
11  4s_0.8       0.680824      0.120265          0.622516         0.166808
12   5s_no       0.676005      0.105790          0.640972         0.196553
13  5s_0.5       0.704671      0.124172          0.646346         0.168711
14  5s_0.8       0.688292      0.125401          0.641582         0.152303

In [25]:
# Get indexes of top N values using nlargest()
def get_top_n_indexes(df, column, n=5):
    """Get indexes of top N values in specified column"""
    top_indexes = df.nlargest(n, column).index.tolist()
    return top_indexes

# Get indexes using argsort() for all values (sorted)
def get_all_indexes_sorted(df, column):
    """Get all indexes sorted by column values (highest to lowest)"""
    sorted_indexes = df[column].argsort()[::-1].tolist()
    return sorted_indexes

# Get indexes above a certain threshold
def get_indexes_above_threshold(df, column, threshold):
    """Get indexes where column values are above threshold"""
    above_threshold_indexes = df[df[column] > threshold].index.tolist()
    return above_threshold_indexes


# print("DataFrame:")
# print(df)
# print("\n" + "="*50)

# Get top 5 indexes
top_5_indexes = get_top_n_indexes(df, 'mean_recall_void', 5)
print(f"\nTop 5 indexes by mean_recall_void:")
print(f"Indexes: {top_5_indexes}")
print("Corresponding configurations and values:")
for idx in top_5_indexes:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_recall_void']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Get all indexes sorted
all_sorted_indexes = get_all_indexes_sorted(df, 'mean_recall_void')
print(f"\nAll indexes sorted by mean_recall_void (highest to lowest):")
print(f"Indexes: {all_sorted_indexes}")

# Get indexes above threshold (e.g., 0.55)
threshold = 0.55
above_threshold = get_indexes_above_threshold(df, 'mean_recall_void', threshold)
print(f"\nIndexes with mean_recall_void > {threshold}:")
print(f"Indexes: {above_threshold}")
print("Corresponding configurations and values:")
for idx in above_threshold:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_recall_void']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Highest value index
max_index = df['mean_recall_void'].idxmax()
max_value = df.loc[max_index, 'mean_recall_void']
max_config = df.loc[max_index, 'config']
print(f"\nHighest mean_recall_void:")
print(f"Index {max_index}: {max_config} = {max_value:.6f}")

Top 5 indexes by mean_recall_void:
Indexes: [6, 9, 7, 13, 14]
Corresponding configurations and values:
  Index 6: 3s_no = 0.679169
  Index 9: 4s_no = 0.672464
  Index 7: 3s_0.5 = 0.647639
  Index 13: 5s_0.5 = 0.646346
  Index 14: 5s_0.8 = 0.641582

All indexes sorted by mean_recall_void (highest to lowest):
Indexes: [6, 9, 7, 13, 14, 12, 10, 11, 0, 4, 8, 3, 1, 5, 2]

Indexes with mean_recall_void > 0.55:
Indexes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
Corresponding configurations and values:
  Index 0: 1s_no = 0.608710
  Index 1: 1s_0.5 = 0.596631
  Index 2: 1s_0.8 = 0.565250
  Index 3: 2s_no = 0.599032
  Index 4: 2s_0.5 = 0.606845
  Index 5: 2s_0.8 = 0.571393
  Index 6: 3s_no = 0.679169
  Index 7: 3s_0.5 = 0.647639
  Index 8: 3s_0.8 = 0.606188
  Index 9: 4s_no = 0.672464
  Index 10: 4s_0.5 = 0.634006
  Index 11: 4s_0.8 = 0.622516
  Index 12: 5s_no = 0.640972
  Index 13: 5s_0.5 = 0.646346
  Index 14: 5s_0.8 = 0.641582

Highest mean_recall_void:
Index 6: 3s_no = 0.679169

In [26]:
# Get indexes of top N values using nlargest()
def get_top_n_indexes(df, column, n=5):
    """Get indexes of top N values in specified column"""
    top_indexes = df.nlargest(n, column).index.tolist()
    return top_indexes

# Get indexes using argsort() for all values (sorted)
def get_all_indexes_sorted(df, column):
    """Get all indexes sorted by column values (highest to lowest)"""
    sorted_indexes = df[column].argsort()[::-1].tolist()
    return sorted_indexes

# Get indexes above a certain threshold
def get_indexes_above_threshold(df, column, threshold):
    """Get indexes where column values are above threshold"""
    above_threshold_indexes = df[df[column] > threshold].index.tolist()
    return above_threshold_indexes


# print("DataFrame:")
# print(df)
# print("\n" + "="*50)

# Get top 5 indexes
top_5_indexes = get_top_n_indexes(df, 'mean_accuracy', 5)
print(f"\nTop 5 indexes by mean_accuracy:")
print(f"Indexes: {top_5_indexes}")
print("Corresponding configurations and values:")
for idx in top_5_indexes:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_accuracy']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Get all indexes sorted
all_sorted_indexes = get_all_indexes_sorted(df, 'mean_accuracy')
print(f"\nAll indexes sorted by mean_accuracy (highest to lowest):")
print(f"Indexes: {all_sorted_indexes}")

# Get indexes above threshold (e.g., 0.55)
threshold = 0.55
above_threshold = get_indexes_above_threshold(df, 'mean_accuracy', threshold)
print(f"\nIndexes with mean_accuracy > {threshold}:")
print(f"Indexes: {above_threshold}")
print("Corresponding configurations and values:")
for idx in above_threshold:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_accuracy']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Highest value index
max_index = df['mean_accuracy'].idxmax()
max_value = df.loc[max_index, 'mean_accuracy']
max_config = df.loc[max_index, 'config']
print(f"\nHighest mean_accuracy:")
print(f"Index {max_index}: {max_config} = {max_value:.6f}")

Top 5 indexes by mean_accuracy:
Indexes: [6, 3, 13, 10, 7]
Corresponding configurations and values:
  Index 6: 3s_no = 0.709369
  Index 3: 2s_no = 0.704811
  Index 13: 5s_0.5 = 0.704671
  Index 10: 4s_0.5 = 0.697581
  Index 7: 3s_0.5 = 0.693693

All indexes sorted by mean_accuracy (highest to lowest):
Indexes: [6, 3, 13, 10, 7, 9, 4, 14, 0, 11, 12, 5, 8, 1, 2]

Indexes with mean_accuracy > 0.55:
Indexes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
Corresponding configurations and values:
  Index 0: 1s_no = 0.684422
  Index 1: 1s_0.5 = 0.670298
  Index 2: 1s_0.8 = 0.668503
  Index 3: 2s_no = 0.704811
  Index 4: 2s_0.5 = 0.689996
  Index 5: 2s_0.8 = 0.675246
  Index 6: 3s_no = 0.709369
  Index 7: 3s_0.5 = 0.693693
  Index 8: 3s_0.8 = 0.671217
  Index 9: 4s_no = 0.691455
  Index 10: 4s_0.5 = 0.697581
  Index 11: 4s_0.8 = 0.680824
  Index 12: 5s_no = 0.676005
  Index 13: 5s_0.5 = 0.704671
  Index 14: 5s_0.8 = 0.688292

Highest mean_accuracy:
Index 6: 3s_no = 0.709369