In [1]:
import pickle
import pandas as pd

In [2]:
with open('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/imb_files/dt_imb_152.pkl', 'rb') as f:
    xgb_results = pickle.load(f)

## Baseline

In [3]:
mean_accuracy = []
std_accuracy = []
mean_recall_void = []
std_recall_void = []
for win_data, data in xgb_results.items(): 
    data_ = data["none"]
    
    mean_accuracy.append(data_['mean_accuracy'])
    std_accuracy.append(data_['std_accuracy'])
    mean_recall_void.append(data_['mean_recall_minority'])
    std_recall_void.append(data_['std_recall_minority'])

indexes = xgb_results.keys()
results = {
    'config': indexes,
    'mean_accuracy': mean_accuracy,
    'std_accuracy': std_accuracy,
    'mean_recall_void': mean_recall_void,
    'std_recall_void': std_recall_void
} 
    
df = pd.DataFrame(results)
# df = pd.DataFrame(results, index=indexes)

In [4]:
df

    config  mean_accuracy  std_accuracy  mean_recall_void  std_recall_void
0    1s_no       0.613319      0.072084          0.528452         0.121564
1   1s_0.5       0.599250      0.060455          0.496429         0.098363
2   1s_0.8       0.605824      0.059812          0.492662         0.127994
3    2s_no       0.607040      0.093535          0.538809         0.163518
4   2s_0.5       0.612498      0.056745          0.530378         0.114032
5   2s_0.8       0.625411      0.076984          0.550796         0.141272
6    3s_no       0.636562      0.074117          0.589795         0.083081
7   3s_0.5       0.604478      0.050605          0.558279         0.098189
8   3s_0.8       0.600139      0.057627          0.505231         0.125279
9    4s_no       0.654436      0.092594          0.526127         0.206255
10  4s_0.5       0.611227      0.098801          0.485042         0.172006
11  4s_0.8       0.607564      0.074996          0.505460         0.180556
12   5s_no       0.608125      0.090469          0.556277         0.148696
13  5s_0.5       0.584747      0.074556          0.500653         0.138513
14  5s_0.8       0.609862      0.083064          0.546212         0.142703

In [5]:
# Get indexes of top N values using nlargest()
def get_top_n_indexes(df, column, n=5):
    """Get indexes of top N values in specified column"""
    top_indexes = df.nlargest(n, column).index.tolist()
    return top_indexes

# Get indexes using argsort() for all values (sorted)
def get_all_indexes_sorted(df, column):
    """Get all indexes sorted by column values (highest to lowest)"""
    sorted_indexes = df[column].argsort()[::-1].tolist()
    return sorted_indexes

# Get indexes above a certain threshold
def get_indexes_above_threshold(df, column, threshold):
    """Get indexes where column values are above threshold"""
    above_threshold_indexes = df[df[column] > threshold].index.tolist()
    return above_threshold_indexes


# print("DataFrame:")
# print(df)
# print("\n" + "="*50)

# Get top 5 indexes
top_5_indexes = get_top_n_indexes(df, 'mean_recall_void', 5)
print(f"\nTop 5 indexes by mean_recall_void:")
print(f"Indexes: {top_5_indexes}")
print("Corresponding configurations and values:")
for idx in top_5_indexes:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_recall_void']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Get all indexes sorted
all_sorted_indexes = get_all_indexes_sorted(df, 'mean_recall_void')
print(f"\nAll indexes sorted by mean_recall_void (highest to lowest):")
print(f"Indexes: {all_sorted_indexes}")

# Get indexes above threshold (e.g., 0.55)
threshold = 0.55
above_threshold = get_indexes_above_threshold(df, 'mean_recall_void', threshold)
print(f"\nIndexes with mean_recall_void > {threshold}:")
print(f"Indexes: {above_threshold}")
print("Corresponding configurations and values:")
for idx in above_threshold:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_recall_void']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Highest value index
max_index = df['mean_recall_void'].idxmax()
max_value = df.loc[max_index, 'mean_recall_void']
max_config = df.loc[max_index, 'config']
print(f"\nHighest mean_recall_void:")
print(f"Index {max_index}: {max_config} = {max_value:.6f}")

Top 5 indexes by mean_recall_void:
Indexes: [6, 7, 12, 5, 14]
Corresponding configurations and values:
  Index 6: 3s_no = 0.589795
  Index 7: 3s_0.5 = 0.558279
  Index 12: 5s_no = 0.556277
  Index 5: 2s_0.8 = 0.550796
  Index 14: 5s_0.8 = 0.546212

All indexes sorted by mean_recall_void (highest to lowest):
Indexes: [6, 7, 12, 5, 14, 3, 4, 0, 9, 11, 8, 13, 1, 2, 10]

Indexes with mean_recall_void > 0.55:
Indexes: [5, 6, 7, 12]
Corresponding configurations and values:
  Index 5: 2s_0.8 = 0.550796
  Index 6: 3s_no = 0.589795
  Index 7: 3s_0.5 = 0.558279
  Index 12: 5s_no = 0.556277

Highest mean_recall_void:
Index 6: 3s_no = 0.589795

In [6]:
# Get indexes of top N values using nlargest()
def get_top_n_indexes(df, column, n=5):
    """Get indexes of top N values in specified column"""
    top_indexes = df.nlargest(n, column).index.tolist()
    return top_indexes

# Get indexes using argsort() for all values (sorted)
def get_all_indexes_sorted(df, column):
    """Get all indexes sorted by column values (highest to lowest)"""
    sorted_indexes = df[column].argsort()[::-1].tolist()
    return sorted_indexes

# Get indexes above a certain threshold
def get_indexes_above_threshold(df, column, threshold):
    """Get indexes where column values are above threshold"""
    above_threshold_indexes = df[df[column] > threshold].index.tolist()
    return above_threshold_indexes


# print("DataFrame:")
# print(df)
# print("\n" + "="*50)

# Get top 5 indexes
top_5_indexes = get_top_n_indexes(df, 'mean_accuracy', 5)
print(f"\nTop 5 indexes by mean_accuracy:")
print(f"Indexes: {top_5_indexes}")
print("Corresponding configurations and values:")
for idx in top_5_indexes:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_accuracy']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Get all indexes sorted
all_sorted_indexes = get_all_indexes_sorted(df, 'mean_accuracy')
print(f"\nAll indexes sorted by mean_accuracy (highest to lowest):")
print(f"Indexes: {all_sorted_indexes}")

# Get indexes above threshold (e.g., 0.55)
threshold = 0.55
above_threshold = get_indexes_above_threshold(df, 'mean_accuracy', threshold)
print(f"\nIndexes with mean_accuracy > {threshold}:")
print(f"Indexes: {above_threshold}")
print("Corresponding configurations and values:")
for idx in above_threshold:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_accuracy']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Highest value index
max_index = df['mean_accuracy'].idxmax()
max_value = df.loc[max_index, 'mean_accuracy']
max_config = df.loc[max_index, 'config']
print(f"\nHighest mean_accuracy:")
print(f"Index {max_index}: {max_config} = {max_value:.6f}")

Top 5 indexes by mean_accuracy:
Indexes: [9, 6, 5, 0, 4]
Corresponding configurations and values:
  Index 9: 4s_no = 0.654436
  Index 6: 3s_no = 0.636562
  Index 5: 2s_0.8 = 0.625411
  Index 0: 1s_no = 0.613319
  Index 4: 2s_0.5 = 0.612498

All indexes sorted by mean_accuracy (highest to lowest):
Indexes: [9, 6, 5, 0, 4, 10, 14, 12, 11, 3, 2, 7, 8, 1, 13]

Indexes with mean_accuracy > 0.55:
Indexes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
Corresponding configurations and values:
  Index 0: 1s_no = 0.613319
  Index 1: 1s_0.5 = 0.599250
  Index 2: 1s_0.8 = 0.605824
  Index 3: 2s_no = 0.607040
  Index 4: 2s_0.5 = 0.612498
  Index 5: 2s_0.8 = 0.625411
  Index 6: 3s_no = 0.636562
  Index 7: 3s_0.5 = 0.604478
  Index 8: 3s_0.8 = 0.600139
  Index 9: 4s_no = 0.654436
  Index 10: 4s_0.5 = 0.611227
  Index 11: 4s_0.8 = 0.607564
  Index 12: 5s_no = 0.608125
  Index 13: 5s_0.5 = 0.584747
  Index 14: 5s_0.8 = 0.609862

Highest mean_accuracy:
Index 9: 4s_no = 0.654436

## Oversample

In [7]:
mean_accuracy = []
std_accuracy = []
mean_recall_void = []
std_recall_void = []
for win_data, data in xgb_results.items(): 
    data_ = data["oversample_smote"]
    
    mean_accuracy.append(data_['mean_accuracy'])
    std_accuracy.append(data_['std_accuracy'])
    mean_recall_void.append(data_['mean_recall_minority'])
    std_recall_void.append(data_['std_recall_minority'])

indexes = xgb_results.keys()
results = {
    'config': indexes,
    'mean_accuracy': mean_accuracy,
    'std_accuracy': std_accuracy,
    'mean_recall_void': mean_recall_void,
    'std_recall_void': std_recall_void
} 
    
df = pd.DataFrame(results)

In [8]:
df

    config  mean_accuracy  std_accuracy  mean_recall_void  std_recall_void
0    1s_no       0.594373      0.064151          0.510035         0.081394
1   1s_0.5       0.612837      0.074165          0.556115         0.115750
2   1s_0.8       0.607846      0.083267          0.489759         0.153856
3    2s_no       0.610707      0.097874          0.493948         0.121232
4   2s_0.5       0.635783      0.047736          0.556440         0.098104
5   2s_0.8       0.607659      0.081110          0.514122         0.134427
6    3s_no       0.539291      0.071037          0.477187         0.089886
7   3s_0.5       0.623084      0.048911          0.563428         0.124316
8   3s_0.8       0.614605      0.073698          0.532075         0.152252
9    4s_no       0.585636      0.128985          0.459232         0.173982
10  4s_0.5       0.582411      0.057401          0.496962         0.152661
11  4s_0.8       0.584563      0.070633          0.551866         0.106279
12   5s_no       0.575969      0.104797          0.437160         0.206973
13  5s_0.5       0.592425      0.065681          0.514890         0.126878
14  5s_0.8       0.587244      0.100311          0.561702         0.094464

In [9]:
# Get indexes of top N values using nlargest()
def get_top_n_indexes(df, column, n=5):
    """Get indexes of top N values in specified column"""
    top_indexes = df.nlargest(n, column).index.tolist()
    return top_indexes

# Get indexes using argsort() for all values (sorted)
def get_all_indexes_sorted(df, column):
    """Get all indexes sorted by column values (highest to lowest)"""
    sorted_indexes = df[column].argsort()[::-1].tolist()
    return sorted_indexes

# Get indexes above a certain threshold
def get_indexes_above_threshold(df, column, threshold):
    """Get indexes where column values are above threshold"""
    above_threshold_indexes = df[df[column] > threshold].index.tolist()
    return above_threshold_indexes


# print("DataFrame:")
# print(df)
# print("\n" + "="*50)

# Get top 5 indexes
top_5_indexes = get_top_n_indexes(df, 'mean_recall_void', 5)
print(f"\nTop 5 indexes by mean_recall_void:")
print(f"Indexes: {top_5_indexes}")
print("Corresponding configurations and values:")
for idx in top_5_indexes:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_recall_void']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Get all indexes sorted
all_sorted_indexes = get_all_indexes_sorted(df, 'mean_recall_void')
print(f"\nAll indexes sorted by mean_recall_void (highest to lowest):")
print(f"Indexes: {all_sorted_indexes}")

# Get indexes above threshold (e.g., 0.55)
threshold = 0.55
above_threshold = get_indexes_above_threshold(df, 'mean_recall_void', threshold)
print(f"\nIndexes with mean_recall_void > {threshold}:")
print(f"Indexes: {above_threshold}")
print("Corresponding configurations and values:")
for idx in above_threshold:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_recall_void']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Highest value index
max_index = df['mean_recall_void'].idxmax()
max_value = df.loc[max_index, 'mean_recall_void']
max_config = df.loc[max_index, 'config']
print(f"\nHighest mean_recall_void:")
print(f"Index {max_index}: {max_config} = {max_value:.6f}")

Top 5 indexes by mean_recall_void:
Indexes: [7, 14, 4, 1, 11]
Corresponding configurations and values:
  Index 7: 3s_0.5 = 0.563428
  Index 14: 5s_0.8 = 0.561702
  Index 4: 2s_0.5 = 0.556440
  Index 1: 1s_0.5 = 0.556115
  Index 11: 4s_0.8 = 0.551866

All indexes sorted by mean_recall_void (highest to lowest):
Indexes: [7, 14, 4, 1, 11, 8, 13, 5, 0, 10, 3, 2, 6, 9, 12]

Indexes with mean_recall_void > 0.55:
Indexes: [1, 4, 7, 11, 14]
Corresponding configurations and values:
  Index 1: 1s_0.5 = 0.556115
  Index 4: 2s_0.5 = 0.556440
  Index 7: 3s_0.5 = 0.563428
  Index 11: 4s_0.8 = 0.551866
  Index 14: 5s_0.8 = 0.561702

Highest mean_recall_void:
Index 7: 3s_0.5 = 0.563428

In [10]:
# Get indexes of top N values using nlargest()
def get_top_n_indexes(df, column, n=5):
    """Get indexes of top N values in specified column"""
    top_indexes = df.nlargest(n, column).index.tolist()
    return top_indexes

# Get indexes using argsort() for all values (sorted)
def get_all_indexes_sorted(df, column):
    """Get all indexes sorted by column values (highest to lowest)"""
    sorted_indexes = df[column].argsort()[::-1].tolist()
    return sorted_indexes

# Get indexes above a certain threshold
def get_indexes_above_threshold(df, column, threshold):
    """Get indexes where column values are above threshold"""
    above_threshold_indexes = df[df[column] > threshold].index.tolist()
    return above_threshold_indexes


# print("DataFrame:")
# print(df)
# print("\n" + "="*50)

# Get top 5 indexes
top_5_indexes = get_top_n_indexes(df, 'mean_accuracy', 5)
print(f"\nTop 5 indexes by mean_accuracy:")
print(f"Indexes: {top_5_indexes}")
print("Corresponding configurations and values:")
for idx in top_5_indexes:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_accuracy']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Get all indexes sorted
all_sorted_indexes = get_all_indexes_sorted(df, 'mean_accuracy')
print(f"\nAll indexes sorted by mean_accuracy (highest to lowest):")
print(f"Indexes: {all_sorted_indexes}")

# Get indexes above threshold (e.g., 0.55)
threshold = 0.55
above_threshold = get_indexes_above_threshold(df, 'mean_accuracy', threshold)
print(f"\nIndexes with mean_accuracy > {threshold}:")
print(f"Indexes: {above_threshold}")
print("Corresponding configurations and values:")
for idx in above_threshold:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_accuracy']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Highest value index
max_index = df['mean_accuracy'].idxmax()
max_value = df.loc[max_index, 'mean_accuracy']
max_config = df.loc[max_index, 'config']
print(f"\nHighest mean_accuracy:")
print(f"Index {max_index}: {max_config} = {max_value:.6f}")

Top 5 indexes by mean_accuracy:
Indexes: [4, 7, 8, 1, 3]
Corresponding configurations and values:
  Index 4: 2s_0.5 = 0.635783
  Index 7: 3s_0.5 = 0.623084
  Index 8: 3s_0.8 = 0.614605
  Index 1: 1s_0.5 = 0.612837
  Index 3: 2s_no = 0.610707

All indexes sorted by mean_accuracy (highest to lowest):
Indexes: [4, 7, 8, 1, 3, 2, 5, 0, 13, 14, 9, 11, 10, 12, 6]

Indexes with mean_accuracy > 0.55:
Indexes: [0, 1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 14]
Corresponding configurations and values:
  Index 0: 1s_no = 0.594373
  Index 1: 1s_0.5 = 0.612837
  Index 2: 1s_0.8 = 0.607846
  Index 3: 2s_no = 0.610707
  Index 4: 2s_0.5 = 0.635783
  Index 5: 2s_0.8 = 0.607659
  Index 7: 3s_0.5 = 0.623084
  Index 8: 3s_0.8 = 0.614605
  Index 9: 4s_no = 0.585636
  Index 10: 4s_0.5 = 0.582411
  Index 11: 4s_0.8 = 0.584563
  Index 12: 5s_no = 0.575969
  Index 13: 5s_0.5 = 0.592425
  Index 14: 5s_0.8 = 0.587244

Highest mean_accuracy:
Index 4: 2s_0.5 = 0.635783

## Undersample

In [11]:
mean_accuracy = []
std_accuracy = []
mean_recall_void = []
std_recall_void = []
for win_data, data in xgb_results.items(): 
    data_ = data["undersample_tomek_links"]
    
    mean_accuracy.append(data_['mean_accuracy'])
    std_accuracy.append(data_['std_accuracy'])
    mean_recall_void.append(data_['mean_recall_minority'])
    std_recall_void.append(data_['std_recall_minority'])

indexes = xgb_results.keys()
results = {
    'config': indexes,
    'mean_accuracy': mean_accuracy,
    'std_accuracy': std_accuracy,
    'mean_recall_void': mean_recall_void,
    'std_recall_void': std_recall_void
} 
    
df = pd.DataFrame(results)

In [12]:
df

    config  mean_accuracy  std_accuracy  mean_recall_void  std_recall_void
0    1s_no       0.600476      0.068433          0.515555         0.095059
1   1s_0.5       0.612765      0.060479          0.528280         0.099985
2   1s_0.8       0.603158      0.081053          0.452793         0.160853
3    2s_no       0.648442      0.080143          0.635889         0.134875
4   2s_0.5       0.619707      0.039085          0.552243         0.072404
5   2s_0.8       0.609201      0.079388          0.551375         0.168218
6    3s_no       0.613483      0.095089          0.602959         0.138735
7   3s_0.5       0.603284      0.050686          0.528352         0.092425
8   3s_0.8       0.620363      0.063956          0.548138         0.092340
9    4s_no       0.586087      0.089240          0.478327         0.115219
10  4s_0.5       0.612316      0.099598          0.542817         0.163417
11  4s_0.8       0.596807      0.076872          0.531160         0.157668
12   5s_no       0.619402      0.089262          0.604767         0.115610
13  5s_0.5       0.618714      0.069746          0.556558         0.119249
14  5s_0.8       0.621087      0.062443          0.549239         0.104455

In [13]:
# Get indexes of top N values using nlargest()
def get_top_n_indexes(df, column, n=5):
    """Get indexes of top N values in specified column"""
    top_indexes = df.nlargest(n, column).index.tolist()
    return top_indexes

# Get indexes using argsort() for all values (sorted)
def get_all_indexes_sorted(df, column):
    """Get all indexes sorted by column values (highest to lowest)"""
    sorted_indexes = df[column].argsort()[::-1].tolist()
    return sorted_indexes

# Get indexes above a certain threshold
def get_indexes_above_threshold(df, column, threshold):
    """Get indexes where column values are above threshold"""
    above_threshold_indexes = df[df[column] > threshold].index.tolist()
    return above_threshold_indexes


# print("DataFrame:")
# print(df)
# print("\n" + "="*50)

# Get top 5 indexes
top_5_indexes = get_top_n_indexes(df, 'mean_recall_void', 5)
print(f"\nTop 5 indexes by mean_recall_void:")
print(f"Indexes: {top_5_indexes}")
print("Corresponding configurations and values:")
for idx in top_5_indexes:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_recall_void']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Get all indexes sorted
all_sorted_indexes = get_all_indexes_sorted(df, 'mean_recall_void')
print(f"\nAll indexes sorted by mean_recall_void (highest to lowest):")
print(f"Indexes: {all_sorted_indexes}")

# Get indexes above threshold (e.g., 0.55)
threshold = 0.55
above_threshold = get_indexes_above_threshold(df, 'mean_recall_void', threshold)
print(f"\nIndexes with mean_recall_void > {threshold}:")
print(f"Indexes: {above_threshold}")
print("Corresponding configurations and values:")
for idx in above_threshold:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_recall_void']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Highest value index
max_index = df['mean_recall_void'].idxmax()
max_value = df.loc[max_index, 'mean_recall_void']
max_config = df.loc[max_index, 'config']
print(f"\nHighest mean_recall_void:")
print(f"Index {max_index}: {max_config} = {max_value:.6f}")

Top 5 indexes by mean_recall_void:
Indexes: [3, 12, 6, 13, 4]
Corresponding configurations and values:
  Index 3: 2s_no = 0.635889
  Index 12: 5s_no = 0.604767
  Index 6: 3s_no = 0.602959
  Index 13: 5s_0.5 = 0.556558
  Index 4: 2s_0.5 = 0.552243

All indexes sorted by mean_recall_void (highest to lowest):
Indexes: [3, 12, 6, 13, 4, 5, 14, 8, 10, 11, 7, 1, 0, 9, 2]

Indexes with mean_recall_void > 0.55:
Indexes: [3, 4, 5, 6, 12, 13]
Corresponding configurations and values:
  Index 3: 2s_no = 0.635889
  Index 4: 2s_0.5 = 0.552243
  Index 5: 2s_0.8 = 0.551375
  Index 6: 3s_no = 0.602959
  Index 12: 5s_no = 0.604767
  Index 13: 5s_0.5 = 0.556558

Highest mean_recall_void:
Index 3: 2s_no = 0.635889

In [14]:
# Get indexes of top N values using nlargest()
def get_top_n_indexes(df, column, n=5):
    """Get indexes of top N values in specified column"""
    top_indexes = df.nlargest(n, column).index.tolist()
    return top_indexes

# Get indexes using argsort() for all values (sorted)
def get_all_indexes_sorted(df, column):
    """Get all indexes sorted by column values (highest to lowest)"""
    sorted_indexes = df[column].argsort()[::-1].tolist()
    return sorted_indexes

# Get indexes above a certain threshold
def get_indexes_above_threshold(df, column, threshold):
    """Get indexes where column values are above threshold"""
    above_threshold_indexes = df[df[column] > threshold].index.tolist()
    return above_threshold_indexes


# print("DataFrame:")
# print(df)
# print("\n" + "="*50)

# Get top 5 indexes
top_5_indexes = get_top_n_indexes(df, 'mean_accuracy', 5)
print(f"\nTop 5 indexes by mean_accuracy:")
print(f"Indexes: {top_5_indexes}")
print("Corresponding configurations and values:")
for idx in top_5_indexes:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_accuracy']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Get all indexes sorted
all_sorted_indexes = get_all_indexes_sorted(df, 'mean_accuracy')
print(f"\nAll indexes sorted by mean_accuracy (highest to lowest):")
print(f"Indexes: {all_sorted_indexes}")

# Get indexes above threshold (e.g., 0.55)
threshold = 0.55
above_threshold = get_indexes_above_threshold(df, 'mean_accuracy', threshold)
print(f"\nIndexes with mean_accuracy > {threshold}:")
print(f"Indexes: {above_threshold}")
print("Corresponding configurations and values:")
for idx in above_threshold:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_accuracy']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Highest value index
max_index = df['mean_accuracy'].idxmax()
max_value = df.loc[max_index, 'mean_accuracy']
max_config = df.loc[max_index, 'config']
print(f"\nHighest mean_accuracy:")
print(f"Index {max_index}: {max_config} = {max_value:.6f}")

Top 5 indexes by mean_accuracy:
Indexes: [3, 14, 8, 4, 12]
Corresponding configurations and values:
  Index 3: 2s_no = 0.648442
  Index 14: 5s_0.8 = 0.621087
  Index 8: 3s_0.8 = 0.620363
  Index 4: 2s_0.5 = 0.619707
  Index 12: 5s_no = 0.619402

All indexes sorted by mean_accuracy (highest to lowest):
Indexes: [3, 14, 8, 4, 12, 13, 6, 1, 10, 5, 7, 2, 0, 11, 9]

Indexes with mean_accuracy > 0.55:
Indexes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
Corresponding configurations and values:
  Index 0: 1s_no = 0.600476
  Index 1: 1s_0.5 = 0.612765
  Index 2: 1s_0.8 = 0.603158
  Index 3: 2s_no = 0.648442
  Index 4: 2s_0.5 = 0.619707
  Index 5: 2s_0.8 = 0.609201
  Index 6: 3s_no = 0.613483
  Index 7: 3s_0.5 = 0.603284
  Index 8: 3s_0.8 = 0.620363
  Index 9: 4s_no = 0.586087
  Index 10: 4s_0.5 = 0.612316
  Index 11: 4s_0.8 = 0.596807
  Index 12: 5s_no = 0.619402
  Index 13: 5s_0.5 = 0.618714
  Index 14: 5s_0.8 = 0.621087

Highest mean_accuracy:
Index 3: 2s_no = 0.648442

## Combined Smote Tomek

In [15]:
mean_accuracy = []
std_accuracy = []
mean_recall_void = []
std_recall_void = []
for win_data, data in xgb_results.items(): 
    data_ = data["combined_smote_tomek"]
    
    mean_accuracy.append(data_['mean_accuracy'])
    std_accuracy.append(data_['std_accuracy'])
    mean_recall_void.append(data_['mean_recall_minority'])
    std_recall_void.append(data_['std_recall_minority'])

indexes = xgb_results.keys()
results = {
    'config': indexes,
    'mean_accuracy': mean_accuracy,
    'std_accuracy': std_accuracy,
    'mean_recall_void': mean_recall_void,
    'std_recall_void': std_recall_void
} 
    
df = pd.DataFrame(results)

In [16]:
df

    config  mean_accuracy  std_accuracy  mean_recall_void  std_recall_void
0    1s_no       0.599988      0.047750          0.504168         0.072353
1   1s_0.5       0.613497      0.065422          0.527348         0.126330
2   1s_0.8       0.610887      0.081066          0.499551         0.139541
3    2s_no       0.600817      0.101778          0.497612         0.157964
4   2s_0.5       0.611854      0.061500          0.544671         0.090147
5   2s_0.8       0.611538      0.099921          0.516809         0.167930
6    3s_no       0.622172      0.107058          0.549228         0.140870
7   3s_0.5       0.602292      0.060970          0.531276         0.120918
8   3s_0.8       0.615730      0.078651          0.531590         0.139461
9    4s_no       0.631821      0.133491          0.588840         0.238514
10  4s_0.5       0.599014      0.082740          0.532011         0.116918
11  4s_0.8       0.583594      0.066225          0.532536         0.091077
12   5s_no       0.650115      0.109844          0.645866         0.191352
13  5s_0.5       0.623175      0.084384          0.504141         0.087878
14  5s_0.8       0.613577      0.094689          0.576630         0.131608

In [17]:
# Get indexes of top N values using nlargest()
def get_top_n_indexes(df, column, n=5):
    """Get indexes of top N values in specified column"""
    top_indexes = df.nlargest(n, column).index.tolist()
    return top_indexes

# Get indexes using argsort() for all values (sorted)
def get_all_indexes_sorted(df, column):
    """Get all indexes sorted by column values (highest to lowest)"""
    sorted_indexes = df[column].argsort()[::-1].tolist()
    return sorted_indexes

# Get indexes above a certain threshold
def get_indexes_above_threshold(df, column, threshold):
    """Get indexes where column values are above threshold"""
    above_threshold_indexes = df[df[column] > threshold].index.tolist()
    return above_threshold_indexes


# print("DataFrame:")
# print(df)
# print("\n" + "="*50)

# Get top 5 indexes
top_5_indexes = get_top_n_indexes(df, 'mean_recall_void', 5)
print(f"\nTop 5 indexes by mean_recall_void:")
print(f"Indexes: {top_5_indexes}")
print("Corresponding configurations and values:")
for idx in top_5_indexes:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_recall_void']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Get all indexes sorted
all_sorted_indexes = get_all_indexes_sorted(df, 'mean_recall_void')
print(f"\nAll indexes sorted by mean_recall_void (highest to lowest):")
print(f"Indexes: {all_sorted_indexes}")

# Get indexes above threshold (e.g., 0.55)
threshold = 0.55
above_threshold = get_indexes_above_threshold(df, 'mean_recall_void', threshold)
print(f"\nIndexes with mean_recall_void > {threshold}:")
print(f"Indexes: {above_threshold}")
print("Corresponding configurations and values:")
for idx in above_threshold:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_recall_void']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Highest value index
max_index = df['mean_recall_void'].idxmax()
max_value = df.loc[max_index, 'mean_recall_void']
max_config = df.loc[max_index, 'config']
print(f"\nHighest mean_recall_void:")
print(f"Index {max_index}: {max_config} = {max_value:.6f}")

Top 5 indexes by mean_recall_void:
Indexes: [12, 9, 14, 6, 4]
Corresponding configurations and values:
  Index 12: 5s_no = 0.645866
  Index 9: 4s_no = 0.588840
  Index 14: 5s_0.8 = 0.576630
  Index 6: 3s_no = 0.549228
  Index 4: 2s_0.5 = 0.544671

All indexes sorted by mean_recall_void (highest to lowest):
Indexes: [12, 9, 14, 6, 4, 11, 10, 8, 7, 1, 5, 0, 13, 2, 3]

Indexes with mean_recall_void > 0.55:
Indexes: [9, 12, 14]
Corresponding configurations and values:
  Index 9: 4s_no = 0.588840
  Index 12: 5s_no = 0.645866
  Index 14: 5s_0.8 = 0.576630

Highest mean_recall_void:
Index 12: 5s_no = 0.645866

In [18]:
# Get indexes of top N values using nlargest()
def get_top_n_indexes(df, column, n=5):
    """Get indexes of top N values in specified column"""
    top_indexes = df.nlargest(n, column).index.tolist()
    return top_indexes

# Get indexes using argsort() for all values (sorted)
def get_all_indexes_sorted(df, column):
    """Get all indexes sorted by column values (highest to lowest)"""
    sorted_indexes = df[column].argsort()[::-1].tolist()
    return sorted_indexes

# Get indexes above a certain threshold
def get_indexes_above_threshold(df, column, threshold):
    """Get indexes where column values are above threshold"""
    above_threshold_indexes = df[df[column] > threshold].index.tolist()
    return above_threshold_indexes


# print("DataFrame:")
# print(df)
# print("\n" + "="*50)

# Get top 5 indexes
top_5_indexes = get_top_n_indexes(df, 'mean_accuracy', 5)
print(f"\nTop 5 indexes by mean_accuracy:")
print(f"Indexes: {top_5_indexes}")
print("Corresponding configurations and values:")
for idx in top_5_indexes:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_accuracy']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Get all indexes sorted
all_sorted_indexes = get_all_indexes_sorted(df, 'mean_accuracy')
print(f"\nAll indexes sorted by mean_accuracy (highest to lowest):")
print(f"Indexes: {all_sorted_indexes}")

# Get indexes above threshold (e.g., 0.55)
threshold = 0.55
above_threshold = get_indexes_above_threshold(df, 'mean_accuracy', threshold)
print(f"\nIndexes with mean_accuracy > {threshold}:")
print(f"Indexes: {above_threshold}")
print("Corresponding configurations and values:")
for idx in above_threshold:
    config = df.loc[idx, 'config']
    value = df.loc[idx, 'mean_accuracy']
    print(f"  Index {idx}: {config} = {value:.6f}")

# Highest value index
max_index = df['mean_accuracy'].idxmax()
max_value = df.loc[max_index, 'mean_accuracy']
max_config = df.loc[max_index, 'config']
print(f"\nHighest mean_accuracy:")
print(f"Index {max_index}: {max_config} = {max_value:.6f}")

Top 5 indexes by mean_accuracy:
Indexes: [12, 9, 13, 6, 8]
Corresponding configurations and values:
  Index 12: 5s_no = 0.650115
  Index 9: 4s_no = 0.631821
  Index 13: 5s_0.5 = 0.623175
  Index 6: 3s_no = 0.622172
  Index 8: 3s_0.8 = 0.615730

All indexes sorted by mean_accuracy (highest to lowest):
Indexes: [12, 9, 13, 6, 8, 14, 1, 4, 5, 2, 7, 3, 0, 10, 11]

Indexes with mean_accuracy > 0.55:
Indexes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
Corresponding configurations and values:
  Index 0: 1s_no = 0.599988
  Index 1: 1s_0.5 = 0.613497
  Index 2: 1s_0.8 = 0.610887
  Index 3: 2s_no = 0.600817
  Index 4: 2s_0.5 = 0.611854
  Index 5: 2s_0.8 = 0.611538
  Index 6: 3s_no = 0.622172
  Index 7: 3s_0.5 = 0.602292
  Index 8: 3s_0.8 = 0.615730
  Index 9: 4s_no = 0.631821
  Index 10: 4s_0.5 = 0.599014
  Index 11: 4s_0.8 = 0.583594
  Index 12: 5s_no = 0.650115
  Index 13: 5s_0.5 = 0.623175
  Index 14: 5s_0.8 = 0.613577

Highest mean_accuracy:
Index 12: 5s_no = 0.650115