In [9]:
import os
import pickle
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from tqdm import tqdm
from essentials import resample_data, three_class_labels, two_class_labels, normalize
from features_acc_gyr_improved import GenerateFeatures 
import copy

Extract windowed features from the 3 axis of the accelerometer and the acceleration magnitude.
1. mean
2. rms
3. std
4. range
5. variance
6. min
7. max
8. time energy
9. spectral energy
10. permutation entropy
11. spectral entropy
12. spectral_centroid
13. spectral_spread
14. spectral_flatness
15. peak_frequency_ratio
16. hjorth_frequency
17. spectral_skewness
18. spectral_kurtosis
19. snr

## Three (3) class data

In [10]:
with open('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/test_data_with_3_class_labels.pkl', 'rb') as f:
    test_data_3_class_labelled = pickle.load(f)

## Data 1
classes: void, non-void

fs: original

sliding window: 1s

overlap: 0

filename: two_class_1s_no.csv

In [11]:
#  do not upsample
all_features = []
for i, exp_id in enumerate(test_data_3_class_labelled.keys()):    
    # Extract features
    
    df = test_data_3_class_labelled[exp_id]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=1.0, overlap=0.0)
    features, _ = analyzer.analyze_multi_axis_imu(test_data_3_class_labelled[exp_id])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id 
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.28it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.03it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.40it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.85it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.60it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.53it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.97it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.82it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.34it/s]

In [12]:
final_features.to_csv('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/extracted_features_data/3_class/test_set/two_class_1s_no.csv', index=False)
final_features

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,0.499464,0.000000,0.998928,0.708341,0.485641,-0.285321,0.229972,0.856918,0.366463,0.052887,...,3.642437,2.511770,0.025061,0.256964,7.194381,1.514172,6.705851,-4.611387,pre-void,5
1,1.498391,0.998928,1.997855,0.867759,0.716267,0.086876,0.069697,0.245330,0.111378,0.004858,...,2.251301,1.742587,0.020095,0.369493,7.898319,4.070010,35.549119,-2.320846,pre-void,5
2,2.497319,1.997855,2.996783,0.783083,0.429708,0.086064,0.145038,0.580256,0.168651,0.021036,...,3.108773,2.857275,0.075154,0.316381,8.885294,2.707666,14.141163,-3.346033,pre-void,5
3,3.496246,2.996783,3.995710,0.843674,0.741431,0.059207,0.029353,0.142897,0.066084,0.000862,...,4.073793,4.614036,0.145401,0.468783,10.191830,1.789849,6.559483,-0.543001,pre-void,5
4,4.495174,3.995710,4.994638,0.834573,0.467505,0.075879,0.117194,0.585752,0.139614,0.013734,...,6.233209,3.804798,0.173085,0.157667,8.929172,1.095824,5.549054,-7.277440,pre-void,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
637,36.229895,35.733595,36.726195,0.861280,0.934936,-0.750239,0.071628,0.299625,0.753651,0.005131,...,7.153462,7.459690,0.414081,0.219796,14.762401,1.197519,3.319281,-5.501879,post-void,41
638,37.222495,36.726195,37.718795,0.885975,0.883050,-0.729479,0.066856,0.430755,0.732536,0.004470,...,7.712756,7.456241,0.271287,0.365839,14.159306,0.791509,2.570576,-2.389096,post-void,41
639,38.215095,37.718795,38.711394,0.927914,0.874430,-0.474310,0.087309,0.327923,0.482278,0.007623,...,3.952352,5.073782,0.134710,0.481806,13.242283,2.087197,7.114907,-0.316204,post-void,41
640,39.207694,38.711394,39.703994,0.914823,0.887964,-0.462066,0.080636,0.388335,0.469049,0.006502,...,9.693511,7.599868,0.331264,0.251665,13.517811,0.549851,2.066472,-4.732730,post-void,41
641,40.200294,39.703994,40.696594,0.942786,0.828630,-0.541521,0.103851,0.462256,0.551389,0.010785,...,8.930709,7.120587,0.530602,0.152081,14.277454,0.788799,2.577106,-7.462803,post-void,41

## Data 1b
classes: void, non-void

fs: original

sliding window: 1s

overlap: 0.5

filename: two_class_1s_0.5.csv

In [13]:
#  do not upsample
all_features = []
for i, exp_id in enumerate(test_data_3_class_labelled.keys()):    
    # Extract features
    
    df = test_data_3_class_labelled[exp_id]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=1.0, overlap=0.5)
    features, _ = analyzer.analyze_multi_axis_imu(test_data_3_class_labelled[exp_id])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id 
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.68it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.51it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.28it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.69it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.50it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.28it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.79it/s]
Analyzing : 100%|██████████| 8/8 [00:05<00:00,  1.46it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.49it/s]

In [14]:
final_features.to_csv('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/extracted_features_data/3_class/test_set/two_class_1s_0.5.csv', index=False)
final_features

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,0.499464,0.000000,0.998928,0.708341,0.485641,-0.285321,0.229972,0.856918,0.366463,0.052887,...,3.642437,2.511770,0.025061,0.256964,7.194381,1.514172,6.705851,-4.611387,pre-void,5
1,1.007393,0.507929,1.506857,0.757774,0.660873,-0.017798,0.160557,0.707477,0.161540,0.025779,...,2.451574,2.115860,0.021601,0.445767,6.966709,2.750391,17.685274,-0.945845,pre-void,5
2,1.515322,1.015859,2.014786,0.866209,0.736374,0.084986,0.071470,0.245330,0.111043,0.005108,...,2.267099,1.825784,0.021970,0.372928,8.023669,4.193574,35.615560,-2.256916,pre-void,5
3,2.023252,1.523788,2.522715,0.852848,0.537112,0.056168,0.118519,0.520797,0.131155,0.014047,...,2.903186,3.255079,0.056175,0.397089,9.584047,2.710967,11.185670,-1.813661,pre-void,5
4,2.531181,2.031717,3.030645,0.791533,0.425662,0.086691,0.144605,0.580256,0.168600,0.020911,...,3.163946,2.938622,0.078086,0.319582,8.879355,2.671515,13.839417,-3.281935,pre-void,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1272,38.711394,38.215095,39.207694,0.959091,0.869244,-0.433725,0.060597,0.261570,0.437938,0.003672,...,9.436021,5.559268,0.326310,0.112827,13.319638,0.930497,3.825502,-8.955961,post-void,41
1273,39.207694,38.711394,39.703994,0.914823,0.887964,-0.462066,0.080636,0.388335,0.469049,0.006502,...,9.693511,7.599868,0.331264,0.251665,13.517811,0.549851,2.066472,-4.732730,post-void,41
1274,39.703994,39.207694,40.200294,0.931853,0.796717,-0.500712,0.105197,0.418931,0.511643,0.011066,...,6.565994,5.481007,0.282093,0.250669,13.456472,1.752950,6.621199,-4.755720,post-void,41
1275,40.200294,39.703994,40.696594,0.942786,0.828630,-0.541521,0.103851,0.462256,0.551389,0.010785,...,8.930709,7.120587,0.530602,0.152081,14.277454,0.788799,2.577106,-7.462803,post-void,41
1276,40.696594,40.200294,41.192894,0.856466,0.886367,-0.632235,0.113074,0.407022,0.642266,0.012786,...,5.970484,5.971771,0.345971,0.208746,13.135917,1.510750,4.473820,-5.786987,post-void,41

## Data 1c
classes: void, non-void

fs: original

sliding window: 1s

overlap: 0.8

filename: two_class_1s_0.8.csv

In [15]:
all_features = []
for i, exp_id in enumerate(test_data_3_class_labelled.keys()):    
    # Extract features
    
    df = test_data_3_class_labelled[exp_id]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=1.0, overlap=0.8)
    features, _ = analyzer.analyze_multi_axis_imu(test_data_3_class_labelled[exp_id])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id 
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.20it/s]
Analyzing : 100%|██████████| 8/8 [00:05<00:00,  1.39it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.76it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.20it/s]
Analyzing : 100%|██████████| 8/8 [00:05<00:00,  1.42it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.71it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.18it/s]
Analyzing : 100%|██████████| 8/8 [00:14<00:00,  1.78s/it]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.75it/s]

In [16]:
final_features.to_csv('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/extracted_features_data/3_class/test_set/two_class_1s_0.8.csv', index=False)
final_features

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,0.499464,0.000000,0.998928,0.708341,0.485641,-0.285321,0.229972,0.856918,0.366463,0.052887,...,3.642437,2.511770,0.025061,0.256964,7.194381,1.514172,6.705851,-4.611387,pre-void,5
1,0.702635,0.203172,1.202099,0.655888,0.512797,-0.173127,0.212504,0.801547,0.274100,0.045158,...,2.797195,2.305788,0.015336,0.328993,7.514798,2.275486,9.546737,-3.095406,pre-void,5
2,0.905807,0.406343,1.405271,0.743236,0.602406,-0.080848,0.219248,0.801547,0.233680,0.048070,...,1.917764,1.776869,0.014850,0.533292,6.942888,4.066633,28.799493,0.579205,pre-void,5
3,1.108979,0.609515,1.608443,0.778678,0.547150,0.030404,0.125473,0.469124,0.129104,0.015743,...,2.887832,2.027836,0.019039,0.319371,6.655746,2.024101,13.700176,-3.286150,pre-void,5
4,1.312151,0.812687,1.811614,0.845735,0.632488,0.095376,0.070226,0.268581,0.118441,0.004932,...,2.353159,1.610860,0.011363,0.351383,6.453911,2.402906,16.231612,-2.662079,pre-void,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3171,39.803254,39.306954,40.299554,0.954554,0.791236,-0.511152,0.098658,0.346526,0.520586,0.009733,...,6.485225,5.798090,0.311412,0.264343,14.034788,1.998490,7.231781,-4.445081,post-void,41
3172,40.001774,39.505474,40.498074,0.949137,0.820820,-0.511490,0.098087,0.346526,0.520810,0.009621,...,7.359889,6.541087,0.344417,0.204672,13.978089,1.375432,4.270821,-5.894870,post-void,41
3173,40.200294,39.703994,40.696594,0.942786,0.828630,-0.541521,0.103851,0.462256,0.551389,0.010785,...,8.930709,7.120587,0.530602,0.152081,14.277454,0.788799,2.577106,-7.462803,post-void,41
3174,40.398814,39.902514,40.895114,0.915219,0.890232,-0.590451,0.095231,0.432490,0.598082,0.009069,...,8.296628,6.701599,0.427063,0.226936,14.126448,1.152821,3.386264,-5.323113,post-void,41
3175,40.597334,40.101034,41.093634,0.900785,0.879770,-0.620651,0.108745,0.407022,0.630106,0.011825,...,6.809275,6.251198,0.395929,0.290911,13.955809,1.334520,3.914314,-3.869407,post-void,41

## Data 2
classes: void, non-void

fs: original

overlap: 0

sliding window: 2s

filename: two_class_2s_no.csv

In [17]:
all_features = []
for i, exp_id in enumerate(test_data_3_class_labelled.keys()):    
    # Extract features
    
    df = test_data_3_class_labelled[exp_id]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=2.0, overlap=0.0)
    features, _ = analyzer.analyze_multi_axis_imu(test_data_3_class_labelled[exp_id])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id 
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 29.27it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.49it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.45it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 32.57it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.79it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.24it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 22.42it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.39it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.51it/s]

In [18]:
final_features.to_csv('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/extracted_features_data/3_class/test_set/two_class_2s_no.csv', index=False)
final_features

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,0.998928,0.000000,1.997855,0.805241,0.558966,-0.099222,0.252002,0.856918,0.270832,0.063505,...,1.441709,1.735797,0.007825,0.586302,7.345245,3.186220,19.407455,1.514385,pre-void,5
1,2.996783,1.997855,3.995710,0.842921,0.473492,0.072635,0.105495,0.580256,0.128082,0.011129,...,2.270149,2.519989,0.042313,0.299367,9.333246,3.278504,20.909223,-3.692863,pre-void,5
2,4.994638,3.995710,5.993565,0.842683,0.585986,0.046851,0.112579,0.585752,0.121939,0.012674,...,3.659089,3.587570,0.054537,0.285383,8.816397,1.253723,4.551026,-3.986444,pre-void,5
3,6.992493,5.993565,7.991420,0.865196,0.778191,-0.043539,0.043794,0.207831,0.061753,0.001918,...,3.988943,3.972753,0.092473,0.253017,10.381293,1.766863,6.913248,-4.701617,void,5
4,8.990348,7.991420,9.989275,0.883331,0.755679,-0.093905,0.030432,0.164518,0.098713,0.000926,...,3.031200,3.970240,0.084866,0.385419,10.371411,1.946497,6.946361,-2.026462,void,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311,31.027017,30.026146,32.027889,0.901531,0.782364,-0.046652,0.338668,1.371048,0.341866,0.114696,...,2.456019,3.741641,0.073296,0.368494,12.651439,3.385471,15.393039,-2.339478,post-void,41
312,33.028760,32.027889,34.029632,0.918177,0.865952,0.554673,0.109647,0.524994,0.565406,0.012022,...,4.791691,7.212122,0.221270,0.428145,14.726866,1.880014,5.757490,-1.256952,post-void,41
313,35.030503,34.029632,36.031375,0.890261,0.716038,-0.361387,0.394131,1.452864,0.534733,0.155339,...,1.197572,2.291588,0.027231,0.508241,13.053376,6.972747,58.407683,0.143170,post-void,41
314,37.032246,36.031375,38.033118,0.881252,0.897407,-0.714302,0.101015,0.636668,0.721409,0.010204,...,8.548022,7.262810,0.312377,0.208881,14.278420,0.427669,1.993175,-5.783435,post-void,41
315,39.033989,38.033118,40.034861,0.938400,0.887951,-0.456412,0.080598,0.418931,0.463474,0.006496,...,8.888692,6.375376,0.381760,0.188383,13.390484,0.831932,3.049167,-6.343083,post-void,41

## Data 2b
classes: void, non-void

fs: original

overlap: 0.5

sliding window: 2s

filename: two_class_2s_0.5.csv

In [19]:
all_features = []
for i, exp_id in enumerate(test_data_3_class_labelled.keys()):    
    # Extract features
    
    df = test_data_3_class_labelled[exp_id]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=2.0, overlap=0.5)
    features, _ = analyzer.analyze_multi_axis_imu(test_data_3_class_labelled[exp_id])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id 
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.03it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.99it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.85it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.08it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.86it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.37it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.86it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.65it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.75it/s]

In [20]:
final_features.to_csv('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/extracted_features_data/3_class/test_set/two_class_2s_0.5.csv', index=False)
final_features

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,0.998928,0.000000,1.997855,0.805241,0.558966,-0.099222,0.252002,0.856918,0.270832,0.063505,...,1.441709,1.735797,0.007825,0.586302,7.345245,3.186220,19.407455,1.514385,pre-void,5
1,1.997855,0.998928,2.996783,0.835954,0.667691,0.086470,0.113785,0.580256,0.142913,0.012947,...,2.659679,2.841099,0.048073,0.299128,8.529024,3.018616,14.610142,-3.697809,pre-void,5
2,2.996783,1.997855,3.995710,0.842921,0.473492,0.072635,0.105495,0.580256,0.128082,0.011129,...,2.270149,2.519989,0.042313,0.299367,9.333246,3.278504,20.909223,-3.692863,pre-void,5
3,3.995710,2.996783,4.994638,0.858970,0.760272,0.067543,0.085834,0.585752,0.109223,0.007368,...,3.263682,3.580497,0.052297,0.439214,9.302631,1.359982,5.386428,-1.061206,pre-void,5
4,4.994638,3.995710,5.993565,0.842683,0.585986,0.046851,0.112579,0.585752,0.121939,0.012674,...,3.659089,3.587570,0.054537,0.285383,8.816397,1.253723,4.551026,-3.986444,pre-void,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
627,35.741867,34.740995,36.742738,0.888845,0.894589,-0.675784,0.127349,0.599968,0.687679,0.016218,...,5.182596,7.079187,0.241804,0.390451,14.233194,1.501855,4.173589,-1.934423,post-void,41
628,36.734466,35.733595,37.735338,0.872707,0.929414,-0.737835,0.073205,0.488159,0.741458,0.005359,...,8.264862,7.226878,0.278682,0.219165,14.344636,0.513354,2.055917,-5.517870,post-void,41
629,37.727066,36.726195,38.727938,0.914484,0.841722,-0.601056,0.149077,0.657182,0.619267,0.022224,...,4.124221,5.606253,0.203179,0.328678,13.882143,2.064572,6.919322,-3.101612,post-void,41
630,38.719666,37.718795,39.720538,0.927706,0.901753,-0.467764,0.084040,0.391664,0.475254,0.007063,...,8.575389,5.952698,0.403549,0.085526,13.387440,0.833587,3.352953,-10.290741,post-void,41
631,39.712266,38.711394,40.713138,0.927846,0.879157,-0.501667,0.100694,0.559146,0.511672,0.010139,...,7.240929,6.206428,0.303838,0.165205,13.741541,1.379207,4.580032,-7.035574,post-void,41

## Data 2c
classes: void, non-void

fs: original

overlap: 0.8

sliding window: 2s

filename: two_class_2s_0.8.csv

In [21]:
all_features = []
for i, exp_id in enumerate(test_data_3_class_labelled.keys()):    
    # Extract features
    
    df = test_data_3_class_labelled[exp_id]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=2.0, overlap=0.8)
    features, _ = analyzer.analyze_multi_axis_imu(test_data_3_class_labelled[exp_id])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id 
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.05it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.63it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.41it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.47it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.64it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.45it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.69it/s]
Analyzing : 100%|██████████| 8/8 [00:07<00:00,  1.13it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.53it/s]

In [22]:
final_features.to_csv('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/extracted_features_data/3_class/test_set/two_class_2s_0.8.csv', index=False)
final_features

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,0.998928,0.000000,1.997855,0.805241,0.558966,-0.099222,0.252002,0.856918,0.270832,0.063505,...,1.441709,1.735797,0.007825,0.586302,7.345245,3.186220,19.407455,1.514385,pre-void,5
1,1.405271,0.406343,2.404199,0.809914,0.596580,0.000546,0.187945,0.941724,0.187946,0.035323,...,1.512162,1.724407,0.013737,0.519953,7.730440,3.545074,26.135620,0.346795,pre-void,5
2,1.811614,0.812687,2.810542,0.837445,0.736867,0.084421,0.114991,0.580256,0.142653,0.013223,...,2.402423,2.774572,0.043155,0.299808,8.359106,3.188331,16.066370,-3.683745,pre-void,5
3,2.217958,1.219030,3.216885,0.858914,0.515434,0.089541,0.111077,0.580256,0.142673,0.012338,...,2.654940,2.658476,0.046895,0.269258,8.500189,3.099583,16.197442,-4.335946,pre-void,5
4,2.624301,1.625374,3.623229,0.842207,0.509594,0.078097,0.108739,0.580256,0.133878,0.011824,...,2.708627,2.643580,0.051943,0.296391,9.337752,3.108075,18.043712,-3.754656,pre-void,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1561,38.322626,37.321755,39.323498,0.911384,0.837471,-0.511477,0.125185,0.561772,0.526574,0.015671,...,5.406244,5.967001,0.278556,0.241197,13.567619,1.315261,4.166908,-4.977564,post-void,41
1562,38.719666,37.718795,39.720538,0.927706,0.901753,-0.467764,0.084040,0.391664,0.475254,0.007063,...,8.575389,5.952698,0.403549,0.085526,13.387440,0.833587,3.352953,-10.290741,post-void,41
1563,39.116706,38.115835,40.117578,0.941672,0.897260,-0.461359,0.087625,0.418931,0.469607,0.007678,...,8.815702,6.510132,0.373449,0.216214,13.377136,0.833752,2.976391,-5.593146,post-void,41
1564,39.513746,38.512875,40.514618,0.943597,0.833414,-0.485379,0.090211,0.418931,0.493691,0.008138,...,7.750584,6.279619,0.343722,0.234578,13.557912,1.203946,3.998784,-5.136144,post-void,41
1565,39.910786,38.909914,40.911658,0.892796,0.830015,-0.526118,0.112478,0.559146,0.538006,0.012651,...,7.287841,6.435587,0.378181,0.096671,14.115542,1.341180,4.260975,-9.705500,post-void,41

## Data 3
classes: void, non-void

fs: original

overlap: 0

sliding window: 3s

filename: two_class_3s_no.csv

In [23]:
all_features = []
for i, exp_id in enumerate(test_data_3_class_labelled.keys()):    
    # Extract features
    
    df = test_data_3_class_labelled[exp_id]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=3.0, overlap=0.0)
    features, _ = analyzer.analyze_multi_axis_imu(test_data_3_class_labelled[exp_id])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id 
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 46.81it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.66it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 24.82it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 47.56it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.93it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.92it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 33.12it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.60it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 40.01it/s]

In [24]:
final_features.to_csv('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/extracted_features_data/3_class/test_set/two_class_3s_no.csv', index=False)
final_features

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,1.498391,0.000000,2.996783,0.811911,0.607805,-0.037460,0.238700,1.056555,0.241622,0.056978,...,1.306868,1.828930,0.014710,0.463928,7.786579,3.955305,27.856947,-0.627731,pre-void,5
1,4.495174,2.996783,5.993565,0.858321,0.674802,0.050970,0.093651,0.585752,0.106623,0.008770,...,2.953053,3.535785,0.056005,0.322715,9.118048,1.478154,5.378862,-3.219521,pre-void,5
2,7.491957,5.993565,8.990348,0.867915,0.737695,-0.060002,0.048289,0.228426,0.077020,0.002332,...,4.166908,4.422502,0.161732,0.185233,10.434515,1.891813,7.280420,-6.433145,void,5
3,10.488739,8.990348,11.987131,0.889524,0.751476,-0.073711,0.037859,0.206919,0.082865,0.001433,...,3.661102,4.490761,0.126722,0.308465,10.885092,1.830279,7.020942,-3.506073,void,5
4,13.485522,11.987131,14.983913,0.909840,0.689750,-0.016950,0.043749,0.250239,0.046918,0.001914,...,3.159572,3.050676,0.057789,0.166243,8.520313,2.351197,12.289421,-7.002962,void,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,25.451915,23.954743,26.949086,0.908979,0.852936,0.405265,0.115069,0.593939,0.421284,0.013241,...,3.848813,5.540263,0.167224,0.343751,13.970890,1.769859,5.547857,-2.808252,void,41
207,28.446258,26.949086,29.943429,0.894037,0.855417,0.504090,0.147203,0.838357,0.525143,0.021669,...,5.460848,6.012319,0.278947,0.125057,13.513177,1.590322,5.294842,-8.448733,post-void,41
208,31.440601,29.943429,32.937772,0.892781,0.696166,0.152626,0.399137,1.559899,0.427324,0.159311,...,1.412368,2.312142,0.029355,0.251584,12.753100,5.716255,42.979193,-4.734604,post-void,41
209,34.434943,32.937772,35.932115,0.916184,0.766080,-0.013538,0.540418,1.618760,0.540588,0.292052,...,1.331618,2.558046,0.033936,0.375215,13.942034,5.393658,38.131771,-2.214496,post-void,41
210,37.429286,35.932115,38.926458,0.917341,0.854507,-0.633703,0.154955,0.657182,0.652373,0.024011,...,5.337086,6.460252,0.212553,0.241333,13.967736,1.400968,4.027818,-4.974342,post-void,41

## Data 3b
classes: void, non-void

fs: original

overlap: 0.5

sliding window: 3s

filename: two_class_3s_0.5.csv

In [25]:
all_features = []
for i, exp_id in enumerate(test_data_3_class_labelled.keys()):    
    # Extract features
    
    df = test_data_3_class_labelled[exp_id]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=3.0, overlap=0.5)
    features, _ = analyzer.analyze_multi_axis_imu(test_data_3_class_labelled[exp_id])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id 
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.96it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.39it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.90it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 24.10it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.33it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.70it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.91it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.28it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.29it/s]

In [26]:
final_features.to_csv('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/extracted_features_data/3_class/test_set/two_class_3s_0.5.csv', index=False)
final_features

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,1.498391,0.000000,2.996783,0.811911,0.607805,-0.037460,0.238700,1.056555,0.241622,0.056978,...,1.306868,1.828930,0.014710,0.463928,7.786579,3.955305,27.856947,-0.627731,pre-void,5
1,2.988317,1.489926,4.486708,0.857879,0.605751,0.074396,0.102626,0.580256,0.126755,0.010532,...,2.067458,2.585613,0.041935,0.289698,9.132679,3.242026,19.235839,-3.894970,pre-void,5
2,4.478243,2.979852,5.976634,0.853485,0.674927,0.051174,0.093448,0.585752,0.106542,0.008732,...,2.943578,3.534649,0.055441,0.327514,9.134145,1.482095,5.398120,-3.124541,pre-void,5
3,5.968169,4.469778,7.466560,0.852683,0.696401,0.005058,0.098501,0.568773,0.098631,0.009702,...,3.260341,3.098127,0.071653,0.131663,9.743277,2.345700,12.832407,-8.192258,void,5
4,7.458095,5.959703,8.956486,0.866483,0.734024,-0.059575,0.048106,0.228426,0.076572,0.002314,...,4.128716,4.402019,0.157524,0.188567,10.436591,1.900553,7.317105,-6.337871,void,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
412,32.764067,31.266896,34.261238,0.912435,0.794528,0.364202,0.370650,1.617359,0.519639,0.137381,...,1.422430,3.718955,0.062057,0.710468,13.373365,4.631928,26.533142,3.898474,post-void,41
413,34.252967,32.755795,35.750138,0.913703,0.817240,0.058306,0.524972,1.581471,0.528200,0.275596,...,1.526966,2.902229,0.040871,0.417506,13.793779,4.687054,29.420899,-1.446288,post-void,41
414,35.741867,34.244695,37.239038,0.890806,0.854435,-0.571704,0.299273,1.267358,0.645298,0.089565,...,1.730121,4.060678,0.074040,0.538715,13.727220,3.979349,19.301085,0.673893,post-void,41
415,37.230766,35.733595,38.727938,0.899544,0.886632,-0.650509,0.146593,0.657182,0.666822,0.021490,...,6.139736,6.805341,0.233920,0.233812,14.042005,1.112235,3.162347,-5.154676,post-void,41
416,38.719666,37.222495,40.216838,0.928936,0.861338,-0.519222,0.124795,0.561772,0.534008,0.015574,...,6.998779,6.309346,0.333252,0.110890,13.583156,0.975922,3.384326,-9.040638,post-void,41

## Data 3c
classes: void, non-void

fs: original

overlap: 0.8

sliding window: 3s

filename: two_class_3s_0.8.csv

In [27]:
all_features = []
for i, exp_id in enumerate(test_data_3_class_labelled.keys()):    
    # Extract features
    
    df = test_data_3_class_labelled[exp_id]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=3.0, overlap=0.8)
    features, _ = analyzer.analyze_multi_axis_imu(test_data_3_class_labelled[exp_id])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id 
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.67it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.17it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.04it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.43it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.04it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.03it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.85it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.68it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.30it/s]

In [28]:
final_features.to_csv('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/extracted_features_data/3_class/test_set/two_class_3s_0.8.csv', index=False)
final_features

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,1.498391,0.000000,2.996783,0.811911,0.607805,-0.037460,0.238700,1.056555,0.241622,0.056978,...,1.306868,1.828930,0.014710,0.463928,7.786579,3.955305,27.856947,-0.627731,pre-void,5
1,2.090975,0.592584,3.589367,0.827972,0.625600,0.061287,0.118743,0.668761,0.133627,0.014100,...,2.575791,2.652284,0.047849,0.274767,8.482547,3.148753,16.796354,-4.215128,pre-void,5
2,2.683560,1.185168,4.181951,0.876040,0.603361,0.079396,0.093365,0.580256,0.122559,0.008717,...,2.271418,2.569453,0.044732,0.216905,9.036694,3.178679,18.607856,-5.575455,pre-void,5
3,3.276144,1.777752,4.774535,0.843118,0.580062,0.073971,0.110235,0.616488,0.132754,0.012152,...,1.896057,2.735733,0.040384,0.363173,9.359602,3.156638,17.262841,-2.439081,pre-void,5
4,3.868728,2.370337,5.367119,0.849080,0.676362,0.077515,0.103613,0.616488,0.129400,0.010736,...,2.302380,3.291298,0.043385,0.431578,9.160129,2.067204,8.334693,-1.196123,pre-void,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1036,37.230766,35.733595,38.727938,0.899544,0.886632,-0.650509,0.146593,0.657182,0.666822,0.021490,...,6.139736,6.805341,0.233920,0.233812,14.042005,1.112235,3.162347,-5.154676,post-void,41
1037,37.826326,36.329155,39.323498,0.919431,0.886939,-0.592846,0.158270,0.720923,0.613609,0.025049,...,4.325826,5.807980,0.173402,0.218702,13.925355,1.844755,5.865921,-5.529638,post-void,41
1038,38.421886,36.924715,39.919058,0.921653,0.877697,-0.532637,0.140999,0.720923,0.550984,0.019881,...,5.574044,6.090383,0.257274,0.151290,13.848144,1.301620,4.127458,-7.489507,post-void,41
1039,39.017446,37.520275,40.514618,0.934054,0.832424,-0.498326,0.103324,0.511993,0.508925,0.010676,...,7.697469,6.383529,0.310134,0.120084,13.703263,0.923682,3.307430,-8.649552,post-void,41
1040,39.613006,38.115835,41.110177,0.930148,0.832754,-0.514662,0.121663,0.564513,0.528847,0.014802,...,7.464171,6.474733,0.324913,0.110088,13.640750,1.196649,3.863939,-9.076054,post-void,41

## Data 4
classes: void, non-void

fs: original

overlap: 0.0

sliding window: 4s

filename: two_class_4s_no.csv

In [29]:
all_features = []
for i, exp_id in enumerate(test_data_3_class_labelled.keys()):    
    # Extract features
    
    df = test_data_3_class_labelled[exp_id]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=4.0, overlap=0.0)
    features, _ = analyzer.analyze_multi_axis_imu(test_data_3_class_labelled[exp_id])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id 
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 62.07it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 27.42it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 35.05it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 64.15it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 26.15it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 32.63it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 42.62it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.18it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 48.70it/s]

In [30]:
final_features.to_csv('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/extracted_features_data/3_class/test_set/two_class_4s_no.csv', index=False)
final_features

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,1.997855,0.000000,3.995710,0.825847,0.644293,-0.013293,0.211426,1.056555,0.211843,0.044701,...,1.980071,2.385292,0.031797,0.192820,8.100955,3.346729,19.815270,-6.218175,pre-void,5
1,5.993565,3.995710,7.991420,0.856235,0.702602,0.001656,0.096636,0.587244,0.096650,0.009339,...,3.098032,3.199585,0.072197,0.151324,9.479248,2.167944,10.932865,-7.488351,void,5
2,9.989275,7.991420,11.987131,0.887661,0.797549,-0.078515,0.039084,0.228755,0.087705,0.001528,...,3.865561,4.437852,0.131322,0.154528,10.840193,1.792665,6.709542,-7.380910,void,5
3,13.984986,11.987131,15.982841,0.912659,0.752824,-0.017135,0.039703,0.250239,0.043242,0.001576,...,2.714079,3.369462,0.074158,0.220270,8.993940,2.749438,14.131786,-5.489899,void,5
4,17.980696,15.982841,19.978551,0.939942,0.821975,0.014247,0.022019,0.144261,0.026226,0.000485,...,5.837917,5.941002,0.249685,0.162048,12.248735,1.197105,3.586757,-7.135761,void,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,22.019174,20.017430,24.020917,0.932078,0.874983,0.329271,0.133752,0.661505,0.355400,0.017890,...,6.996550,6.457826,0.303153,0.119519,14.191097,1.084389,3.702382,-8.672822,void,41
151,26.022660,24.020917,28.024403,0.893574,0.865851,0.406669,0.118678,0.719658,0.423632,0.014084,...,3.700006,5.756520,0.158496,0.355273,13.957028,2.026974,6.585017,-2.588134,void,41
152,30.026146,28.024403,32.027889,0.908206,0.719325,0.254008,0.395635,1.690690,0.470156,0.156527,...,1.421710,3.045379,0.038744,0.267691,13.013933,4.883561,29.443429,-4.370598,post-void,41
153,34.029632,32.027889,36.031375,0.907581,0.841612,0.096643,0.541731,1.618760,0.550284,0.293472,...,1.530249,3.225930,0.043683,0.360792,13.839951,4.757488,29.764033,-2.483849,post-void,41
154,38.033118,36.031375,40.034861,0.914393,0.873088,-0.585357,0.158040,0.720923,0.606316,0.024977,...,4.877030,6.035109,0.204951,0.146266,13.915231,1.571768,4.836122,-7.661807,post-void,41

## Data 4b
classes: void, non-void

fs: original

overlap: 0.5

sliding window: 4s

filename: two_class_4s_0.5.csv

In [31]:
all_features = []
for i, exp_id in enumerate(test_data_3_class_labelled.keys()):    
    # Extract features
    
    df = test_data_3_class_labelled[exp_id]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=4.0, overlap=0.5)
    features, _ = analyzer.analyze_multi_axis_imu(test_data_3_class_labelled[exp_id])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id 
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 30.35it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.60it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.38it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 30.30it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.18it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.11it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 22.80it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.44it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 27.89it/s]

In [32]:
final_features.to_csv('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/extracted_features_data/3_class/test_set/two_class_4s_0.5.csv', index=False)
final_features

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,1.997855,0.000000,3.995710,0.825847,0.644293,-0.013293,0.211426,1.056555,0.211843,0.044701,...,1.980071,2.385292,0.031797,0.192820,8.100955,3.346729,19.815270,-6.218175,pre-void,5
1,3.995710,1.997855,5.993565,0.848527,0.687760,0.059743,0.109854,0.616488,0.125048,0.012068,...,2.206559,3.226380,0.038032,0.304455,9.046388,2.094717,8.369872,-3.588017,pre-void,5
2,5.993565,3.995710,7.991420,0.856235,0.702602,0.001656,0.096636,0.587244,0.096650,0.009339,...,3.098032,3.199585,0.072197,0.151324,9.479248,2.167944,10.932865,-7.488351,void,5
3,7.991420,5.993565,9.989275,0.872985,0.710820,-0.068722,0.045345,0.228426,0.082334,0.002056,...,3.998361,4.414128,0.146493,0.156725,10.354397,1.781462,6.976185,-7.308306,void,5
4,9.989275,7.991420,11.987131,0.887661,0.797549,-0.078515,0.039084,0.228755,0.087705,0.001528,...,3.865561,4.437852,0.131322,0.154528,10.840193,1.792665,6.709542,-7.380910,void,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302,30.026146,28.024403,32.027889,0.908206,0.719325,0.254008,0.395635,1.690690,0.470156,0.156527,...,1.421710,3.045379,0.038744,0.267691,13.013933,4.883561,29.443429,-4.370598,post-void,41
303,32.027889,30.026146,34.029632,0.908532,0.683198,0.254010,0.392119,1.617359,0.467203,0.153757,...,0.985806,2.036335,0.018974,0.318482,13.594595,7.267164,67.463930,-3.303933,post-void,41
304,34.029632,32.027889,36.031375,0.907581,0.841612,0.096643,0.541731,1.618760,0.550284,0.293472,...,1.530249,3.225930,0.043683,0.360792,13.839951,4.757488,29.764033,-2.483849,post-void,41
305,36.031375,34.029632,38.033118,0.887310,0.756403,-0.537844,0.337504,1.591946,0.634969,0.113909,...,1.866425,4.324758,0.066852,0.485635,13.641360,3.562914,15.787101,-0.249607,post-void,41
306,38.033118,36.031375,40.034861,0.914393,0.873088,-0.585357,0.158040,0.720923,0.606316,0.024977,...,4.877030,6.035109,0.204951,0.146266,13.915231,1.571768,4.836122,-7.661807,post-void,41

## Data 4c
classes: void, non-void

fs: original

overlap: 0.8

sliding window: 4s

filename: two_class_4s_0.8.csv

In [33]:
all_features = []
for i, exp_id in enumerate(test_data_3_class_labelled.keys()):    
    # Extract features
    
    df = test_data_3_class_labelled[exp_id]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=4.0, overlap=0.8)
    features, _ = analyzer.analyze_multi_axis_imu(test_data_3_class_labelled[exp_id])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id 
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.93it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.45it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.86it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.36it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.19it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.57it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.89it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.26it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.15it/s]

In [34]:
final_features.to_csv('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/extracted_features_data/3_class/test_set/two_class_4s_0.8.csv', index=False)
final_features

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,1.997855,0.000000,3.995710,0.825847,0.644293,-0.013293,0.211426,1.056555,0.211843,0.044701,...,1.980071,2.385292,0.031797,0.192820,8.100955,3.346729,19.815270,-6.218175,pre-void,5
1,2.793611,0.795756,4.791466,0.845330,0.647683,0.077851,0.102820,0.616488,0.128968,0.010572,...,2.205251,2.645047,0.044007,0.191371,8.754760,3.122878,17.617453,-6.258735,pre-void,5
2,3.589367,1.591512,5.587222,0.849058,0.655373,0.075138,0.104151,0.616488,0.128425,0.010847,...,1.978401,2.964899,0.035202,0.304348,9.146841,2.575942,11.933381,-3.590206,pre-void,5
3,4.385123,2.387268,6.382978,0.851907,0.688829,0.048885,0.107987,0.616488,0.118537,0.011661,...,2.626366,3.427892,0.045523,0.253254,8.973432,1.702273,6.332424,-4.696174,pre-void,5
4,5.180878,3.183023,7.178734,0.860105,0.692843,0.026442,0.091970,0.585752,0.095696,0.008459,...,2.977362,3.352402,0.057704,0.216021,9.225735,1.671695,6.973378,-5.598081,void,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
763,35.353098,33.351355,37.354841,0.900031,0.760098,-0.341100,0.516649,1.728478,0.619093,0.266926,...,1.109365,2.619213,0.030203,0.317039,13.573027,6.225742,46.566800,-3.332823,post-void,41
764,36.147178,34.145435,38.148921,0.889898,0.802385,-0.563310,0.299538,1.305750,0.637998,0.089723,...,2.237590,4.841987,0.078732,0.517553,13.693069,3.021916,11.779960,0.305046,post-void,41
765,36.941258,34.939515,38.943001,0.915174,0.916144,-0.639075,0.140404,0.657182,0.654316,0.019713,...,6.495155,6.974086,0.243564,0.191533,14.139515,1.023504,2.944842,-6.254189,post-void,41
766,37.735338,35.733595,39.737081,0.908062,0.864863,-0.602587,0.156531,0.720923,0.622586,0.024502,...,4.929007,6.179922,0.199554,0.173177,13.931500,1.541958,4.604006,-6.789234,post-void,41
767,38.529418,36.527675,40.531161,0.934187,0.842139,-0.557595,0.139856,0.720923,0.574867,0.019560,...,5.636389,6.173076,0.261749,0.101163,13.858250,1.315464,4.143516,-9.486589,post-void,41

## Data 5
classes: void, non-void

fs: original

overlap: 0.0

sliding window: 5s

filename: two_class_5s_no.csv

In [35]:
all_features = []
for i, exp_id in enumerate(test_data_3_class_labelled.keys()):    
    # Extract features
    
    df = test_data_3_class_labelled[exp_id]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=5.0, overlap=0.0)
    features, _ = analyzer.analyze_multi_axis_imu(test_data_3_class_labelled[exp_id])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id 
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 68.95it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 33.71it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 41.74it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 83.20it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 32.02it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 38.39it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 55.20it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.17it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 62.25it/s]

In [36]:
final_features.to_csv('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/extracted_features_data/3_class/test_set/two_class_5s_no.csv', index=False)
final_features

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,2.497319,0.000000,4.994638,0.833939,0.658774,0.004541,0.199449,1.092786,0.199501,0.039780,...,2.078979,2.454777,0.033952,0.156496,8.292906,3.280773,19.175182,-7.315834,pre-void,5
1,7.491957,4.994638,9.989275,0.868767,0.762241,-0.051413,0.069491,0.439227,0.086442,0.004829,...,3.423737,3.942357,0.090516,0.194040,9.905010,2.089575,8.652554,-6.184233,void,5
2,12.486594,9.989275,14.983913,0.905050,0.728213,-0.035420,0.048190,0.252321,0.059806,0.002322,...,3.517807,2.863427,0.062797,0.091096,9.015288,1.971972,9.734164,-9.990176,void,5
3,17.481232,14.983913,19.978551,0.937051,0.825673,0.007859,0.025761,0.159905,0.026933,0.000664,...,5.180887,5.288189,0.244239,0.142548,12.529518,1.600217,5.463265,-7.792495,void,5
4,22.475870,19.978551,24.973189,0.881799,0.803654,0.021918,0.036070,0.202994,0.042207,0.001301,...,4.409706,4.571548,0.127081,0.123772,11.284845,1.601113,6.727383,-8.499933,void,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119,17.486301,14.988258,19.984344,0.933870,0.785269,0.247786,0.119812,0.866507,0.275232,0.014355,...,5.146166,6.566605,0.275642,0.152312,14.218971,1.761819,5.247968,-7.455027,void,41
120,22.482387,19.984344,24.980430,0.927374,0.891085,0.349627,0.134142,0.661505,0.374477,0.017994,...,6.785468,6.518522,0.310715,0.099456,14.078592,1.164162,3.899617,-9.568723,void,41
121,27.478473,24.980430,29.976516,0.896290,0.834908,0.458781,0.148458,0.838357,0.482203,0.022040,...,4.059209,6.212520,0.181482,0.269849,13.779116,1.981955,6.285964,-4.322923,void,41
122,32.474559,29.976516,34.972602,0.901525,0.632824,0.206944,0.391273,1.617359,0.442628,0.153094,...,0.978661,2.104432,0.020777,0.310210,13.149025,7.218240,66.189695,-3.470618,post-void,41
123,37.470645,34.972602,39.968688,0.913730,0.873725,-0.603675,0.148975,0.720923,0.621785,0.022194,...,6.055999,6.816474,0.223994,0.193140,14.094057,1.146989,3.253264,-6.209249,post-void,41

## Data 5b
classes: void, non-void

fs: original

overlap: 0.5

sliding window: 5s

filename: two_class_5s_0.5.csv

In [37]:
all_features = []
for i, exp_id in enumerate(test_data_3_class_labelled.keys()):    
    # Extract features
    
    df = test_data_3_class_labelled[exp_id]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=5.0, overlap=0.5)
    features, _ = analyzer.analyze_multi_axis_imu(test_data_3_class_labelled[exp_id])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id 
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 37.87it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.65it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.16it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 41.44it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.60it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.66it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 28.17it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.77it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 33.82it/s]

In [38]:
final_features.to_csv('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/extracted_features_data/3_class/test_set/two_class_5s_0.5.csv', index=False)
final_features

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,2.497319,0.000000,4.994638,0.833939,0.658774,0.004541,0.199449,1.092786,0.199501,0.039780,...,2.078979,2.454777,0.033952,0.156496,8.292906,3.280773,19.175182,-7.315834,pre-void,5
1,5.003103,2.505784,7.500422,0.860111,0.719000,0.033565,0.101944,0.585752,0.107327,0.010392,...,2.765672,3.430444,0.052293,0.215449,9.547708,1.638535,6.210430,-5.612773,pre-void,5
2,7.508888,5.011569,10.006206,0.871297,0.761656,-0.052283,0.068402,0.439227,0.086095,0.004679,...,3.439378,3.957139,0.091703,0.193402,9.919338,2.082060,8.598836,-6.201961,void,5
3,10.014672,7.517353,12.511991,0.894085,0.762960,-0.071376,0.042427,0.234018,0.083034,0.001800,...,3.661567,4.288226,0.112569,0.126038,10.978249,1.838377,6.836033,-8.409901,void,5
4,12.520456,10.023137,15.017775,0.902519,0.729731,-0.035283,0.048047,0.252321,0.059611,0.002309,...,3.523344,2.856197,0.063028,0.088438,9.032855,1.968471,9.722548,-10.131456,void,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238,27.478473,24.980430,29.976516,0.896290,0.834908,0.458781,0.148458,0.838357,0.482203,0.022040,...,4.059209,6.212520,0.181482,0.269849,13.779116,1.981955,6.285964,-4.322923,void,41
239,29.976516,27.478473,32.474559,0.890419,0.662965,0.298920,0.370125,1.690690,0.475758,0.136993,...,1.479793,3.287686,0.050101,0.294907,13.010431,4.532404,26.620707,-3.785606,post-void,41
240,32.474559,29.976516,34.972602,0.901525,0.632824,0.206944,0.391273,1.617359,0.442628,0.153094,...,0.978661,2.104432,0.020777,0.310210,13.149025,7.218240,66.189695,-3.470618,post-void,41
241,34.972602,32.474559,37.470645,0.910231,0.679893,-0.192548,0.580980,1.757843,0.612056,0.337537,...,1.136782,2.459247,0.030053,0.286543,14.000160,6.078235,46.969358,-3.961783,post-void,41
242,37.470645,34.972602,39.968688,0.913730,0.873725,-0.603675,0.148975,0.720923,0.621785,0.022194,...,6.055999,6.816474,0.223994,0.193140,14.094057,1.146989,3.253264,-6.209249,post-void,41

## Data 5c
classes: void, non-void

fs: original

overlap: 0.8

sliding window: 5s

filename: two_class_5s_0.8.csv

In [39]:
all_features = []
for i, exp_id in enumerate(test_data_3_class_labelled.keys()):    
    # Extract features
    
    df = test_data_3_class_labelled[exp_id]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=5.0, overlap=0.8)
    features, _ = analyzer.analyze_multi_axis_imu(test_data_3_class_labelled[exp_id])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id 
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.03it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.57it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.69it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.10it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.58it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.03it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.20it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.62it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.71it/s]

In [40]:
final_features.to_csv('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/extracted_features_data/3_class/test_set/two_class_5s_0.8.csv', index=False)
final_features

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,2.497319,0.000000,4.994638,0.833939,0.658774,0.004541,0.199449,1.092786,0.199501,0.039780,...,2.078979,2.454777,0.033952,0.156496,8.292906,3.280773,19.175182,-7.315834,pre-void,5
1,3.496246,0.998928,5.993565,0.852163,0.687567,0.065170,0.103651,0.616488,0.122436,0.010744,...,1.994478,2.733193,0.037710,0.261143,8.886090,2.957062,15.722742,-4.516829,pre-void,5
2,4.495174,1.997855,6.992493,0.850384,0.709413,0.041912,0.106173,0.616488,0.114146,0.011273,...,2.345612,3.299098,0.041894,0.286361,9.132058,1.944681,7.524925,-3.965651,pre-void,5
3,5.494102,2.996783,7.991420,0.862116,0.718313,0.013166,0.090405,0.587244,0.091359,0.008173,...,2.907175,3.345359,0.060326,0.217101,9.581069,1.699949,7.081822,-5.570443,void,5
4,6.493029,3.995710,8.990348,0.860244,0.731754,-0.017261,0.095963,0.607839,0.097503,0.009209,...,3.022974,3.262077,0.072056,0.175813,9.597153,2.209135,10.844982,-6.709759,void,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,34.261238,31.763195,36.759281,0.900708,0.758239,-0.019415,0.578471,1.654336,0.578797,0.334629,...,1.692780,3.563110,0.058850,0.333465,13.876668,4.411423,25.606987,-3.007733,post-void,41
601,35.253838,32.755795,37.751881,0.903151,0.759127,-0.259895,0.564760,1.757843,0.621690,0.318954,...,1.086224,2.391655,0.028093,0.289155,13.867304,6.390805,50.860694,-3.906438,post-void,41
602,36.246438,33.748395,38.744481,0.906503,0.667884,-0.471466,0.373166,1.591946,0.601277,0.139253,...,1.438552,3.561310,0.047246,0.410722,13.555902,4.536030,24.774157,-1.567714,post-void,41
603,37.239038,34.740995,39.737081,0.905755,0.893204,-0.602032,0.151119,0.720923,0.620709,0.022837,...,6.287829,6.980684,0.227178,0.191398,13.933244,1.070703,3.043743,-6.257963,post-void,41
604,38.231638,35.733595,40.729681,0.918521,0.871316,-0.591037,0.149132,0.720923,0.609561,0.022240,...,4.985321,6.158738,0.193320,0.150135,13.993494,1.524084,4.583909,-7.528665,post-void,41