In [1]:
import pickle
import pandas as pd

In [2]:
with open('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/training_results/dt_cv_results_10_fold_logo.pkl', 'rb') as f:
    dt_results = pickle.load(f)
with open('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/training_results/rf_cv_results_10_fold_logo.pkl', 'rb') as f:
    rf_results = pickle.load(f)
with open('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/training_results/xgb_cv_results_10_fold_logo.pkl', 'rb') as f:
    xgb_results = pickle.load(f)

In [3]:
imb_tech = ['none', 'oversample_smote', 'undersample_tomek_links', 'combined_smote_tomek']
models = ['Decision Tree', 'Random Forest', 'XGBoost']

In [4]:
# Combine all model results into one dictionary
all_results = {
    'Decision Tree': dt_results,
    'Random Forest': rf_results,
    'XGBoost': xgb_results
}

In [5]:
def format_cv_results_separate_models(model_results_dict, imb_tech, models):
    """
    Convert cross-validation results from separate model dictionaries to tabular format.
    
    Parameters:
    model_results_dict: Dictionary where keys are model names and values are 
                    dictionaries with structure {dataset: {imbalance_technique: {metrics...}}}
    imb_tech: List of imbalance handling techniques
    models: List of model names
    
    Returns:
    pandas.DataFrame: Formatted results table
    """
    
    formatted_data = []
    
    # Iterate through each model
    for model in models:
        if model in model_results_dict:
            model_data = model_results_dict[model]
            
            
            # Iterate through each dataset for this model
            for dataset, dataset_results in model_data.items():
                
                # Iterate through each imbalance technique
                for technique in imb_tech:
                    # Check if this technique exists in the results
                    if technique in dataset_results:
                        technique_results = dataset_results[technique]
                        
                        recall_void_avg = technique_results.get('mean_recall_minority', 0)
                        recall_void_std = technique_results.get('std_recall_minority', 0)
                        accuracy_avg = technique_results.get('mean_accuracy', 0)
                        accuracy_std = technique_results.get('std_accuracy', 0)
                        f1_void_avg = technique_results.get('mean_f1_minority', 0)
                        f1_void_std = technique_results.get('std_f1_minority', 0)
                        macro_f1_avg = technique_results.get('macro_f1', 0)
                        macro_f1_std = technique_results.get('std_macro_f1', 0)
                        weighted_f1_avg = technique_results.get('weighted_f1', 0)
                        weighted_f1_std = technique_results.get('std_weighted_f1', 0)
                        
                        if technique == "none":
                            technique = "Baseline (none)"
                        elif technique == "oversample_smote":
                            technique = "SMOTE"
                        elif technique == "undersample_tomek_links":
                            technique = "TomekLinks"
                        elif technique == "combined_smote_tomek":
                            technique = "SMOTETomek"
                        
                        # Add row to formatted data
                        formatted_data.append({
                            'Dataset': dataset,
                            'Model': model,
                            'Imbalance Technique': technique,
                            'F1-Score (avg)': round(f1_void_avg, 5),
                            'F1-Score (std)': round(f1_void_std, 5),
                            'F1-Score (avg:std)': round(f1_void_avg/f1_void_std, 5),
                            'Recall (avg)': round(recall_void_avg, 5),
                            'Recall (std)': round(recall_void_std, 5),
                            'Recall (avg:std)': round(recall_void_avg/recall_void_std, 5),
                            'Accuracy (avg)': round(accuracy_avg, 5),
                            'Accuracy (std)': round(accuracy_std, 5),
                            'Accuracy (avg:std)': round(accuracy_avg/accuracy_std, 5),
                            'Macro F1 (avg)': round(macro_f1_avg, 5),
                            'Macro F1 (std)': round(macro_f1_std, 5),
                            'Macro F1 (avg:std)': round(macro_f1_avg/macro_f1_std, 5),
                            'Weighted F1 (avg)': round(weighted_f1_avg, 5),
                            'Weighted F1 (std)': round(weighted_f1_std, 5),
                            'Weighted F1 (avg:std)': round(weighted_f1_avg/weighted_f1_std, 5)
                            
                        })
                        
                        
    
    # Create DataFrame
    df = pd.DataFrame(formatted_data)
    
    # Sort by Dataset, Model, and Imbalance Technique for better organization
    # df = df.sort_values(['Dataset', 'Model', 'Imbalance Technique']).reset_index(drop=True)
    
    return df


print("Function ready to use for separate model dictionaries.")

Function ready to use for separate model dictionaries.

In [6]:
df = format_cv_results_separate_models(all_results, imb_tech, models)
df

,Dataset,Model,Imbalance Technique,F1-Score (avg),F1-Score (std),F1-Score (avg:std),Recall (avg),Recall (std),Recall (avg:std),Accuracy (avg),Accuracy (std),Accuracy (avg:std),Macro F1 (avg),Macro F1 (std),Macro F1 (avg:std),Weighted F1 (avg),Weighted F1 (std),Weighted F1 (avg:std)
0,1s_no,Decision Tree,Baseline (none),0.54514,0.24135,2.25874,0.57356,0.26784,2.14147,0.65763,0.14637,4.49275,0.61722,0.16042,3.84745,0.65547,0.15813,4.14502
1,1s_no,Decision Tree,SMOTE,0.56817,0.22620,2.51184,0.58516,0.26189,2.23442,0.67854,0.13094,5.18203,0.63272,0.14667,4.31392,0.67335,0.14211,4.73810
2,1s_no,Decision Tree,TomekLinks,0.52734,0.28164,1.87237,0.53499,0.30919,1.73032,0.66467,0.14548,4.56869,0.60948,0.17316,3.51979,0.65734,0.15678,4.19266
3,1s_no,Decision Tree,SMOTETomek,0.54150,0.27421,1.97476,0.58077,0.30579,1.89926,0.66776,0.14170,4.71240,0.61602,0.16296,3.78016,0.65931,0.15222,4.33133
4,1s_0.5,Decision Tree,Baseline (none),0.58030,0.25498,2.27589,0.59130,0.27828,2.12484,0.70412,0.12781,5.50906,0.65073,0.15311,4.25007,0.69675,0.13717,5.07947
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,5s_0.5,XGBoost,SMOTETomek,0.72990,0.23605,3.09212,0.79223,0.25519,3.10449,0.78709,0.16138,4.87732,0.75535,0.18365,4.11301,0.78595,0.17872,4.39762
176,5s_0.8,XGBoost,Baseline (none),0.66837,0.27284,2.44970,0.69758,0.29064,2.40012,0.73646,0.18016,4.08775,0.69456,0.19946,3.48227,0.73468,0.18767,3.91465
177,5s_0.8,XGBoost,SMOTE,0.69610,0.25674,2.71125,0.73811,0.28054,2.63106,0.75427,0.17964,4.19881,0.71552,0.19790,3.61564,0.75226,0.18692,4.02455
178,5s_0.8,XGBoost,TomekLinks,0.68009,0.25499,2.66707,0.70654,0.28641,2.46693,0.74278,0.17691,4.19861,0.70279,0.19244,3.65193,0.74160,0.18373,4.03626
179,5s_0.8,XGBoost,SMOTETomek,0.71932,0.21056,3.41632,0.77431,0.23115,3.34984,0.75437,0.16721,4.51158,0.72164,0.17673,4.08336,0.75460,0.17523,4.30646

In [13]:
df_sorted_f1_score = df.sort_values(by='Dataset', ascending=True).reset_index(drop=True)
df_sorted_f1_score.head(20)

,Dataset,Model,Imbalance Technique,F1-Score (avg),F1-Score (std),F1-Score (avg:std),Recall (avg),Recall (std),Recall (avg:std),Accuracy (avg),Accuracy (std),Accuracy (avg:std),Macro F1 (avg),Macro F1 (std),Macro F1 (avg:std),Weighted F1 (avg),Weighted F1 (std),Weighted F1 (avg:std)
0,1s_0.5,Decision Tree,SMOTE,0.58784,0.10692,5.49798,0.56736,0.12647,4.48621,0.68898,0.03996,17.24318,0.66469,0.05646,11.77315,0.68561,0.04231,16.20339
1,1s_0.5,Random Forest,SMOTETomek,0.66091,0.09400,7.03101,0.60864,0.14034,4.33698,0.75782,0.05059,14.98061,0.73278,0.05677,12.90760,0.75098,0.05399,13.90873
2,1s_0.5,XGBoost,Baseline (none),0.66841,0.07398,9.03481,0.65351,0.11031,5.92438,0.74531,0.02919,25.53364,0.72798,0.03914,18.59767,0.74326,0.03159,23.52622
3,1s_0.5,XGBoost,SMOTETomek,0.69328,0.06418,10.80170,0.68547,0.11239,6.09890,0.76206,0.02662,28.62716,0.74667,0.03272,22.82213,0.76042,0.02956,25.72335
4,1s_0.5,Random Forest,SMOTE,0.64775,0.10961,5.90937,0.59143,0.15616,3.78735,0.75354,0.05167,14.58289,0.72542,0.06405,11.32575,0.74521,0.05685,13.10822
5,1s_0.5,Decision Tree,TomekLinks,0.60791,0.08184,7.42788,0.59869,0.11433,5.23628,0.69783,0.02285,30.54327,0.67737,0.03518,19.25319,0.69576,0.02527,27.53768
6,1s_0.5,XGBoost,TomekLinks,0.67044,0.09129,7.34379,0.64575,0.12384,5.21446,0.75331,0.03470,21.70742,0.73379,0.04968,14.77029,0.75047,0.03774,19.88741
7,1s_0.5,XGBoost,SMOTE,0.69077,0.07158,9.64992,0.67671,0.10092,6.70507,0.76179,0.03410,22.33797,0.74673,0.04235,17.63211,0.76057,0.03655,20.80953
8,1s_0.5,Random Forest,Baseline (none),0.65624,0.10854,6.04623,0.59865,0.15860,3.77455,0.75984,0.05417,14.02778,0.73243,0.06540,11.19900,0.75138,0.06007,12.50803
9,1s_0.5,Random Forest,TomekLinks,0.65370,0.09321,7.01326,0.60569,0.14796,4.09363,0.75232,0.04449,16.91159,0.72687,0.05271,13.78952,0.74514,0.04932,15.10838
10,1s_0.5,Decision Tree,Baseline (none),0.60295,0.07664,7.86751,0.58361,0.10798,5.40489,0.69802,0.02711,25.74562,0.67703,0.03793,17.84810,0.69472,0.03372,20.60459
11,1s_0.5,Decision Tree,SMOTETomek,0.60216,0.09768,6.16487,0.60794,0.15116,4.02188,0.68953,0.02917,23.63683,0.66721,0.04375,15.25175,0.68588,0.03286,20.87059
12,1s_0.8,XGBoost,Baseline (none),0.67956,0.08664,7.84372,0.65112,0.10677,6.09841,0.75788,0.04387,17.27667,0.74071,0.05413,13.68482,0.75569,0.04595,16.44461
13,1s_0.8,Decision Tree,Baseline (none),0.61649,0.08415,7.32589,0.59343,0.12416,4.77941,0.71096,0.02062,34.47350,0.68868,0.03652,18.85634,0.70676,0.02657,26.60161
14,1s_0.8,Decision Tree,SMOTE,0.62400,0.12678,4.92195,0.59957,0.15067,3.97944,0.72125,0.04618,15.61896,0.69844,0.07124,9.80388,0.71782,0.04975,14.42810
15,1s_0.8,XGBoost,SMOTETomek,0.66970,0.09051,7.39899,0.63448,0.11580,5.47911,0.75485,0.03462,21.80625,0.73454,0.04937,14.87828,0.75141,0.03769,19.93925
16,1s_0.8,Decision Tree,TomekLinks,0.65281,0.05413,12.06052,0.65272,0.10633,6.13832,0.72447,0.02333,31.05405,0.70868,0.02142,33.08542,0.72277,0.02653,27.24597
17,1s_0.8,XGBoost,TomekLinks,0.67417,0.09017,7.47667,0.64397,0.12346,5.21601,0.75648,0.03839,19.70336,0.73718,0.05127,14.37734,0.75326,0.04172,18.05637
18,1s_0.8,Random Forest,TomekLinks,0.63855,0.10430,6.12252,0.56463,0.14791,3.81733,0.75318,0.04925,15.29174,0.72223,0.06045,11.94811,0.74254,0.05507,13.48398
19,1s_0.8,Random Forest,Baseline (none),0.64244,0.10529,6.10192,0.57248,0.15522,3.68820,0.75477,0.04990,15.12671,0.72428,0.06077,11.91883,0.74433,0.05543,13.42848

In [8]:
df_sorted_f1_score.to_csv('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/f1_score_sorted_stage_3_logo.csv', index=False)

5-fold stra

In [14]:
df = pd.read_csv('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/f1_score_sorted_stage_3_5_fold_sgkf.csv')
df = df.sort_values(by='Dataset', ascending=True).reset_index(drop=True)
df.head(20)

,Dataset,Model,Imbalance Technique,F1-Score (avg),F1-Score (std),F1-Score (avg:std),Recall (avg),Recall (std),Recall (avg:std),Accuracy (avg),Accuracy (std),Accuracy (avg:std),Macro F1 (avg),Macro F1 (std),Macro F1 (avg:std),Weighted F1 (avg),Weighted F1 (std),Weighted F1 (avg:std)
0,1s_0.5,XGBoost,TomekLinks,0.69335,0.06133,11.30496,0.67302,0.08611,7.81611,0.75843,0.04568,16.60292,0.74596,0.04663,15.99650,0.75641,0.04495,16.82778
1,1s_0.5,XGBoost,Baseline (none),0.68353,0.05263,12.98794,0.65247,0.06368,10.24661,0.75364,0.04154,18.14121,0.74013,0.04159,17.79762,0.75120,0.04052,18.54027
2,1s_0.5,Random Forest,TomekLinks,0.66506,0.08000,8.31338,0.62117,0.14609,4.25191,0.75461,0.03998,18.87380,0.73406,0.04864,15.09183,0.74780,0.04344,17.21654
3,1s_0.5,Random Forest,SMOTE,0.66237,0.07412,8.93592,0.62036,0.14021,4.42443,0.74992,0.04366,17.17661,0.73010,0.04794,15.22903,0.74345,0.04528,16.41809
4,1s_0.5,Random Forest,SMOTETomek,0.65860,0.07965,8.26817,0.60984,0.15086,4.04232,0.75243,0.03956,19.02202,0.73021,0.04744,15.39280,0.74465,0.04236,17.58117
5,1s_0.5,Decision Tree,Baseline (none),0.55946,0.07101,7.87833,0.52402,0.08931,5.86723,0.66726,0.04266,15.64096,0.64525,0.04804,13.43015,0.66170,0.04420,14.97125
6,1s_0.5,Random Forest,Baseline (none),0.64872,0.07505,8.64426,0.58292,0.12798,4.55479,0.74990,0.03966,18.90811,0.72589,0.04671,15.54098,0.74103,0.04239,17.47971
7,1s_0.5,XGBoost,SMOTETomek,0.68942,0.06106,11.29099,0.67112,0.07818,8.58424,0.75441,0.04599,16.40240,0.74231,0.04727,15.70189,0.75274,0.04526,16.63040
8,1s_0.5,XGBoost,SMOTE,0.67747,0.04116,16.45797,0.65403,0.05257,12.44018,0.74553,0.03525,21.14897,0.73271,0.03343,21.91584,0.74358,0.03384,21.97278
9,1s_0.5,Decision Tree,TomekLinks,0.53691,0.03846,13.95863,0.48911,0.07218,6.77640,0.65861,0.02787,23.62787,0.63226,0.02496,25.33445,0.64986,0.02877,22.58498
10,1s_0.5,Decision Tree,SMOTE,0.63760,0.06541,9.74765,0.61632,0.08428,7.31258,0.71631,0.04753,15.07110,0.70162,0.04996,14.04286,0.71402,0.04843,14.74387
11,1s_0.5,Decision Tree,SMOTETomek,0.60721,0.07542,8.05119,0.59920,0.12658,4.73364,0.69075,0.04835,14.28731,0.67404,0.05024,13.41559,0.68738,0.04789,14.35387
12,1s_0.8,Decision Tree,Baseline (none),0.62474,0.02350,26.58204,0.59880,0.04562,13.12520,0.70656,0.02981,23.69972,0.69035,0.01996,34.59204,0.70386,0.02795,25.18450
13,1s_0.8,XGBoost,Baseline (none),0.69681,0.04900,14.22023,0.67958,0.08178,8.30996,0.75915,0.04313,17.60262,0.74687,0.04086,18.27810,0.75683,0.04383,17.26567
14,1s_0.8,XGBoost,SMOTE,0.69861,0.03112,22.44937,0.68301,0.05987,11.40856,0.75737,0.04497,16.83970,0.74599,0.03794,19.66346,0.75553,0.04364,17.31477
15,1s_0.8,Random Forest,SMOTE,0.66874,0.05925,11.28713,0.61016,0.11625,5.24884,0.75884,0.03258,23.29198,0.73764,0.03444,21.41993,0.75169,0.03470,21.66474
16,1s_0.8,XGBoost,SMOTETomek,0.70236,0.03538,19.85182,0.68548,0.05611,12.21652,0.76053,0.04649,16.35880,0.74931,0.03980,18.82761,0.75885,0.04504,16.85000
17,1s_0.8,XGBoost,TomekLinks,0.70357,0.04802,14.65027,0.68215,0.07521,9.06967,0.76469,0.04825,15.84804,0.75240,0.04407,17.07399,0.76239,0.04754,16.03674
18,1s_0.8,Random Forest,Baseline (none),0.66378,0.04304,15.42394,0.60029,0.08830,6.79832,0.75554,0.02074,36.42720,0.73409,0.01914,38.36011,0.74865,0.02062,36.30096
19,1s_0.8,Random Forest,SMOTETomek,0.66368,0.06624,10.01893,0.60412,0.12295,4.91362,0.75744,0.02975,25.45887,0.73487,0.03551,20.69672,0.74961,0.03340,22.44059

In [15]:
df = pd.read_csv('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/f1_score_sorted_stage_3_5_fold_gkf.csv')
df = df.sort_values(by='Dataset', ascending=True).reset_index(drop=True)
df.head(20)

,Dataset,Model,Imbalance Technique,F1-Score (avg),F1-Score (std),F1-Score (avg:std),Recall (avg),Recall (std),Recall (avg:std),Accuracy (avg),Accuracy (std),Accuracy (avg:std),Macro F1 (avg),Macro F1 (std),Macro F1 (avg:std),Weighted F1 (avg),Weighted F1 (std),Weighted F1 (avg:std)
0,1s_0.5,Decision Tree,SMOTE,0.58784,0.10692,5.49798,0.56736,0.12647,4.48621,0.68898,0.03996,17.24318,0.66469,0.05646,11.77315,0.68561,0.04231,16.20339
1,1s_0.5,Decision Tree,Baseline (none),0.60295,0.07664,7.86751,0.58361,0.10798,5.40489,0.69802,0.02711,25.74562,0.67703,0.03793,17.84810,0.69472,0.03372,20.60459
2,1s_0.5,Random Forest,TomekLinks,0.65370,0.09321,7.01326,0.60569,0.14796,4.09363,0.75232,0.04449,16.91159,0.72687,0.05271,13.78952,0.74514,0.04932,15.10838
3,1s_0.5,Random Forest,Baseline (none),0.65624,0.10854,6.04623,0.59865,0.15860,3.77455,0.75984,0.05417,14.02778,0.73243,0.06540,11.19900,0.75138,0.06007,12.50803
4,1s_0.5,XGBoost,SMOTE,0.69077,0.07158,9.64992,0.67671,0.10092,6.70507,0.76179,0.03410,22.33797,0.74673,0.04235,17.63211,0.76057,0.03655,20.80953
5,1s_0.5,Decision Tree,SMOTETomek,0.60216,0.09768,6.16487,0.60794,0.15116,4.02188,0.68953,0.02917,23.63683,0.66721,0.04375,15.25175,0.68588,0.03286,20.87059
6,1s_0.5,Decision Tree,TomekLinks,0.60791,0.08184,7.42788,0.59869,0.11433,5.23628,0.69783,0.02285,30.54327,0.67737,0.03518,19.25319,0.69576,0.02527,27.53768
7,1s_0.5,Random Forest,SMOTE,0.64775,0.10961,5.90937,0.59143,0.15616,3.78735,0.75354,0.05167,14.58289,0.72542,0.06405,11.32575,0.74521,0.05685,13.10822
8,1s_0.5,XGBoost,TomekLinks,0.67044,0.09129,7.34379,0.64575,0.12384,5.21446,0.75331,0.03470,21.70742,0.73379,0.04968,14.77029,0.75047,0.03774,19.88741
9,1s_0.5,XGBoost,SMOTETomek,0.69328,0.06418,10.80170,0.68547,0.11239,6.09890,0.76206,0.02662,28.62716,0.74667,0.03272,22.82213,0.76042,0.02956,25.72335
10,1s_0.5,XGBoost,Baseline (none),0.66841,0.07398,9.03481,0.65351,0.11031,5.92438,0.74531,0.02919,25.53364,0.72798,0.03914,18.59767,0.74326,0.03159,23.52622
11,1s_0.5,Random Forest,SMOTETomek,0.66091,0.09400,7.03101,0.60864,0.14034,4.33698,0.75782,0.05059,14.98061,0.73278,0.05677,12.90760,0.75098,0.05399,13.90873
12,1s_0.8,Random Forest,SMOTETomek,0.64138,0.09158,7.00347,0.57465,0.13147,4.37088,0.74930,0.04356,17.20121,0.72123,0.05224,13.80735,0.74057,0.04841,15.29634
13,1s_0.8,Random Forest,SMOTE,0.64006,0.10712,5.97516,0.56659,0.13996,4.04835,0.75408,0.04340,17.37368,0.72320,0.05901,12.25582,0.74424,0.04874,15.26907
14,1s_0.8,Decision Tree,SMOTETomek,0.60218,0.08614,6.99064,0.55644,0.11260,4.94165,0.71074,0.02926,24.29297,0.68542,0.04512,15.19152,0.70439,0.03656,19.26931
15,1s_0.8,Random Forest,Baseline (none),0.64244,0.10529,6.10192,0.57248,0.15522,3.68820,0.75477,0.04990,15.12671,0.72428,0.06077,11.91883,0.74433,0.05543,13.42848
16,1s_0.8,Random Forest,TomekLinks,0.63855,0.10430,6.12252,0.56463,0.14791,3.81733,0.75318,0.04925,15.29174,0.72223,0.06045,11.94811,0.74254,0.05507,13.48398
17,1s_0.8,XGBoost,SMOTE,0.68286,0.08929,7.64765,0.66312,0.12251,5.41266,0.75954,0.03453,21.99440,0.74175,0.04874,15.21722,0.75725,0.03734,20.27854
18,1s_0.8,Decision Tree,TomekLinks,0.65281,0.05413,12.06052,0.65272,0.10633,6.13832,0.72447,0.02333,31.05405,0.70868,0.02142,33.08542,0.72277,0.02653,27.24597
19,1s_0.8,XGBoost,Baseline (none),0.67956,0.08664,7.84372,0.65112,0.10677,6.09841,0.75788,0.04387,17.27667,0.74071,0.05413,13.68482,0.75569,0.04595,16.44461

In [16]:
df = pd.read_csv('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/f1_score_sorted_stage_3_10_fold_sgkf.csv')
df = df.sort_values(by='Dataset', ascending=True).reset_index(drop=True)
df.head(20)

,Dataset,Model,Imbalance Technique,F1-Score (avg),F1-Score (std),F1-Score (avg:std),Recall (avg),Recall (std),Recall (avg:std),Accuracy (avg),Accuracy (std),Accuracy (avg:std),Macro F1 (avg),Macro F1 (std),Macro F1 (avg:std),Weighted F1 (avg),Weighted F1 (std),Weighted F1 (avg:std)
0,1s_0.5,XGBoost,Baseline (none),0.67432,0.13070,5.15920,0.66077,0.18428,3.58563,0.75216,0.07606,9.88955,0.73398,0.08881,8.26428,0.74763,0.08173,9.14780
1,1s_0.5,XGBoost,SMOTE,0.66794,0.13983,4.77682,0.65571,0.19716,3.32570,0.75024,0.07620,9.84620,0.73003,0.09156,7.97294,0.74452,0.08332,8.93530
2,1s_0.5,Random Forest,TomekLinks,0.67278,0.15189,4.42937,0.63112,0.19487,3.23874,0.76661,0.07829,9.79164,0.74245,0.09815,7.56462,0.75817,0.08875,8.54280
3,1s_0.5,Random Forest,Baseline (none),0.66383,0.15756,4.21310,0.61431,0.19790,3.10414,0.76473,0.07614,10.04411,0.73836,0.09953,7.41821,0.75468,0.08920,8.46004
4,1s_0.5,Decision Tree,SMOTE,0.64130,0.11352,5.64909,0.64333,0.16761,3.83828,0.71932,0.05275,13.63677,0.70196,0.06751,10.39773,0.71591,0.05838,12.26218
5,1s_0.5,Random Forest,SMOTE,0.67510,0.15318,4.40714,0.63987,0.20363,3.14226,0.76742,0.07738,9.91737,0.74364,0.09801,7.58713,0.75878,0.08892,8.53357
6,1s_0.5,Decision Tree,TomekLinks,0.60354,0.13720,4.39898,0.57961,0.18258,3.17453,0.70514,0.07714,9.14129,0.68056,0.08937,7.61518,0.69676,0.08729,7.98241
7,1s_0.5,XGBoost,SMOTETomek,0.68901,0.14008,4.91862,0.67860,0.19201,3.53425,0.76474,0.07725,9.89922,0.74646,0.09299,8.02755,0.75994,0.08422,9.02318
8,1s_0.5,Random Forest,SMOTETomek,0.67571,0.14830,4.55631,0.63789,0.20214,3.15569,0.76866,0.07386,10.40633,0.74487,0.09432,7.89765,0.75937,0.08688,8.74036
9,1s_0.5,XGBoost,TomekLinks,0.68841,0.12213,5.63689,0.67702,0.17336,3.90536,0.76075,0.07048,10.79446,0.74381,0.08248,9.01823,0.75715,0.07454,10.15753
10,1s_0.5,Decision Tree,SMOTETomek,0.60630,0.10515,5.76620,0.58117,0.15366,3.78219,0.70170,0.06408,10.94990,0.67997,0.07050,9.64483,0.69471,0.07166,9.69404
11,1s_0.5,Decision Tree,Baseline (none),0.61421,0.11878,5.17079,0.59973,0.18139,3.30637,0.70830,0.05169,13.70155,0.68541,0.06754,10.14793,0.70112,0.05918,11.84790
12,1s_0.8,Decision Tree,TomekLinks,0.60080,0.13618,4.41191,0.58131,0.17166,3.38648,0.69460,0.10022,6.93039,0.67381,0.10441,6.45337,0.69012,0.10294,6.70428
13,1s_0.8,Decision Tree,Baseline (none),0.60746,0.15270,3.97817,0.59270,0.19144,3.09606,0.70372,0.09843,7.14965,0.68073,0.10770,6.32049,0.69864,0.10122,6.90198
14,1s_0.8,XGBoost,TomekLinks,0.66697,0.13404,4.97581,0.62710,0.17727,3.53754,0.75652,0.08351,9.05905,0.73468,0.09484,7.74621,0.75027,0.08795,8.53031
15,1s_0.8,Random Forest,Baseline (none),0.66336,0.12622,5.25568,0.60011,0.17472,3.43478,0.76448,0.07850,9.73892,0.73858,0.08797,8.39600,0.75404,0.08799,8.56958
16,1s_0.8,Random Forest,SMOTETomek,0.65349,0.13701,4.76981,0.59246,0.19038,3.11199,0.76119,0.07653,9.94573,0.73272,0.09076,8.07323,0.74903,0.08817,8.49508
17,1s_0.8,Random Forest,TomekLinks,0.64616,0.14510,4.45325,0.58235,0.18613,3.12874,0.75543,0.08952,8.43848,0.72657,0.10134,7.16935,0.74395,0.09857,7.54743
18,1s_0.8,Random Forest,SMOTE,0.64524,0.14138,4.56385,0.58414,0.19229,3.03778,0.75681,0.07559,10.01236,0.72726,0.09212,7.89501,0.74433,0.08769,8.48824
19,1s_0.8,XGBoost,Baseline (none),0.67849,0.14318,4.73879,0.63990,0.17919,3.57102,0.76393,0.09301,8.21363,0.74319,0.10406,7.14229,0.75831,0.09731,7.79291

In [17]:
df = pd.read_csv('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/f1_score_sorted_stage_3_10_fold_gkf.csv')
df = df.sort_values(by='Dataset', ascending=True).reset_index(drop=True)
df.head(20)

,Dataset,Model,Imbalance Technique,F1-Score (avg),F1-Score (std),F1-Score (avg:std),Recall (avg),Recall (std),Recall (avg:std),Accuracy (avg),Accuracy (std),Accuracy (avg:std),Macro F1 (avg),Macro F1 (std),Macro F1 (avg:std),Weighted F1 (avg),Weighted F1 (std),Weighted F1 (avg:std)
0,1s_0.5,XGBoost,SMOTE,0.68012,0.16089,4.22732,0.66570,0.19524,3.40964,0.77460,0.06178,12.53828,0.74738,0.09219,8.10660,0.77148,0.06497,11.87481
1,1s_0.5,Decision Tree,TomekLinks,0.55295,0.15162,3.64688,0.52166,0.18342,2.84400,0.68227,0.09670,7.05573,0.64887,0.10473,6.19543,0.67394,0.10554,6.38554
2,1s_0.5,Random Forest,TomekLinks,0.65103,0.15667,4.15544,0.60368,0.20651,2.92319,0.76678,0.06285,12.20004,0.73169,0.08838,8.27913,0.75792,0.06855,11.05626
3,1s_0.5,XGBoost,SMOTETomek,0.66097,0.15965,4.14020,0.63706,0.20547,3.10046,0.76706,0.05579,13.74927,0.73538,0.08703,8.44990,0.76123,0.06090,12.49897
4,1s_0.5,Random Forest,SMOTE,0.64915,0.15653,4.14714,0.60021,0.20408,2.94111,0.76666,0.05807,13.20207,0.73058,0.08561,8.53405,0.75764,0.06342,11.94560
5,1s_0.5,XGBoost,TomekLinks,0.66044,0.16561,3.98796,0.63580,0.20126,3.15906,0.76500,0.06190,12.35908,0.73472,0.09403,7.81381,0.76032,0.06649,11.43556
6,1s_0.5,Decision Tree,SMOTETomek,0.57011,0.12606,4.52240,0.53409,0.17770,3.00559,0.69511,0.08073,8.61068,0.66227,0.08377,7.90554,0.68658,0.08724,7.86982
7,1s_0.5,Decision Tree,SMOTE,0.57466,0.13612,4.22184,0.56768,0.18640,3.04550,0.68441,0.07106,9.63201,0.65653,0.08405,7.81102,0.68105,0.07444,9.14915
8,1s_0.5,XGBoost,Baseline (none),0.65797,0.14680,4.48209,0.63136,0.19000,3.32290,0.76060,0.05530,13.75343,0.73171,0.08206,8.91644,0.75609,0.05866,12.88912
9,1s_0.5,Decision Tree,Baseline (none),0.56582,0.12353,4.58032,0.53877,0.15313,3.51830,0.68571,0.07019,9.76904,0.65482,0.07624,8.58856,0.68060,0.07471,9.11030
10,1s_0.5,Random Forest,Baseline (none),0.64266,0.17492,3.67399,0.58372,0.21001,2.77941,0.77033,0.05936,12.97765,0.72977,0.09464,7.71072,0.75924,0.06749,11.24921
11,1s_0.5,Random Forest,SMOTETomek,0.63396,0.18967,3.34236,0.58237,0.23102,2.52082,0.76556,0.06271,12.20858,0.72316,0.10254,7.05217,0.75321,0.07266,10.36622
12,1s_0.8,XGBoost,TomekLinks,0.64529,0.17053,3.78394,0.61656,0.21058,2.92784,0.75515,0.06491,11.63306,0.72344,0.09734,7.43222,0.74953,0.06995,10.71579
13,1s_0.8,XGBoost,Baseline (none),0.63633,0.15801,4.02718,0.59213,0.19969,2.96523,0.75375,0.06335,11.89842,0.71916,0.08936,8.04826,0.74588,0.06891,10.82394
14,1s_0.8,XGBoost,SMOTETomek,0.65679,0.16121,4.07412,0.63502,0.20298,3.12849,0.75952,0.06129,12.39307,0.73022,0.09138,7.99072,0.75504,0.06566,11.49933
15,1s_0.8,Random Forest,SMOTE,0.61203,0.21701,2.82030,0.55544,0.24141,2.30082,0.75775,0.06623,11.44140,0.71018,0.11671,6.08476,0.74253,0.08094,9.17431
16,1s_0.8,XGBoost,SMOTE,0.64484,0.16356,3.94243,0.61545,0.20295,3.03252,0.75558,0.05536,13.64929,0.72317,0.08902,8.12368,0.74978,0.06071,12.35025
17,1s_0.8,Random Forest,Baseline (none),0.63088,0.20032,3.14928,0.57012,0.22671,2.51479,0.76762,0.06371,12.04883,0.72333,0.10849,6.66728,0.75455,0.07541,10.00535
18,1s_0.8,Decision Tree,SMOTETomek,0.56092,0.15450,3.63067,0.53569,0.18956,2.82595,0.68475,0.08696,7.87460,0.65090,0.09815,6.63167,0.67835,0.09053,7.49347
19,1s_0.8,Decision Tree,SMOTE,0.57108,0.17462,3.27049,0.54408,0.21794,2.49645,0.70057,0.08603,8.14308,0.66327,0.10533,6.29694,0.69251,0.09072,7.63390