In [1]:
import pickle
import pandas as pd

In [2]:
with open('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/training_results/dt_cv_results_5_fold.pkl', 'rb') as f:
    dt_results = pickle.load(f)
with open('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/training_results/rf_cv_results_5_fold.pkl', 'rb') as f:
    rf_results = pickle.load(f)
with open('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/training_results/xgb_cv_results_5_fold.pkl', 'rb') as f:
    xgb_results = pickle.load(f)

In [3]:
imb_tech = ['none', 'oversample_smote', 'undersample_tomek_links', 'combined_smote_tomek']
models = ['Decision Tree', 'Random Forest', 'XGBoost']

In [4]:
# Combine all model results into one dictionary
all_results = {
    'Decision Tree': dt_results,
    'Random Forest': rf_results,
    'XGBoost': xgb_results
}

In [5]:
def format_cv_results_separate_models(model_results_dict, imb_tech, models):
    """
    Convert cross-validation results from separate model dictionaries to tabular format.
    
    Parameters:
    model_results_dict: Dictionary where keys are model names and values are 
                    dictionaries with structure {dataset: {imbalance_technique: {metrics...}}}
    imb_tech: List of imbalance handling techniques
    models: List of model names
    
    Returns:
    pandas.DataFrame: Formatted results table
    """
    
    formatted_data = []
    
    # Iterate through each model
    for model in models:
        if model in model_results_dict:
            model_data = model_results_dict[model]
            
            
            # Iterate through each dataset for this model
            for dataset, dataset_results in model_data.items():
                
                # Iterate through each imbalance technique
                for technique in imb_tech:
                    # Check if this technique exists in the results
                    if technique in dataset_results:
                        technique_results = dataset_results[technique]
                        
                        recall_void_avg = technique_results.get('mean_recall_minority', 0)
                        recall_void_std = technique_results.get('std_recall_minority', 0)
                        accuracy_avg = technique_results.get('mean_accuracy', 0)
                        accuracy_std = technique_results.get('std_accuracy', 0)
                        f1_void_avg = technique_results.get('mean_f1_minority', 0)
                        f1_void_std = technique_results.get('std_f1_minority', 0)
                        macro_f1_avg = technique_results.get('macro_f1', 0)
                        macro_f1_std = technique_results.get('std_macro_f1', 0)
                        weighted_f1_avg = technique_results.get('weighted_f1', 0)
                        weighted_f1_std = technique_results.get('std_weighted_f1', 0)
                        
                        if technique == "none":
                            technique = "Baseline (none)"
                        elif technique == "oversample_smote":
                            technique = "SMOTE"
                        elif technique == "undersample_tomek_links":
                            technique = "TomekLinks"
                        elif technique == "combined_smote_tomek":
                            technique = "SMOTETomek"
                        
                        # Add row to formatted data
                        formatted_data.append({
                            'Dataset': dataset,
                            'Model': model,
                            'Imbalance Technique': technique,
                            'F1-Score (avg)': round(f1_void_avg, 5),
                            'F1-Score (std)': round(f1_void_std, 5),
                            'F1-Score (avg:std)': round(f1_void_avg/f1_void_std, 5),
                            'Recall (avg)': round(recall_void_avg, 5),
                            'Recall (std)': round(recall_void_std, 5),
                            'Recall (avg:std)': round(recall_void_avg/recall_void_std, 5),
                            'Accuracy (avg)': round(accuracy_avg, 5),
                            'Accuracy (std)': round(accuracy_std, 5),
                            'Accuracy (avg:std)': round(accuracy_avg/accuracy_std, 5),
                            'Macro F1 (avg)': round(macro_f1_avg, 5),
                            'Macro F1 (std)': round(macro_f1_std, 5),
                            'Macro F1 (avg:std)': round(macro_f1_avg/macro_f1_std, 5),
                            'Weighted F1 (avg)': round(weighted_f1_avg, 5),
                            'Weighted F1 (std)': round(weighted_f1_std, 5),
                            'Weighted F1 (avg:std)': round(weighted_f1_avg/weighted_f1_std, 5)
                            
                        })
                        
                        
    
    # Create DataFrame
    df = pd.DataFrame(formatted_data)
    
    # Sort by Dataset, Model, and Imbalance Technique for better organization
    # df = df.sort_values(['Dataset', 'Model', 'Imbalance Technique']).reset_index(drop=True)
    
    return df


print("Function ready to use for separate model dictionaries.")

Function ready to use for separate model dictionaries.

In [6]:
df = format_cv_results_separate_models(all_results, imb_tech, models)
df

,Dataset,Model,Imbalance Technique,F1-Score (avg),F1-Score (std),F1-Score (avg:std),Recall (avg),Recall (std),Recall (avg:std),Accuracy (avg),Accuracy (std),Accuracy (avg:std),Macro F1 (avg),Macro F1 (std),Macro F1 (avg:std),Weighted F1 (avg),Weighted F1 (std),Weighted F1 (avg:std)
0,1s_no,Decision Tree,Baseline (none),0.58779,0.04797,12.25255,0.56760,0.07420,7.64941,0.68345,0.03198,21.37161,0.66373,0.02972,22.33048,0.68098,0.03613,18.84771
1,1s_no,Decision Tree,SMOTE,0.54172,0.08411,6.44049,0.51369,0.10642,4.82689,0.66038,0.00804,82.12496,0.63203,0.02794,22.61906,0.65501,0.00710,92.20187
2,1s_no,Decision Tree,TomekLinks,0.56574,0.03962,14.27972,0.53966,0.07829,6.89314,0.67091,0.02324,28.87430,0.64792,0.00888,72.99479,0.66697,0.02346,28.43536
3,1s_no,Decision Tree,SMOTETomek,0.59759,0.06505,9.18668,0.58848,0.12490,4.71155,0.69056,0.02587,26.68957,0.66900,0.02278,29.36815,0.68688,0.02702,25.42264
4,1s_0.5,Decision Tree,Baseline (none),0.60295,0.07664,7.86751,0.58361,0.10798,5.40489,0.69802,0.02711,25.74562,0.67703,0.03793,17.84810,0.69472,0.03372,20.60459
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,5s_0.5,XGBoost,SMOTETomek,0.73267,0.08044,9.10836,0.74874,0.10692,7.00291,0.77713,0.05496,14.13926,0.76979,0.05945,12.94784,0.77742,0.05555,13.99466
176,5s_0.8,XGBoost,Baseline (none),0.71314,0.06501,10.96933,0.70971,0.11846,5.99100,0.75653,0.05195,14.56278,0.75037,0.05360,14.00020,0.75615,0.05465,13.83713
177,5s_0.8,XGBoost,SMOTE,0.71811,0.05885,12.20314,0.71639,0.11098,6.45515,0.75951,0.04659,16.30279,0.75375,0.04821,15.63563,0.75954,0.04777,15.89988
178,5s_0.8,XGBoost,TomekLinks,0.72758,0.06234,11.67147,0.75137,0.15102,4.97535,0.76308,0.04502,16.94955,0.75841,0.04741,15.99540,0.76285,0.04833,15.78369
179,5s_0.8,XGBoost,SMOTETomek,0.73607,0.06520,11.28951,0.75805,0.14058,5.39220,0.77014,0.05015,15.35764,0.76575,0.05214,14.68553,0.77041,0.05202,14.80982

In [7]:
df_sorted_f1_score = df.sort_values(by='F1-Score (avg)', ascending=False).reset_index(drop=True)
df_sorted_f1_score

,Dataset,Model,Imbalance Technique,F1-Score (avg),F1-Score (std),F1-Score (avg:std),Recall (avg),Recall (std),Recall (avg:std),Accuracy (avg),Accuracy (std),Accuracy (avg:std),Macro F1 (avg),Macro F1 (std),Macro F1 (avg:std),Weighted F1 (avg),Weighted F1 (std),Weighted F1 (avg:std)
0,3s_no,XGBoost,TomekLinks,0.73638,0.09174,8.02723,0.75589,0.09958,7.59079,0.77729,0.07168,10.84421,0.77103,0.07496,10.28608,0.77842,0.07087,10.98316
1,5s_0.8,XGBoost,SMOTETomek,0.73607,0.06520,11.28951,0.75805,0.14058,5.39220,0.77014,0.05015,15.35764,0.76575,0.05214,14.68553,0.77041,0.05202,14.80982
2,5s_0.5,XGBoost,SMOTETomek,0.73267,0.08044,9.10836,0.74874,0.10692,7.00291,0.77713,0.05496,14.13926,0.76979,0.05945,12.94784,0.77742,0.05555,13.99466
3,3s_no,Random Forest,Baseline (none),0.73145,0.09084,8.05209,0.71697,0.10832,6.61887,0.78677,0.05481,14.35496,0.77599,0.06329,12.26111,0.78575,0.05587,14.06439
4,3s_no,Random Forest,SMOTE,0.73118,0.09699,7.53841,0.73281,0.11631,6.30033,0.78156,0.06247,12.51156,0.77202,0.07001,11.02699,0.78134,0.06290,12.42168
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,2s_0.5,Decision Tree,SMOTE,0.55775,0.05400,10.32886,0.52663,0.09382,5.61289,0.66653,0.03363,19.81824,0.64365,0.03399,18.93461,0.66141,0.04159,15.90494
176,5s_0.8,Decision Tree,SMOTE,0.55680,0.07375,7.54980,0.53478,0.10327,5.17840,0.63399,0.06943,9.13078,0.62177,0.06803,9.13913,0.63176,0.07357,8.58692
177,5s_no,Decision Tree,SMOTE,0.55130,0.07152,7.70857,0.52986,0.09558,5.54364,0.64141,0.06142,10.44356,0.62612,0.06230,10.05026,0.63758,0.06087,10.47537
178,1s_no,Decision Tree,SMOTE,0.54172,0.08411,6.44049,0.51369,0.10642,4.82689,0.66038,0.00804,82.12496,0.63203,0.02794,22.61906,0.65501,0.00710,92.20187
179,5s_no,Decision Tree,Baseline (none),0.50295,0.06886,7.30347,0.46686,0.09575,4.87580,0.62149,0.02465,25.21278,0.59749,0.03664,16.30479,0.61333,0.02656,23.08811

In [8]:
df_sorted_f1_score.to_csv('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/f1_score_sorted_stage_3.csv', index=False)