In [1]:
import os
import pickle
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from tqdm import tqdm
from essentials import resample_data, three_class_labels, two_class_labels, normalize
from features_acc_gyr_improved import GenerateFeatures 
import copy

Extract windowed features from the 3 axis of the accelerometer and the acceleration magnitude.
1. mean
2. rms
3. std
4. range
5. variance
6. min
7. max
8. time energy
9. spectral energy
10. permutation entropy
11. spectral entropy
12. spectral_centroid
13. spectral_spread
14. spectral_flatness
15. peak_frequency_ratio
16. hjorth_frequency
17. spectral_skewness
18. spectral_kurtosis
19. snr

## Two class data

In [2]:
# Save the dictionay
with open('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/train_data_with_3_class_labels.pkl', 'rb') as f:
    train_data_3_class_labelled = pickle.load(f)

## Data 1
classes: void, non-void

fs: original

sliding window: 1s

overlap: 0

filename: two_class_1s_no.csv

In [3]:
#  do not upsample
all_features = []
for i, exp_id in enumerate(train_data_3_class_labelled.keys()):    
    # Extract features
    
    df = train_data_3_class_labelled[exp_id]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=1.0, overlap=0.0)
    features, _ = analyzer.analyze_multi_axis_imu(train_data_3_class_labelled[exp_id])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id 
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.89it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.82it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.95it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.56it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.33it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.25it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.59it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.32it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.90it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.29it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.41it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.98it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.06it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.62it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.97it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.34it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.82it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.78it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.47it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.39it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.81it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.21it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.16it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.08it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.54it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.88it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.19it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.67it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.49it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.40it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.48it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.46it/s]

In [4]:
final_features.to_csv('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/extracted_features_data/3_class/train_set/two_class_1s_no.csv', index=False)
final_features

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,0.499593,0.000000,0.999186,0.840598,0.524760,-0.149886,0.135005,0.636465,0.201723,0.018226,...,6.128988,3.270609,0.077737,0.159635,9.035772,0.684807,4.290588,-7.213397,pre-void,1
1,1.498779,0.999186,1.998371,0.816380,0.561207,-0.128859,0.100911,0.422721,0.163669,0.010183,...,3.162707,2.380611,0.044891,0.342972,8.006620,2.638890,16.398712,-2.823253,pre-void,1
2,2.497964,1.998371,2.997557,0.892873,0.755155,-0.165836,0.029221,0.125490,0.168390,0.000854,...,5.081961,6.491006,0.301986,0.507223,15.227381,1.773974,5.174935,0.125484,pre-void,1
3,3.497150,2.997557,3.996743,0.928689,0.707887,-0.175810,0.034849,0.179349,0.179231,0.001214,...,4.064340,4.811542,0.133161,0.464447,11.886504,1.854312,6.262267,-0.618664,pre-void,1
4,4.496336,3.996743,4.995929,0.874944,0.797456,-0.191594,0.027546,0.138242,0.193564,0.000759,...,5.471171,4.586688,0.155900,0.204887,11.699750,1.089969,3.556831,-5.889156,pre-void,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1765,32.258156,31.761877,32.754436,0.846669,0.599915,-1.097566,0.243207,1.034034,1.124188,0.059149,...,7.150803,5.004041,0.246490,0.156285,12.559290,1.491561,6.154050,-7.322793,post-void,39
1766,33.250715,32.754436,33.746994,0.869830,0.679786,-1.170488,0.233427,0.940667,1.193537,0.054488,...,9.349971,6.679339,0.372982,0.202429,13.443788,0.682798,2.682979,-5.954979,post-void,39
1767,34.243274,33.746994,34.739553,0.877840,0.701789,-1.414645,0.267592,1.096611,1.439731,0.071606,...,4.046879,5.220814,0.128217,0.453700,13.849622,2.308186,8.140533,-0.806631,post-void,39
1768,35.235832,34.739553,35.732112,0.748730,0.625765,-2.110039,0.614345,2.331285,2.197654,0.377420,...,2.178804,2.833705,0.030173,0.657779,11.225785,3.454192,16.753635,2.837733,post-void,39
1769,36.228391,35.732112,36.724670,0.801472,0.578007,-3.005887,0.356878,1.555198,3.026999,0.127362,...,6.944647,6.473886,0.379348,0.169834,13.413586,1.786140,5.970940,-6.891407,post-void,39

## Data 1b
classes: void, non-void

fs: original

sliding window: 1s

overlap: 0.5

filename: two_class_1s_0.5.csv

In [5]:
#  do not upsample
all_features = []
for i, exp_id in enumerate(train_data_3_class_labelled.keys()):    
    # Extract features
    
    df = train_data_3_class_labelled[exp_id]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=1.0, overlap=0.5)
    features, _ = analyzer.analyze_multi_axis_imu(train_data_3_class_labelled[exp_id])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id 
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.95it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.46it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.56it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.95it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.43it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.90it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.31it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.27it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.57it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.49it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.60it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.23it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.04it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.91it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.01it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.61it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.66it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.53it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.86it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.49it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.00it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.81it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.30it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.28it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.12it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.75it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.08it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.30it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.45it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.92it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.62it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.43it/s]

In [6]:
final_features.to_csv('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/extracted_features_data/3_class/train_set/two_class_1s_0.5.csv', index=False)
final_features

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,0.499593,0.000000,0.999186,0.840598,0.524760,-0.149886,0.135005,0.636465,0.201723,0.018226,...,6.128988,3.270609,0.077737,0.159635,9.035772,0.684807,4.290588,-7.213397,pre-void,1
1,1.007653,0.508061,1.507246,0.782302,0.569386,-0.116189,0.144666,0.636465,0.185548,0.020928,...,5.825284,3.327186,0.109678,0.206261,9.324631,1.250563,5.699692,-5.852595,pre-void,1
2,1.515714,1.016121,2.015307,0.836558,0.566357,-0.127848,0.100060,0.422721,0.162349,0.010012,...,3.012122,2.339783,0.042194,0.371534,8.062902,2.770082,17.571583,-2.282827,pre-void,1
3,2.023774,1.524182,2.523367,0.890205,0.731923,-0.173969,0.036694,0.176019,0.177797,0.001346,...,6.192510,7.392962,0.355143,0.304635,13.393570,1.442088,3.786784,-3.584328,pre-void,1
4,2.531835,2.032242,3.031428,0.892873,0.739814,-0.164056,0.029785,0.125490,0.166738,0.000887,...,4.831671,6.447955,0.284025,0.551200,15.314346,1.847847,5.397736,0.892573,pre-void,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3486,34.739553,34.243274,35.235832,0.820859,0.687372,-1.596480,0.334536,1.219866,1.631154,0.111914,...,2.790669,4.190898,0.107156,0.492565,12.461179,3.698342,16.898797,-0.129171,post-void,39
3487,35.235832,34.739553,35.732112,0.748730,0.625765,-2.110039,0.614345,2.331285,2.197654,0.377420,...,2.178804,2.833705,0.030173,0.657779,11.225785,3.454192,16.753635,2.837733,post-void,39
3488,35.732112,35.235832,36.228391,0.808091,0.588694,-2.750538,0.423527,2.050909,2.782954,0.179376,...,2.382355,3.603588,0.086511,0.704855,12.892031,3.926562,20.968950,3.780649,post-void,39
3489,36.228391,35.732112,36.724670,0.801472,0.578007,-3.005887,0.356878,1.555198,3.026999,0.127362,...,6.944647,6.473886,0.379348,0.169834,13.413586,1.786140,5.970940,-6.891407,post-void,39
3490,36.724670,36.228391,37.220950,0.819410,0.576496,-3.168008,0.441661,1.846962,3.198647,0.195065,...,3.435039,5.327833,0.149333,0.627097,13.504292,2.545835,8.687655,2.257381,post-void,39

## Data 1c
classes: void, non-void

fs: original

sliding window: 1s

overlap: 0.8

filename: two_class_1s_0.8.csv

In [7]:
all_features = []
for i, exp_id in enumerate(train_data_3_class_labelled.keys()):    
    # Extract features
    
    df = train_data_3_class_labelled[exp_id]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=1.0, overlap=0.8)
    features, _ = analyzer.analyze_multi_axis_imu(train_data_3_class_labelled[exp_id])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id 
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.37it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.95it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.77it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.01it/s]
Analyzing : 100%|██████████| 8/8 [00:05<00:00,  1.52it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.50it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.67it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.68it/s]
Analyzing : 100%|██████████| 8/8 [00:06<00:00,  1.22it/s]
Analyzing : 100%|██████████| 8/8 [00:05<00:00,  1.40it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.94it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.03it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.76it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.70it/s]
Analyzing : 100%|██████████| 8/8 [00:07<00:00,  1.05it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.96it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.67it/s]
Analyzing : 100%|██████████| 8/8 [00:06<00:00,  1.21it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.10it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.62it/s]
Analyzing : 100%|██████████| 8/8 [00:11<00:00,  1.49s/it]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.06it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.82it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.96it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.57it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.23it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.68it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.67it/s]
Analyzing : 100%|██████████| 8/8 [00:04<00:00,  1.73it/s]
Analyzing : 100%|██████████| 8/8 [00:05<00:00,  1.51it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.45it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.66it/s]

In [8]:
final_features.to_csv('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/extracted_features_data/3_class/train_set/two_class_1s_0.8.csv', index=False)
final_features

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,0.499593,0.000000,0.999186,0.840598,0.524760,-0.149886,0.135005,0.636465,0.201723,0.018226,...,6.128988,3.270609,0.077737,0.159635,9.035772,0.684807,4.290588,-7.213397,pre-void,1
1,0.702817,0.203224,1.202410,0.837070,0.531177,-0.144630,0.137085,0.636465,0.199274,0.018792,...,5.945896,4.516311,0.149935,0.204095,9.106386,0.938409,3.738801,-5.910291,pre-void,1
2,0.906041,0.406448,1.405634,0.820866,0.551507,-0.115810,0.144308,0.636465,0.185032,0.020825,...,6.612315,3.921351,0.173680,0.162904,9.573358,0.906207,4.717683,-7.108427,pre-void,1
3,1.109266,0.609673,1.608858,0.845735,0.549954,-0.110630,0.140647,0.636465,0.178943,0.019782,...,4.953244,2.795979,0.056057,0.277068,9.237566,1.723568,7.467920,-4.165102,pre-void,1
4,1.312490,0.812897,1.812083,0.832624,0.599562,-0.125701,0.142798,0.636465,0.190241,0.020391,...,4.246927,2.427224,0.049224,0.377922,8.774607,2.270194,12.131074,-2.164424,pre-void,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8666,35.831368,35.335088,36.327647,0.796407,0.563314,-2.862205,0.365402,1.581726,2.885435,0.133519,...,3.015421,4.522670,0.157647,0.599473,14.016518,3.238579,14.475131,1.751372,post-void,39
8667,36.029879,35.533600,36.526159,0.804800,0.599143,-2.960879,0.318725,1.495445,2.977984,0.101586,...,4.907747,5.872714,0.252161,0.298235,13.403143,2.373037,8.386840,-3.716335,post-void,39
8668,36.228391,35.732112,36.724670,0.801472,0.578007,-3.005887,0.356878,1.555198,3.026999,0.127362,...,6.944647,6.473886,0.379348,0.169834,13.413586,1.786140,5.970940,-6.891407,post-void,39
8669,36.426903,35.930623,36.923182,0.805660,0.582599,-3.045145,0.398491,1.555198,3.071108,0.158795,...,8.076466,5.770468,0.313274,0.262188,13.990290,1.589551,5.823798,-4.493323,post-void,39
8670,36.625415,36.129135,37.121694,0.819868,0.575103,-3.093234,0.418553,1.623489,3.121423,0.175186,...,4.941836,6.247022,0.221445,0.479710,13.667158,1.741166,5.086343,-0.352666,post-void,39

## Data 2
classes: void, non-void

fs: original

overlap: 0

sliding window: 2s

filename: two_class_2s_no.csv

In [9]:
all_features = []
for i, exp_id in enumerate(train_data_3_class_labelled.keys()):    
    # Extract features
    
    df = train_data_3_class_labelled[exp_id]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=2.0, overlap=0.0)
    features, _ = analyzer.analyze_multi_axis_imu(train_data_3_class_labelled[exp_id])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id 
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.88it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 26.74it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.81it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.72it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.72it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.60it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 24.13it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.62it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.98it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.62it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.91it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 32.03it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.68it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 22.80it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.72it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 28.56it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.00it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.74it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.48it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.64it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.21it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 22.32it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 26.11it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.17it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 32.71it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.41it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 26.84it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.04it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.21it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.15it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 22.97it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 28.08it/s]

In [10]:
final_features.to_csv('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/extracted_features_data/3_class/train_set/two_class_2s_no.csv', index=False)
final_features

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,0.999186,0.000000,1.998371,0.837517,0.656083,-0.139372,0.119646,0.636465,0.183684,0.014315,...,4.973245,3.402193,0.080453,0.144977,8.783728,1.407393,6.138293,-7.706802,pre-void,1
1,2.997557,1.998371,3.996743,0.914142,0.780981,-0.170823,0.032543,0.179349,0.173895,0.001059,...,5.024069,5.999596,0.217646,0.198182,13.076126,1.654593,5.624663,-6.070107,pre-void,1
2,4.995929,3.996743,5.995114,0.911102,0.825743,-0.216171,0.057080,0.389462,0.223580,0.003258,...,3.728964,5.269030,0.140931,0.482816,9.867078,1.920452,6.117087,-0.298632,pre-void,1
3,6.994300,5.995114,7.993486,0.880385,0.714032,-0.161397,0.100771,0.649299,0.190273,0.010155,...,4.542228,4.966225,0.161914,0.201230,12.481580,1.777758,6.371291,-5.987279,pre-void,1
4,8.992671,7.993486,9.991857,0.915965,0.812030,-0.194357,0.052768,0.351772,0.201393,0.002784,...,3.403561,4.203849,0.066647,0.321067,10.418367,1.793800,5.839936,-3.252304,pre-void,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
868,27.022409,26.021580,28.023239,0.847764,0.573672,-0.982597,0.175037,0.706943,0.998065,0.030638,...,7.144130,6.863254,0.372152,0.155142,15.661849,1.481164,4.413282,-7.360543,void,39
869,29.024069,28.023239,30.024899,0.873126,0.582061,-0.891175,0.201570,0.896987,0.913687,0.040631,...,5.755416,7.314940,0.278575,0.259670,15.802308,1.618340,4.813061,-4.550038,void,39
870,31.025729,30.024899,32.026559,0.844462,0.578726,-1.213362,0.249084,1.099539,1.238665,0.062043,...,8.730852,6.318585,0.384311,0.100759,14.365634,0.652464,2.878272,-9.505924,post-void,39
871,33.027389,32.026559,34.028219,0.850670,0.687727,-1.148687,0.237756,1.161008,1.173035,0.056528,...,8.497276,6.242294,0.320527,0.138286,13.249134,0.735665,2.954532,-7.945840,post-void,39
872,35.029049,34.028219,36.029879,0.838860,0.633065,-2.009793,0.680092,2.409411,2.121743,0.462526,...,1.705524,2.678839,0.039359,0.378956,13.126762,5.007277,32.402363,-2.145334,post-void,39

## Data 2b
classes: void, non-void

fs: original

overlap: 0.5

sliding window: 2s

filename: two_class_2s_0.5.csv

In [11]:
all_features = []
for i, exp_id in enumerate(train_data_3_class_labelled.keys()):    
    # Extract features
    
    df = train_data_3_class_labelled[exp_id]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=2.0, overlap=0.5)
    features, _ = analyzer.analyze_multi_axis_imu(train_data_3_class_labelled[exp_id])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id 
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.47it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.89it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.15it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.41it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.73it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.52it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.75it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.50it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.08it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.31it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.26it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.84it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.57it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.01it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.40it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.59it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.11it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.90it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.79it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.14it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.67it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.52it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.40it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.86it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.93it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.57it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.45it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.64it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.67it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.68it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.26it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.55it/s]

In [12]:
final_features.to_csv('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/extracted_features_data/3_class/train_set/two_class_2s_0.5.csv', index=False)
final_features

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,0.999186,0.000000,1.998371,0.837517,0.656083,-0.139372,0.119646,0.636465,0.183684,0.014315,...,4.973245,3.402193,0.080453,0.144977,8.783728,1.407393,6.138293,-7.706802,pre-void,1
1,1.998371,0.999186,2.997557,0.872310,0.644016,-0.147347,0.076552,0.422721,0.166047,0.005860,...,1.862911,3.236142,0.069860,0.480370,9.259358,4.720475,28.888165,-0.341188,pre-void,1
2,2.997557,1.998371,3.996743,0.914142,0.780981,-0.170823,0.032543,0.179349,0.173895,0.001059,...,5.024069,5.999596,0.217646,0.198182,13.076126,1.654593,5.624663,-6.070107,pre-void,1
3,3.996743,2.997557,4.995929,0.909732,0.722111,-0.183702,0.032387,0.179349,0.186535,0.001049,...,5.606923,4.872742,0.115606,0.137108,11.758527,0.899243,2.581943,-7.988937,pre-void,1
4,4.995929,3.996743,5.995114,0.911102,0.825743,-0.216171,0.057080,0.389462,0.223580,0.003258,...,3.728964,5.269030,0.140931,0.482816,9.867078,1.920452,6.117087,-0.298632,pre-void,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1729,31.770148,30.769318,32.770978,0.851780,0.585915,-1.193678,0.260643,1.204562,1.221802,0.067935,...,5.926666,6.175735,0.248717,0.233556,12.691763,1.051892,3.325783,-5.160895,post-void,39
1730,32.762707,31.761877,33.763537,0.866022,0.641904,-1.136146,0.241261,1.161008,1.161480,0.058207,...,8.111971,5.702927,0.337216,0.120810,12.907105,0.963092,3.769417,-8.619789,post-void,39
1731,33.755266,32.754436,34.756096,0.874985,0.708876,-1.295161,0.279488,1.318397,1.324974,0.078114,...,6.173198,5.929398,0.275066,0.139552,13.831997,1.595303,5.012786,-7.899869,post-void,39
1732,34.747824,33.746994,35.748654,0.844601,0.661254,-1.770115,0.591440,2.409411,1.866309,0.349802,...,2.309005,3.481662,0.072750,0.374355,12.894727,4.176257,22.318018,-2.230443,post-void,39
1733,35.740383,34.739553,36.741213,0.809557,0.579979,-2.556069,0.670607,2.726056,2.642575,0.449713,...,1.844479,3.395916,0.072617,0.410767,12.996261,4.387055,25.400811,-1.566911,post-void,39

## Data 2c
classes: void, non-void

fs: original

overlap: 0.8

sliding window: 2s

filename: two_class_2s_0.8.csv

In [13]:
all_features = []
for i, exp_id in enumerate(train_data_3_class_labelled.keys()):    
    # Extract features
    
    df = train_data_3_class_labelled[exp_id]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=2.0, overlap=0.8)
    features, _ = analyzer.analyze_multi_axis_imu(train_data_3_class_labelled[exp_id])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id 
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.96it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.77it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.94it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.73it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.92it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.83it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.24it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.35it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.29it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.52it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.92it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.28it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.82it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.98it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.11it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.91it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.53it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.40it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.24it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.43it/s]
Analyzing : 100%|██████████| 8/8 [00:05<00:00,  1.44it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.64it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.05it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.22it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.62it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.65it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.49it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.29it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.56it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.22it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.94it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.83it/s]

In [14]:
final_features.to_csv('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/extracted_features_data/3_class/train_set/two_class_2s_0.8.csv', index=False)
final_features

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,0.999186,0.000000,1.998371,0.837517,0.656083,-0.139372,0.119646,0.636465,0.183684,0.014315,...,4.973245,3.402193,0.080453,0.144977,8.783728,1.407393,6.138293,-7.706802,pre-void,1
1,1.405634,0.406448,2.404820,0.848505,0.635690,-0.138511,0.110606,0.636465,0.177254,0.012234,...,3.020223,2.743667,0.033970,0.251538,9.791299,1.968992,9.884177,-4.735654,pre-void,1
2,1.812083,0.812897,2.811268,0.873042,0.645428,-0.145194,0.104743,0.636465,0.179032,0.010971,...,1.900022,2.548418,0.044766,0.421032,9.486592,4.345030,30.805002,-1.383389,pre-void,1
3,2.218531,1.219345,3.217717,0.891110,0.693331,-0.154689,0.066550,0.422721,0.168398,0.004429,...,2.539390,4.815557,0.129651,0.532229,9.430916,3.256985,13.411339,0.560659,pre-void,1
4,2.624979,1.625794,3.624165,0.904195,0.787057,-0.169165,0.030420,0.176019,0.171879,0.000925,...,4.632770,6.346648,0.231039,0.374316,14.005519,1.914875,5.905884,-2.231173,pre-void,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4256,34.350801,33.349971,35.351631,0.862857,0.690602,-1.480867,0.353794,1.728180,1.522543,0.125170,...,3.337781,4.583624,0.133775,0.290590,13.182892,2.964210,12.042134,-3.876161,post-void,39
4257,34.747824,33.746994,35.748654,0.844601,0.661254,-1.770115,0.591440,2.409411,1.866309,0.349802,...,2.309005,3.481662,0.072750,0.374355,12.894727,4.176257,22.318018,-2.230443,post-void,39
4258,35.144848,34.144018,36.145678,0.834552,0.623518,-2.113615,0.688950,2.388198,2.223065,0.474651,...,1.602282,2.526483,0.031661,0.427280,12.775651,5.034380,32.962644,-1.272294,post-void,39
4259,35.541871,34.541041,36.542701,0.816474,0.608873,-2.432096,0.692325,2.631123,2.528716,0.479314,...,1.542655,2.734335,0.042603,0.430123,13.151705,4.915684,31.659987,-1.221888,post-void,39
4260,35.938895,34.938065,36.939725,0.812103,0.555407,-2.700371,0.641205,2.726056,2.775455,0.411144,...,2.615143,4.437368,0.118681,0.389629,13.097804,3.384815,15.878372,-1.949426,post-void,39

## Data 3
classes: void, non-void

fs: original

overlap: 0

sliding window: 3s

filename: two_class_3s_no.csv

In [15]:
all_features = []
for i, exp_id in enumerate(train_data_3_class_labelled.keys()):    
    # Extract features
    
    df = train_data_3_class_labelled[exp_id]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=3.0, overlap=0.0)
    features, _ = analyzer.analyze_multi_axis_imu(train_data_3_class_labelled[exp_id])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id 
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 29.26it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 38.72it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.75it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 26.76it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.40it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 33.15it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 35.48it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 22.74it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.66it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.81it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 31.26it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 48.98it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 38.23it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 37.97it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.06it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 44.73it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 41.61it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.79it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 27.17it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.52it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.27it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 32.88it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 41.19it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 28.91it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 48.02it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 32.84it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 40.60it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.19it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.72it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 22.25it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 33.42it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 39.95it/s]

In [16]:
final_features.to_csv('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/extracted_features_data/3_class/train_set/two_class_3s_no.csv', index=False)
final_features

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,1.498779,0.000000,2.997557,0.868352,0.694367,-0.148194,0.099919,0.636465,0.178732,0.009984,...,2.656225,2.949630,0.049307,0.248389,9.106205,2.243864,11.056188,-4.808599,pre-void,1
1,4.496336,2.997557,5.995114,0.919605,0.790731,-0.202718,0.054212,0.389462,0.209841,0.002939,...,5.066600,5.201107,0.141633,0.174256,10.305932,1.150427,3.507220,-6.756563,pre-void,1
2,7.493893,5.995114,8.992671,0.903234,0.730563,-0.171332,0.084604,0.649299,0.191082,0.007158,...,5.055212,4.458169,0.161638,0.101784,11.676143,1.263329,4.954845,-9.457007,pre-void,1
3,10.491450,8.992671,11.990229,0.873187,0.787136,-0.185989,0.058548,0.351772,0.194987,0.003428,...,2.225391,3.602693,0.078070,0.369148,10.888851,3.340817,15.950191,-2.327278,pre-void,1
4,13.489007,11.990229,14.987786,0.915277,0.765171,-0.215575,0.056531,0.428480,0.222864,0.003196,...,3.922351,4.390918,0.097305,0.130874,11.348421,1.475079,4.596238,-8.222292,pre-void,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
573,22.456640,20.959530,23.953749,0.925636,0.800629,-0.481958,0.155392,0.799633,0.506389,0.024147,...,4.262057,6.033539,0.241452,0.314368,15.181524,1.891727,5.767294,-3.386533,void,39
574,25.450858,23.953749,26.947968,0.843216,0.574470,-0.984026,0.244694,1.230357,1.013994,0.059875,...,4.163125,6.394834,0.212572,0.273939,15.611999,2.123986,6.585957,-4.233185,void,39
575,28.445077,26.947968,29.942186,0.856017,0.567938,-0.921485,0.198829,0.896987,0.942691,0.039533,...,6.779742,8.573495,0.363882,0.183993,15.335031,1.317932,3.371843,-6.468929,void,39
576,31.439296,29.942186,32.936405,0.842292,0.579710,-1.159737,0.254708,1.204562,1.187378,0.064876,...,7.328603,6.431473,0.284553,0.126143,13.676037,0.812490,2.855378,-8.405753,post-void,39
577,34.433514,32.936405,35.930623,0.847811,0.663063,-1.688227,0.650583,2.631198,1.809245,0.423258,...,2.526650,3.963764,0.094749,0.262980,13.140935,3.564512,16.845843,-4.475574,post-void,39

## Data 3b
classes: void, non-void

fs: original

overlap: 0.5

sliding window: 3s

filename: two_class_3s_0.5.csv

In [17]:
all_features = []
for i, exp_id in enumerate(train_data_3_class_labelled.keys()):    
    # Extract features
    
    df = train_data_3_class_labelled[exp_id]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=3.0, overlap=0.5)
    features, _ = analyzer.analyze_multi_axis_imu(train_data_3_class_labelled[exp_id])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id 
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.37it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.25it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.12it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.20it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.94it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.06it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.22it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.15it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.70it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.73it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.31it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.09it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.91it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.22it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.65it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.40it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.57it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.23it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.89it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.46it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.38it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.77it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.58it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.57it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.29it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.49it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.45it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.31it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.72it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.47it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.36it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.41it/s]

In [18]:
final_features.to_csv('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/extracted_features_data/3_class/train_set/two_class_3s_0.5.csv', index=False)
final_features

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,1.498779,0.000000,2.997557,0.868352,0.694367,-0.148194,0.099919,0.636465,0.178732,0.009984,...,2.656225,2.949630,0.049307,0.248389,9.106205,2.243864,11.056188,-4.808599,pre-void,1
1,2.989089,1.490311,4.487868,0.906822,0.799264,-0.174538,0.034140,0.179349,0.177846,0.001166,...,3.598938,5.267812,0.162077,0.332296,12.143409,2.129258,7.544642,-3.030593,pre-void,1
2,4.479400,2.980622,5.978179,0.919605,0.791796,-0.204069,0.051464,0.297212,0.210459,0.002649,...,5.187087,5.197030,0.141814,0.152158,11.021239,1.114990,3.415616,-7.460201,pre-void,1
3,5.969711,4.470933,7.468490,0.892201,0.713119,-0.196286,0.096299,0.649299,0.218636,0.009274,...,2.592291,3.151812,0.073457,0.167498,11.397388,3.461575,20.012066,-6.963742,pre-void,1
4,7.460022,5.961244,8.958801,0.902390,0.730050,-0.169235,0.086090,0.649299,0.189874,0.007412,...,5.018273,4.496509,0.165104,0.106355,11.200776,1.290345,5.027651,-9.244050,pre-void,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1138,28.296193,26.799084,29.793302,0.850714,0.576087,-0.922354,0.197748,0.896987,0.943314,0.039104,...,6.352680,8.368838,0.336708,0.229734,15.264180,1.425502,3.665895,-5.254148,void,39
1139,29.785031,28.287922,31.282140,0.843303,0.550396,-1.011855,0.270730,1.250551,1.047447,0.073294,...,4.603439,6.666846,0.281030,0.175240,14.948121,2.044503,6.368343,-6.726930,void,39
1140,31.273869,29.776760,32.770978,0.850726,0.558539,-1.151897,0.263942,1.204562,1.181750,0.069665,...,8.076575,6.526329,0.307457,0.102704,13.980464,0.745450,2.878411,-9.413495,post-void,39
1141,32.762707,31.265598,34.259816,0.867587,0.639873,-1.190413,0.245424,1.161008,1.215449,0.060233,...,7.783980,5.875353,0.343871,0.093281,13.567907,1.016747,3.787473,-9.876807,post-void,39
1142,34.251545,32.754436,35.748654,0.855702,0.687467,-1.571344,0.575835,2.631198,1.673531,0.331586,...,2.912535,4.384346,0.118675,0.244639,13.164283,3.117610,13.302315,-4.896291,post-void,39

## Data 3c
classes: void, non-void

fs: original

overlap: 0.8

sliding window: 3s

filename: two_class_3s_0.8.csv

In [19]:
all_features = []
for i, exp_id in enumerate(train_data_3_class_labelled.keys()):    
    # Extract features
    
    df = train_data_3_class_labelled[exp_id]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=3.0, overlap=0.8)
    features, _ = analyzer.analyze_multi_axis_imu(train_data_3_class_labelled[exp_id])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id 
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.83it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.40it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.52it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.00it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.87it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.43it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.54it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.15it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.11it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.57it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.77it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.67it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.30it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.47it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.17it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.22it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.21it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.63it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.58it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.95it/s]
Analyzing : 100%|██████████| 8/8 [00:03<00:00,  2.13it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.87it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.65it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.80it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.49it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.31it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.01it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.71it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.16it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.30it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.19it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.03it/s]

In [20]:
final_features.to_csv('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/extracted_features_data/3_class/train_set/two_class_3s_0.8.csv', index=False)
final_features

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,1.498779,0.000000,2.997557,0.868352,0.694367,-0.148194,0.099919,0.636465,0.178732,0.009984,...,2.656225,2.949630,0.049307,0.248389,9.106205,2.243864,11.056188,-4.808599,pre-void,1
1,2.091516,0.592737,3.590294,0.891024,0.700772,-0.150083,0.089513,0.636465,0.174750,0.008013,...,1.761556,2.879331,0.056553,0.442731,10.036862,4.346431,28.385433,-0.999250,pre-void,1
2,2.684253,1.185475,4.183032,0.904307,0.779004,-0.162039,0.061438,0.422721,0.173295,0.003775,...,2.192618,4.542934,0.095324,0.606233,10.231359,3.296614,14.329393,1.874007,pre-void,1
3,3.276990,1.778212,4.775769,0.900103,0.797495,-0.175351,0.032583,0.179349,0.178352,0.001062,...,4.213149,5.096180,0.168869,0.193751,12.472739,1.696852,5.690334,-6.192239,pre-void,1
4,3.869728,2.370949,5.368506,0.917587,0.797179,-0.183709,0.034388,0.184520,0.186900,0.001183,...,4.973583,4.920308,0.145046,0.116837,12.226078,1.143910,3.359634,-8.784610,pre-void,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2844,33.060475,31.563365,34.557584,0.867587,0.667021,-1.201659,0.257890,1.360230,1.229021,0.066507,...,7.727934,6.107240,0.324016,0.102339,13.161236,1.013565,3.529090,-9.430704,post-void,39
2845,33.656010,32.158901,35.153119,0.861009,0.721822,-1.294598,0.326069,1.634230,1.335030,0.106321,...,5.039791,5.801170,0.214476,0.146086,13.351794,1.756961,5.630781,-7.668041,post-void,39
2846,34.251545,32.754436,35.748654,0.855702,0.687467,-1.571344,0.575835,2.631198,1.673531,0.331586,...,2.912535,4.384346,0.118675,0.244639,13.164283,3.117610,13.302315,-4.896291,post-void,39
2847,34.847080,33.349971,36.344190,0.841897,0.644074,-1.942170,0.743946,2.715278,2.079779,0.553456,...,1.857036,3.107541,0.052422,0.224279,13.359625,4.574878,27.023587,-5.389169,post-void,39
2848,35.442615,33.945506,36.939725,0.834479,0.606663,-2.306019,0.787462,2.804181,2.436764,0.620097,...,1.539571,2.745916,0.042786,0.274553,13.394626,5.064978,33.585263,-4.219785,post-void,39

## Data 4
classes: void, non-void

fs: original

overlap: 0.0

sliding window: 4s

filename: two_class_4s_no.csv

In [21]:
all_features = []
for i, exp_id in enumerate(train_data_3_class_labelled.keys()):    
    # Extract features
    
    df = train_data_3_class_labelled[exp_id]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=4.0, overlap=0.0)
    features, _ = analyzer.analyze_multi_axis_imu(train_data_3_class_labelled[exp_id])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id 
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing :   0%|          | 0/8 [00:00<?, ?it/s]

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 34.55it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 50.40it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 29.60it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 32.81it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 22.22it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 35.65it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 42.47it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 28.25it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.12it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.72it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 35.43it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 62.31it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 49.72it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 45.08it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.42it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 52.52it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 46.89it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 22.90it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 36.50it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 30.39it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.74it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 42.07it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 48.86it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 35.85it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 64.24it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 41.87it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 46.76it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.23it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 32.66it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 28.21it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 45.89it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 41.92it/s]

In [22]:
final_features.to_csv('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/extracted_features_data/3_class/train_set/two_class_4s_no.csv', index=False)
final_features

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,1.998371,0.000000,3.996743,0.888082,0.724174,-0.155098,0.089075,0.636465,0.178857,0.007934,...,1.909569,2.840415,0.051068,0.358098,9.336721,3.345724,19.714721,-2.534673,pre-void,1
1,5.995114,3.996743,7.993486,0.900675,0.721296,-0.188784,0.086351,0.649299,0.207596,0.007457,...,2.643921,3.387922,0.084417,0.180121,11.414681,3.343380,18.048869,-6.581840,pre-void,1
2,9.991857,7.993486,11.990229,0.901749,0.809333,-0.187292,0.052143,0.351772,0.194415,0.002719,...,2.370933,3.347807,0.066390,0.167660,10.631576,2.952960,13.302648,-6.958698,pre-void,1
3,13.988600,11.990229,15.986972,0.917454,0.790501,-0.226437,0.054810,0.428480,0.232976,0.003004,...,3.846981,4.463164,0.099669,0.139962,11.474948,1.616866,5.348652,-7.885084,pre-void,1
4,17.985343,15.986972,19.983714,0.922168,0.631454,-0.214692,0.119053,0.643976,0.245492,0.014174,...,2.813603,3.799587,0.080936,0.272445,10.334469,2.283603,9.231717,-4.265872,void,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423,18.014940,16.013280,20.016600,0.941384,0.828816,-0.480586,0.103297,0.611486,0.491562,0.010670,...,6.107244,7.632854,0.347991,0.098506,15.422755,1.478061,4.047763,-9.615018,void,39
424,22.018260,20.016600,24.019920,0.912920,0.851334,-0.455176,0.156586,0.984625,0.481357,0.024519,...,3.752646,6.475265,0.199892,0.390675,15.272107,2.257345,7.245874,-1.930339,void,39
425,26.021580,24.019920,28.023239,0.845126,0.582316,-0.989292,0.222735,1.069275,1.014056,0.049611,...,4.148235,6.753496,0.201585,0.223111,15.287947,2.208502,6.918738,-5.418388,void,39
426,30.024899,28.023239,32.026559,0.858313,0.540817,-1.052269,0.278007,1.250551,1.088374,0.077288,...,5.653540,7.232977,0.343699,0.120847,15.063592,1.686078,5.025310,-8.618266,post-void,39
427,34.028219,32.026559,36.029879,0.847805,0.724468,-1.579240,0.667010,2.851538,1.714322,0.444902,...,2.854787,4.477608,0.109956,0.249871,13.157163,2.974462,12.359381,-4.774195,post-void,39

## Data 4b
classes: void, non-void

fs: original

overlap: 0.5

sliding window: 4s

filename: two_class_4s_0.5.csv

In [23]:
all_features = []
for i, exp_id in enumerate(train_data_3_class_labelled.keys()):    
    # Extract features
    
    df = train_data_3_class_labelled[exp_id]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=4.0, overlap=0.5)
    features, _ = analyzer.analyze_multi_axis_imu(train_data_3_class_labelled[exp_id])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id 
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.92it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 26.49it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.24it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.93it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.77it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.17it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.98it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.28it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.12it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.21it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.02it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 32.56it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.52it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 24.07it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.48it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 27.35it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 26.48it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.09it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.34it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.67it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.83it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.05it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 26.71it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.85it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 31.91it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.09it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 24.44it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.99it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.08it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.09it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.82it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.86it/s]

In [24]:
final_features.to_csv('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/extracted_features_data/3_class/train_set/two_class_4s_0.5.csv', index=False)
final_features

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,1.998371,0.000000,3.996743,0.888082,0.724174,-0.155098,0.089075,0.636465,0.178857,0.007934,...,1.909569,2.840415,0.051068,0.358098,9.336721,3.345724,19.714721,-2.534673,pre-void,1
1,3.996743,1.998371,5.995114,0.916050,0.817238,-0.193497,0.051698,0.389462,0.200284,0.002673,...,5.140307,5.043920,0.153675,0.085654,10.866629,1.143548,3.485275,-10.283653,pre-void,1
2,5.995114,3.996743,7.993486,0.900675,0.721296,-0.188784,0.086351,0.649299,0.207596,0.007457,...,2.643921,3.387922,0.084417,0.180121,11.414681,3.343380,18.048869,-6.581840,pre-void,1
3,7.993486,5.995114,9.991857,0.908323,0.745699,-0.177877,0.082105,0.649299,0.195912,0.006741,...,5.226977,4.125527,0.115679,0.086507,11.314465,1.214850,4.727328,-10.236525,pre-void,1
4,9.991857,7.993486,11.990229,0.901749,0.809333,-0.187292,0.052143,0.351772,0.194415,0.002719,...,2.370933,3.347807,0.066390,0.167660,10.631576,2.952960,13.302648,-6.958698,pre-void,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
836,26.021580,24.019920,28.023239,0.845126,0.582316,-0.989292,0.222735,1.069275,1.014056,0.049611,...,4.148235,6.753496,0.201585,0.223111,15.287947,2.208502,6.918738,-5.418388,void,39
837,28.023239,26.021580,30.024899,0.862262,0.553972,-0.936886,0.194226,0.896987,0.956807,0.037724,...,5.677647,7.683147,0.306420,0.184705,15.693730,1.631141,4.482134,-6.448372,void,39
838,30.024899,28.023239,32.026559,0.858313,0.540817,-1.052269,0.278007,1.250551,1.088374,0.077288,...,5.653540,7.232977,0.343699,0.120847,15.063592,1.686078,5.025310,-8.618266,post-void,39
839,32.026559,30.024899,34.028219,0.852881,0.566385,-1.181025,0.245624,1.204562,1.206296,0.060331,...,6.539484,5.977841,0.233480,0.076679,13.674199,1.074348,3.790184,-10.806754,post-void,39
840,34.028219,32.026559,36.029879,0.847805,0.724468,-1.579240,0.667010,2.851538,1.714322,0.444902,...,2.854787,4.477608,0.109956,0.249871,13.157163,2.974462,12.359381,-4.774195,post-void,39

## Data 4c
classes: void, non-void

fs: original

overlap: 0.8

sliding window: 4s

filename: two_class_4s_0.8.csv

In [25]:
all_features = []
for i, exp_id in enumerate(train_data_3_class_labelled.keys()):    
    # Extract features
    
    df = train_data_3_class_labelled[exp_id]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=4.0, overlap=0.8)
    features, _ = analyzer.analyze_multi_axis_imu(train_data_3_class_labelled[exp_id])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id 
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.32it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.04it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.62it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.31it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.50it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.73it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.37it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.82it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.18it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.75it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.76it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.52it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.22it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.41it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.18it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.28it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.87it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  4.83it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.85it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.58it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  2.78it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.92it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.80it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.86it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.57it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.40it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.51it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.85it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.56it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.68it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.02it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.71it/s]

In [26]:
final_features.to_csv('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/extracted_features_data/3_class/train_set/two_class_4s_0.8.csv', index=False)
final_features

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,1.998371,0.000000,3.996743,0.888082,0.724174,-0.155098,0.089075,0.636465,0.178857,0.007934,...,1.909569,2.840415,0.051068,0.358098,9.336721,3.345724,19.714721,-2.534673,pre-void,1
1,2.794333,0.795962,4.792704,0.888588,0.758875,-0.162448,0.080490,0.636465,0.181295,0.006479,...,1.874274,3.838942,0.087579,0.533272,10.136224,3.590633,17.530375,0.578857,pre-void,1
2,3.590294,1.591923,5.588666,0.914118,0.829681,-0.185043,0.039191,0.205576,0.189148,0.001536,...,4.544132,5.011379,0.157894,0.118087,12.482063,1.382813,4.320982,-8.732222,pre-void,1
3,4.386256,2.387885,6.384627,0.918808,0.782531,-0.189887,0.065811,0.456941,0.200968,0.004331,...,4.529654,4.987441,0.128046,0.144968,10.425583,1.353319,4.113602,-7.707114,pre-void,1
4,5.182217,3.183846,7.180589,0.906615,0.724715,-0.193835,0.081253,0.649299,0.210176,0.006602,...,2.353348,3.224285,0.074364,0.198959,11.691420,3.123905,15.966765,-6.048917,pre-void,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2082,31.381396,29.379736,33.383056,0.852516,0.547914,-1.120885,0.273356,1.231643,1.153736,0.074723,...,7.414159,6.555657,0.313507,0.082407,13.964554,0.940481,3.371459,-10.466858,post-void,39
2083,32.175443,30.173783,34.177103,0.853904,0.574513,-1.189126,0.247693,1.204562,1.214649,0.061352,...,6.647317,5.936407,0.249964,0.074812,13.706626,1.079962,3.870892,-10.922556,post-void,39
2084,32.969490,30.967830,34.971150,0.863862,0.652710,-1.269446,0.297699,1.634230,1.303886,0.088625,...,7.209813,6.026511,0.280920,0.082254,13.569999,1.140399,3.873786,-10.475639,post-void,39
2085,33.763537,31.761877,35.765197,0.855310,0.689305,-1.460168,0.561726,2.851538,1.564489,0.315536,...,3.465019,5.037037,0.134213,0.266754,13.053957,2.432546,8.920115,-4.391380,post-void,39
2086,34.557584,32.555924,36.559244,0.848029,0.692682,-1.836823,0.798835,2.931035,2.003012,0.638137,...,2.024023,3.494040,0.064944,0.201193,13.162128,4.080344,21.780774,-5.988290,post-void,39

## Data 5
classes: void, non-void

fs: original

overlap: 0.0

sliding window: 5s

filename: two_class_5s_no.csv

In [27]:
all_features = []
for i, exp_id in enumerate(train_data_3_class_labelled.keys()):    
    # Extract features
    
    df = train_data_3_class_labelled[exp_id]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=5.0, overlap=0.0)
    features, _ = analyzer.analyze_multi_axis_imu(train_data_3_class_labelled[exp_id])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id 
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 41.82it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 57.48it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 38.11it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 40.09it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.23it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 45.66it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 49.45it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 34.64it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.72it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 27.12it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 42.60it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 66.81it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 64.34it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 55.82it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 24.81it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 61.13it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 62.39it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 29.23it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 51.62it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 36.27it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 17.10it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 49.89it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 65.26it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 47.08it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 76.92it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 50.48it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 63.22it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 37.31it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 35.80it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 36.18it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 57.57it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 62.46it/s]

In [28]:
final_features.to_csv('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/extracted_features_data/3_class/train_set/two_class_5s_no.csv', index=False)
final_features

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,2.497964,0.000000,4.995929,0.888117,0.737073,-0.162397,0.081929,0.636465,0.181893,0.006712,...,1.773251,2.851367,0.050851,0.382830,9.525205,3.622310,21.935383,-2.073985,pre-void,1
1,7.493893,4.995929,9.991857,0.911608,0.753020,-0.190451,0.083279,0.649299,0.207863,0.006935,...,4.340479,4.619315,0.167017,0.157899,10.857686,1.864614,7.143838,-7.269853,pre-void,1
2,12.489822,9.991857,14.987786,0.897663,0.801344,-0.201436,0.056910,0.428480,0.209321,0.003239,...,3.351115,3.712951,0.091602,0.138694,11.332125,2.472221,10.418986,-7.931007,pre-void,1
3,17.485750,14.987786,19.983714,0.924754,0.681130,-0.223558,0.108885,0.643976,0.248665,0.011856,...,4.978257,4.434836,0.138242,0.087191,10.731888,1.438136,5.528805,-10.199076,void,1
4,22.481679,19.983714,24.979643,0.944870,0.844899,-0.144463,0.046437,0.333030,0.151743,0.002156,...,5.185187,4.874981,0.172279,0.149966,12.294581,1.723733,6.645897,-7.534421,void,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336,12.489696,9.991757,14.987636,0.920460,0.764522,-0.638778,0.135789,0.603065,0.653052,0.018439,...,4.221016,6.064399,0.205344,0.191317,15.106137,2.201534,6.834523,-6.260245,void,39
337,17.485575,14.987636,19.983514,0.947062,0.827473,-0.486574,0.100039,0.611486,0.496751,0.010008,...,8.048537,8.315102,0.451318,0.096174,15.271695,0.794627,2.263502,-9.730294,void,39
338,22.481454,19.983514,24.979393,0.897395,0.852017,-0.537240,0.245630,1.331653,0.590729,0.060334,...,3.537831,6.241668,0.205514,0.414772,15.283835,2.330755,7.672128,-1.495160,void,39
339,27.477332,24.979393,29.975272,0.858554,0.581592,-0.973524,0.210152,1.031839,0.995948,0.044164,...,5.267487,7.098227,0.297102,0.134968,15.441706,1.779131,5.236194,-8.068012,void,39
340,32.473211,29.975272,34.971150,0.859567,0.617874,-1.241713,0.296427,1.634230,1.276605,0.087869,...,6.638401,5.984508,0.251174,0.078552,13.748947,1.064868,3.782232,-10.693120,post-void,39

## Data 5b
classes: void, non-void

fs: original

overlap: 0.5

sliding window: 5s

filename: two_class_5s_0.5.csv

In [29]:
all_features = []
for i, exp_id in enumerate(train_data_3_class_labelled.keys()):    
    # Extract features
    
    df = train_data_3_class_labelled[exp_id]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=5.0, overlap=0.5)
    features, _ = analyzer.analyze_multi_axis_imu(train_data_3_class_labelled[exp_id])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id 
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.84it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 31.84it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 19.76it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.10it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.68it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 28.00it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 29.63it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.95it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.33it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.06it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.10it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 43.12it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 33.20it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 30.74it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.07it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 35.20it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 31.96it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.35it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 26.22it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.55it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.17it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 26.03it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 33.98it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 23.86it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 45.71it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 25.79it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 33.23it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 20.15it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 21.29it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 18.93it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 31.32it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 35.41it/s]

In [30]:
final_features.to_csv('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/extracted_features_data/3_class/train_set/two_class_5s_0.5.csv', index=False)
final_features

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,2.497964,0.000000,4.995929,0.888117,0.737073,-0.162397,0.081929,0.636465,0.181893,0.006712,...,1.773251,2.851367,0.050851,0.382830,9.525205,3.622310,21.935383,-2.073985,pre-void,1
1,5.004396,2.506432,7.502361,0.897512,0.745939,-0.187870,0.078069,0.649299,0.203445,0.006095,...,3.049529,4.121320,0.098068,0.207338,11.507707,2.195891,8.061412,-5.824089,pre-void,1
2,7.510828,5.012864,10.008793,0.914115,0.753870,-0.190713,0.083358,0.649299,0.208135,0.006949,...,4.375136,4.623077,0.167601,0.156533,10.876881,1.841766,7.047121,-7.314633,pre-void,1
3,10.017260,7.519296,12.515225,0.910004,0.820431,-0.186061,0.051399,0.351772,0.193030,0.002642,...,2.508483,3.419540,0.064957,0.135204,10.770818,2.711204,11.444394,-8.059237,pre-void,1
4,12.523692,10.025728,15.021657,0.897663,0.801561,-0.201470,0.056883,0.428480,0.209346,0.003236,...,3.376372,3.739436,0.095582,0.141575,11.326843,2.437237,10.181336,-7.827171,pre-void,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
657,22.481454,19.983514,24.979393,0.897395,0.852017,-0.537240,0.245630,1.331653,0.590729,0.060334,...,3.537831,6.241668,0.205514,0.414772,15.283835,2.330755,7.672128,-1.495160,void,39
658,24.979393,22.481454,27.477332,0.852665,0.576934,-0.858447,0.290581,1.230357,0.906294,0.084437,...,2.588676,5.289910,0.100738,0.303296,15.117203,2.888334,10.704528,-3.611813,void,39
659,27.477332,24.979393,29.975272,0.858554,0.581592,-0.973524,0.210152,1.031839,0.995948,0.044164,...,5.267487,7.098227,0.297102,0.134968,15.441706,1.779131,5.236194,-8.068012,void,39
660,29.975272,27.477332,32.473211,0.857232,0.535397,-1.050729,0.271530,1.250551,1.085247,0.073729,...,4.950553,6.907456,0.278216,0.157372,14.752653,1.889713,5.743806,-7.287082,void,39
661,32.473211,29.975272,34.971150,0.859567,0.617874,-1.241713,0.296427,1.634230,1.276605,0.087869,...,6.638401,5.984508,0.251174,0.078552,13.748947,1.064868,3.782232,-10.693120,post-void,39

## Data 5c
classes: void, non-void

fs: original

overlap: 0.8

sliding window: 5s

filename: two_class_5s_0.8.csv

In [31]:
all_features = []
for i, exp_id in enumerate(train_data_3_class_labelled.keys()):    
    # Extract features
    
    df = train_data_3_class_labelled[exp_id]
    fs = 1 / df['time'].diff().median()
    analyzer = GenerateFeatures(fs, window_duration=5.0, overlap=0.8)
    features, _ = analyzer.analyze_multi_axis_imu(train_data_3_class_labelled[exp_id])

    table = analyzer.create_summary_table()
    table['experiment_id'] = exp_id 
    all_features.append(table)
    

final_features = pd.concat(all_features, ignore_index=True)

Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.31it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.76it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.68it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.97it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.94it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.45it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.03it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.69it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.33it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  6.41it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.91it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.25it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.25it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 12.75it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.02it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 15.35it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.19it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  5.92it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.30it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  8.23it/s]
Analyzing : 100%|██████████| 8/8 [00:02<00:00,  3.58it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.84it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.61it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00,  9.43it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 16.84it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 10.42it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 13.01it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.68it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.33it/s]
Analyzing : 100%|██████████| 8/8 [00:01<00:00,  7.16it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 11.91it/s]
Analyzing : 100%|██████████| 8/8 [00:00<00:00, 14.44it/s]

In [32]:
final_features.to_csv('/home/edumaba/Public/MPhil_Thesis/Code/uropatch-data-analysis/deployable/data/extracted_features_data/3_class/train_set/two_class_5s_0.8.csv', index=False)
final_features

,center_time,start_time,end_time,acc_x_permutation_entropy,acc_x_spectral_entropy,acc_x_mean,acc_x_std,acc_x_range,acc_x_rms,acc_x_var,...,gyr_mag_spectral_centroid,gyr_mag_spectral_spread,gyr_mag_spectral_flatness,gyr_mag_peak_frequency_ratio,gyr_mag_hjorth_frequency,gyr_mag_spectral_skewness,gyr_mag_spectral_kurtosis,gyr_mag_snr,label,experiment_id
0,2.497964,0.000000,4.995929,0.888117,0.737073,-0.162397,0.081929,0.636465,0.181893,0.006712,...,1.773251,2.851367,0.050851,0.382830,9.525205,3.622310,21.935383,-2.073985,pre-void,1
1,3.497150,0.999186,5.995114,0.903643,0.831936,-0.180569,0.069594,0.492463,0.193516,0.004843,...,3.031480,4.684984,0.116389,0.350989,9.851394,2.213580,7.954390,-2.669579,pre-void,1
2,4.496336,1.998371,6.994300,0.909907,0.748054,-0.184686,0.065340,0.456941,0.195903,0.004269,...,4.689136,5.022314,0.139632,0.126190,11.974523,1.282678,3.891335,-8.403902,pre-void,1
3,5.495521,2.997557,7.993486,0.907527,0.743781,-0.186189,0.078962,0.649299,0.202241,0.006235,...,2.372988,3.264510,0.069802,0.180207,11.450536,3.102987,15.731637,-6.579324,pre-void,1
4,6.494707,3.996743,8.992671,0.908827,0.746843,-0.189267,0.077978,0.649299,0.204701,0.006081,...,2.805621,3.597939,0.096213,0.176479,11.080817,3.181584,16.194801,-6.689808,pre-void,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1633,30.289582,27.791642,32.787521,0.854276,0.536813,-1.053046,0.269207,1.250551,1.086912,0.072473,...,5.428463,7.122566,0.308686,0.134603,14.662419,1.746329,5.237124,-8.081603,post-void,39
1634,31.282140,28.784201,33.780080,0.853151,0.550446,-1.102233,0.275283,1.250551,1.136089,0.075781,...,7.847559,7.208347,0.378485,0.099258,13.863763,1.047833,3.541143,-9.578360,post-void,39
1635,32.274699,29.776760,34.772638,0.864717,0.586275,-1.211898,0.281287,1.538738,1.244114,0.079122,...,6.626011,6.068403,0.243303,0.080279,13.871753,1.046386,3.670500,-10.590553,post-void,39
1636,33.267258,30.769318,35.765197,0.856046,0.642657,-1.426834,0.518598,2.851538,1.518156,0.268944,...,7.124474,6.008047,0.284653,0.069694,13.053355,1.142744,3.909517,-11.254319,post-void,39
1637,34.259816,31.761877,36.757756,0.847969,0.712711,-1.764917,0.808763,3.246309,1.941398,0.654097,...,3.082247,4.712138,0.121035,0.251148,13.420225,2.730461,10.726128,-4.744652,post-void,39